# -*- coding: utf-8 -*-
"""Shared English->Chinese term/title fragments reused across pages."""

# Chapter / section titles as they appear in toctree links and headings
# (without the leading number, which is plain text and preserved).
CHAPTER_TITLES = [
    ("Introduction", "简介"),
    ("Getting Started", "快速入门"),
    ("Architecture", "架构"),
    ("Architectural Overview", "架构概览"),
    ("Naming Conventions", "命名约定"),
    ("State management", "状态管理"),
    ("Code Generation", "代码生成"),
    ("Configuration Parameters", "配置参数"),
    ("Scheduling and Optimization", "调度与优化"),
    ("State Machine", "状态机"),
    ("Treatment of Numerical Algorithms", "数值算法处理"),
    ("Components", "组件"),
    ("Main Application", "主应用程序"),
    ("ADC Calibration and Compensation", "ADC 校准与补偿"),
    ("Field-Oriented Control (FOC)", "磁场定向控制（FOC）"),
    ("Test Harness", "测试框架"),
    ("Supervisory Algorithms", "监督算法"),
    ("External Interface", "外部接口"),
    ("Diagnostic Kernel", "诊断内核"),
    ("Hardware Abstraction Layer (HAL)", "硬件抽象层（HAL）"),
    ("Motion Control API (MCAPI)", "运动控制 API（MCAPI）"),
    ("Miscellaneous", "其他"),
    ("Detailed Algorithm Notes", "详细算法说明"),
    ("Field-oriented Current Control", "磁场定向电流控制"),
    ("Startup", "启动"),
    ("Stopping", "停止"),
    ("Position and Velocity Estimation", "位置与速度估计"),
    ("Flux control", "磁通控制"),
    ("Current limit", "电流限制"),
    ("Dead-time Compensation", "死区补偿"),
    ("Voltage Control", "电压控制"),
    ("Temperature measurement", "温度测量"),
    ("General Implementation Issues", "通用实现问题"),
    ("Source Tree Structure", "源码树结构"),
    ("Parameter customization", "参数定制"),
    ("Sampling Rate and PWM Frequency Implications", "采样率与 PWM 频率的影响"),
    ("Integration with Custom Code", "与自定义代码的集成"),
    ("Custom Board Support", "定制板级支持"),
    ("Resource Usage", "资源占用"),
    ("Appendix", "附录"),
    ("Glossary", "术语表"),
    ("Error code list", "错误代码列表"),
    ("MCLV-2 Sense Resistors", "MCLV-2 采样电阻"),
    ("Related Documents", "相关文档"),
    ("Revision History", "修订历史"),
    ("Frequently Asked Questions (FAQ)", "常见问题解答（FAQ）"),
    ("Contacting Microchip", "联系 Microchip"),
    ("USB compatibility", "USB 兼容性"),
    ("RTOS compatibility", "RTOS 兼容性"),
]

# Common UI / structural fragments appearing in body across many pages
UI_FRAGMENTS = [
    ("Contents:", "目录："),
    ("Indices and tables", "索引与表格"),
    ("Search Page", "搜索页"),
    ("Previous topic", "上一主题"),
    ("Next topic", "下一主题"),
]

# Reusable technical terms (applied where they appear in prose)
TECH_TERMS = [
    ("field-oriented control (FOC)", "磁场定向控制（FOC）"),
    ("field-oriented control", "磁场定向控制"),
    ("Field-Oriented Control", "磁场定向控制"),
    ("brushless DC", "无刷直流"),
    ("Brushless DC", "无刷直流"),
    ("permanent magnet synchronous motor", "永磁同步电机"),
    ("Permanent magnet synchronous motor", "永磁同步电机"),
    ("Permanent-magnet synchronous motor", "永磁同步电机"),
    ("reference frame", "参考坐标系"),
    ("Reference frame", "参考坐标系"),
    ("rotor", "转子"),
    ("Rotor", "转子"),
    ("stator", "定子"),
    ("Stator", "定子"),
    ("torque", "转矩"),
    ("Torque", "转矩"),
    ("flux", "磁通"),
    ("Flux", "磁通"),
    ("inverter", "逆变器"),
    ("Inverter", "逆变器"),
    ("pulse-width modulation", "脉宽调制"),
    ("Pulse-width modulation", "脉宽调制"),
    ("Pulse-Width Modulation", "脉宽调制"),
]
