# -*- coding: utf-8 -*-
import txutil

rel = "appendix/glossary"
title_zh = "7.1. 术语表"

m = {
    "7.1. Glossary — MCAF R9 RC31 文档 (docver 9.0.1)": "7.1. 术语表 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "Appendix": "附录",
    "Glossary": "术语表",
    "analog-to-digital converter": "模数转换器",
    "Application Programming Interface": "应用编程接口",
    "brushless DC motor \u2014 generally used in six-step control. Also known as": "无刷直流电机——通常用于六步控制。也称为",
    "data model": "数据模型",
    "A hierarchical or structured set of data. See": "层次化或结构化的数据集合。参见",
    "Working with Serialized Data Models": "使用序列化数据模型",
    "for more information.": "以获取更多信息。",
    "dead time": "死区时间",
    "Brief period of time when the high and low PWM signals in a half-bridge are both off, preventing a short circuit across the DC link. See": "半桥中高侧和低侧 PWM 信号同时关闭的短暂时间，防止 DC 母线短路。参见",
    "Definition and origin of dead time": "死区时间的定义与来源",
    "feedback path": "反馈通道",
    "The section of the": "The section of the",
    "current control loop": "电流控制环",
    "between ADC inputs and the current controllers, including Park and Clarke transforms. See also": "中 ADC 输入与电流控制器之间的部分，包括 Park 和 Clarke 变换。另见",
    "FOC block diagram": "FOC 框图",
    "field-oriented control": "磁场定向控制",
    "\u2014 a type of control scheme for permanent-magnet synchronous motors or induction motors, where the stator field is controlled relative to the rotor field. It generally results in smoother torque, slightly higher efficiency, and higher torque-speed curve, compared to six-step control, but requires a measurement or estimate of rotor position, and is more computationally intensive.": "\u2014 一种用于永磁同步电机或感应电机的控制方案，其中定子磁场相对于转子磁场进行控制。与六步控制相比，它通常产生更平滑的转矩、略高的效率和更高的转矩-速度曲线，但需要测量或估计转子位置，且计算量更大。",
    "forward path": "前向通道",
    "between the output of the current controllers and the transistor gate drives, including inverse Park and Clarke transforms,": "中电流控制器输出与晶体管栅极驱动之间的部分，包括逆 Park 和 Clarke 变换、",
    "DC link compensation": "DC 母线补偿",
    "zero sequence modulation": "零序调制",
    ", and": "和",
    "overmodulation": "过调制",
    ". See also": "。另见",
    "Hardware Abstraction Layer": "硬件抽象层",
    "interior permanent-magnet motors (see": "内置式永磁电机（见",
    "rotor saliency": "转子凸极性",
    "interior permanent-magnet synchronous motors (see": "内置式永磁同步电机（见",
    "interrupt service routine": "中断服务例程",
    "Motor Control Application Framework": "电机控制应用框架",
    "Multi-input, multi-output systems, usually specified and analyzed with state-space equations. See also": "多输入多输出系统，通常用状态空间方程描述和分析。另见",
    "Maximum Torque per Ampere": "最大转矩/电流比",
    "Plug-In Module": "插件模块",
    "\u2014 a small circuit board containing a processor and several passive components (such as bypass capacitors), meant to plug in to one of Microchip\u2019s development boards.": "\u2014 一块包含处理器和若干无源器件（如旁路电容）的小型电路板，用于插入 Microchip 的开发板。",
    "phase-locked loop \u2014 see": "锁相环——见",
    "for the Microchip Application Note covering the PLL-style sensorless estimator.": "了解涵盖 PLL 式无传感器估计器的 Microchip 应用笔记。",
    "permanent-magnet synchronous motor \u2014 generally used with": "永磁同步电机——通常用于",
    ". Also known as": "。也称为",
    "pulse-width modulation": "脉宽调制",
    "Quadrature Encoder Interface \u2014 the name of the hardware encoder counter peripheral in some Microchip devices.": "正交编码器接口——某些 Microchip 器件中硬件编码器计数外设的名称。",
    "Permanent magnet synchronous motors can be divided into two types, interior permanent-magnet synchronous motors (IPM or IPMSM) with magnets located inside the rotor, and surface permanent-magnet synchronous motors (SPM or SPMSM) with magnets placed evenly over the surface of the rotor.": "永磁同步电机可分为两种类型：磁铁位于转子内部的内置式永磁同步电机（IPM 或 IPMSM），以及磁铁均匀放置在转子表面的表贴式永磁同步电机（SPM 或 SPMSM）。",
    "These can be distinguished quantitatively through the ratio of the synchronous inductances": "它们可通过同步电感的比值定量区分",
    ", known as the saliency ratio.": "，称为凸极比。",
    "The SPMSM has stator inductance which is independent of rotor position, and has no significant difference between the two synchronous inductances, so": "SPMSM 的定子电感与转子位置无关，两个同步电感之间没有显著差异，因此",
    "The IPMSM has stator inductance which is dependent of rotor position, and has significant difference between the two synchronous inductances, typically with saliency ratio": "IPMSM 的定子电感与转子位置相关，两个同步电感之间有显著差异，通常凸极比为",
    "Single-input, single-output systems, usually specified and analyzed with state-space equations. See also": "单输入单输出系统，通常用状态空间方程描述和分析。另见",
    "sliding-mode observer \u2014 see": "滑模观测器——见",
    "for the Microchip Application Note covering the SMO-style sensorless estimator.": "了解涵盖 SMO 式无传感器估计器的 Microchip 应用笔记。",
    "surface permanent-magnet motors (see": "表贴式永磁电机（见",
    "surface permanent-magnet synchronous motors (see": "表贴式永磁同步电机（见",
    "Zero-Speed / Maximum Torque": "零速/最大转矩",
    "estimator": "估计器",
    "Error code list": "错误代码列表",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
