# -*- coding: utf-8 -*-
import txutil

rel = "appendix/rev_history"
title_zh = "7.5. 修订历史"

m = {
    "7.5. Revision History — MCAF R9 RC31 文档 (docver 9.0.1)": "7.5. 修订历史 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "Appendix": "附录",
    "Revision History": "修订历史",
    "This section covers both the revision history for this documentation and for the MCAF itself.": "本节涵盖本文档和 MCAF 本身的修订历史。",
    "MCAF Documentation Revision History": "MCAF 文档修订历史",
    "Revision": "版本",
    "Date": "日期",
    "Notes": "备注",
    "Preliminary draft": "初步草案",
    "Clarifications, glossary, and other minor edits": "澄清、术语表及其他小幅编辑",
    "Edits based on staff review": "基于员工审查的编辑",
    "Added subsection on thread safety": "添加了线程安全子节",
    "Corrected": "修正了",
    "prefix in documentation": "文档中的前缀",
    "Fixed test harness documentation issues": "修复了测试框架文档问题",
    "Corrected block diagram (DC link compensation in wrong place)": "修正了框图（DC 母线补偿位置错误）",
    "Added updates for MCAF R2": "添加了 MCAF R2 的更新",
    "scaling factor": "缩放因子",
    "information": "信息",
    "Updated for MCAF R3": "为 MCAF R3 更新",
    "Added": "添加了",
    "code generation": "代码生成",
    "section": "节",
    "pwm duty cycle": "PWM 占空比",
    "section from existing internal documentation": "节（来自现有内部文档）",
    "Minor edits based on staff review": "基于员工审查的小幅编辑",
    "Updated for MCAF R4:": "为 MCAF R4 更新：",
    "Quadrature encoder support": "正交编码器支持",
    "Back-EMF synchronization": "反电动势同步",
    "sections": "节",
    "Startup": "启动",
    "Parameter customization": "参数定制",
    "Updated for MCAF R5:": "为 MCAF R5 更新：",
    "Position and Velocity Estimation": "位置与速度估计",
    "Angle-tracking Phase-locked Loop (ATPLL)": "角度跟踪锁相环 (ATPLL)",
    "AN1292 Phase-locked Loop (PLL)": "AN1292 锁相环 (PLL)",
    "Updated": "更新了",
    "section to cover ADC timing and dsPIC33CK support": "节以涵盖 ADC 时序和 dsPIC33CK 支持",
    "Added test harness section on": "添加了测试框架节关于",
    "Pause at end of open-loop startup": "开环启动结束时暂停",
    "customizable parameters": "可定制参数",
    "Updated for MCAF R6:": "为 MCAF R6 更新：",
    "Sampling Rate and PWM Frequency Implications": "采样率与 PWM 频率的影响",
    "Current loop tuning": "电流环整定",
    "Motion Control API (MCAPI)": "运动控制 API (MCAPI)",
    "Flux control": "磁通控制",
    "Dead-time Compensation": "死区补偿",
    "introductory section on FOC": "FOC 简介节",
    "Rewrote section": "重写了",
    "Integration with Custom Code": "与自定义代码的集成",
    "to reflect MCAPI": "以反映 MCAPI",
    "section to include the implication of differences in PWM deadtime behavior between dsPIC33E and dsPIC33C": "节以包含 dsPIC33E 和 dsPIC33C 之间 PWM 死区行为差异的影响",
    "Usage statistics for MCAF R6": "MCAF R6 使用统计",
    "Stylistic changes": "风格变更",
    "Updated for MCAF R7:": "为 MCAF R7 更新：",
    "Comparison between FOC and six-step control": "FOC 与六步控制的比较",
    "Current measurement": "电流测量",
    "Field-oriented control (FOC): an overview": "磁场定向控制 (FOC)：概述",
    "Current limit": "电流限制",
    "Simple dynamic current limit": "简单动态电流限制",
    "Temperature measurement": "温度测量",
    "Voltage Control": "电压控制",
    "Zero-Speed / Maximum Torque (ZS/MT)": "零速/最大转矩 (ZS/MT)",
    "Marked": "标记了",
    "Pullout torque method": "失步转矩方法",
    "as deprecated": "为已弃用",
    "section to include ZS/MT estimator and": "节以包含 ZS/MT 估计器和",
    "Firmware Interface": "固件接口",
    "section to include ZS/MT initial position correction startup method": "节以包含 ZS/MT 初始位置校正启动方法",
    "Field Oriented Control": "磁场定向控制",
    "section to describe": "节以描述",
    "voltage loop": "电压环",
    "section to describe an updated design of the": "节以描述",
    "PWM bootstrap charging routine": "PWM 自举充电例程",
    "Main application": "主应用",
    "section to reflect the changes in the structure of the main application": "节以反映主应用结构的变化",
    "Motion Control API": "运动控制 API",
    "section to describe the new methods": "节以描述新方法",
    "State machine": "状态机",
    "section to document changes in the MCAF state machine": "节以记录 MCAF 状态机的变化",
    "Supervisory algorithms": "监督算法",
    "overtemperature detection": "过温检测",
    "Test harness": "测试框架",
    "section to describe new features": "节以描述新功能",
    "Resource usage": "资源使用",
    "Integration with custom code": "与自定义代码的集成",
    "section to reflect changes in the structure of the": "节以反映",
    "main application": "主应用",
    "ADC Calibration and Compensation": "ADC 校准与补偿",
    "section to reflect changes in MCAF R7 for single-channel and triple-channel support": "节以反映 MCAF R7 中单通道和三通道支持的变更",
    "Updated for MCAF R8:": "为 MCAF R8 更新：",
    "Custom Board Support": "自定义板级支持",
    "Removed obsolete content on custom boards in": "移除了",
    "Integration": "集成",
    "Diagnostic Kernel": "诊断内核",
    "section to describe \u201cnone\u201d option and remove RTDM support": "节以描述\u201cnone\u201d选项并移除 RTMD 支持",
    "Update": "更新",
    "HAL section": "HAL 节",
    "to clarify estimator and hardware requirements for dual and single update PWM": "以澄清双更新和单更新 PWM 的估计器和硬件要求",
    "MCAPI fault flags": "MCAPI 故障标志",
    "table": "表",
    "Updated Supervisory Algorithms section to add section on": "更新了监督算法节以添加",
    "fault-clearing logic": "故障清除逻辑",
    "Updated for MCAF R9:": "为 MCAF R9 更新：",
    "Added support for": "添加了对",
    "dsPIC33AK devices": "dsPIC33AK 器件的支持",
    "Added section for": "添加了",
    "ADC gain error compensation": "ADC 增益误差补偿",
    "for dsPIC33AK devices": "节（用于 dsPIC33AK 器件）",
    "Added information for MCHV\u2011230VAC\u20111.5kW Motor Control High-Voltage Development Board": "添加了 MCHV-230VAC-1.5kW 电机控制高压开发板的信息",
    "Sliding Mode Observer (SMO)": "滑模观测器 (SMO)",
    "External Interface": "外部接口",
    "section to condense information for MCAF external UI on development boards": "节以精简开发板上 MCAF 外部 UI 的信息",
    "Added guidance for selecting PWM trigger for ADC conversion in": "添加了在",
    "Analog-to-digital conversion": "模数转换",
    "Fault Clearing Logic": "故障清除逻辑",
    "section with guidance on overcurrent faults and MCAPI interaction": "节以提供过流故障和 MCAPI 交互的指导",
    "Creating a custom board configuration": "创建自定义板级配置",
    "section to clarify modification of custom board schema": "节以澄清自定义板级 schema 的修改",
    "board configuration features table": "板级配置功能表",
    "in": "在",
    "Overview of board support in motorBench\u00ae Development Suite": "motorBench Development Suite 中的板级支持概述",
    "Open-loop voltage operation": "开环电压运行",
    "section with more information on ZSM Updated": "节以提供更多 ZSM 信息 更新了",
    "Verify PWM operation": "验证 PWM 运行",
    "subsection to improve instructions for PWM operation verification": "子节以改进 PWM 运行验证说明",
    "Updated Test case and CPU usage sections in": "更新了",
    "Resource Usage": "资源使用",
    "Fixed error in": "修复了",
    "Usage Statistics for MCAF R8": "MCAF R8 使用统计",
    "for XCDSC 3.21": "中 XCDSC 3.21 的错误",
    "on dsPIC33CK64MC105": "（在 dsPIC33CK64MC105 上）",
    "section and UI for motorBench": "节和 motorBench 的 UI",
    "Development Suite system parameters image": "Development Suite 系统参数图像",
    "MCAF Revision History": "MCAF 修订历史",
    "In brief:": "简要：",
    "Initial release as part of motorBench": "作为 motorBench",
    "Development Suite 1.15": "Development Suite 1.15 的一部分首次发布",
    "Internal release:": "内部发布：",
    "Added support for overmodulation": "添加了过调制支持",
    "Added support for DC link compensation": "添加了 DC 母线补偿支持",
    "Added support for wider range of low-voltage motors": "添加了对更宽范围低压电机的支持",
    "Scaling factors": "缩放因子",
    "updated": "已更新",
    "All voltages now use scaling factor of maximum ADC input for the DC link; R1 used": "所有电压现在使用 DC 母线最大 ADC 输入的缩放因子；R1 使用",
    "for FOC voltages": "用于 FOC 电压",
    "Mechanical velocity now uses 1.5 times maximum motor velocity; R1 used 30000 electrical RPM": "机械速度现在使用最大电机速度的 1.5 倍；R1 使用 30000 电气 RPM",
    "Updated HAL for future MCHV-2 support": "更新了 HAL 以支持未来的 MCHV-2",
    "Updated Motor Control Library": "更新了电机控制库",
    "Numerous minor fixes": "大量小幅修复",
    "Release intended as part of motorBench": "作为 motorBench",
    "Development Suite 2.0": "Development Suite 2.0 的一部分发布",
    "Supports use of MCC for system / oscillator module": "支持使用 MCC 进行系统/振荡器模块配置",
    "Completed support for MCHV-2 HAL": "完成了 MCHV-2 HAL 支持",
    "Other minor fixes": "其他小幅修复",
    "Development Suite 2.15": "Development Suite 2.15",
    "MCC peripheral support": "MCC 外设支持",
    "Added new startup method (": "添加了新启动方法（",
    "Weathervane startup": "Weathervane 启动",
    "Development Suite 2.25": "Development Suite 2.25",
    "dsPIC33CK support": "dsPIC33CK 支持",
    "Customize page improvements": "Customize 页面改进",
    "Other minor fixes and improvements": "其他小幅修复和改进",
    "Development Suite 2.35": "Development Suite 2.35",
    "device support for new devices in dsPIC33CK series": "对 dsPIC33CK 系列新器件的器件支持",
    "module with support for": "模块，支持",
    "flux weakening": "弱磁",
    "(FW) and": "(FW) 和",
    "maximum torque per ampere": "最大转矩/电流比",
    "(MTPA)": "(MTPA)",
    "dead-time compensation": "死区补偿",
    "Redesigned": "重新设计了",
    "board service module": "板级服务模块",
    "Development Suite 2.45": "Development Suite 2.45",
    "MCC Melody": "MCC Melody",
    "Added several new features:": "添加了多项新功能：",
    "Single-channel": "单通道",
    "measurement (\u201csingle-shunt\u201d)": "测量（\u201c单分流\u201d）",
    "Triple-channel": "三通道",
    "measurement (\u201ctriple-shunt\u201d)": "测量（\u201c三分流\u201d）",
    "estimator": "估计器",
    "Dynamic current limiting": "动态电流限制",
    "Voltage outer loop control": "电压外环控制",
    "Closed-loop stopping methods": "闭环停止方法",
    "Added new methods for": "添加了新方法用于",
    "Restructured the": "重构了",
    "sample application": "示例应用",
    "and": "和",
    "module": "模块",
    "Added support for internal op-amps": "添加了内部运放支持",
    "Added support for new development boards": "添加了新开发板支持",
    "dsPIC33CK Low Voltage Motor Control (LVMC) Development Board": "dsPIC33CK 低压电机控制 (LVMC) 开发板",
    "MCS MCLV\u201148V\u2011300W Development Board": "MCS MCLV-48V-300W 开发板",
    "Development Suite 2.50": "Development Suite 2.50",
    "SiP devices with MCP8021 gate driver, and MCP802X gate drivers": "带 MCP8021 栅极驱动器的 SiP 器件以及 MCP802X 栅极驱动器",
    "firmware library packaged with MCAF to v2.1": "与 MCAF 打包的固件库升级至 v2.1",
    "Development Suite 2.55": "Development Suite 2.55",
    "In detail:": "详细：",
    "Modules added/removed": "添加/移除的模块",
    "was removed (not required by any other modules)": "被移除（其他模块不需要）",
    "added": "已添加",
    "Core FOC": "核心 FOC",
    "The inverse Clarke transform has been replaced by its conventional variant. (MCAF R1 had swapped": "逆 Clarke 变换已被其常规变体替代。（MCAF R1 交换了",
    "Space vector modulation with phase-shifted inputs has been replaced by an implementation of": "带相移输入的空间矢量调制已被",
    "zero-sequence modulation": "零序调制",
    "that includes clipping in order to implement": "的实现替代，包含削波以实现",
    "overmodulation": "过调制",
    "Overmodulation": "过调制",
    "support has been added.": "支持已添加。",
    "DC link compensation": "DC 母线补偿",
    "Expanded range of supported motors": "扩展了支持的电机范围",
    "Parameter generation tested under a wide range of motor parameters to identify and correct range issues.": "在广泛的电机参数范围内测试了参数生成，以识别和纠正范围问题。",
    "Several shift counts changed to be selected at code generation time (rather than a fixed Q15).": "若干移位计数改为在代码生成时选择（而非固定 Q15）。",
    "Several time delay values (mostly in startup and stall detection) changed to utilize 32-bit counts, so that longer time constants can be supported.": "若干时间延迟值（主要在启动和堵转检测中）改为使用 32 位计数，以支持更长的时间常数。",
    "Some of the PLL calculations were rewritten to prevent overflow.": "部分 PLL 计算被重写以防止溢出。",
    "Scaling factors and operating range": "缩放因子和运行范围",
    "The scaling factors for voltages have been unified to one value based on maximum DC link voltage.": "电压的缩放因子已统一为基于最大 DC 母线电压的一个值。",
    "The scaling factor for motor velocity has been changed to be 1.5 times the base speed of the motor; the capability has been added in MCAF to override this from motorBench": "电机速度的缩放因子已改为电机基速的 1.5 倍；MCAF 中已添加从 motorBench",
    "Development Suite, although as of motorBench": "Development Suite 覆盖此值的功能，尽管截至 motorBench",
    "Development Suite revision 1.35 this is not yet possible.": "Development Suite 1.35 版本此功能尚不可用。",
    "Minimum operating speed is now set based on the minimum electrical frequency selected in motorBench": "最小运行速度现在基于 motorBench",
    "Development Suite.": "Development Suite 中选择的最小电气频率设置。",
    "Fault detection": "故障检测",
    "The torque angle method of stall detection was rewritten to improve accuracy over a wider range of motors.": "堵转检测的转矩角方法被重写以提高在更宽电机范围内的精度。",
    "The Ed method of stall detection was adjusted to remove low-pass filtering that was hindering stall detection with some motors.": "堵转检测的 Ed 方法被调整以移除阻碍某些电机堵转检测的低通滤波。",
    "Test Harness": "测试框架",
    "Added ability to": "添加了",
    "force state change": "强制状态变更",
    "(e.g.": "（例如",
    "Added new interfaces for": "添加了新接口用于",
    "(hardware timer 1)": "（硬件定时器 1）",
    "Added additional functions for": "添加了附加函数用于",
    "Refactored some of the Application Interfaces in BSP, moved LED and test-point related interfaces to HAF": "重构了 BSP 中的部分应用接口，将 LED 和测试点相关接口移至 HAF",
    "Added a new": "添加了新",
    "The version of the Motor Control Library included with MCAF R2 has added a number of new functions, including zero sequence modulation with clipping, and the conventional Inverse Clarke transform.": "MCAF R2 包含的电机控制库版本添加了大量新函数，包括带削波的零序调制和常规逆 Clarke 变换。",
    "Please do not use this version of the Motor Control Library in other projects outside the MCAF.": "请不要在 MCAF 之外的其他项目中使用此版本的电机控制库。",
    "Miscellaneous": "杂项",
    "MCAF version information (\u201cR2/RC9\u201d along with a commit id and build date) has been added to all C source files outside of the libraries.": "MCAF 版本信息（\u201cR2/RC9\u201d以及提交 ID 和构建日期）已添加到库之外的所有 C 源文件中。",
    "Note to the reader: starting with this release, you may see issue tracker keys listed in the revision history in parentheses, such as DB_MC-97. These are present to assist Microchip staff in referring to more detailed information as necessary.": "致读者：从此版本开始，您可能会在修订历史中看到括号中列出的问题跟踪键，如 DB_MC-97。这些键用于帮助 Microchip 工作人员根据需要引用更详细的信息。",
    "MCC compatibility": "MCC 兼容性",
    "MCAF is now compatible with the MCC system module including oscillator setup.": "MCAF 现在与 MCC 系统模块（包括振荡器设置）兼容。",
    "modules of MCAF have been renamed": "模块已被重命名",
    "There is now an mcaf_main.h as well to include function declarations.": "现在还有 mcaf_main.h 以包含函数声明。",
    "MCAF is no longer responsible for producing": "MCAF 不再负责生成",
    "; instead, the MCC": "；而是由 MCC 的",
    "function now calls into MCAF for initialization and the main loop.": "函数调用 MCAF 进行初始化和主循环。",
    "MCAF has yielded responsibility to MCC for generating configuration bits": "MCAF 已将配置位生成的责任交给 MCC",
    "MCAF has yielded responsibility to MCC for oscillator configuration": "MCAF 已将振荡器配置的责任交给 MCC",
    "Some functions in the HAL have been renamed with an": "HAL 中的某些函数已使用",
    "prefix to avoid name conflicts with MCC-generated HAL functions.": "前缀重命名，以避免与 MCC 生成的 HAL 函数的名称冲突。",
    "MCAF is still not compatible with other modules from MCC, including the ADC, UART, and PWM. The HAL within MCAF takes responsibility for configuring and using these modules.": "MCAF 仍不与 MCC 的其他模块（包括 ADC、UART 和 PWM）兼容。MCAF 内的 HAL 负责配置和使用这些模块。",
    "See the documentation for the": "参见",
    "for more information.": "的文档以获取更多信息。",
    "MCHV-2 and MCHV-3 compatibility": "MCHV-2 和 MCHV-3 兼容性",
    "The HAL generated by MCAF is now fully compatible with the MCHV-2 and MCHV-3 development boards. (MCAF R2 did contain the required HAL functions for MCHV-2/MCHV-3 but always generated code for MCLV-2.)": "MCAF 生成的 HAL 现在完全兼容 MCHV-2 和 MCHV-3 开发板。（MCAF R2 确实包含 MCHV-2/MCHV-3 所需的 HAL 函数，但始终为 MCLV-2 生成代码。）",
    "The continuous rated inverter current as entered in motorBench": "在 motorBench",
    "Development Suite is now exactly equal to the maximum dq-frame commanded current amplitude. In MCAF R2, there was a 0.824 derating factor applied.": "Development Suite 中输入的连续额定逆变器电流现在精确等于最大 dq 坐标系指令电流幅值。在 MCAF R2 中，应用了 0.824 的降额因子。",
    "ADC compensation": "ADC 补偿",
    "The ADC current gain matrix is now generated dynamically. In MCAF R2 it was fixed to support unmodified MCLV-2 boards. It now can handle arbitrary gains setup in motorBench": "ADC 电流增益矩阵现在动态生成。在 MCAF R2 中，它固定为支持未修改的 MCLV-2 板。现在可以处理 motorBench",
    "Development Suite.": "Development Suite 中设置的任意增益。",
    "supervisory errata": "监督勘误",
    "for clarity.": "以提高清晰度。",
    "cause stack overflow": "导致堆栈溢出",
    "delay loop for commutation overrides": "换相覆盖的延迟循环",
    "DC link compensation can be disabled by setting the corresponding override bit.": "DC 母线补偿可通过设置相应的覆盖位来禁用。",
    "Added additional functions for the QEI and PWM modules": "添加了 QEI 和 PWM 模块的附加函数",
    "Removed configuration bits and oscillator initialization": "移除了配置位和振荡器初始化",
    "Renamed functions in": "重命名了",
    "modules with": "模块中的函数，使用",
    "A minor error in the inline assembly in": "内联汇编中的一个小错误在",
    "has been fixed.": "中已修复。",
    "This manifested as a build failure (": "表现为构建失败（",
    "Error:": "Error:",
    "Invalid": "Invalid",
    "operands": "operands",
    "specified": "specified",
    ") when building with": "）在使用",
    "; as a reminder, please note that MCAF requires optimization level": "构建时；提醒一下，MCAF 需要优化级别",
    "or higher to meet timing constraints.": "或更高才能满足时序约束。",
    "No other changes have been made.": "未进行其他更改。",
    "Updated documentation for the MC Library is not yet available.": "MC 库的更新文档尚不可用。",
    "Code generation": "代码生成",
    "Improved code generation error messages when an out-of-range error is encountered.": "改进了遇到超范围错误时的代码生成错误消息。",
    "Improved internal mechanisms for calculating parameters in code generation.": "改进了代码生成中计算参数的内部机制。",
    "Overvoltage and undervoltage margins are now set to 2V for MCLV-2 and 20V for MCHV-2.": "过压和欠压裕量现在设为 MCLV-2 的 2V 和 MCHV-2 的 20V。",
    "Development Suite will allow these values to be edited.": "Development Suite 将允许编辑这些值。",
    "Auxiliary reports": "辅助报告",
    "The list of derived parameters in aux-files/report.html has been expanded.": "aux-files/report.html 中的派生参数列表已扩展。",
    "Reports in aux-files/ now include traceability to the corresponding MCAF version.": "aux-files/ 中的报告现在包含对相应 MCAF 版本的可追溯性。",
    "Updated KaTeX to a more recent version.": "将 KaTeX 更新到更新的版本。",
    "Fixed a bug in report.xml, specifically a missing close tag": "修复了 report.xml 中的错误，特别是缺少闭合标签",
    "The file report.xml has been renamed report.xml.txt to avoid triggering an error in MCC.": "文件 report.xml 已重命名为 report.xml.txt 以避免在 MCC 中触发错误。",
    "MCAF version information has been updated to \u201cR3/RC14\u201d.": "MCAF 版本信息已更新为\u201cR3/RC14\u201d。",
    "MCAF copyright date updated to 2018.": "MCAF 版权日期更新为 2018。",
    "Types header files have been pulled out of the": "类型头文件已从",
    "modules \u2013 there is now a": "模块中分离——现在有",
    "Certain state variables have been updated from": "某些状态变量已从",
    "to an appropriate units typedef such as": "更新为适当的单位 typedef，如",
    ", etc.": "等。",
    "Removed unused": "移除了未使用的",
    "function from the": "函数从",
    "module.": "模块。",
    "Unused": "未使用的",
    "removed.": "已移除。",
    "module has been added for": "模块已添加用于",
    "module has been moved to": "模块已移至",
    "module has been temporarily renamed": "模块已临时重命名",
    "until a conflict with MCC can be resolved.": "直到与 MCC 的冲突解决。",
    "MCAF peripheral and system initialization code generation is completely handled by MCC. The only exception to this is the": "MCAF 外设和系统初始化代码生成完全由 MCC 处理。唯一的例外是",
    "peripheral as this is not supported by MCC yet.": "外设，因为 MCC 尚不支持。",
    "functions have been added to use new MCC PWM APIs.": "函数已添加以使用新的 MCC PWM API。",
    "function for retrieving interrupt vector number has been added.": "函数已添加用于获取中断向量号。",
    "Support quadrature encoders as a primary position and velocity estimator": "支持正交编码器作为主位置和速度估计器",
    "Velocity estimated from the": "从",
    ", for use by the velocity control loop, has been corrected to use the filtered velocity": "估计的速度（用于速度控制环）已修正为使用滤波速度",
    "rather than the unfiltered velocity": "而非未滤波速度",
    "index capture support": "索引捕获支持",
    "Parameter customization support": "参数定制支持",
    "Added ability to adjust key MCAF parameters within the motorBench": "添加了在 motorBench",
    "Development Suite user interface.": "Development Suite 用户界面中调整关键 MCAF 参数的能力。",
    "Added \u201cweathervane\u201d startup method": "添加了\u201cweathervane\u201d启动方法",
    "Fixed bug where startup state machine was initialized to": "修复了启动状态机初始化为",
    "state at device reset": "状态（在器件复位时）的 bug",
    "Refactored commutation module to support multiple estimators": "重构换相模块以支持多个估计器",
    "Fixed error in startup hold time calculation so that 32-bit values are now supported": "修复了启动保持时间计算中的错误，现在支持 32 位值",
    "control slew rates with slow commutation steps": "用慢速换相步骤控制压摆率",
    "Corrected state initialization when entering a test mode": "修正了进入测试模式时的状态初始化",
    "Fixed uninitialized": "修复了未初始化的",
    "Style and readability": "风格和可读性",
    "Startup currents in the": "启动电流在",
    "module have been renamed for clarify": "模块中已重命名以澄清",
    "Updated util.h to add assembly comments to inline assembly, for traceability": "更新了 util.h 以向内联汇编添加汇编注释，用于可追溯性",
    "Consistency in MCAF identifier naming:": "MCAF 标识符命名的一致性：",
    "Estimator types changed to": "估计器类型改为",
    "from": "从",
    "Estimator functions changed to": "估计器函数改为",
    "MCC compatibility and dsPIC33CK support": "MCC 兼容性和 dsPIC33CK 支持",
    "MCAF R5 now supports dsPIC33CK devices.": "MCAF R5 现在支持 dsPIC33CK 器件。",
    "Moved": "移动了",
    "definition out of ui.c and into HAL": "定义从 ui.c 移至 HAL",
    "Improved proper encapsulation of device-specific issues through Hardware Access Functions layer": "通过硬件访问函数层改进了器件特定问题的适当封装",
    "Other miscellaneous improvements \u2014 see": "其他杂项改进——见",
    "Diagnostics": "诊断",
    "Updated X2Cscope library": "更新了 X2Cscope 库",
    "Added dsPIC33CK support.": "添加了 dsPIC33CK 支持。",
    "Now allows application to specify buffer": "现在允许应用指定缓冲区",
    "Recompiled with": "重新编译使用",
    "Improve parameter management of pullout synchronization method": "改进了失步同步方法的参数管理",
    "Clarified and corrected angle units in QEI tracking loop": "澄清并修正了 QEI 跟踪环路中的角度单位",
    "ATPLL support": "ATPLL 支持",
    "angle-tracking PLL": "角度跟踪 PLL",
    "(ATPLL) sensorless estimator.": "(ATPLL) 无传感器估计器。",
    "Miscellaneous sensorless estimator issues": "杂项无传感器估计器问题",
    "Categorized ATPLL and PLL estimator state variables to help distinguish core algorithm state from auxiliary state used for logging": "对 ATPLL 和 PLL 估计器状态变量进行了分类，以帮助区分核心算法状态和用于日志的辅助状态",
    "Clarified ATPLL and PLL inductance identifiers and units": "澄清了 ATPLL 和 PLL 电感标识符和单位",
    "Fixed issue involving estimator initialization, and provided initialization hooks for all sensorless estimators": "修复了涉及估计器初始化的问题，并为所有无传感器估计器提供了初始化钩子",
    "Improved naming of": "改进了",
    "to": "到",
    "Improve support for slower transitions to closed-loop in Classic startup": "改进了 Classic 启动中向闭环的较慢过渡支持",
    "Fixed small residual": "修复了小的残余",
    "values in Classic startup": "值（在 Classic 启动中）",
    "Fixed proper assignment of": "修复了",
    "in Weathervane startup": "的正确赋值（在 Weathervane 启动中）",
    "Fixed initialization of startup counter in Weathervane startup": "修复了 Weathervane 启动中启动计数器的初始化",
    "Allow nonzero ALIGN time": "允许非零 ALIGN 时间",
    "Corrected units of": "修正了",
    "Added feature to allow": "添加了允许",
    "open-loop mode in test harness after normal startup": "正常启动后在测试框架中使用开环模式",
    "Development Suite Customize page support": "Development Suite Customize 页面支持",
    "MCAF firmware package can now specify transfer functions used for autotuning in motorBench": "MCAF 固件包现在可以指定 motorBench",
    "Development Suite.": "Development Suite 中用于自动整定的传递函数。",
    "Added \u201cAdvice\u201d pane for guidance based on motor and system parameters.": "添加了基于电机和系统参数提供指导的\u201cAdvice\u201d面板。",
    "Added display of normalized values in engineering units.": "添加了工程单位的归一化值显示。",
    "Included additional": "包含了额外的",
    "Support migration of existing data from previous version of motorBench": "支持从先前版本的 motorBench",
    "Development Suite.": "Development Suite 迁移现有数据。",
    "Upgraded to Motor Control Library 0.20": "升级到电机控制库 0.20",
    "Adds support for dsPIC33CK devices": "添加了 dsPIC33CK 器件支持",
    "Back-ported additional functions used in MCAF R4": "回移植了 MCAF R4 中使用的附加函数",
    "Added section \u201cNormalization factors used in fixed-point representation\u201d": "添加了\u201c定点表示中使用的归一化因子\u201d节",
    "Flux Control": "磁通控制",
    "Dead-time compensation": "死区补偿",
    "Adjustable PWM frequency": "可调 PWM 频率",
    "Added support for adjusting PWM frequency and control frequency as a submultiple of the PWM frequency.": "添加了将 PWM 频率和控制频率调整为 PWM 频率约数倍的支持。",
    "to provide a high-level abstracted interface for custom applications to control and obtain feedback from the motor.": "以提供高层抽象接口供自定义应用控制电机并获取反馈。",
    "Added a": "添加了",
    "that demonstrates the use of": "演示了",
    "to implement a simple user interface with pushbuttons and the potentiometer.": "以实现带按钮和电位器的简单用户界面。",
    "to extend velocity range.": "以扩展速度范围。",
    "to improve torque and efficiency for": "以提高",
    "motors.": "电机的转矩和效率。",
    "Refactored FOC with structural changes to support flux weakening and MTPA.": "重构了 FOC 并进行结构变更以支持弱磁和 MTPA。",
    "For more information, see": "更多信息见",
    "Velocity loop current limit": "速度环电流限制",
    "Saturation and anti-windup": "饱和与抗积分饱和",
    "to mitigate some of the effects of": "以减轻",
    "deadtime distortion": "死区失真",
    "Added support for dsPIC33CK64MP105 and dsPIC33CK64MC105": "添加了对 dsPIC33CK64MP105 和 dsPIC33CK64MC105 的支持",
    "Board service module": "板级服务模块",
    "Restructured to improve timing robustness and to interface with the": "重构以提高时序鲁棒性并与",
    "changes for more information.": "的变更以获取更多信息。",
    "Added feature to": "添加了功能以",
    "override d-axis current computation": "覆盖 d 轴电流计算",
    ", preventing flux control module from changing it, and allowing it to be changed via real-time diagnostic tools.": "，防止磁通控制模块更改它，并允许通过实时诊断工具更改。",
    "Added read-only parameter calculations such as Saliency ratio": "添加了只读参数计算，如凸极比",
    "Included additional customizable parameters.": "包含了额外的可定制参数。",
    "Improvements in modularity": "模块化改进",
    "All calls to MCC HAL are now made through HAF": "所有对 MCC HAL 的调用现在通过 HAF 进行",
    "Removed directly modifying registers to clear status bits": "移除了直接修改寄存器以清除状态位的操作",
    "Refactored data flow interface for estimators and flux control module to reduce tight coupling": "重构了估计器和磁通控制模块的数据流接口以减少紧密耦合",
    "Refactored back-emf calculation for use by estimators and flux control module": "重构了反电动势计算以供估计器和磁通控制模块使用",
    "Naming improvements": "命名改进",
    "Improved names for PWM generators": "改进了 PWM 发生器的名称",
    "Replaced inconsistent PI parameters": "替换了不一致的 PI 参数",
    "Removed": "移除了",
    "prefix from ATPLL constants": "前缀（从 ATPLL 常量中）",
    "Rename test harness functions to use verb \u201cTrigger\u201d for clarification (TriggerSeizure, TriggerStackOverflow)": "重命名测试框架函数以使用动词\u201cTrigger\u201d以澄清 (TriggerSeizure, TriggerStackOverflow)",
    "Addressed potential naming collision between PLL and ATPLL": "解决了 PLL 和 ATPLL 之间的潜在命名冲突",
    "Miscellaneous firmware issues": "杂项固件问题",
    "Improve how velocities are represented in generated code in parameters/* files": "改进了 parameters/* 文件中生成代码的速度表示方式",
    "Removed unnecessary and added missing #include statements in several locations": "在多处移除了不必要的并添加了缺失的 #include 语句",
    "Tracking loop Kp value can now vary between a Q8 - Q15 value": "跟踪环路 Kp 值现在可在 Q8 到 Q15 值之间变化",
    "Fixed half-PWM-cycle short circuit across motor during entry to STOPPING state": "修复了进入 STOPPING 状态期间电机上的半 PWM 周期短路",
    "current_measure": "current_measure",
    "module to support": "模块以支持",
    "single-channel": "单通道",
    "and multi-channel current measurement": "和多通道电流测量",
    "dynamic current limit": "动态电流限制",
    "and ZS/MT hybrid estimator modules": "和 ZS/MT 混合估计器模块",
    "to use": "以使用",
    "timer interfaces.": "定时器接口。",
    "Dynamic current limit": "动态电流限制",
    "to allow short transient currents above the continuous current limit.": "以允许短时瞬态电流超过连续电流限制。",
    "Zero-Speed / Maximum Torque (ZS/MT) estimator": "零速/最大转矩 (ZS/MT) 估计器",
    "estimator": "估计器",
    "initial position correction startup": "初始位置校正启动",
    "Refactored startup interface to accommodate the requirements of ZS/MT initial position correction startup method.": "重构了启动接口以适应 ZS/MT 初始位置校正启动方法的要求。",
    "Refactored FOC": "重构了 FOC",
    "forward path": "前向通道",
    "and commutation module with structural changes to support": "和换相模块并进行结构变更以支持",
    "intrusive estimators": "侵入式估计器",
    "Binary hard switching hybrid estimator": "二进制硬切换混合估计器",
    "Added Binary hard switching hybrid estimator": "添加了二进制硬切换混合估计器",
    "Added new interfaces to the": "添加了新接口到",
    "module of": "模块（属于",
    "AN1292 PLL estimator": "AN1292 PLL 估计器",
    "that enables it to interact with the hybrid estimator.": "）使其能够与混合估计器交互。",
    "Closed loop stopping methods": "闭环停止方法",
    "closed-loop stopping": "闭环停止",
    "methods to restart motion quickly with certain types of estimators": "方法以使用某些类型的估计器快速重启运动",
    "Voltage control outer loop": "电压控制外环",
    "Updated the FOC module to support outer": "更新了 FOC 模块以支持外",
    "in addition to the existing outer velocity loop": "（除现有的外速度环之外）",
    "Added methods to get and set the application fault code.": "添加了获取和设置应用故障代码的方法。",
    "Function calls to user-defined ADC": "对用户定义 ADC 的函数调用",
    "functions can now be enabled or disabled in the Customize page of motorBench": "函数现在可在 motorBench",
    "Restructured": "重构了",
    "module": "模块",
    "to separate MCAF related code from the": "以将 MCAF 相关代码与",
    "See": "见",
    "for more details.": "以获取更多详情。",
    "Single and multi-channel current measurement": "单通道和多通道电流测量",
    "current measurement (\u201csingle-shunt\u201d)": "电流测量（\u201c单分流\u201d）",
    "Upgrades to the": "升级了",
    "component to support one/two/three channel current measurement schemes": "组件以支持一/二/三通道电流测量方案",
    "Updated FOC": "更新了 FOC",
    "feedback path": "反馈通道",
    "to optionally use a": "以可选地使用",
    "three-input Clarke transform": "三输入 Clarke 变换",
    "to support three-channel current measurement.": "以支持三通道电流测量。",
    "Internal op amp support": "内部运放支持",
    "Added support for internal op amps on dsPIC": "添加了 dsPIC",
    "DSC devices for motor phase current measurement": "DSC 器件上用于电机相电流测量的内部运放支持",
    "Development board support": "开发板支持",
    "triggered average": "触发平均",
    "calculation": "计算",
    "Asymmetric perturbation": "非对称扰动",
    "Added override for": "添加了覆盖",
    "Added new customizable parameters": "添加了新的可定制参数",
    "Decoupled customization parameter for motor": "解耦了电机的定制参数",
    "startup speed": "启动速度",
    "minimum speed command": "最小速度指令",
    "Made minor improvements in overall Customize page user interface behavior": "对 Customize 页面整体用户界面行为进行了小幅改进",
    "Miscellaneous firmware improvements and issues": "杂项固件改进和问题",
    "module to allow runtime adjustment of the tuning parameter for Ke using a real time debug tool such as": "模块以允许使用实时调试工具（如",
    "Compensated for time delays in voltage input of sensorless estimators": "补偿了无传感器估计器电压输入中的时间延迟",
    "Customize parameter": "Customize 参数",
    "to select the voltage feedback for sensorless estimators from zero sequence shifted voltage or unshifted voltage from the FOC": "以从零序移位电压或 FOC 的未移位电压中选择无传感器估计器的电压反馈",
    "Updated DC link voltage scaling to allow a different gain compared to ADC full-scale": "更新了 DC 母线电压缩放以允许与 ADC 满量程不同的增益",
    "stall detect": "堵转检测",
    "to detect motor stall condition only after the motor startup is complete": "以仅在电机启动完成后检测电机堵转条件",
    "Fixed an issue with": "修复了",
    "ADC offset compensation routine": "ADC 偏置补偿例程",
    "executing concurrently in the": "在",
    "state": "状态中并发执行的问题",
    "Inverter bridge temperature measurement": "逆变桥温度测量",
    "overtemperature fault": "过温故障",
    "Removed the use of direction flag in the UI module from": "从 UI 模块中移除了方向标志的使用",
    "commutation": "换相",
    "mcapi": "mcapi",
    "modules": "模块",
    "Added new instruction cycle optimized right shift functions in": "添加了新的指令周期优化的右移函数到",
    "Added new functions to the": "添加了新函数到",
    "module in support of updates to other modules in MCAF": "模块以支持 MCAF 中其他模块的更新",
    "Consolidated low-pass filter implementation variants into one canonical low-pass filter implementation in filter.h": "将低通滤波器实现变体合并为 filter.h 中的一个规范低通滤波器实现",
    "Fixed an issue with motor startup state machine that caused it to lose synchronization with MCAF state machine at initialization": "修复了电机启动状态机在初始化时与 MCAF 状态机失去同步的问题",
    "to use a fixed value of minimum pulse width on PWMxL channels rather than a ramp of PWMxL duty cycle from zero": "以在 PWMxL 通道上使用固定的最小脉冲宽度值，而非从零开始的 PWMxL 占空比斜坡",
    "to eliminate all instances of global variable access of": "以消除",
    "board": "板",
    "Custom board support": "自定义板级支持",
    "custom board support": "自定义板级支持",
    "SiP devices": "SiP 器件",
    "with MCP8021 gate driver, and MCP802X gate drivers": "带 MCP8021 栅极驱动器以及 MCP802X 栅极驱动器",
    "Added new system parameter": "添加了新系统参数",
    "to support Custom Board Support": "以支持自定义板级支持",
    "Moved coastdown parameters into": "将惯性减速参数移入",
    "group": "组",
    "Added selection of real-time": "添加了实时",
    "diagnostic kernel": "诊断内核",
    "Updated generated code to reference the primary estimator consistent with Customize UI": "更新了生成代码以引用与 Customize UI 一致的主估计器",
    "section to spell out \u201cZero-Speed / Maximum Torque\u201d consistently": "节以一致地拼写\u201cZero-Speed / Maximum Torque\u201d",
    "Fixed a bug where voltage control gains could cause parameter out-of-range error during code generation, even if voltage controller is not selected": "修复了电压控制增益可能在代码生成期间导致参数超范围错误的 bug（即使未选择电压控制器）",
    "Updated code generation to skip parameter calculations for features that are disabled in Customize page": "更新了代码生成以跳过 Customize 页面中禁用功能的参数计算",
    "Made warnings for Single Channel and Triple Channel current measurement consistent in Customize UI": "使 Customize UI 中单通道和三通道电流测量的警告一致",
    "Added support for input validation expressions in numeric fields": "添加了对数字字段中输入验证表达式的支持",
    "Added \u201cprobe current\u201d parameter": "添加了\u201cprobe current\u201d参数",
    "Various improvements to": "对",
    "ZS/MT algorithm": "ZS/MT 算法的各种改进",
    "MCAPI fault logic": "MCAPI 故障逻辑",
    "Fixed bug in": "修复了",
    "to allow MCAPI_FAULT_FLAG_OVERCURRENT or MCAPI_FAULT_FLAG_MOTOR_DRIVE faults to be cleared if there are other active faults. (See": "中的 bug，以允许在其他活动故障存在时清除 MCAPI_FAULT_FLAG_OVERCURRENT 或 MCAPI_FAULT_FLAG_MOTOR_DRIVE 故障。（见",
    "MCAPI errata": "MCAPI 勘误",
    ".)": "。）",
    "Ensured": "确保了",
    "is called before reading new faults": "在读取新故障之前被调用",
    "Added comments explaining empty HAL functions": "添加了说明空 HAL 函数的注释",
    "Removed deprecated": "移除了已弃用的",
    "functions from": "函数从",
    "Renamed ADC value getter functions for DC link voltage and current, so they are more consistent with ADC channel names": "重命名了 DC 母线电压和电流的 ADC 值获取函数，使其与 ADC 通道名称更一致",
    "Clarified intentional use of overflow in qei.h": "澄清了 qei.h 中溢出的有意使用",
    "Updated precision in current sense time constants for": "更新了",
    "Fixed bug in current calibration with single-channel current sense": "修复了单通道电流检测的电流校准 bug",
    "Fixed issue where high L/R ratio of specific motors leads to": "修复了特定电机高 L/R 比导致",
    "of zero": "为零的问题",
    "inline": "inline",
    "functions not declared properly as": "函数未正确声明为",
    "static": "static",
    "when compiled with newer C99-compliant compilers": "（在使用更新的 C99 兼容编译器编译时）",
    "assembly code in": "汇编代码在",
    "Changed usage of": "更改了",
    "in foc.c to maintain consistent usage of Motor Control Library functions": "在 foc.c 中的使用以保持电机控制库函数使用的一致性",
    "Added function comments explaining decision tree logic in": "添加了函数注释以说明中的决策树逻辑",
    "Added doc comments to": "添加了文档注释到",
    "Refactored": "重构了",
    "to take": "以接受",
    "volatile": "volatile",
    "instead of": "而非",
    "dsPIC33AK support": "dsPIC33AK 支持",
    "MCAF R9 adds support for the first dsPIC33A devices.": "MCAF R9 添加了对首批 dsPIC33A 器件的支持。",
    "MCAF targets fixed-point math with 16-bit values and selected 32-bit state variables. This is sufficient to handle 12-bit ADC inputs and to handle the quantization needs of filters, integrators, and other time-dependent algorithms. Floating-point support (dsPIC33A only) is planned for a future version of MCAF.": "MCAF 以 16 位值和选定的 32 位状态变量为目标进行定点数学运算。这足以处理 12 位 ADC 输入并满足滤波器、积分器和其他时间相关算法的量化需求。浮点支持（仅 dsPIC33A）计划在未来版本的 MCAF 中实现。",
    "Supported devices:": "支持的器件：",
    "Use XC-DSC 3.21 or newer with these devices.": "这些器件使用 XC-DSC 3.21 或更新版本。",
    "ADC calibration and compensation": "ADC 校准与补偿",
    "Improved current offset calibration to allow wider maximum range in the Customize page, and cause a fault if outside acceptable limits": "改进了电流偏置校准以允许 Customize 页面中更宽的最大范围，并在超出可接受限制时产生故障",
    "Corrected comment in adc_compensation_types.h to describe gain values as Q14, not Q15": "修正了 adc_compensation_types.h 中的注释，将增益值描述为 Q14 而非 Q15",
    "Implemented ADC gain compensation for dsPIC33AK devices": "为 dsPIC33AK 器件实现了 ADC 增益补偿",
    "Add option to apply intentional offset, for testing current calibration": "添加了应用有意偏移的选项，用于测试电流校准",
    "MCHV\u2011230VAC\u20111.5kW Motor Control High-Voltage Development Board": "MCHV-230VAC-1.5kW 电机控制高压开发板",
    "Added power-on delay of 50ms to prevent overcurrent fault due to false trip from current inrush pulse on": "添加了 50ms 上电延迟以防止电流涌入脉冲导致的误触发过流故障",
    "continuous current limit": "连续电流限制",
    "Added option to remap a pin to a PCIxR PWM fault source in custom board configuration": "添加了在自定义板级配置中将引脚重映射到 PCIxR PWM 故障源的选项",
    "Included board ID in generated hal_params.h, to add traceability and context": "在生成的 hal_params.h 中包含板 ID，以增加可追溯性和上下文",
    "Moved potentiometer ADC signal to optional inputs; a potentiometer is no longer required": "将电位器 ADC 信号移至可选输入；不再需要电位器",
    "Added optional power-on delay": "添加了可选的上电延迟",
    "Removed comparator DAC configuration from MCAF HAL to utilize MCC configuration instead": "从 MCAF HAL 中移除了比较器 DAC 配置以改用 MCC 配置",
    "Fix bug in": "修复了",
    "which incorrectly disabled high-side output but not low-side output": "中的 bug，错误地禁用了高侧输出但未禁用低侧输出",
    "Changed HAL UART functions to generate only if UART is available on selected board": "更改了 HAL UART 函数以仅在所选板上有 UART 时生成",
    "MISRA compliance": "MISRA 合规性",
    "Reduced a significant number of MISRA violations by addressing these three rules:": "通过解决以下三条规则减少了大量 MISRA 违规：",
    "Rule 1.5: Obsolescent language features shall not be used \u2014 use": "规则 1.5：不应使用过时的语言特性——使用",
    "void": "void",
    "in function parameter list for no-argument functions": "于无参函数的参数列表中",
    "Rule 15.7: All if - else if constructs shall be terminated with an else statement": "规则 15.7：所有 if - else if 构造应以 else 语句终止",
    "Rule 21.1: define and undef directives shall not be used on a reserved identifier or reserved macro name": "规则 21.1：define 和 undef 指令不应用于保留标识符或保留宏名",
    "Fixed bug preventing use of optional analog inputs": "修复了阻止使用可选模拟输入的 bug",
    "Provided tuning parameters for the ATPLL estimator": "为 ATPLL 估计器提供了整定参数",
    "Added options to enable/disable test harness and test profiling through Customize page": "添加了通过 Customize 页面启用/禁用测试框架和测试性能分析的选项",
    "Include yellow indicator in Customize UI to note further guidance in release notes": "在 Customize UI 中包含黄色指示器以注明发行说明中的进一步指导",
    "Limited active damping current to maximum startup current": "将主动阻尼电流限制为最大启动电流",
    "Various bug fixes and improvements to": "各种 bug 修复和改进",
    "Corrected anti-windup comment in": "修正了中的抗积分饱和注释",
    "Ensured diagnostic UART TX pin sets output high at initialization": "确保诊断 UART TX 引脚在初始化时设置输出为高",
    "Fixed watchdog timeout when using motor phase to PWM mapping that is different from ABC \u21d4 PWM123": "修复了使用不同于 ABC \u21d4 PWM123 的电机相位到 PWM 映射时的看门狗超时",
    "and moved associated state to": "并将关联状态移至",
    "in the sample application": "（在示例应用中）",
    "Fixed code generation for outer voltage loop": "修复了外电压环的代码生成",
    "Added argument to": "添加了参数到",
    "to specify initial filter state": "以指定初始滤波器状态",
    "Fixed": "修复了",
    "in gate_drive.c to refer to symbolic": "在 gate_drive.c 中以引用符号",
    "instead of its value of zero": "而非其零值",
    "Removed use of Q15, Q14, Q13, etc. macros": "移除了 Q15、Q14、Q13 等宏的使用",
    "Removed blank commutation_params.h file": "移除了空白的 commutation_params.h 文件",
    "Included floating-point": "包含了浮点",
    "macros for each configurable parameter in generated parameters files": "宏（在生成的参数文件中为每个可配置参数）",
    "Changed software overcurrent \u201cstall\u201d detector to disabled by default": "将软件过流\u201c堵转\u201d检测器改为默认禁用",
    "Removed remaining RTDM content from firmware package": "从固件包中移除了剩余的 RTMD 内容",
    "Changed include guards in all MCAF header files to use": "更改了所有 MCAF 头文件中的包含保护以使用",
    "identifiers starting with": "标识符以",
    "prefix": "前缀开头",
    "Provided": "提供了",
    "in util.h rather than processor-specific builtins": "在 util.h 中而非处理器特定的内建函数",
    "7.5. Revision History": "7.5. 修订历史",
    "7.5.1. MCAF Documentation Revision History": "7.5.1. MCAF 文档修订历史",
    "7.5.2. MCAF Revision History": "7.5.2. MCAF 修订历史",
    "7.5.2.1. MCAF R2 RC9": "7.5.2.1. MCAF R2 RC9",
    "7.5.2.1.1. Modules added/removed": "7.5.2.1.1. 添加/移除的模块",
    "7.5.2.1.2. Core FOC": "7.5.2.1.2. 核心 FOC",
    "7.5.2.1.3. Overmodulation": "7.5.2.1.3. 过调制",
    "7.5.2.1.4. DC link compensation": "7.5.2.1.4. DC 母线补偿",
    "7.5.2.1.5. Expanded range of supported motors": "7.5.2.1.5. 扩展支持的电机范围",
    "7.5.2.1.6. Scaling factors and operating range": "7.5.2.1.6. 缩放因子和运行范围",
    "7.5.2.1.7. Fault detection": "7.5.2.1.7. 故障检测",
    "7.5.2.1.8. Test Harness": "7.5.2.1.8. 测试框架",
    "7.5.2.1.9. HAL": "7.5.2.1.9. HAL",
    "7.5.2.1.10. Motor Control Library": "7.5.2.1.10. 电机控制库",
    "7.5.2.1.11. Miscellaneous": "7.5.2.1.11. 杂项",
    "7.5.2.2. MCAF R3 RC14": "7.5.2.2. MCAF R3 RC14",
    "7.5.2.2.1. Modules added/removed": "7.5.2.2.1. 添加/移除的模块",
    "7.5.2.2.2. MCC compatibility": "7.5.2.2.2. MCC 兼容性",
    "7.5.2.2.3. MCHV-2 and MCHV-3 compatibility": "7.5.2.2.3. MCHV-2 和 MCHV-3 兼容性",
    "7.5.2.2.4. Scaling factors and operating range": "7.5.2.2.4. 缩放因子和运行范围",
    "7.5.2.2.5. ADC compensation": "7.5.2.2.5. ADC 补偿",
    "7.5.2.2.6. Core FOC": "7.5.2.2.6. 核心 FOC",
    "7.5.2.2.7. Fault detection": "7.5.2.2.7. 故障检测",
    "7.5.2.2.8. Test Harness": "7.5.2.2.8. 测试框架",
    "7.5.2.2.9. HAL": "7.5.2.2.9. HAL",
    "7.5.2.2.10. Motor Control Library": "7.5.2.2.10. 电机控制库",
    "7.5.2.2.11. Code generation": "7.5.2.2.11. 代码生成",
    "7.5.2.2.12. Auxiliary reports": "7.5.2.2.12. 辅助报告",
    "7.5.2.2.13. Miscellaneous": "7.5.2.2.13. 杂项",
    "7.5.2.3. MCAF R4 RC12": "7.5.2.3. MCAF R4 RC12",
    "7.5.2.3.1. Modules added/removed": "7.5.2.3.1. 添加/移除的模块",
    "7.5.2.3.2. MCC compatibility": "7.5.2.3.2. MCC 兼容性",
    "7.5.2.3.3. Quadrature encoder support": "7.5.2.3.3. 正交编码器支持",
    "7.5.2.3.4. Parameter customization support": "7.5.2.3.4. 参数定制支持",
    "7.5.2.3.5. Startup": "7.5.2.3.5. 启动",
    "7.5.2.3.6. Core FOC": "7.5.2.3.6. 核心 FOC",
    "7.5.2.3.7. Code generation": "7.5.2.3.7. 代码生成",
    "7.5.2.3.8. Test Harness": "7.5.2.3.8. 测试框架",
    "7.5.2.3.9. Style and readability": "7.5.2.3.9. 风格和可读性",
    "7.5.2.4. MCAF R5 RC11": "7.5.2.4. MCAF R5 RC11",
    "7.5.2.4.1. Modules added/removed": "7.5.2.4.1. 添加/移除的模块",
    "7.5.2.4.2. MCC compatibility and dsPIC33CK support": "7.5.2.4.2. MCC 兼容性和 dsPIC33CK 支持",
    "7.5.2.4.3. HAL": "7.5.2.4.3. HAL",
    "7.5.2.4.4. Diagnostics": "7.5.2.4.4. 诊断",
    "7.5.2.4.5. Quadrature encoder support": "7.5.2.4.5. 正交编码器支持",
    "7.5.2.4.6. ATPLL support": "7.5.2.4.6. ATPLL 支持",
    "7.5.2.4.7. Miscellaneous sensorless estimator issues": "7.5.2.4.7. 杂项无传感器估计器问题",
    "7.5.2.4.8. Startup": "7.5.2.4.8. 启动",
    "7.5.2.4.9. Test Harness": "7.5.2.4.9. 测试框架",
    "7.5.2.4.10. motorBench": "7.5.2.4.10. motorBench",
    "7.5.2.4.11. Motor Control Library": "7.5.2.4.11. 电机控制库",
    "7.5.2.4.12. Auxiliary reports": "7.5.2.4.12. 辅助报告",
    "7.5.2.5. MCAF R6 RC8": "7.5.2.5. MCAF R6 RC8",
    "7.5.2.5.1. Modules added/removed": "7.5.2.5.1. 添加/移除的模块",
    "7.5.2.5.2. Adjustable PWM frequency": "7.5.2.5.2. 可调 PWM 频率",
    "7.5.2.5.3. Motion Control API": "7.5.2.5.3. 运动控制 API",
    "7.5.2.5.4. Flux Control": "7.5.2.5.4. 磁通控制",
    "7.5.2.5.5. Dead-time compensation": "7.5.2.5.5. 死区补偿",
    "7.5.2.5.6. dsPIC33CK support": "7.5.2.5.6. dsPIC33CK 支持",
    "7.5.2.5.7. Board service module": "7.5.2.5.7. 板级服务模块",
    "7.5.2.5.8. Test Harness": "7.5.2.5.8. 测试框架",
    "7.5.2.5.9. motorBench": "7.5.2.5.9. motorBench",
    "7.5.2.5.10. Improvements in modularity": "7.5.2.5.10. 模块化改进",
    "7.5.2.5.11. Naming improvements": "7.5.2.5.11. 命名改进",
    "7.5.2.5.12. Miscellaneous firmware issues": "7.5.2.5.12. 杂项固件问题",
    "7.5.2.6. MCAF R7 RC37": "7.5.2.6. MCAF R7 RC37",
    "7.5.2.6.1. Modules added/removed": "7.5.2.6.1. 添加/移除的模块",
    "7.5.2.6.2. MCC Melody": "7.5.2.6.2. MCC Melody",
    "7.5.2.6.3. Dynamic current limit": "7.5.2.6.3. 动态电流限制",
    "7.5.2.6.4. Zero-Speed / Maximum Torque (ZS/MT) estimator": "7.5.2.6.4. 零速/最大转矩 (ZS/MT) 估计器",
    "7.5.2.6.5. Binary hard switching hybrid estimator": "7.5.2.6.5. 二进制硬切换混合估计器",
    "7.5.2.6.6. Closed loop stopping methods": "7.5.2.6.6. 闭环停止方法",
    "7.5.2.6.7. Voltage control outer loop": "7.5.2.6.7. 电压控制外环",
    "7.5.2.6.8. MCAPI": "7.5.2.6.8. MCAPI",
    "7.5.2.6.9. Main application": "7.5.2.6.9. 主应用",
    "7.5.2.6.10. Single and multi-channel current measurement": "7.5.2.6.10. 单通道和多通道电流测量",
    "7.5.2.6.11. Internal op amp support": "7.5.2.6.11. 内部运放支持",
    "7.5.2.6.12. Development board support": "7.5.2.6.12. 开发板支持",
    "7.5.2.6.13. Test harness": "7.5.2.6.13. 测试框架",
    "7.5.2.6.14. motorBench": "7.5.2.6.14. motorBench",
    "7.5.2.6.15. Miscellaneous firmware improvements and issues": "7.5.2.6.15. 杂项固件改进和问题",
    "7.5.2.7. MCAF R8 RC38": "7.5.2.7. MCAF R8 RC38",
    "7.5.2.7.1. Modules added/removed": "7.5.2.7.1. 添加/移除的模块",
    "7.5.2.7.2. Custom board support": "7.5.2.7.2. 自定义板级支持",
    "7.5.2.7.3. motorBench": "7.5.2.7.3. motorBench",
    "7.5.2.7.4. Zero-Speed / Maximum Torque (ZS/MT) estimator": "7.5.2.7.4. 零速/最大转矩 (ZS/MT) 估计器",
    "7.5.2.7.5. Diagnostics": "7.5.2.7.5. 诊断",
    "7.5.2.7.6. MCAPI fault logic": "7.5.2.7.6. MCAPI 故障逻辑",
    "7.5.2.7.7. Miscellaneous firmware improvements and issues": "7.5.2.7.7. 杂项固件改进和问题",
    "7.5.2.8. MCAF R9 RC31": "7.5.2.8. MCAF R9 RC31",
    "7.5.2.8.1. Modules added/removed": "7.5.2.8.1. 添加/移除的模块",
    "7.5.2.8.2. dsPIC33AK support": "7.5.2.8.2. dsPIC33AK 支持",
    "7.5.2.8.3. ADC calibration and compensation": "7.5.2.8.3. ADC 校准与补偿",
    "7.5.2.8.4. Test harness": "7.5.2.8.4. 测试框架",
    "7.5.2.8.5. Development board support": "7.5.2.8.5. 开发板支持",
    "7.5.2.8.6. Custom board support": "7.5.2.8.6. 自定义板级支持",
    "7.5.2.8.7. HAL": "7.5.2.8.7. HAL",
    "7.5.2.8.8. MISRA compliance": "7.5.2.8.8. MISRA 合规性",
    "7.5.2.8.9. motorBench": "7.5.2.8.9. motorBench",
    "7.5.2.8.10. Startup": "7.5.2.8.10. 启动",
    "7.5.2.8.11. Zero-Speed / Maximum Torque (ZS/MT) estimator": "7.5.2.8.11. 零速/最大转矩 (ZS/MT) 估计器",
    "7.5.2.8.12. Miscellaneous firmware improvements and issues": "7.5.2.8.12. 杂项固件改进和问题",
    "Related Documents": "相关文档",
    "Frequently Asked Questions (FAQ)": "常见问题 (FAQ)",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
