# -*- coding: utf-8 -*-
import txutil

rel = "components/supervisory"
title_zh = "4.6. 监控算法"

m = {
    "Components": "组件",
    "Supervisory Algorithms": "监控算法",
    "4.6. Supervisory Algorithms": "4.6. 监控算法",
    "Supervisory algorithms include:": "监控算法包括：",
    "Monitoring (including fault detection)": "监控（包括故障检测）",
    "Overvoltage/undervoltage detection": "过压/欠压检测",
    "Overcurrent detection": "过流检测",
    "Overtemperature detection": "过温检测",
    "Watchdog timer management": "看门狗定时器管理",
    "Stall detection and recovery": "堵转检测和恢复",
    "Other supervisory algorithms": "其他监控算法",
    "Thermal management": "热管理",
    "Saturation and antiwindup management (if not already present in the velocity and current controllers)": "饱和和反饱和管理（如果速度和电流控制器中尚未包含）",
    "Adaptive estimators (e.g. online resistance estimation)": "自适应估计器（例如在线电阻估计）",
    "Field weakening": "弱磁控制",
    "Maximum torque per ampere (MTPA) controllers": "最大转矩每安培（MTPA）控制器",
    "Implementation Notes": "实现说明",
    "4.6.1. Implementation Notes": "4.6.1. 实现说明",
    "Stall Detection": "堵转检测",
    "4.6.1.1. Stall Detection": "4.6.1.1. 堵转检测",
    "Stall detection consists of five methods intended to detect an overloaded or stalled motor:": "堵转检测由五种方法组成，用于检测过载或堵转的电机：",
    "Underspeed": "速度不足",
    "— If the motor velocity estimator remains accurate, a stalled motor can be detected if the magnitude of velocity estimate drops below a threshold.": "——如果电机速度估计器保持准确，当速度估计的幅值降至阈值以下时，可以检测到电机堵转。",
    "Variance": "方差",
    "— In the event that a sensorless angle estimator loses synchronism with motor back-emf, the motor will tend to stall but the sensorless estimator may continue to estimate a nonzero electrical frequency. Under these conditions, voltages and currents exhibit oscillations at the estimated electrical frequency. Variance detection attempts to identify voltage and current oscillations.": "——如果无传感器角度估计器与电机反电动势失去同步，电机将趋于堵转，但无传感器估计器可能继续估计非零电气频率。在这种情况下，电压和电流在估计的电气频率处表现出振荡。方差检测试图识别电压和电流振荡。",
    "Negative Ed": "负 Ed",
    "— Spikes in negative d-axis estimated back-emf (": "——负 d 轴估计反电动势（",
    ") can occur when a motor stalls and a sensorless angle estimator loses synchronism. This can be used as a detection method.": "）的尖峰可能在电机堵转且无传感器角度估计器失去同步时出现。这可以用作检测方法。",
    "Torque angle": "转矩角",
    "— The angle between estimated back-emf and motor terminal voltage increases as the motor becomes more heavily loaded or stalls. This is equivalent mathematically to a ratio of back-emf magnitude to terminal voltage dropping below a speed-dependent threshold.": "——估计反电动势与电机端电压之间的角度随电机负载增加或堵转而增大。这在数学上等价于反电动势幅值与端电压的比值降至低于速度相关阈值。",
    "Software overcurrent": "软件过流",
    "— Heavily loaded motors may exceed acceptable levels of stator current.": "——重载电机可能超过可接受的定子电流水平。",
    "Different motors present different symptoms of a stalled motor, which are detected by different algorithms of the ones listed above. All of the algorithms have some kind of filter or delay to avoid premature or false detection. (see": "不同电机呈现不同的堵转症状，由上述不同算法检测。所有算法都有某种滤波器或延迟以避免过早或误检测。（见",
    "errata": "勘误",
    "More specific information is available on": "更具体的信息可在",
    "monitoring": "监控",
    "(including stall detection), and": "（包括堵转检测）和",
    "recovery": "恢复",
    "in the corresponding documents.": "的相关文档中找到。",
    "Overtemperature Detection": "过温检测",
    "4.6.1.2. Overtemperature Detection": "4.6.1.2. 过温检测",
    "MCAF provides an overtemperature detection fault for": "MCAF 为",
    "boards which provide bridge temperature measurement": "提供桥臂温度测量的电路板",
    ", added in MCAF R7.": "提供过温检测故障，在 MCAF R7 中添加。",
    "A fault is triggered if the": "如果",
    "filtered bridge temperature": "滤波后的桥臂温度",
    "exceeds a specified threshold. This provides some noise immunity from spikes in the raw temperature signal.": "超过指定阈值，则触发故障。这提供了一定的抗噪声能力，以避免原始温度信号中的尖峰影响。",
    "Other Algorithms": "其他算法",
    "4.6.1.3. Other Algorithms": "4.6.1.3. 其他算法",
    "MCAF R1 – R5 do not include any of these algorithms:": "MCAF R1 – R5 不包含以下任何算法：",
    "Adaptive estimators": "自适应估计器",
    "Watchdog Timer Management": "看门狗定时器管理",
    "4.6.1.4. Watchdog Timer Management": "4.6.1.4. 看门狗定时器管理",
    "The": "The ",
    "module leverages the watchdog timer found in PIC": "模块利用了 PIC",
    "microcontroller and dsPIC": "微控制器和 dsPIC",
    "DSC devices. The hardware watchdog timeout is relatively simple, just a counter that automatically increments and causes a watchdog reset if it overflows; firmware prevents this by clearing the watchdog timer as a signal that it is operating normally, so that in the event that a blocking operation unexpectedly stops the firmware from being responsive, a reset will occur.": "DSC 器件中的看门狗定时器。硬件看门狗超时相对简单，只是一个自动递增的计数器，溢出时会导致看门狗复位；固件通过清除看门狗定时器作为其正常运行的信号来防止这种情况，因此如果阻塞操作意外地使固件停止响应，将发生复位。",
    "The MCAF uses the hardware watchdog timer to catch unresponsive code in": "MCAF 使用硬件看门狗定时器来捕获",
    "both": "中",
    "the main loop and the control": "主循环和控制",
    ". It does this by requiring two simple tasks to run, one in the main loop and the other in the control": "的不响应代码。它通过要求运行两个简单任务来实现，一个在主循环中，另一个在控制",
    ", in order for the watchdog timer to be reset. The function": "中，以便看门狗定时器被复位。函数",
    "is the task that actually clears the watchdog timer from within the control": "是在控制",
    ", but it also maintains a \u201csoftware watchdog\u201d counter": "中实际清除看门狗定时器的任务，但它还维护一个\u201c软件看门狗\u201d计数器",
    "which increments on each control loop update. It is the responsibility of the main loop task to call": "，在每次控制环路更新时递增。主循环任务有责任调用",
    ", which clears the software counter, often enough so that the software watchdog does not reach a timeout.": "，该函数清除软件计数器，频率要足够高以使软件看门狗不会达到超时。",
    "If the": "如果",
    "becomes unresponsive, it will not clear the hardware watchdog timer, and upon the next watchdog timeout, a watchdog reset will occur.": "变得不响应，它将不会清除硬件看门狗定时器，在下一次看门狗超时时，将发生看门狗复位。",
    "If the main loop becomes unresponsive, it will not clear the software watchdog timer, and when that timer reaches a timeout threshold, the": "如果主循环变得不响应，它将不会清除软件看门狗定时器，当该定时器达到超时阈值时，",
    "will stop clearing the hardware watchdog timer. Upon the next watchdog timeout, a watchdog reset will occur. The main loop software watchdog timeout is essentially much longer than the hardware watchdog timeout, but it is also a much less critical task thread.": "将停止清除硬件看门狗定时器。在下一次看门狗超时时，将发生看门狗复位。主循环软件看门狗超时本质上比硬件看门狗超时长得多，但它也是一个不太关键的任务线程。",
    "Cause of a watchdog reset can be determined by examining the value of the software watchdog counter; if it is above the timeout threshold then the main loop was unresponsive, whereas if the software counter is below the timeout threshold then the control ISR was unresponsive.": "看门狗复位的原因可以通过检查软件看门狗计数器的值来确定；如果它高于超时阈值，则主循环不响应；如果软件计数器低于超时阈值，则控制 ISR 不响应。",
    "Fault Clearing Logic": "故障清除逻辑",
    "4.6.1.5. Fault Clearing Logic": "4.6.1.5. 故障清除逻辑",
    "implements fault clearing logic when the various fault handling procedures within MCAF invoke the": "在 MCAF 中的各种故障处理过程调用",
    "function. The purpose of the fault clearing logic is to maintain system stability and safety by capturing fault information, analyzing fault-specific conditions, and executing appropriate recovery actions.": "函数时实现故障清除逻辑。故障清除逻辑的目的是通过捕获故障信息、分析特定故障条件并执行适当的恢复操作来维持系统稳定性和安全性。",
    "Faults Detected in MCAF": "MCAF 中检测到的故障",
    "4.6.1.5.1. Faults Detected in MCAF": "4.6.1.5.1. MCAF 中检测到的故障",
    "Fault flags in MCAF are mapped to corresponding fault flags in the MCAPI as described in the MCAPI fault flag table in the": "MCAF 中的故障标志映射到 MCAPI 中的相应故障标志，如",
    "API Description": "API 描述",
    ". For example,": "中的 MCAPI 故障标志表所述。例如，",
    "is mapped to": "映射到",
    "These faults are categorized based on the source of detection:": "这些故障根据检测来源分类：",
    "Faults detected by MCAF firmware": "MCAF 固件检测到的故障",
    "Faults detected by external hardware": "外部硬件检测到的故障",
    "fault in MCAPI is defined as a general-purpose flag to represent all MCAF faults that are not explicitly mapped.": "故障在 MCAPI 中定义为通用标志，用于表示所有未显式映射的 MCAF 故障。",
    "is reported for overcurrent conditions, and will be reported for overvoltage if a hardware configuration shares the hardware fault source for overcurrent and overvoltage detection.": "用于报告过流条件，如果硬件配置共享过流和过压检测的硬件故障源，则也会报告过压。",
    "Every hardware combination has its own fault source pin configured. (See": "每种硬件组合都有自己配置的故障源引脚。（见",
    "Custom board format": "自定义电路板格式",
    ".)": "。）",
    "Clearing MCAF Firmware-level Faults": "清除 MCAF 固件级故障",
    "4.6.1.5.2. Clearing MCAF Firmware-level Faults": "4.6.1.5.2. 清除 MCAF 固件级故障",
    "Most MCAF firmware-level faults are cleared within the current ISR cycle through the following sequence:": "大多数 MCAF 固件级故障在当前 ISR 周期内通过以下序列清除：",
    "MCAPI clears the fault flags if the corresponding fault clear flag is set.": "如果相应的故障清除标志已设置，MCAPI 清除故障标志。",
    "MCAPI reads active fault status from MCAF.": "MCAPI 从 MCAF 读取活动故障状态。",
    "If no active faults remain, MCAPI requests MCAF to exit the fault state.": "如果没有剩余的活动故障，MCAPI 请求 MCAF 退出故障状态。",
    "Clearing Hardware-level Faults": "清除硬件级故障",
    "4.6.1.5.3. Clearing Hardware-level Faults": "4.6.1.5.3. 清除硬件级故障",
    "Certain hardware-level faults require multiple ISR cycles to clear and must be handled differently from firmware-level faults.": "某些硬件级故障需要多个 ISR 周期才能清除，必须与固件级故障不同地处理。",
    "— At least two ISR cycles are required to clear this fault due to PWM fault latching.": "——由于 PWM 故障锁定，至少需要两个 ISR 周期才能清除此故障。",
    "module interacts with MCAF to clear the fault.": "模块与 MCAF 交互以清除故障。",
    "— Performing a power cycle is currently the only available method to clear this fault. (see": "——执行电源循环是目前清除此故障的唯一可用方法。（见",
    "Custom Boards Without PWM Fault Input": "无 PWM 故障输入的自定义电路板",
    "4.6.1.5.4. Custom Boards Without PWM Fault Input": "4.6.1.5.4. 无 PWM 故障输入的自定义电路板",
    "MCAF supports the use of a hardware PWM fault signal to detect overvoltage or overcurrent conditions in a processor-independent manner. By specifying this fault source in the board definition — either as an input on a designated pin or as the output of an on-chip comparator — MCAF can configure the PWM generators on the dsPIC": "MCAF 支持使用硬件 PWM 故障信号以处理器无关的方式检测过压或过流条件。通过在电路板定义中指定此故障源——作为指定引脚上的输入或片上比较器的输出——MCAF 可以配置 dsPIC",
    "DSC to monitor this input and automatically disable the PWM outputs if a hardware fault occurs.": "DSC 上的 PWM 发生器来监控此输入，并在发生硬件故障时自动禁用 PWM 输出。",
    "For custom boards that do not include such a fault signal, the fault source can be set to": "对于不包含此类故障信号的自定义电路板，故障源可以设置为",
    "none": "无",
    ", thereby disabling hardware-based fault detection. In this configuration,": "，从而禁用基于硬件的故障检测。在这种配置下，",
    "will not be triggered.": "不会被触发。",
    "Warning": "警告",
    "Designing motor control boards without a hardware PWM fault signal is not recommended. This is a vital function that helps detect failures and prevent failure propagation.": "不建议设计没有硬件 PWM 故障信号的电机控制电路板。这是一项关键功能，有助于检测故障并防止故障传播。",
    "Interaction with the MCAPI": "与 MCAPI 的交互",
    "4.6.1.5.5. Interaction with the MCAPI": "4.6.1.5.5. 与 MCAPI 的交互",
    "The application can query and clear MCAPI fault flags:": "应用程序可以查询和清除 MCAPI 故障标志：",
    "returns the current fault bit-field for the motor.": "返回电机的当前故障位域。",
    "requests clearing of selected fault flags via a mask (clearing does not restart the motor).": "请求通过掩码清除选定的故障标志（清除不会重启电机）。",
    "A typical sequence is to read the fault flags with": "典型序列是使用",
    ", call": "读取故障标志，调用",
    "for the desired bits, then re-read until those bits clear. Latency limits of MCAPI functions are not strictly bounded, but fault status read/clear requests typically take effect within 2 ISR cycles.": "清除所需位，然后重新读取直到这些位清除。MCAPI 函数的延迟限制没有严格界定，但故障状态读取/清除请求通常在 2 个 ISR 周期内生效。",
    "may take 2 additional ISR cycles to clear due to PWM fault latching mentioned in": "由于",
    "Supervisory errata": "监控勘误",
    "4.6.1.6. Supervisory errata": "4.6.1.6. 监控勘误",
    "The torque angle detection method of stall detection is difficult to tune automatically. It works well for some motors, but can cause false detection faults in others. We have disabled this detection method by default since MCAF R3. It can be re-enabled by changing": "堵转检测的转矩角检测方法难以自动调优。它对某些电机效果良好，但对其他电机可能导致误检测故障。自 MCAF R3 起，我们默认禁用了此检测方法。可以通过更改",
    "to initialize the stall detection flag mask as follows:": "来重新启用，将堵转检测标志掩码初始化如下：",
    "MCAPI will not clear": "MCAPI 不会清除",
    "fault due to gate driver fault latch. (DB_MC-5666; Applicability: R8)": "故障，因为栅极驱动器故障锁定。（DB_MC-5666；适用性：R8）",
    "Modules": "模块",
    "4.6.1.7. Modules": "4.6.1.7. 模块",
    "Module": "模块",
    "Files": "文件",
    "Description": "描述",
    "Comments": "说明",
    "Fault detection": "故障检测",
    "Fault-handling": "故障处理",
    "see section on": "参见",
    "monitor": "监控",
    "Recovery from stall detection": "堵转检测的恢复",
    "Stall detection": "堵转检测",
    "Test Harness": "测试框架",
    "External Interface": "外部接口",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
