# -*- coding: utf-8 -*-
import txutil

rel = "components/hal"
title_zh = "4.9. 硬件抽象层（HAL）"

m = {
    "Components": "组件",
    "Hardware Abstraction Layer (HAL)": "硬件抽象层（HAL）",
    "4.9. Hardware Abstraction Layer (HAL)": "4.9. 硬件抽象层（HAL）",
    "The HAL is used by the MCAF to decouple all knowledge of device-specific hardware registers, via well-known function calls. The HAL is made up of two layers:": "HAL 被 MCAF 用于通过众所周知的函数调用来解耦所有设备特定硬件寄存器的知识。HAL 由两层组成：",
    "Code Configurator": "代码配置器",
    "(MCC) layer and HAF layer. The MCC layer is the base layer where device-specific hardware registers are abstracted out into a series of peripheral driver APIs. The HAF layer then calls functions in the MCC layer to abstract out device specific functionality, enabling the higher level MCAF layers to be device-independent.": "（MCC）层和 HAF 层。MCC 层是基础层，其中设备特定的硬件寄存器被抽象为一系列外设驱动 API。然后 HAF 层调用 MCC 层中的函数来抽象设备特定功能，使更高层的 MCAF 层与设备无关。",
    "As long as the HAL function names and semantics are preserved, the HAL component can be swapped out and replaced with an alternative implementation.": "只要保留 HAL 函数名称和语义，HAL 组件就可以被替换为替代实现。",
    "Hardware-related behavior": "硬件相关行为",
    "4.9.1. Hardware-related behavior": "4.9.1. 硬件相关行为",
    "Certain aspects of the MCAF utilize the functions provided by the HAL, but the choice of behavior lies within the MCAF. Some of these choices have been made to facilitate portability between devices that have different underlying peripheral mechanisms.": "MCAF 的某些方面利用 HAL 提供的功能，但行为的选择在于 MCAF。其中一些选择是为了便于在具有不同底层外设机制的设备之间移植。",
    "Note: this portability comes at a cost": "注意：这种可移植性是有代价的",
    "— each series of microcontrollers has certain peripheral usage patterns that are optimal but which may not translate well across different series.": "——每个系列的微控制器都有某些最优的外设使用模式，但这些模式可能无法很好地跨不同系列使用。",
    "Customers for whom CPU or peripheral performance is a severe constraint that takes precedence over portability and maintainability, should consider modifying the HAL as necessary to meet those constraints. Microchip does not recommend this approach unless absolutely necessary.": "对于 CPU 或外设性能是严重约束且优先于可移植性和可维护性的客户，应考虑根据需要修改 HAL 以满足这些约束。Microchip 不推荐这种方法，除非绝对必要。",
    "Interrupt Priorities": "中断优先级",
    "4.9.1.1. Interrupt Priorities": "4.9.1.1. 中断优先级",
    "The majority of MCAF code is executed in several different interrupt service routines. The following interrupts, listed from highest to lowest priority, are used by MCAF. See the": "MCAF 的大部分代码在几个不同的中断服务程序中执行。以下中断按从高到低的优先级列出，供 MCAF 使用。参见",
    "scheduling requirements": "调度要求",
    "section for more information.": "一节了解更多信息。",
    "Main ADC ISR — Executes the": "主 ADC ISR——执行",
    "state machine": "状态机",
    "and several other critical MCAF components once every PWM period.": "和几个其他关键 MCAF 组件，每个 PWM 周期执行一次。",
    "Single-channel ADC ISR — Samples the DC link current twice every PWM period. Only executed if": "单通道 ADC ISR——每个 PWM 周期对直流母线电流采样两次。仅在",
    "single-channel current measurement": "单通道电流测量",
    "is used.": "时执行。",
    "Timer ISR — Executes the": "定时器 ISR——执行",
    "board service": "板级服务",
    "tasks and the": "任务和",
    "main application": "主应用程序",
    "periodically.": "周期性地。",
    "PWM outputs": "PWM 输出",
    "4.9.1.2. PWM outputs": "4.9.1.2. PWM 输出",
    "outputs for the three-phase bridge are set in one of three modes:": "三相桥的输出设置为以下三种模式之一：",
    "off": "关闭",
    "— at device reset, and during severe faults, the bridge is turned off completely": "——在设备复位时和严重故障期间，桥完全关闭",
    "\u201cminimal impact\u201d": "\u201c最小影响\u201d",
    "— when not applying voltage across the motor terminals (in certain states of the": "——当不对电机端子施加电压时（在",
    "), the upper transistors are turned off completely, but the lower transistors are turned on at a low duty cycle (typically 1-3%), to maintain charge in bootstrap gate drive capacitors. See": "的某些状态下），上桥臂晶体管完全关闭，但下桥臂晶体管以低占空比（通常 1-3%）导通，以维持自举栅极驱动电容器的电荷。参见",
    "in the": "在",
    "module.": "模块中。",
    "normal": "正常",
    "— when applying voltage across the motor terminals, all 6 of the transistors are switching, in three complementary pairs, one for each phase. Each phase has a dead-time between turn-off of one transistor and turn-on of the complementary transistor, to avoid shoot-through.": "——当对电机端子施加电压时，所有 6 个晶体管都在开关，分为三对互补对，每相一对。每相在一个晶体管关断和互补晶体管导通之间有死区时间，以避免直通。",
    "Overcurrent fault detection and clearing": "过流故障检测与清除",
    "4.9.1.3. Overcurrent fault detection and clearing": "4.9.1.3. 过流故障检测与清除",
    "MCAF requires a two phase fault clearing scheme to reset the latch circuitry. In order to clear the fault in Latched mode in dsPIC33EP devices, it is necessary to clear the interrupt flag and enable the fault mode at the next PWM cycle. Please refer to": "MCAF 需要两阶段故障清除方案来复位锁存电路。为了在 dsPIC33EP 设备的锁存模式下清除故障，需要在下一个 PWM 周期清除中断标志并启用故障模式。请参阅",
    "for additional information.": "获取更多信息。",
    "Phase 1 occurs at current PWM cycle": "阶段 1 在当前 PWM 周期发生",
    "33EP: Disable the fault latch mode": "33EP：禁用故障锁存模式",
    "33CK: Clear the fault latch": "33CK：清除故障锁存",
    "Phase 2 occurs at the next PWM cycle": "阶段 2 在下一个 PWM 周期发生",
    "33CK & 33EP: Clear the fault interrupt flag": "33CK 和 33EP：清除故障中断标志",
    "33EP: Enable the fault latch": "33EP：启用故障锁存",
    "Analog-to-digital conversion": "模数转换",
    "4.9.1.4. Analog-to-digital conversion": "4.9.1.4. 模数转换",
    "Some of the ADC inputs have strict timing requirements, as shown in": "一些 ADC 输入有严格的时序要求，如",
    "(At present, MCAF requires a fixed": "（目前，MCAF 要求固定的",
    "Sampling requirements for MCAF": "MCAF 的采样要求",
    "Analog input": "模拟输入",
    "Sampling frequency": "采样频率",
    "Timing requirements": "时序要求",
    "Motor currents (A,B,Sum)": "电机电流（A、B、Sum）",
    "Sample near the center of the PWM cycle(typically the start of center-aligned cycle). All samples should be complete within some small time Tskew. (Typically 1 \u03bcs or less)": "在 PWM 周期中心附近采样（通常为中心对齐周期的起始点）。所有采样应在某个较小时间 Tskew 内完成。（通常 1 \u03bc s 或更小）",
    "DC link voltage": "直流母线电压",
    "K=1 or K=2 typical. (Minimizing K is preferred.) Otherwise, no strict timing requirements": "典型 K=1 或 K=2。（优先最小化 K。）否则，无严格时序要求",
    "Potentiometer": "电位器",
    "Depends on the application; MCAF uses K=2. Otherwise, no strict timing requirements": "取决于应用；MCAF 使用 K=2。否则，无严格时序要求",
    "Given the above constraints, multiple ADC sample scheduling schemes can be used. The timing diagrams below show the sampling schedules of motor phase currents, DC link voltage, and potentiometer in both 33CK and 33EP. The ADC trigger source is selected by mapping any available PWM instance to Phase A in the board configuration file. This allows users to select different PWM generators, for example, PWM generator 2 or 3, to trigger the ADC by mapping it accordingly.": "给定上述约束，可以使用多种 ADC 采样调度方案。下面的时序图显示了 33CK 和 33EP 中电机相电流、直流母线电压和电位器的采样调度。ADC 触发源通过在电路板配置文件中将任何可用的 PWM 实例映射到 Phase A 来选择。这允许用户选择不同的 PWM 生成器（例如 PWM 生成器 2 或 3）通过相应映射来触发 ADC。",
    "Suggested ADC Timing on dsPIC33CK devices with multiple ADC cores (horizontal axis not to scale)": "具有多个 ADC 核的 dsPIC33CK 设备的建议 ADC 时序（横轴未按比例）",
    "shows an example of dsPIC33CK devices with multiple cores (such as the dsPIC33CK64MP105, and dsPIC33CK256MP508) sampling motor currents phase A and B simultaneously at the beginning of the center-aligned PWM cycle. After motor current phase B, with less than 1 \u03bcs between samples, the shared core sequentially samples the DC link voltage, and potentiometer, followed by the end of conversion of the potentiometer which triggers the ADC ISR.": "展示了具有多个核的 dsPIC33CK 设备（如 dsPIC33CK64MP105 和 dsPIC33CK256MP508）在中心对齐 PWM 周期开始时同时采样电机相电流 A 和 B 的示例。在电机相电流 B 之后，采样间隔小于 1 \u03bc s，共享核依次采样直流母线电压和电位器，随后电位器转换结束触发 ADC ISR。",
    "Suggested ADC Timing on dsPIC33CK devices with single ADC cores (horizontal axis not to scale)": "具有单个 ADC 核的 dsPIC33CK 设备的建议 ADC 时序（横轴未按比例）",
    "shows an example of dsPIC33CK devices with a single ADC core (such as dsPIC33CK64MC105) sampling analog inputs: motor currents phase A, B, DC link voltage, and potentiometer sequentially. At the end of the conversion sequence the ADC ISR is triggered and executes.": "展示了具有单个 ADC 核的 dsPIC33CK 设备（如 dsPIC33CK64MC105）依次采样模拟输入的示例：电机相电流 A、B、直流母线电压和电位器。在转换序列结束时，ADC ISR 被触发并执行。",
    "Suggested ADC Timing on dsPIC33EP devices (horizontal axis not to scale)": "dsPIC33EP 设备的建议 ADC 时序（横轴未按比例）",
    "shows an example of dsPIC33EP256MC506 sampling all analog inputs simultaneously at the beginning of the center-aligned PWM cycle, with the exception of the potentiometer input. After analog inputs have been sampled and converted this triggers the beginning of the ADC ISR. At the next center-aligned PWM cycle the shared ADC core is switched from sensing DC link voltage to sensing the potentiometer input. At the next PWM boundary this cycle repeats.": "展示了 dsPIC33EP256MC506 在中心对齐 PWM 周期开始时同时采样所有模拟输入（电位器输入除外）的示例。模拟输入采样和转换完成后，触发 ADC ISR 的开始。在下一个中心对齐 PWM 周期，共享 ADC 核从感测直流母线电压切换到感测电位器输入。在下一个 PWM 边界，此循环重复。",
    "Difference between 33EP and 33CK PWM modules and its implications on ADC operation": "33EP 和 33CK PWM 模块之间的差异及其对 ADC 操作的影响",
    "4.9.1.4.1. Difference between 33EP and 33CK PWM modules and its implications on ADC operation": "4.9.1.4.1. 33EP 和 33CK PWM 模块之间的差异及其对 ADC 操作的影响",
    "To measure the motor phase currents accurately the ADC must begin sampling in the middle of the low-side duty cycle pulse. This is to allow enough time for current sense signal conditioning to settle and charge the ADC sampling capacitor before the low-side pulse has ended.": "为了准确测量电机相电流，ADC 必须在低侧占空比脉冲的中间开始采样。这是为了在低侧脉冲结束前留出足够的时间让电流检测信号调理稳定并给 ADC 采样电容充电。",
    "shows the difference between symmetric and asymmetric dead time. In symmetric dead time high-to-low transitions are advanced by DT/2 and low-to-high transitions are delayed by DT/2. In asymmetric dead time low-to-high transitions are delayed by DT. This figure also shows that in asymmetric dead time insertion the PWM deadcenter event is delayed by T1.": "显示了对称和不对称死区时间之间的差异。在对称死区时间中，高到低转换提前 DT/2，低到高转换延迟 DT/2。在不对称死区时间中，低到高转换延迟 DT。此图还显示在不对称死区时间插入中，PWM 中心事件延迟 T1。",
    "dsPIC33EP:": "dsPIC33EP：",
    "Implements symmetric dead time in PWM module": "在 PWM 模块中实现对称死区时间",
    "Due to symmetric dead time the beginning of the center-aligned cycle is aligned with the center of the low-side pulse.": "由于对称死区时间，中心对齐周期的开始与低侧脉冲的中心对齐。",
    "No delay is required to ensure sampling/conversion occurs in the middle of the low-side pulse.": "不需要延迟来确保采样/转换发生在低侧脉冲的中间。",
    "dsPIC33CK:": "dsPIC33CK：",
    "Implements asymmetric dead time in PWM module": "在 PWM 模块中实现不对称死区时间",
    "Due to asymmetric dead time the beginning of the center-aligned cycle is slightly ahead of the center of the low-side pulse.": "由于不对称死区时间，中心对齐周期的开始略超前于低侧脉冲的中心。",
    "We suggest adding a small delay of half the dead time to the ADC trigger to ensure sampling/conversion occurs in the middle of the low-side pulse.": "我们建议在 ADC 触发中添加半个死区时间的小延迟，以确保采样/转换发生在低侧脉冲的中间。",
    "PWM update options": "PWM 更新选项",
    "4.9.1.5. PWM update options": "4.9.1.5. PWM 更新选项",
    "For center-aligned PWM, there are several choices that determine when updates to the PWM duty cycle registers are actually loaded into the PWM generator for use.": "对于中心对齐 PWM，有几个选项决定 PWM 占空比寄存器的更新何时实际加载到 PWM 生成器中使用。",
    "These choices usually include the following:": "这些选项通常包括以下内容：",
    "immediate update": "立即更新",
    "— duty cycle register updates are loaded into the PWM generator immediately. This has the lowest additional delay, but can cause extra output transitions (for example, if the duty cycle registers are updated from an older larger duty cycle, to a newer smaller duty cycle, after the older duty cycle has already caused a low-to-high transition, but before the newer duty cycle would cause a low-to-high transition) or fall within known errata of the PWM module. Immediate update is not recommended for use with MCAF.": "——占空比寄存器更新立即加载到 PWM 生成器中。这具有最低的额外延迟，但可能导致额外的输出转换（例如，如果占空比寄存器从较旧的较大占空比更新为较新的较小占空比，在较旧占空比已引起低到高转换之后，但在较新占空比将引起低到高转换之前）或落入 PWM 模块的已知勘误中。不建议在 MCAF 中使用立即更新。",
    "single update": "单次更新",
    "(single synchronous update) — duty cycle register updates are loaded into the PWM generator at the start of the center-aligned PWM period. This creates only one opportunity per PWM cycle for control loops to update the duty cycle.": "（单次同步更新）——占空比寄存器更新在中心对齐 PWM 周期开始时加载到 PWM 生成器中。这每个 PWM 周期只为控制环路创建一次更新占空比的机会。",
    "double update": "双次更新",
    "(double synchronous update) — duty cycle register updates are loaded into the PWM generator both at the start and the center of the center-aligned PWM period. This creates two opportunities per PWM cycle for control loops to update the duty cycle.": "（双次同步更新）——占空比寄存器更新在中心对齐 PWM 周期的开始和中心都加载到 PWM 生成器中。这每个 PWM 周期为控制环路创建两次更新占空比的机会。",
    "The choice of update creates an effective delay in the current control loop timing. The critical metric is the": "更新选择在电流控制环路时序中产生有效延迟。关键指标是",
    "sample-to-update delay": "采样到更新延迟",
    ", which measures the time between the instant that information is available from ADC sampling, until a new set of PWM duty cycles is loaded into the PWM generator. Single update and double update are shown in": "，它测量从 ADC 采样信息可用的时刻到新一组 PWM 占空比加载到 PWM 生成器的时间。单次更新和双次更新如",
    ". Double-update PWM allows for a minimum delay": "所示。双次更新 PWM 允许最小延迟",
    "of one half PWM cycle. Single-update PWM allows for a minimum delay": "为半个 PWM 周期。单次更新 PWM 允许最小延迟",
    "of one full cycle. The actual delay depends on how quickly the control loop executes the critical code between ADC sampling and PWM duty cycle register update.": "为一个完整周期。实际延迟取决于控制环路执行 ADC 采样和 PWM 占空比寄存器更新之间关键代码的速度。",
    "Single update and double update. The dashed lines represent opportunities for PWM generator update.": "单次更新和双次更新。虚线表示 PWM 生成器更新的机会。",
    "Double update is recommended for MCAF, in general, to reduce sample-to-update delay, but some control methods require other PWM update options.": "通常建议 MCAF 使用双次更新以减少采样到更新延迟，但某些控制方法需要其他 PWM 更新选项。",
    "requires single update in Center Aligned PWM Mode. For other estimators,": "在中心对齐 PWM 模式下需要单次更新。对于其他估算器，",
    "current measurement requires single update in Dual Edge Center Aligned PWM Mode, and for": "电流测量在双沿中心对齐 PWM 模式下需要单次更新，而对于",
    "or": "或",
    "current measurement, Double Update Center Aligned PWM Mode is configured to reduce sample-to-update delay.": "电流测量，配置双次更新中心对齐 PWM 模式以减少采样到更新延迟。",
    "Note: In dsPIC33E devices double update is enabled by default and does not require or allow any change in peripheral configuration. For dsPIC33E please check the device errata. Earlier silicon revisions for some devices implement the single-update behavior rather than double-update behavior.": "注意：在 dsPIC33E 设备中，双次更新默认启用，不需要也不允许更改外设配置。对于 dsPIC33E，请检查设备勘误。某些设备的早期硅片版本实现单次更新行为而非双次更新行为。",
    "Board service module": "板级服务模块",
    "4.9.1.6. Board service module": "4.9.1.6. 板级服务模块",
    "The board service module in MCAF works with Hardware Access Functions (HAF) in the HAL in order to provide MCAF with board-level functionality. It provides two main board-related features: a board handler and a PWM bootstrap charging routine.": "MCAF 中的板级服务模块与 HAL 中的硬件访问功能（HAF）协同工作，以为 MCAF 提供板级功能。它提供两个主要的板级相关功能：板级处理程序和 PWM 自举充电例程。",
    "Board handler": "板级处理程序",
    "4.9.1.6.1. Board handler": "4.9.1.6.1. 板级处理程序",
    "The board handler includes interfaces to configure and execute a board service process. The board service process uses a timer to periodically handle board level services. Working with appropriate HAL interfaces, the board handler provides services to push buttons, potentiometer and configurable PWM drivers (if available) to user-level applications, such as the": "板级处理程序包括配置和执行板级服务进程的接口。板级服务进程使用定时器周期性地处理板级服务。与适当的 HAL 接口配合工作，板级处理程序向用户级应用程序（如",
    "sample application": "示例应用程序",
    "PWM bootstrap charging routine": "PWM 自举充电例程",
    "4.9.1.6.2. PWM bootstrap charging routine": "4.9.1.6.2. PWM 自举充电例程",
    "The PWM bootstrap charging routine includes interfaces to initialize and execute the PWM bootstrap charging process. The routine begins by turning the high-side transistors off and setting the low-side transistors to 0% duty cycle. Then the PWM bootstrap charging routine delays a preset number of PWM cycles before beginning to charge the bootstrap capacitors. During the process, the PWM bootstrap capacitors are sequentially charged at a controlled rate (see": "PWM 自举充电例程包括初始化和执行 PWM 自举充电过程的接口。该例程首先关闭高侧晶体管并将低侧晶体管设置为 0% 占空比。然后 PWM 自举充电例程延迟预设数量的 PWM 周期，再开始充电自举电容。在此过程中，PWM 自举电容以受控速率依次充电（参见",
    "errata": "勘误",
    "). The process begins by switching the phase A low-side transistor at a low duty cycle for a short time, before proceeding with phase B for a short time, and then phase C:": "）。该过程首先以低占空比短时间开关 A 相低侧晶体管，然后短时间进行 B 相，最后是 C 相：",
    "PWM low-side signals during bootstrap charging routine.": "自举充电例程期间的 PWM 低侧信号。",
    "Implementation": "实现",
    "4.9.2. Implementation": "4.9.2. 实现",
    "MCC integration": "MCC 集成",
    "4.9.2.1. MCC integration": "4.9.2.1. MCC 集成",
    "Prior to MCAF R3, generated code was not integrated with MCC; MCAF provided its own HAL completely.": "在 MCAF R3 之前，生成的代码未与 MCC 集成；MCAF 完全提供自己的 HAL。",
    "In MCAF R3, the following items have been removed from MCAF and made the responsibility of MCC:": "在 MCAF R3 中，以下项目已从 MCAF 中移除并由 MCC 负责：",
    "Configuration bits": "配置位",
    "Oscillator setup": "振荡器设置",
    "Some aspects of the MCC system module are still present in MCAF. Both MCC and MCAF code executes; the MCAF code runs later and overrides any settings from MCC. The following areas are handled both by MCC and MCAF:": "MCC 系统模块的某些方面仍存在于 MCAF 中。MCC 和 MCAF 代码都执行；MCAF 代码稍后运行并覆盖 MCC 的任何设置。以下区域由 MCC 和 MCAF 共同处理：",
    "GPIO configuration": "GPIO 配置",
    "Interrupt initialization": "中断初始化",
    "CORCON initialization": "CORCON 初始化",
    "This overlap is temporary, and these areas are planned to be shifted fully to MCC.": "这种重叠是暂时的，这些区域计划完全转移到 MCC。",
    "Other modules such as ADC and PWM are configured solely by MCAF, and will be shifted to MCC in a future version of MCAF.": "其他模块如 ADC 和 PWM 完全由 MCAF 配置，将在未来版本的 MCAF 中转移到 MCC。",
    "In MCAF R4, the following items have been removed from MCAF and made the responsibility of MCC:": "在 MCAF R4 中，以下项目已从 MCAF 中移除并由 MCC 负责：",
    "Interrupt module": "中断模块",
    "PWM module": "PWM 模块",
    "ADC module": "ADC 模块",
    "Timer module": "定时器模块",
    "UART module": "UART 模块",
    "DMA module": "DMA 模块",
    "Watchdog module": "看门狗模块",
    "LEDs module": "LED 模块",
    "Switches module": "开关模块",
    "Pin Management (partially)": "引脚管理（部分）",
    "MCC handles all peripheral initialization, pin initialization, pin management, and is the base layer for interacting with hardware. Currently, because MCC does not yet support QEI, pin management cannot be fully handled by MCC alone. First, the MCC system module configures all peripherals including device pin management. Then, after the MCC system module is done with configuration, MCAF pin management is run as well to initialize QEI pins. The QEI module is fully handled by MCAF and will be shifted to MCC when QEI support is available in MCC for 16-bit devices.": "MCC 处理所有外设初始化、引脚初始化、引脚管理，并且是与硬件交互的基础层。目前，由于 MCC 尚不支持 QEI，引脚管理不能完全由 MCC 单独处理。首先，MCC 系统模块配置所有外设包括设备引脚管理。然后，在 MCC 系统模块完成配置后，MCAF 引脚管理也运行以初始化 QEI 引脚。QEI 模块完全由 MCAF 处理，将在 MCC 为 16 位设备提供 QEI 支持时转移到 MCC。",
    "Most hardware access actions occur through the HAF layer but a few calls to the MCC peripheral layer are made directly from the MCAF application. In the future, all hardware access will be delegated to the HAF layer. This is to avoid coupling between the MCAF application and MCC.": "大多数硬件访问操作通过 HAF 层进行，但少量对 MCC 外设层的调用直接从 MCAF 应用程序发出。未来，所有硬件访问将委托给 HAF 层。这是为了避免 MCAF 应用程序与 MCC 之间的耦合。",
    "is a function that has been added to the HAF layer. This function retrieves the interrupt vector number, and does not directly go through MCC to do so.": "是添加到 HAF 层的函数。此函数获取中断向量号，不直接通过 MCC 执行此操作。",
    "More information about MCC configuration in MCAF is available in the": "有关 MCAF 中 MCC 配置的更多信息，请参见",
    "MCC Peripheral documentation": "MCC 外设文档",
    "Added support for dsPIC33CK256MP508.": "增加了对 dsPIC33CK256MP508 的支持。",
    "All peripheral and hardware related functions called by MCAF are made through the Hardware Access Functions layer.": "MCAF 调用的所有外设和硬件相关功能都通过硬件访问功能层进行。",
    "MCAF requires certain instances of peripherals. Required instances are: PWM, ADC1, TMR1, SCCP1-TMR/TMR2, UART1 and QEI1": "MCAF 需要特定的外设实例。所需实例为：PWM、ADC1、TMR1、SCCP1-TMR/TMR2、UART1 和 QEI1",
    "MCC handles most peripheral generated code except for QEI and clearing of the fault interrupt status bits.": "MCC 处理大部分外设生成代码，QEI 和故障中断状态位清除除外。",
    "Added support for dsPIC33CK64MP105, and dsPIC33CK64MC105.": "增加了对 dsPIC33CK64MP105 和 dsPIC33CK64MC105 的支持。",
    "MCC now handles all of the peripheral generated code except for QEI.": "MCC 现在处理所有外设生成代码，QEI 除外。",
    "Board service module restructured to split into": "板级服务模块重构为分为",
    "PWM bootstrap charging": "PWM 自举充电",
    "and": "和",
    "board handler": "板级处理程序",
    "sections": "部分",
    "Added support for both": "增加了对",
    "MCC Melody": "MCC Melody",
    "MCC Classic": "MCC Classic",
    "MCC Melody is supported only for the dsPIC33CK family of devices.": "MCC Melody 仅支持 dsPIC33CK 系列设备。",
    "MCC Classic is supported only for the dsPIC33EP family of devices.": "MCC Classic 仅支持 dsPIC33EP 系列设备。",
    "MCC Melody handles all of the peripheral generated code, including QEI. When using MCC Classic, MCAF provides QEI code.": "MCC Melody 处理所有外设生成代码，包括 QEI。使用 MCC Classic 时，MCAF 提供 QEI 代码。",
    "Interrupt priorities used by MCAF are summarized in": "MCAF 使用的中断优先级总结于",
    "ISR priorities for MCAF": "MCAF 的 ISR 优先级",
    "ISR type": "ISR 类型",
    "Main ADC": "主 ADC",
    "Single-channel ADC": "单通道 ADC",
    "N/A": "不适用",
    "Timer": "定时器",
    "Prior to MCAF R9 the ADC trigger was hardcoded to PWM generator 1. Since MCAF R9 users can customize the ADC trigger source by mapping any available PWM instance to Phase A in the board configuration file.": "在 MCAF R9 之前，ADC 触发器硬编码为 PWM 生成器 1。从 MCAF R9 开始，用户可以通过在电路板配置文件中将任何可用的 PWM 实例映射到 Phase A 来自定义 ADC 触发源。",
    "HAL errata": "HAL 勘误",
    "4.9.2.2. HAL errata": "4.9.2.2. HAL 勘误",
    "includes a soft-start sequence intended to slowly turn on duty cycle and reduce gate drive power supply loading in order to charge up bootstrap capacitors. This sequence starts with duty cycles that are too low, and may produce runt pulses with certain gate drivers. (DB_MC-978; Applicability: MCAF R2 – R6)": "包含一个软启动序列，旨在缓慢打开占空比并减少栅极驱动电源负载，以充电自举电容。此序列以过低的占空比开始，可能在某些栅极驱动器中产生残缺脉冲。（DB_MC-978；适用性：MCAF R2 – R6）",
    "Diagnostic Kernel": "诊断内核",
    "Motion Control API (MCAPI)": "运动控制 API（MCAPI）",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
