# -*- coding: utf-8 -*-
import txutil

rel = "components/ext-interface"
title_zh = "4.7. 外部接口"

m = {
    "Components": "组件",
    "External Interface": "外部接口",
    "4.7. External Interface": "4.7. 外部接口",
    "This section describes the external interfaces to the motor control application framework, including potentiometer, pushbuttons, and LEDs.": "本节描述电机控制应用程序框架的外部接口，包括电位器、按键和 LED。",
    "In MCAF R6 – R9, the": "在 MCAF R6 – R9 中，",
    "board service module": "板级服务模块",
    "implements the potentiometer and pushbutton handlers, while the": "实现了电位器和按键处理程序，而",
    "Sample Application": "示例应用程序",
    "defines the behavior on a button press.": "定义了按键按下时的行为。",
    "General UI guidelines": "通用 UI 指南",
    "4.7.1. General UI guidelines": "4.7.1. 通用 UI 指南",
    "The following table summarizes the UI elements available on each supported development board:": "下表总结了每个支持的开发板上可用的 UI 元素：",
    "Board": "电路板",
    "LEDs": "LED",
    "Pushbuttons": "按键",
    "Potentiometer": "电位器",
    "LED placement": "LED 布局",
    "MCLV\u20112 Development Board": "MCLV-2 开发板",
    "next to each other": "相邻",
    "MCS MCLV\u201148V\u2011300W Development Board": "MCS MCLV-48V-300W 开发板",
    "dsPIC33CK Low Voltage Motor Control (LVMC) Development Board": "dsPIC33CK 低压电机控制（LVMC）开发板",
    "MCHV\u20112 Development Board": "MCHV-2 开发板",
    "opposite sides of": "位于",
    "PIM": "PIM",
    "MCHV\u20113 Development Board": "MCHV-3 开发板",
    "MCHV\u2011230VAC\u20111.5kW Motor Control High-Voltage Development Board": "MCHV-230VAC-1.5kW 电机控制高压开发板",
    "In order to support all these systems and when creating a custom board, the following guidelines are suggested. See": "为了支持所有这些系统以及在创建自定义电路板时，建议遵循以下指南。有关将 UI 元素添加到",
    "Creating a custom board configuration": "创建自定义电路板配置",
    "for more information on adding UI elements to the": "的更多信息，请参见",
    "starter board definition.": "入门电路板定义。",
    "A minimum of two pushbuttons are strongly recommended but not required.": "强烈建议至少使用两个按键，但不是必需的。",
    "Pushbutton inputs are used to manually control input event functionality, such as the two sample application input events:": "按键输入用于手动控制输入事件功能，例如两个示例应用程序输入事件：",
    "Start/stop the motor and provide manual restart from a fault. Recommended to be controlled by the primary pushbutton.": "启动/停止电机并提供从故障中手动重启。建议由主按键控制。",
    "Reverse direction of motor rotation. Recommended to be controlled by the secondary pushbutton.": "反转电机旋转方向。建议由副按键控制。",
    "Each pushbutton can provide three different inputs depending on the duration of press and release:": "每个按键可以根据按下和释放的持续时间提供三种不同的输入：",
    "debounce: release \u2192 press and press \u2192 release transitions occur in less than some time T1 (e.g. 20msec). This is ignored.": "去抖：释放→按下和按下→释放转换在某个时间 T1（例如 20ms）内发生。此事件被忽略。",
    "single press: release \u2192 press and press \u2192 release transitions occur in some time T where T1 \u2264 T \u2264 T2": "单次按下：释放→按下和按下→释放转换在某个时间 T 内发生，其中 T1 \u2264 T \u2264 T2",
    "sustained press: release \u2192 press transition occurs, and press is held for more than some time T2 (e.g. 2 seconds). This is available for providing seldom-used input. Once a time T2 has elapsed, if a sustained press is allowed, an LED will provide some type of visual feedback that a sustained press has occurred.": "长按：释放→按下转换发生，且按下保持超过某个时间 T2（例如 2 秒）。这可用于提供不常用的输入。一旦时间 T2 已过，如果允许长按，LED 将提供某种视觉反馈以指示长按已发生。",
    "double press: two single press events occur within some interval T3 (e.g. 0.5 seconds). This is available for providing seldom-used input.": "双击：两次单次按下事件在某个间隔 T3（例如 0.5 秒）内发生。这可用于提供不常用的输入。",
    "A minimum of two LEDs are strongly recommended but not required.": "强烈建议至少使用两个 LED，但不是必需的。",
    "Each LED can provide different types of indication depending on how it is energized over time:": "每个 LED 可以根据其随时间的通电方式提供不同类型的指示：",
    "Fully off": "完全关闭",
    "Fully on": "完全点亮",
    "Modulated at high frequency (>100 Hz) in order to operate at \u00bd perceived brightness. (NOTE: because of the quirks of the human brain, this may not be at 50% duty cycle.)": "以高频（>100 Hz）调制以在 \u00bd 感知亮度下工作。（注意：由于人脑的特性，这可能不是 50% 占空比。）",
    "Perceptible blink rates and duty cycles (e.g. 5%/50%/95% duty at 0.5 / 1 / 2Hz blink rates)": "可感知的闪烁速率和占空比（例如 0.5 / 1 / 2Hz 闪烁速率下 5%/50%/95% 占空比）",
    "Blink rates between 2Hz and 55Hz should be avoided: although LEDs are fairly small in visual extent, these frequencies can be a trigger to people who have photosensitive epilepsy.": "应避免 2Hz 至 55Hz 之间的闪烁速率：尽管 LED 的视觉范围相当小，但这些频率可能成为光敏性癫痫患者的触发因素。",
    "Error codes \u2014 sequences of on/off patterns that are repeated and easily perceptible, e.g. 250msec on-time separated by different-length delimiting spaces of off-time (250msec, 750msec, 2250msec); see section on": "错误代码——重复且易于感知的开/关模式序列，例如 250ms 点亮时间被不同长度的熄灭间隔分隔（250ms、750ms、2250ms）；参见",
    "error codes": "错误代码",
    "for more information": "一节了解更多信息",
    "Some coordination between the two LEDs should be maintained to provide simple visual information (it is difficult to interpret two LEDs blinking at different rates next to each other)": "两个 LED 之间应保持一定的协调以提供简单的视觉信息（很难解读相邻的两个 LED 以不同速率闪烁）",
    "For indicating \u201cliveness\u201d, dynamic patterns should be preferred over static patterns, to indicate that the controller is alive and not stuck in a particular state.": "对于指示\u201c活跃性\u201d，应优先使用动态模式而非静态模式，以指示控制器处于活动状态且未卡在特定状态。",
    "A potentiometer is strongly recommended but not required.": "强烈建议使用电位器，但不是必需的。",
    "The potentiometer should provide a continuous range input, which can be used, for example, to control speed, current, or voltage.": "电位器应提供连续范围输入，例如可用于控制速度、电流或电压。",
    "Aside from these general guidelines, the choice of UI behavior is somewhat arbitrary.": "除这些通用指南外，UI 行为的选择在一定程度上是任意的。",
    "Custom boards without pushbuttons or potentiometer": "无按键或电位器的自定义电路板",
    "provides more information for custom boards with fewer than the recommended number of UI elements.": "为 UI 元素数量少于推荐数量的自定义电路板提供了更多信息。",
    "Implemented Behavior": "已实现的行为",
    "4.7.2. Implemented Behavior": "4.7.2. 已实现的行为",
    "Start/stop:": "启动/停止：",
    "Single press events on primary button provide a \u201cstart\u201d and \u201cstop\u201d input. (request to start motor if it is stopped; request to stop motor if it is not stopped) This was done to be consistent with the behavior of existing application notes AN1078 and AN1292.": "主按键上的单次按下事件提供\u201c启动\u201d和\u201c停止\u201d输入。（如果电机已停止则请求启动电机；如果电机未停止则请求停止电机）这样做是为了与现有应用笔记 AN1078 和 AN1292 的行为保持一致。",
    "Reverse direction:": "反转方向：",
    "Direction flag is maintained": "方向标志被保持",
    "Reverse direction request:": "反转方向请求：",
    "If 2nd button is present: single press event of 2nd button": "如果存在第二个按键：第二个按键的单次按下事件",
    "If 2nd button is not present: sustained press of first button, first supported in MCAF R2.": "如果不存在第二个按键：第一个按键的长按，首次在 MCAF R2 中支持。",
    "The time needed for this is nominally 3 seconds, set by": "所需时间标称为 3 秒，由",
    "in": "在",
    "and": "和",
    ", along with the motor control loop frequency. (see": "以及电机控制环路频率决定。（见",
    "errata": "勘误",
    "If reverse direction request occurs when motor is stopped, direction flag is reversed but no other action is taken.": "如果反转方向请求在电机停止时发生，方向标志被反转但不采取其他操作。",
    "If reverse direction request occurs when motor is running, then the following sequence occurs:": "如果反转方向请求在电机运行时发生，则以下序列发生：",
    "Request to stop motor": "请求停止电机",
    "Motor reaches a stopped state": "电机达到停止状态",
    "Direction flag reversed": "方向标志反转",
    "Request to start motor": "请求启动电机",
    "Manual restart from a recoverable fault (see": "从可恢复故障中手动重启（见",
    "):": "）：",
    "Single press event, if in fault state, clears fault latch and restarts normal operation.": "单次按下事件，如果处于故障状态，则清除故障锁定并重启正常操作。",
    "Velocity control:": "速度控制：",
    "Potentiometer adjusts magnitude of velocity (speed) from minimum to maximum. Same as behavior of existing appnotes.": "电位器从最小到最大调节速度（转速）的幅值。与现有应用笔记的行为相同。",
    "State indication: see table below": "状态指示：见下表",
    "direction": "方向",
    "state": "状态",
    "both": "两者",
    "off": "关闭",
    "forward": "正向",
    "reverse": "反向",
    "error code blink": "错误代码闪烁",
    "Error Codes": "错误代码",
    "4.7.3. Error Codes": "4.7.3. 错误代码",
    "The MCAF has fault detection logic to cover a number of different conditions and summarize as a unique fault code. The MCAF displays this fault code as a blinking LED pattern based on groups of 1 \u2013 4 blinks. The rationale for this approach is that blink counts greater than 4 are difficult to count.": "MCAF 具有故障检测逻辑，可覆盖多种不同条件并汇总为唯一的故障代码。MCAF 将此故障代码显示为基于 1–4 次闪烁组的 LED 闪烁模式。采用此方法的原因是大于 4 次的闪烁计数难以计数。",
    "Error Code LED Behavior": "错误代码 LED 行为",
    "4.7.3.1. Error Code LED Behavior": "4.7.3.1. 错误代码 LED 行为",
    "Converting Error Code to LED Blink Pattern": "将错误代码转换为 LED 闪烁模式",
    "4.7.3.1.1. Converting Error Code to LED Blink Pattern": "4.7.3.1.1. 将错误代码转换为 LED 闪烁模式",
    "Given a positive (nonzero) integer X which represents an error code, and an LED that can be turned on:": "给定一个表示错误代码的正（非零）整数 X，以及一个可以点亮的 LED：",
    "Convert X to a sequence of base 4 digits, least significant digit first, ending in the last nonzero digit.": "将 X 转换为基数为 4 的数字序列，最低有效位在前，以最后一个非零数字结尾。",
    "Add 1 to each value in the sequence.": "将序列中的每个值加 1。",
    "For each value": "对于每个值",
    "in the sequence:": "在序列中：",
    "Repeat": "重复",
    "times:": "次：",
    "Turn LED on for 250msec": "LED 点亮 250ms",
    "Turn LED off for 250msec": "LED 熄灭 250ms",
    "Wait 500 msec": "等待 500ms",
    "Wait 1500 msec, then goto step 3": "等待 1500ms，然后转到步骤 3",
    "This always produces a sequence containing at least one double/triple/quadruple blink.": "这总是产生一个包含至少一次双/三/四闪烁的序列。",
    "Converting LED Blink Pattern to Error Code": "将 LED 闪烁模式转换为错误代码",
    "4.7.3.1.2. Converting LED Blink Pattern to Error Code": "4.7.3.1.2. 将 LED 闪烁模式转换为错误代码",
    "This is not usually necessary (error code tables include a column indicating the number of blinks directly), but to convert back to a numeric error code:": "这通常不是必需的（错误代码表包含直接指示闪烁次数的列），但要转换回数字错误代码：",
    "Count the number of blinks as a sequence of numbers from 1 \u2013 4": "将闪烁次数计为 1–4 的数字序列",
    "Subtract 1 from each value in the sequence": "从序列中的每个值减去 1",
    "Interpret the sequence as a base 4 number, least significant digit first": "将序列解释为基数为 4 的数字，最低有效位在前",
    "Examples": "示例",
    "4.7.3.1.3. Examples": "4.7.3.1.3. 示例",
    "The examples below include a visual representation of a blink pattern. Each of the": "以下示例包含闪烁模式的视觉表示。每个",
    "symbols represents the LED turning on, and the pattern is drawn to scale in time (each character represents 250msec).": "符号代表 LED 点亮，模式按时间比例绘制（每个字符代表 250ms）。",
    "Error code": "错误代码",
    "Sequence of base 4 digits": "基数为 4 的数字序列",
    "sequence": "序列",
    "two repetitions of blink pattern": "闪烁模式的两次重复",
    "Timing and Fault-Clearing Issues in UI Indicators": "UI 指示器中的时序和故障清除问题",
    "4.7.4. Timing and Fault-Clearing Issues in UI Indicators": "4.7.4. UI 指示器中的时序和故障清除问题",
    "There are two associated issues that are indirectly related to error-code reporting:": "有两个与错误代码报告间接相关的关联问题：",
    "timing of UI indicators (how delays are implemented)": "UI 指示器的时序（延迟如何实现）",
    "fault-clearing issues (what has to happen in order for the system to return to normal operation)": "故障清除问题（系统返回正常操作需要发生什么）",
    "The MCAF uses chosen the following strategy, based on recoverability:": "MCAF 根据可恢复性选择了以下策略：",
    "Error recoverability": "错误可恢复性",
    "recoverability": "可恢复性",
    "timing": "时序",
    "fault-clearing": "故障清除",
    "Recoverable": "可恢复",
    ": faults expected to be caused by a momentary condition: overcurrent, overspeed, overvoltage, etc.": "：预期由瞬时条件引起的故障：过流、超速、过压等。",
    "We rely on the system state machine running at a periodic rate as a timebase for UI delays.": "我们依赖以周期性速率运行的系统状态机作为 UI 延迟的时基。",
    "User intervention required: press the start/stop input button.": "需要用户干预：按下启动/停止输入按钮。",
    "Nonrecoverable": "不可恢复",
    ": something really bad has happened, such as an oscillator failure, stack overflow, or watchdog timeout.": "：发生了严重问题，如振荡器故障、堆栈溢出或看门狗超时。",
    "We cannot necessarily rely on the system state machine operating properly, and instead go into a \u201cparanoid\u201d mode (see below); busy-waiting for a fixed number of CPU cycles is used for timing.": "我们不一定能依赖系统状态机正常运行，而是进入\u201c偏执\u201d模式（见下文）；使用忙等待固定数量的 CPU 周期来实现时序。",
    "User intervention via a manual reset is required.": "需要通过手动复位进行用户干预。",
    "Upon nonrecoverable faults (\u201cparanoid mode\u201d), the following actions occur:": "在不可恢复故障时（\u201c偏执模式\u201d），以下操作发生：",
    "Disable all interrupts": "禁用所有中断",
    "Put": "将",
    "outputs at a safe state": "输出置于安全状态",
    "Report error code via LEDs, relying on busy-waiting to create time delays for UI": "通过 LED 报告错误代码，依赖忙等待创建 UI 的时间延迟",
    "Implementation": "实现",
    "4.7.5. Implementation": "4.7.5. 实现",
    "External interface errata": "外部接口勘误",
    "4.7.5.1. External interface errata": "4.7.5.1. 外部接口勘误",
    "LED patterns are not displayed when in the": "在",
    "or": "或",
    "states. (DB_MC-1922; Applicability: MCAF R1 \u2013 R9.)": "状态下不显示 LED 模式。（DB_MC-1922；适用性：MCAF R1 – R9。）",
    "Timing of emulated button press for MCHV-2 and MCHV-3 are not guaranteed; if there are long-running tasks within the main loop, this can delay the time needed to detect an extended button press. (DB_MC-1920; Applicability: MCAF R2 \u2013 R5; fixed in MCAF R6.)": "MCHV-2 和 MCHV-3 的模拟按键按下时序不保证；如果主循环中有长时间运行的任务，这可能会延迟检测长按按钮所需的时间。（DB_MC-1920；适用性：MCAF R2 – R5；在 MCAF R6 中修复。）",
    "Modules": "模块",
    "4.7.5.2. Modules": "4.7.5.2. 模块",
    "Module": "模块",
    "Files": "文件",
    "Description": "描述",
    "Comments": "说明",
    "List of all error codes": "所有错误代码列表",
    "The Appendix contains": "附录包含",
    "an annotated list of error codes": "带注释的错误代码列表",
    "User interface": "用户界面",
    "Supervisory Algorithms": "监控算法",
    "Diagnostic Kernel": "诊断内核",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
