# -*- coding: utf-8 -*-
import txutil

rel = "components/mcapi"
title_zh = "4.10. 运动控制 API（MCAPI）"

m = {
    "Components": "组件",
    "Motion Control API (MCAPI)": "运动控制 API（MCAPI）",
    "4.10. Motion Control API (MCAPI)": "4.10. 运动控制 API（MCAPI）",
    "provides a set of high-level interfaces that can be used by an application to control the motor and obtain feedback information from it while requiring no underlying knowledge of MCAF and its inner-workings.": "提供了一组高级接口，应用程序可使用这些接口来控制电机并从中获取反馈信息，而无需了解 MCAF 及其内部工作原理。",
    "Block diagram showing MCAPI relative to MCAF and the application": "显示 MCAPI 与 MCAF 和应用程序关系的框图",
    "Overview": "概述",
    "4.10.1. Overview": "4.10.1. 概述",
    "provides the following interfaces for an application to use:": "为应用程序提供以下接口：",
    "Public functions to interact with MCAF — defined in": "与 MCAF 交互的公共函数——定义在",
    "enum": "enum",
    "and": "和",
    "struct": "struct",
    "typedefs to work with these": "typedef 以配合这些",
    "functions — defined in": "函数使用——定义在",
    "All": "所有",
    "functions are designed with following goals:": "函数的设计目标如下：",
    "Minimize CPU execution time": "最小化 CPU 执行时间",
    "Non-blocking implementation": "非阻塞实现",
    "Do not need to be called at any particular rate and do not require any timing reference": "不需要以任何特定速率调用，且不需要任何时序参考",
    "Do not require access to any of the device peripherals": "不需要访问任何设备外设",
    "API Description": "API 描述",
    "4.10.2. API Description": "4.10.2. API 描述",
    "functions that are defined in": "函数定义在",
    "also include doc comments with relevant information. The table below shows a list of these functions and a brief summary of their description.": "中还包含带相关信息的文档注释。下表显示了这些函数的列表及其简要描述。",
    "Top-level API feature": "顶层 API 功能",
    "API description": "API 描述",
    "Start the motor": "启动电机",
    "Starts the specified motor. There will be no change if the motor is already running. If there is an active MCAF fault, this function will have no effect.": "启动指定的电机。如果电机已在运行，则不会发生变化。如果存在活动的 MCAF 故障，此函数将无效。",
    "Stop the motor": "停止电机",
    "Stops the specified motor. There will be no change if the motor is already in fault, stopped or stopping states.": "停止指定的电机。如果电机已处于故障、停止或正在停止状态，则不会发生变化。",
    "Set velocity reference": "设置速度参考",
    "Uses the specified value to update velocity reference for the motor. Input value is a signed Q15 number that has the same scaling factor for velocity as used within MCAF. Sign of the input value will determine the direction of rotation.": "使用指定值更新电机的速度参考。输入值为有符号 Q15 数，具有与 MCAF 中使用的速度相同的缩放因子。输入值的符号决定旋转方向。",
    "Changes in velocity command when the motor is not in": "当电机不在",
    "state will be saved and will take effect only when the motor reaches this state.": "状态时，速度命令的更改将被保存，仅在电机达到此状态时生效。",
    "Before this function is called for the first time after initialization, the set value of velocity reference is either zero, or equal to the minimum value of velocity reference that is valid for MCAF.": "在初始化后首次调用此函数之前，速度参考的设定值为零，或等于对 MCAF 有效的速度参考最小值。",
    "Note:": "注意：",
    "There are slew rate limits within MCAF that will limit step changes in reference from taking effect on the motor on an immediate basis.": "MCAF 内部有压摆率限制，将限制参考的阶跃变化立即对电机生效。",
    "Also, changes in the direction of rotation at runtime is not currently supported by MCAF. There is a band of velocity reference around zero that is considered as invalid input for MCAF.": "此外，MCAF 当前不支持在运行时更改旋转方向。在零附近有一个速度参考带被视为 MCAF 的无效输入。",
    "Invalid values of velocity reference will be limited to the minimum velocity parameter that is defined in MCAF.": "无效的速度参考值将被限制为 MCAF 中定义的最小速度参数。",
    "Get velocity reference": "获取速度参考",
    "Returns a signed Q15 value of velocity reference for the motor. The return value will exactly match the set value set by \u201cset velocity\u201d function and have the same scaling factor for velocity as used within MCAF. Sign of the return value will determine the direction of rotation.": "返回电机速度参考的有符号 Q15 值。返回值将与\u201c设置速度\u201d函数设定的值完全匹配，并具有与 MCAF 中使用的速度相同的缩放因子。返回值的符号决定旋转方向。",
    "Before the \u201cset velocity\u201d function is called for the first time after initialization, the return value of velocity reference is either zero, or equal to the minimum value of velocity reference that is valid for MCAF.": "在初始化后首次调用\u201c设置速度\u201d函数之前，速度参考的返回值为零，或等于对 MCAF 有效的速度参考最小值。",
    "Get motor velocity": "获取电机速度",
    "Returns a signed Q15 value of velocity for the motor as measured by an estimator in MCAF. The return value will have the same scaling factor for velocity as used within MCAF. Sign of the return value will determine the direction of rotation.": "返回由 MCAF 中估算器测量的电机速度的有符号 Q15 值。返回值具有与 MCAF 中使用的速度相同的缩放因子。返回值的符号决定旋转方向。",
    "Get magnitude of current": "获取电流幅值",
    "Returns a signed Q15 value that represents the amplitude of current in the motor. The return value is scaled in terms of the same scaling factor for full-scale current as used in MCAF.": "返回表示电机电流幅值的有符号 Q15 值。返回值按与 MCAF 中使用的满量程电流相同的缩放因子进行缩放。",
    "Since this value is derived from signals with low pass filtering, this is not an instantaneous value and will have some delay compared to the actual current in the motor. The filter time constant used in this case can be changed in the": "由于此值来自经过低通滤波的信号，因此不是瞬时值，与电机中的实际电流相比会有一些延迟。此情况下使用的滤波器时间常数可以在",
    "Customize": "自定义",
    "page of motorBench": "页面的 motorBench",
    "Development Suite.": "Development Suite 中更改。",
    "Get fault status": "获取故障状态",
    "Returns a": "返回一个",
    "type bit-field with individual flags for each fault type.": "类型的位域，每个故障类型有独立的标志位。",
    "Clear fault status": "清除故障状态",
    "Clears the specified fault flag or a given set of fault flags. This function does not implicitly start the motor after clearing all pending faults.": "清除指定的故障标志或给定的一组故障标志。此函数在清除所有待处理故障后不会隐式启动电机。",
    "Get motor status": "获取电机状态",
    "type motor status.": "类型的电机状态。",
    "Get current Iq": "获取电流 Iq",
    "Returns a signed Q15 value that represents the q-axis current in the motor. This return value is scaled in terms of the same scaling factor for full-scale current as used in MCAF.": "返回表示电机 q 轴电流的有符号 Q15 值。此返回值按与 MCAF 中使用的满量程电流相同的缩放因子进行缩放。",
    "value of full-scale current": "满量程电流值",
    "Returns a floating point formatted full-scale value of current that is being used by MCAF.": "返回 MCAF 正在使用的电流满量程值的浮点格式。",
    "value of full-scale voltage": "满量程电压值",
    "Returns a floating point formatted full-scale value of voltage that is being used by MCAF.": "返回 MCAF 正在使用的电压满量程值的浮点格式。",
    "value of full-scale torque": "满量程转矩值",
    "Returns a floating point formatted full-scale value of electromagnetic torque for the given hardware system being used with MCAF.": "返回与 MCAF 一起使用的给定硬件系统的电磁转矩满量程值的浮点格式。",
    "Factors such as reluctance torque, iron saturation and changes in magnet flux due to temperature can impact the accuracy of this scaling factor. Hence, this is to be consumed by the application on a \u201cfor indication only\u201d basis.": "磁阻转矩、铁芯饱和以及温度导致的磁通变化等因素会影响此缩放因子的准确性。因此，应用程序应仅以\u201c仅供参考\u201d的方式使用此值。",
    "value of full-scale velocity": "满量程速度值",
    "Returns a floating point formatted full-scale value of velocity that is being used by MCAF.": "返回 MCAF 正在使用的速度满量程值的浮点格式。",
    "Pre-ADC ISR function": "ADC ISR 前函数",
    "This is a place-holder implementation of the pre-ADC ISR function that will get called at the beginning of ADC ISR that is used by MCAF.": "这是 ADC ISR 前函数的占位实现，将在 MCAF 使用的 ADC ISR 开始时被调用。",
    "This interface is intended to support the need for functional safety features that check for periodicity of interrupts and execute some test cases.": "此接口旨在支持检查中断周期性并执行某些测试用例的功能安全需求。",
    "Post-ADC ISR functions": "ADC ISR 后函数",
    "This is a place-holder implementation of the post-ADC ISR function that will get called at the end of ADC ISR that is used by MCAF.": "这是 ADC ISR 后函数的占位实现，将在 MCAF 使用的 ADC ISR 结束时被调用。",
    "Get DC link voltage": "获取直流母线电压",
    "Returns a signed Q15 value that represents DC link voltage in the system. This return value is scaled in terms of the same scaling factor for full-scale voltage as used in MCAF.": "返回表示系统中直流母线电压的有符号 Q15 值。此返回值按与 MCAF 中使用的满量程电压相同的缩放因子进行缩放。",
    "Get upper current saturation limit": "获取电流饱和上限",
    "Returns a signed Q15 value that represents upper bound of the current saturation limit that is implemented in MCAF.": "返回表示 MCAF 中实现的电流饱和上限的有符号 Q15 值。",
    "Get lower current saturation limit": "获取电流饱和下限",
    "Returns a signed Q15 value that represents lower bound of the current saturation limit that is implemented in MCAF.": "返回表示 MCAF 中实现的电流饱和下限的有符号 Q15 值。",
    "Get maximum value of velocity reference": "获取速度参考最大值",
    "Gets the maximum command value of velocity reference that is currently supported in the given configuration of MCAF.": "获取给定 MCAF 配置中当前支持的速度参考最大命令值。",
    "Get minimum value of velocity reference": "获取速度参考最小值",
    "Gets the minimum command value of velocity reference that is currently supported in the given configuration of MCAF.": "获取给定 MCAF 配置中当前支持的速度参考最小命令值。",
    "Set application-level fault code": "设置应用级故障代码",
    "Allows the application to set an application-level fault code that impacts the motor drive. The application is responsible for setting the following fault codes:": "允许应用程序设置影响电机驱动的应用级故障代码。应用程序负责设置以下故障代码：",
    "Get application-level fault code": "获取应用级故障代码",
    "Gets the fault code set by the application.": "获取由应用程序设置的故障代码。",
    "enum defines the possible fault flags in the bit-field returned by": "enum 定义了由",
    ". The table below shows a list of these fault flags and a brief description.": "返回的位域中可能的故障标志。下表显示了这些故障标志的列表及简要描述。",
    "MCAPI fault flag": "MCAPI 故障标志",
    "Fault description": "故障描述",
    "An over-current fault has occurred.": "发生了过流故障。",
    "An under-voltage fault has occurred.": "发生了欠压故障。",
    "An over-voltage fault has occurred.": "发生了过压故障。",
    "An over-temperature fault has occurred. This may be in the inverter power stage or the motor.": "发生了过温故障。这可能是在逆变器功率级或电机中。",
    "A gate driver fault has occurred.": "发生了栅极驱动器故障。",
    "An unspecified fault has occurred. This fault flag encapsulates all errors that are not covered by the fault flags listed above. See": "发生了未指定的故障。此故障标志封装了上述故障标志未涵盖的所有错误。参见",
    "Error Codes": "错误代码",
    "for a complete list of possible errors.": "获取可能的错误完整列表。",
    "Usage Notes": "使用说明",
    "4.10.3. Usage Notes": "4.10.3. 使用说明",
    "This guidance is available for application developers accessing MCAF through": "本指南适用于通过",
    "functions.": "函数访问 MCAF 的应用程序开发者。",
    "Do not use any of the interfaces defined in": "不要使用定义在",
    "Do not use the types": "不要使用类型",
    "or access their contents.": "或访问其内容。",
    "After device startup, call": "设备启动后，调用",
    "once before calling any MCAPI functions from the application.": "一次，然后再从应用程序调用任何 MCAPI 函数。",
    "functions have certain latency limits. Latency for a setter function or command function is the time delay between the beginning of MCAPI function call and the instant the corresponding MCAF control variable is set (note that because of interaction between main thread and ISR, this change may not take effect until some time after MCAPI function call has completed). Latency for a getter function or feedback function is the time delay between the instant MCAF ISR samples a value from its internal state, and the instant MCAPI returns that value as a result of MCAPI function call.": "函数有一定的延迟限制。setter 函数或命令函数的延迟是指 MCAPI 函数调用开始到相应 MCAF 控制变量被设置之间的时间延迟（注意，由于主线程和 ISR 之间的交互，此更改可能在 MCAPI 函数调用完成后一段时间才生效）。getter 函数或反馈函数的延迟是指 MCAF ISR 从其内部状态采样值的时刻到 MCAPI 作为 MCAPI 函数调用结果返回该值的时刻之间的时间延迟。",
    "Despite this latency limitation, calling one of the": "尽管有此延迟限制，在调用对应的",
    "get": "get",
    "functions immediately after calling its counterpart": "函数后立即调用",
    "set": "set",
    "function will promptly return the set value. In this case, the return value from": "函数将立即返回设定值。在这种情况下，",
    "function represents the request and not necessarily the state of the motor.": "函数的返回值代表请求，不一定是电机的实际状态。",
    "Latency limits of": "的延迟限制",
    "functions are not bounded in MCAF R6, R7. However, latency for both getter and setter functions are typically within 2 ISR cycles.": "函数在 MCAF R6、R7 中没有界限。但是，getter 和 setter 函数的延迟通常在 2 个 ISR 周期内。",
    "Calling one or more": "连续快速调用一个或多个",
    "functions in quick succession, for instance, less than 1 ms apart, can cause latency to increase. Similarly, calling one of the": "函数（例如间隔小于 1 ms）可能导致延迟增加。类似地，在",
    "functions within a": "函数中调用",
    "loop without any delay will cause": "循环中无延迟地调用",
    "to lose synchronization with MCAF.": "会导致其与 MCAF 失去同步。",
    "Since": "由于",
    "interacts with sections of MCAF that execute from an interrupt, the application cannot assume the motor state to be unchanged in between successive calls to the": "与从中断执行的 MCAF 部分交互，应用程序不能假设在连续调用",
    "See": "参见",
    "Main Application": "主应用程序",
    "for a description of an example application that is included with MCAF.": "了解 MCAF 附带的示例应用程序的描述。",
    "Implementation Notes": "实现说明",
    "4.10.4. Implementation Notes": "4.10.4. 实现说明",
    "The MCAPI was introduced in MCAF R6 to provide the main application a set of high-level interfaces to MCAF.": "MCAPI 在 MCAF R6 中引入，为主应用程序提供一组 MCAF 的高级接口。",
    "The following functions were introduced in MCAF R7:": "以下函数在 MCAF R7 中引入：",
    "MCAPI Architecture": "MCAPI 架构",
    "4.10.4.2. MCAPI Architecture": "4.10.4.2. MCAPI 架构",
    "Block diagram showing MCAPI implementation architecture": "显示 MCAPI 实现架构的框图",
    "MCAPI uses a single data buffer approach in MCAPI motor data in order to reliably communicate in between the application, which is asynchronous to the ADC ISR, and MCAF routines that execute from the ADC ISR.": "MCAPI 在 MCAPI 电机数据中使用单数据缓冲区方法，以便在与 ADC ISR 异步的应用程序和从 ADC ISR 执行的 MCAF 例程之间可靠通信。",
    "On the application-facing side of MCAPI: all MCAPI functions that are called by the application write to and read from MCAPI motor data.": "在 MCAPI 面向应用程序的一侧：应用程序调用的所有 MCAPI 函数都向 MCAPI 电机数据写入和读取。",
    "On the MCAF-facing side of MCAPI: an API service routine that is called from the ADC ISR synchronizes MCAPI motor data with control variables within MCAF motor data.": "在 MCAPI 面向 MCAF 的一侧：从 ADC ISR 调用的 API 服务例程将 MCAPI 电机数据与 MCAF 电机数据中的控制变量同步。",
    "MCAPI Data Access": "MCAPI 数据访问",
    "4.10.4.2.1. MCAPI Data Access": "4.10.4.2.1. MCAPI 数据访问",
    "MCAPI motor data, defined by the type": "MCAPI 电机数据，由类型",
    ", is allocated within the MCAF motor structure of type": "定义，分配在类型为",
    "MCAF ADC ISR accesses MCAPI motor data structure through MCAPI internal function,": "MCAF ADC ISR 通过 MCAPI 内部函数",
    ", from a function call in": "从",
    "The application should use one of the public MCAPI functions to indirectly access MCAPI motor data structure using the pointer": "应用程序应使用公共 MCAPI 函数之一通过指针",
    ". This should be treated as an opaque data structure, and the application should not access its contents directly.": "间接访问 MCAPI 电机数据结构。这应被视为不透明数据结构，应用程序不应直接访问其内容。",
    "motor": "motor",
    "int": "int",
    "main": "main",
    "void": "void",
    "apiData": "apiData",
    "...": "...",
    "motorState": "motorState",
    "switch": "switch",
    "case": "case",
    "# do something": "# 执行某些操作",
    "return": "return",
    "Handling Concurrency": "处理并发",
    "4.10.4.2.2. Handling Concurrency": "4.10.4.2.2. 处理并发",
    "The application may execute at some arbitrary rate, with calls to MCAPI that are asynchronous to the ADC ISR. Shared MCAPI motor data that is used in both MCAPI function calls and the ADC ISR must be protected against unsynchronized concurrent memory access, known as a": "应用程序可以以任意速率执行，对 MCAPI 的调用与 ADC ISR 异步。在 MCAPI 函数调用和 ADC ISR 中都使用的共享 MCAPI 电机数据必须受到保护，以防止未同步的并发内存访问，即所谓的",
    "data race": "数据竞争",
    "For example, the following sequence of events could occur within MCAPI function": "例如，以下事件序列可能发生在 MCAPI 函数",
    ", which sets a series of bit flags in": "中，该函数在",
    "to request clearing faults:": "中设置一系列位标志以请求清除故障：",
    "The application calls": "应用程序调用",
    "reads a preexisting value of 8 (bit 3 is set) from": "从",
    "in MCAPI motor data": "在 MCAPI 电机数据中读取预先存在的值 8（位 3 已设置）",
    "is interrupted by the ADC ISR and": "被 ADC ISR 中断，且",
    "clears bit 3, writing": "清除位 3，写入",
    "to 0": "为 0",
    "calculates a value of 10 from 8 OR 2": "从 8 OR 2 计算出值 10",
    "writes the value 10 to": "将值 10 写入",
    "In this case, the write made by the ADC ISR was lost.": "在这种情况下，ADC ISR 所做的写入丢失了。",
    "To prevent data races, MCAPI functions use the": "为防止数据竞争，MCAPI 函数使用",
    "flag to claim ownership of MCAPI motor data structure while they are executing a critical section of code. The API service routine is designed to skip execution when it sees that the": "标志来声明对 MCAPI 电机数据结构的所有权，同时执行代码的关键部分。API 服务例程设计为在看到",
    "flag is set.": "标志已设置时跳过执行。",
    "MCAPI errata": "MCAPI 勘误",
    "4.10.4.3. MCAPI errata": "4.10.4.3. MCAPI 勘误",
    "MCAPI will not individually clear": "MCAPI 不会单独清除",
    "fault or": "故障或",
    "fault if there are other active faults": "故障，如果存在其他活动故障",
    ". (DB_MC-3012; Applicability: MCAF R6, R7; fixed in MCAF R8.)": "。（DB_MC-3012；适用性：MCAF R6、R7；在 MCAF R8 中修复。）",
    "For example, if there are three active faults at a given instance of time:": "例如，如果在给定时刻有三个活动故障：",
    "fault": "故障",
    "Then, in this case the following code snippet will not clear": "那么在这种情况下，以下代码片段不会清除",
    "Application can workaround this issue by clearing all faults in one attempt as shown in the code snippet below.": "应用程序可以通过一次性清除所有故障来规避此问题，如下面的代码片段所示。",
    "MCAPI may drop fault events from MCAF under certain corner-cases.": "在某些极端情况下，MCAPI 可能会丢失来自 MCAF 的故障事件。",
    "(DB_MC-2978; Applicability: MCAF R6, R7; fixed in MCAF R8.)": "（DB_MC-2978；适用性：MCAF R6、R7；在 MCAF R8 中修复。）",
    "This issue may occur if these two events occur in the same ADC interrupt:": "如果以下两个事件在同一个 ADC 中断中发生，则可能出现此问题：",
    "clears a particular fault condition.": "清除特定故障条件。",
    "MCAF raises another instance of the same fault condition.": "MCAF 引发同一故障条件的另一个实例。",
    "In the existing implementation of": "在现有",
    ", the application does not have a workaround for this issue.": "的实现中，应用程序没有此问题的规避方法。",
    "Modules": "模块",
    "4.10.4.4. Modules": "4.10.4.4. 模块",
    "Module": "模块",
    "Files": "文件",
    "Description": "描述",
    "Comments": "说明",
    "MCAPI source": "MCAPI 源码",
    "MCAPI routines internal to MCAF": "MCAF 内部的 MCAPI 例程",
    "Hardware Abstraction Layer (HAL)": "硬件抽象层（HAL）",
    "Miscellaneous": "杂项",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
