# -*- coding: utf-8 -*-
import txutil

rel = "components/main"
title_zh = "4.1. 主应用程序"

m = {
    "Components": "组件",
    "Main Application": "主应用程序",
    "4.1. Main Application": "4.1. 主应用程序",
    "As mentioned in the section on": "如",
    "scheduling": "调度",
    ", the main application consists of a portion of code that executes in": "一节中所述，主应用程序由一部分在",
    "Implementation Notes": "实现说明",
    "4.1.1. Implementation Notes": "4.1.1. 实现说明",
    "Prior to MCAF R6, the main application was tightly integrated with MCAF, while keeping the responsibility for the user interface entirely within the": "在 MCAF R6 之前，主应用程序与 MCAF 紧密集成，同时将用户界面的职责完全交由",
    "External Interface": "外部接口",
    "component.": "组件定义和实现。",
    "The main application has been rewritten to include a sample application. The sample application interacts with MCAF through the": "主应用程序已被重写以包含一个示例应用程序。示例应用程序通过",
    "Motion Control API (MCAPI)": "运动控制 API（MCAPI）",
    "to control and obtain feedback from the motor.": "与 MCAF 交互，以控制电机并获取反馈。",
    "The main application now utilizes the": "主应用程序现在使用",
    "Motion Control API": "运动控制 API",
    "as the single point of interface to MCAF, reducing exposure to MCAF internals.": "作为与 MCAF 接口的唯一入口，减少了对 MCAF 内部的暴露。",
    "Sample application can attempt to restart the motor while it is stopping": "示例应用程序可以在电机停止过程中尝试重新启动电机",
    "Added two new files: mcaf_main.c and mcaf_sample_application.h": "新增了两个文件：mcaf_main.c 和 mcaf_sample_application.h",
    "Moved the definition of": "将",
    "and": "和",
    "from": "的定义从",
    "sample_mcaf_application.c to mcaf_main.c": "sample_mcaf_application.c 到 mcaf_main.c",
    "Updated the function signature of": "更新了",
    "to include a pointer to the MCAPI data structure.": "的函数签名，以包含指向 MCAPI 数据结构的指针。",
    "Moved": "将",
    "to mcaf_main.c": "移至 mcaf_main.c",
    "Sample Application": "示例应用程序",
    "4.1.1.3.1. Sample Application": "4.1.1.3.1. 示例应用程序",
    "The sample application user interface behavior can be summarized as follows:": "示例应用程序的用户界面行为可概括如下：",
    "If the motor is stopping/stopped, then the primary pushbutton starts the motor. If the primary pushbutton is pressed during the": "如果电机正在停止/已停止，则主按键启动电机。如果在",
    "state, the": "状态下按下主按键，",
    "state machine": "状态机",
    "will behave differently depending on the": "将根据",
    "stopping mode": "停止模式",
    "Minimal-impact PWM": "最小影响 PWM",
    "state transition sequence:": "状态转换序列：",
    "Closed-loop (current or velocity)": "闭环（电流或速度）",
    "If the motor is starting/running, then the primary pushbutton stops the motor.": "如果电机正在启动/运行，则主按键停止电机。",
    "If the motor is in fault condition, then the primary pushbutton clears all pending faults.": "如果电机处于故障状态，则主按键清除所有待处理的故障。",
    "If MCAF is in one of its test modes, then the primary pushbutton and the secondary pushbutton do not have any effect.": "如果 MCAF 处于其某种测试模式，则主按键和副按键不起任何作用。",
    "The secondary pushbutton changes the direction of rotation.": "副按键改变旋转方向。",
    "The potentiometer sets the speed reference for the motor, with minimum and maximum limits as defined by MCAF and made available through MCAPI functions": "电位器为电机设定速度参考值，其最小和最大限值由 MCAF 定义并通过 MCAPI 函数",
    "respectively.": "提供。",
    "The pushbutton and potentiometer user interface can be disabled in the sample application by clearing": "在示例应用程序中，可以通过清除",
    "in the application data structure, for instance using a real-time diagnostic tool like": "来禁用按键和电位器用户界面，例如使用实时诊断工具",
    "See": "有关按键用户界面的实现细节，请参见",
    "for implementation details of the user interface for pushbuttons.": "。",
    "The user interface for LEDs is defined and implemented by the": "LED 的用户界面由",
    "Modules": "模块",
    "4.1.1.4. Modules": "4.1.1.4. 模块",
    "Module": "模块",
    "Files": "文件",
    "Description": "描述",
    "Comments": "说明",
    "Top-level ISR": "顶层 ISR",
    "The main control": "主控制",
    "function runs on a periodic basis. It is triggered at the completion of": "函数周期性运行。它在",
    "sampling, which in turn is triggered once per": "采样完成时触发，而采样又由",
    "cycle, as mentioned in the": "周期触发一次，如",
    "Scheduling": "调度",
    "section. It contains profiling logic:": "一节中所述。它包含性能分析逻辑：",
    "generates a pulse on a GPIO pin that starts on": "在 GPIO 引脚上生成一个脉冲，该脉冲在",
    "entry and ends on": "入口开始，在",
    "exit": "出口结束",
    "capture of timer counter (see": "捕获定时器计数值（参见",
    "test harness": "测试框架",
    "Various": "各种",
    "subtasks are executed in rough order of priority (state machine tasks first, test harness and diagnostic tasks last).": "子任务按大致的优先级顺序执行（状态机任务优先，测试框架和诊断任务最后）。",
    "The actual name of the": "实际的",
    "function is hardware-dependent and is encapsulated in the": "函数名称与硬件相关，并由",
    "HAL": "HAL",
    "by the": "中的",
    "macro.": "宏封装。",
    "Main MCAF entry points called from": "从",
    "(initialization and main loop)": "调用的 MCAF 主入口点（初始化和主循环）",
    "Provides": "提供",
    ". These are the entry points for MCAF from the": "。这些是 MCAF 从",
    "Sample application": "示例应用程序",
    "Sample application starts/stops the motor using pushbuttons and sets motor speed reference using the potentiometer.": "示例应用程序使用按键启动/停止电机，并使用电位器设定电机速度参考值。",
    "Trap interrupt handlers": "陷阱中断处理程序",
    "System initialization": "系统初始化",
    "Initializes state variables and special function registers prior to the main loop (intended to be called in": "在主循环之前初始化状态变量和特殊功能寄存器（预期在",
    "— called at the beginning of": "— 在",
    "to initialize certain SFRs and system-wide state variables as soon as possible.": "的开头调用，以尽快初始化某些 SFR 和系统级状态变量。",
    "— called near the end of": "— 在",
    "for deferred initialization. This includes code to enable interrupts, and therefore main-thread code that executes prior to": "的末尾附近调用，用于延迟初始化。这包括启用中断的代码，因此在",
    "is not prone to race conditions caused by conflicts with an": "之前执行的主线程代码不会受到与刚刚启用的",
    "that has just been enabled.": "冲突而导致的竞态条件的影响。",
    "System state variable type definitions": "系统状态变量类型定义",
    "Defines the main": "定义了主要的",
    "structure types.": "结构体类型。",
    "Trap-handler module": "陷阱处理模块",
    "4.1.1.4.1. Trap-handler module": "4.1.1.4.1. 陷阱处理模块",
    "Hardware trap vectors in dsPIC": "dsPIC",
    "DSC devices contain handlers for events like a stack overflow, or an address alignment error. In the MCAF, these are located in the": "DSC 器件中的硬件陷阱向量包含针对堆栈溢出或地址对齐错误等事件的处理程序。在 MCAF 中，这些位于",
    "module. The normal handling logic is to signal a nonrecoverable error, by calling the": "模块中。正常的处理逻辑是通过调用",
    "function, which records an error code and goes into an endless loop to flash the LEDs to indicate an error code via": "函数来发出不可恢复错误的信号，该函数记录错误代码并进入无限循环，通过",
    "as discussed in the UI module.": "闪烁 LED 来指示错误代码，如 UI 模块中所述。",
    "Two minor deviations from this behavior:": "此行为有两个小的偏差：",
    "DMA write collision": "DMA 写冲突",
    ": this occurs when the CPU and a DMA channel write to the same address (in which case the CPU \u201cwins\u201d and the DMA write is ignored). This condition is not considered an error in this application, and arises in rare cases for one variant of the diagnostic module which utilizes the DMA for reading and writing the UART. The DMA trap handler increments a counter for assessing the frequency of DMA write collisions.": "：当 CPU 和 DMA 通道写入同一地址时发生（此时 CPU \u201c获胜\u201d，DMA 写入被忽略）。在本应用程序中，此情况不视为错误，仅在使用 DMA 读写 UART 的诊断模块的某个变体中偶尔出现。DMA 陷阱处理程序会递增一个计数器，用于评估 DMA 写冲突的频率。",
    "Stack overflow": "堆栈溢出",
    ": a stack overflow is a nonrecoverable error, but is slightly different in that the stack pointer (W15 on dsPIC": "：堆栈溢出是一种不可恢复的错误，但略有不同，因为堆栈指针（dsPIC",
    "DSC devices) may not be valid. In this condition, the MCAF takes extra care by using a small \u201cfailsafe stack\u201d, which is a static area of memory reserved for this case, and is large enough to cover the stack requirements needed by the": "DSC 器件上的 W15）可能无效。在这种情况下，MCAF 会格外小心地使用一个小的\u201c故障安全堆栈\u201d，这是一个为此情况预留的静态内存区域，其大小足以满足",
    "function.": "函数的堆栈需求。",
    "In addition to hardware traps, the": "除了硬件陷阱外，",
    "module also includes logic to examine cause of reset, so that in the event of a watchdog reset, a nonrecoverable error can be signaled via": "模块还包含检查复位原因的逻辑，以便在看门狗复位时，可以通过",
    "ADC Calibration and Compensation": "ADC 校准与补偿",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
