# -*- coding: utf-8 -*-
import txutil

rel = "components/foc"
title_zh = "4.4. 磁场定向控制（FOC）"

m = {
    "Components": "组件",
    "Field-Oriented Control (FOC)": "磁场定向控制（FOC）",
    "4.4. Field-Oriented Control (FOC)": "4.4. 磁场定向控制（FOC）",
    "consists of a velocity controller, a current controller, and commutation and estimation subcomponents. A high-level block diagram of the": "由速度控制器、电流控制器以及换相和估计子组件组成。",
    "components is shown in": "组件的高层框图如",
    "Block diagram of MCAF Field Oriented Control": "MCAF 磁场定向控制框图",
    "This diagram shows a number of features that are described in the": "此框图显示了多个在",
    "test harness": "测试框架",
    "Velocity Control": "速度控制",
    "4.4.1. Velocity Control": "4.4.1. 速度控制",
    "The velocity control loop is a straightforward, scalar PI controller, with managed saturation features to prevent integrator windup when either the velocity or current controller saturates.": "速度控制环路是一个简单的标量 PI 控制器，具有管理的饱和特性，以防止在速度或电流控制器饱和时出现积分器饱和。",
    "It is preceded by a rate limiter, to provide more gentle trajectory shaping and reduce transient overshoot.": "其前级有一个速率限制器，以提供更平滑的轨迹整形并减少瞬态过冲。",
    "Saturation and antiwindup features are present and covered in a": "饱和和反饱和特性已包含并在",
    "separate document": "单独的文档",
    "Voltage Control": "电压控制",
    "4.4.1.1. Voltage Control": "4.4.1.1. 电压控制",
    "Voltage control": "电压控制",
    "is an alternative control structure available in MCAF R7. In voltage control, back-emf is used as a proxy for velocity control, with some compliance due to the stator resistance. When this feature is active, the current control loop and the active position/velocity estimators are operating normally.": "是 MCAF R7 中提供的替代控制结构。在电压控制中，反电动势被用作速度控制的代理，由于定子电阻的存在而具有一定的柔量。当此功能激活时，电流控制环路和活动的位置/速度估计器正常运行。",
    "Current Control": "电流控制",
    "4.4.2. Current Control": "4.4.2. 电流控制",
    "The current control loop is a vector control loop that operates in the": "电流控制环路是一个在",
    "reference frame, with reference transforms to convert to/from the": "参考坐标系中运行的矢量控制环路，通过参考变换与",
    "stationary reference frame in which currents are measured and duty cycles are commanded. The vector control loop itself is a straightforward pair of PI controllers, with managed saturation features to prevent integrator windup when the current controller saturates. (Saturation and antiwindup features are covered in more detail in a": "静止参考坐标系（电流测量和占空比指令的坐标系）进行转换。矢量控制环路本身是一对简单的 PI 控制器，具有管理的饱和特性，以防止在电流控制器饱和时出现积分器饱和。（饱和和反饱和特性在",
    ".)": "中有更详细的介绍。）",
    "shows a filter block preceding the current controller. It is intended to slow down incoming commands from the velocity loop, which typically executes at a slower rate.": "显示了一个位于电流控制器之前的滤波器模块。其目的是减缓来自速度环路的输入命令，速度环路通常以较慢的速率执行。",
    "also shows DC link voltage compensation following the Inverse Park Transform.": "还显示了逆 Park 变换之后的直流母线电压补偿。",
    "Position and Velocity Estimator": "位置和速度估计器",
    "4.4.3. Position and Velocity Estimator": "4.4.3. 位置和速度估计器",
    "MCAF provides several": "MCAF 提供了多种",
    "position and velocity estimators": "位置和速度估计器",
    "used for commutation and velocity control:": "用于换相和速度控制：",
    "Angle-tracking phase-locked loop (ATPLL)": "角度跟踪锁相环（ATPLL）",
    "Quadrature encoder (QEI)": "正交编码器（QEI）",
    "Zero-Speed / Maximum Torque (ZS/MT)": "零速/最大转矩（ZS/MT）",
    "Implementation Notes": "实现说明",
    "4.4.4. Implementation Notes": "4.4.4. 实现说明",
    "FOC feature support": "FOC 功能支持",
    "4.4.4.1. FOC feature support": "4.4.4.1. FOC 功能支持",
    "Flux weakening": "弱磁控制",
    "4.4.4.1.1. Flux weakening": "4.4.4.1.1. 弱磁控制",
    "In MCAF R1 – R5, flux weakening was not provided, and the velocity controller set the d-axis current command to zero.": "在 MCAF R1 – R5 中，未提供弱磁控制，速度控制器将 d 轴电流指令设为零。",
    "Since MCAF R6, flux weakening has been provided as part of the": "从 MCAF R6 开始，弱磁控制已作为",
    "Flux control": "磁通控制",
    "module.": "模块的一部分提供。",
    "4.4.4.1.7. Flux control": "4.4.4.1.7. 磁通控制",
    "Current command prefilter": "电流指令预滤波器",
    "4.4.4.1.2. Current command prefilter": "4.4.4.1.2. 电流指令预滤波器",
    "The filter just prior to the current controller is unimplemented in MCAF R1 – R9, but is reserved for a future version.": "电流控制器之前的滤波器在 MCAF R1 – R9 中未实现，但保留供未来版本使用。",
    "DC link voltage compensation": "直流母线电压补偿",
    "4.4.4.1.3. DC link voltage compensation": "4.4.4.1.3. 直流母线电压补偿",
    "was not implemented for MCAF R1, but has been implemented since MCAF R2. In MCAF R1, the multiply between": "在 MCAF R1 中未实现，但从 MCAF R2 开始已实现。在 MCAF R1 中，",
    "and": "和",
    "is not present.": "之间的乘法不存在。",
    "PWM duty cycle realization": "PWM 占空比实现",
    "4.4.4.1.4. PWM duty cycle realization": "4.4.4.1.4. PWM 占空比实现",
    "MCAF R1 used an implementation of conventional space-vector PWM (CSVPWM) from the Microchip Motor Control Library (": "MCAF R1 使用了 Microchip 电机控制库（",
    "). Starting with MCAF R2, this has been switched to use a Zero Sequence Modulation block, which includes clipping within realizable limits (minimum and maximum duty cycle limits) in order to support": "）中的传统空间矢量 PWM（CSVPWM）实现。从 MCAF R2 开始，已切换为使用零序调制模块，该模块包含在可实现范围内的削波（最小和最大占空比限制），以支持",
    "overmodulation": "过调制",
    ". See": "。参见",
    "For more information on ZSM, see Microchip\u2019s": "有关 ZSM 的更多信息，请参见 Microchip 的",
    "Zero Sequence Modulation Tutorial": "零序调制教程",
    "Velocity loop current limit": "速度环路电流限制",
    "4.4.4.1.5. Velocity loop current limit": "4.4.4.1.5. 速度环路电流限制",
    "The velocity loop controller has upper and lower limits for its output, a q-axis current reference.": "速度环路控制器对其输出（q 轴电流参考值）设有上限和下限。",
    "MCAF R1 – R5 used fixed upper and lower limits, equal to": "MCAF R1 – R5 使用固定的上限和下限，等于",
    ", the rated continuous drive current or rated continuous motor current, whichever is loewr.": "，即额定连续驱动电流或额定连续电机电流中的较小值。",
    "Since MCAF R6, the velocity controller uses a limit computed by the": "从 MCAF R6 开始，速度控制器使用由",
    "flux control module": "磁通控制模块",
    ", that is bounded by": "计算的限值，该限值以",
    ". Depending on the type of current limit region used, this limit may be fixed or may be changing dynamically. For more details, see": "为界。根据所使用的电流限制区域类型，此限值可能是固定的或动态变化的。更多详情请参见",
    "Calculation of q-axis current limit": "q 轴电流限值的计算",
    "Saturation and anti-windup": "饱和和反饱和",
    "4.4.4.1.6. Saturation and anti-windup": "4.4.4.1.6. 饱和和反饱和",
    "Velocity loop error integration is inhibited when certain velocity anti-windup conditions occur.": "当某些速度反饱和条件发生时，速度环路误差积分被抑制。",
    "In MCAF R1 – R5, velocity anti-windup conditions include detection of current and voltage saturation.": "在 MCAF R1 – R5 中，速度反饱和条件包括电流和电压饱和的检测。",
    "Since MCAF R6, voltage saturation is not used for velocity anti-windup, when": "从 MCAF R6 开始，当启用",
    "is enabled, to allow entry into the flux-weakening region. When flux weakening is disabled, voltage saturation is used for velocity anti-windup.": "时，电压饱和不用于速度反饱和，以允许进入弱磁区域。当弱磁控制禁用时，电压饱和用于速度反饱和。",
    ", including": "，包括",
    ", was added as an option in MCAF R6.": "，作为选项在 MCAF R6 中添加。",
    "was added as an option in MCAF R6.": "作为选项在 MCAF R6 中添加。",
    "Current measurement / gain and offset compensation": "电流测量/增益和偏移补偿",
    "4.4.4.1.8. Current measurement / gain and offset compensation": "4.4.4.1.8. 电流测量/增益和偏移补偿",
    "Gain and offset compensation": "增益和偏移补偿",
    "are included in MCAF to handle several aspects of": "包含在 MCAF 中，以处理",
    "current measurement": "电流测量",
    "run-time compensation of current offset error": "电流偏移误差的运行时补偿",
    "compile-time compensation of current gain error, for cases such as the": "电流增益误差的编译时补偿，用于",
    "use of single/dual/triple-channel measurement": "使用单/双/三通道测量",
    "Dead-time compensation": "死区补偿",
    "4.4.4.1.9. Dead-time compensation": "4.4.4.1.9. 死区补偿",
    "Numerical values for PWM duty cycle and dead time": "PWM 占空比和死区的数值",
    "4.4.4.2. Numerical values for PWM duty cycle and dead time": "4.4.4.2. PWM 占空比和死区的数值",
    "It is important to understand some of the subtleties of PWM duty cycle in MCAF, in the presence of dead time. Interpretation of particular numeric duty cycles (for example, d = 0.1) can be slightly tricky. This section documents how they are used, and how to determine the correct values given known limits of the power electronics.": "了解 MCAF 中存在死区时 PWM 占空比的一些细微之处很重要。特定数值占空比（例如 d = 0.1）的解释可能略有难度。本节记录了它们的使用方式，以及如何在已知功率电子器件限制的情况下确定正确的值。",
    "shows several important points related to PWM duty cycle and dead time.": "显示了与 PWM 占空比和死区相关的几个重要点。",
    "Interpreting duty cycle correctly": "正确解释占空比",
    "A typical PWM peripheral for use with a half-bridge circuit produces three waveforms:": "用于半桥电路的典型 PWM 外设产生三个波形：",
    "a raw generated pulse waveform G with duty cycle": "原始生成的脉冲波形 G，占空比为",
    "high-side output H with the leading edge delayed by dead time": "高侧输出 H，前沿延迟死区时间",
    "low-side output L inverted and with the trailing edge delayed by dead time": "低侧输出 L，反相且后沿延迟死区时间",
    "Other implementations may split dead time in half symmetrically. (see": "其他实现可能会对称地将死区时间分成两半。（参见",
    "note on dsPIC33 PWM": "dsPIC33 PWM 说明",
    "The intended duty cycle of the entire half-bridge is": "整个半桥的预期占空比为",
    "The duty cycle of the high-side gate drive is": "高侧栅极驱动的占空比为",
    ". (with": "。（其中",
    "expressed as a fraction of total PWM period)": "表示为总 PWM 周期的分数）",
    "The duty cycle of the low-side gate drive is": "低侧栅极驱动的占空比为",
    "With inductive loads, and transistor on-time and off-time roughly equal, the effective duty cycle of the entire half bridge is": "对于感性负载，且晶体管的导通时间和关断时间大致相等时，整个半桥的有效占空比为",
    "if current is flowing out of the half bridge (the low-side diode conducts during dead time),": "如果电流流出半桥（死区期间低侧二极管导通），",
    "if current is flowing into the half bridge (the high-side diode conducts during dead time),": "如果电流流入半桥（死区期间高侧二极管导通），",
    "or somewhere in between if current does not stay positive or negative during the entire dead time — this represents discontinuous conduction.": "或者介于两者之间（如果电流在整个死区期间不保持正或负）——这表示不连续导通。",
    "Circuit designers of the half bridge should record the following quantities:": "半桥的电路设计者应记录以下量：",
    "Minimum duty cycle": "最小占空比",
    "and maximum duty cycle": "和最大占空比",
    "of the high-side transistor": "高侧晶体管的",
    "of the low-side transistor": "低侧晶体管的",
    "Desired dead time": "所需死区时间",
    "The relevant parameters that should be entered into motorBench": "应输入 motorBench",
    "Development Suite are:": "开发套件的相关参数为：",
    "Minimum duty cycle of the bridge": "桥臂的最小占空比",
    "Maximum duty cycle of the bridge": "桥臂的最大占空比",
    "This will produce the range of duty cycles shown in": "这将产生",
    "Duty cycle ranges for PWM waveforms": "PWM 波形的占空比范围",
    "Waveform": "波形",
    "Maximum duty cycle": "最大占空比",
    "Usually the two minimum duty cycles": "通常两个最小占空比",
    "determine the duty cycle limits, not the maximum duty cycles.": "决定占空比限制，而不是最大占空比。",
    "To help clarify how this works, some concrete examples are given below.": "为了帮助说明其工作原理，下面给出一些具体示例。",
    "PWM peripheral in dsPIC33 devices": "dsPIC33 器件中的 PWM 外设",
    "4.4.4.2.1. PWM peripheral in dsPIC33 devices": "4.4.4.2.1. dsPIC33 器件中的 PWM 外设",
    "The PWM peripheral in dsPIC33EP parts splits the dead time in half, calculating edges for the low-side and high-side outputs so that they are centered in time around the \u201cideal\u201d switching instant if there were no dead time. The widths of waveforms G, H, and L in": "dsPIC33EP 器件中的 PWM 外设将死区时间分成两半，计算低侧和高侧输出的边沿，使其在时间上以无死区时的\u201c理想\u201d开关时刻为中心。",
    "are the same, but waveforms H and L are advanced in time by": "中的波形 G、H 和 L 的宽度相同，但波形 H 和 L 在时间上提前了",
    "Example 1": "示例 1",
    "4.4.4.2.2. Example 1": "4.4.4.2.2. 示例 1",
    "High-side transistor must be limited between": "高侧晶体管必须限制在",
    "duty cycle and": "占空比和",
    "duty cycle": "占空比之间",
    "Low-side transistor must be limited between": "低侧晶体管必须限制在",
    "Dead time of 2%": "2% 死区时间",
    "This is a realistic case for a bootstrap gate drive, where": "这是自举栅极驱动的实际情况，其中",
    "is larger, to ensure adequate recharge time of the bootstrap capacitors.": "较大，以确保自举电容有足够的充电时间。",
    "We calculate": "我们计算",
    "The waveform values produced by this are shown in": "由此产生的波形值如",
    "Duty cycle ranges for Example 1": "示例 1 的占空比范围",
    "Note that in this case, the limits are determined by the minimum duty cycles; the maximum duty cycles of the H and L waveforms are comfortably below their required maximum.": "注意，在这种情况下，限制由最小占空比决定；H 和 L 波形的最大占空比远低于其所需的最大值。",
    "Example 2": "示例 2",
    "4.4.4.2.3. Example 2": "4.4.4.2.3. 示例 2",
    "The waveform values produced by this are shown in shown in": "由此产生的波形值如",
    "Duty cycle ranges for Example 2": "示例 2 的占空比范围",
    "In this case, the limits are determined by the maximum duty cycles; the minimum duty cycles of the H and L waveforms are comfortably above their required minimum.": "在这种情况下，限制由最大占空比决定；H 和 L 波形的最小占空比远高于其所需的最小值。",
    "Recommended values for use with motorBench": "motorBench 推荐值",
    "4.4.4.2.4. Recommended values for use with motorBench": "4.4.4.2.4. motorBench 推荐值",
    "Development Suite and MCLV-2": "开发套件和 MCLV-2",
    "Dead time of 4%": "4% 死区时间",
    "Recommended duty cycle ranges for MCLV-2": "MCLV-2 推荐占空比范围",
    "Affected source code files": "受影响的源代码文件",
    "4.4.4.2.5. Affected source code files": "4.4.4.2.5. 受影响的源代码文件",
    "Since MCAF R3, the generated file parameters/hal_params.h contains": "从 MCAF R3 开始，生成的文件 parameters/hal_params.h 包含",
    "symbols to determine minimum and maximum duty cycles. There is also a comment that appears as follows:": "符号，用于确定最小和最大占空比。还有一个如下所示的注释：",
    "Support for full on/off time in MCAF": "MCAF 对全导通/关断时间的支持",
    "4.4.4.2.6. Support for full on/off time in MCAF": "4.4.4.2.6. MCAF 对全导通/关断时间的支持",
    "MCAF does not support full on-time or off-time of either high-side or low-side transistor. This is a tricky feature to implement, because it represents a small jump discontinuity of the intended duty cycle.": "MCAF 不支持高侧或低侧晶体管的全导通或全关断时间。这是一个难以实现的功能，因为它代表占空比的一个小的跳变不连续性。",
    "Modules": "模块",
    "4.4.4.3. Modules": "4.4.4.3. 模块",
    "Core FOC": "核心 FOC",
    "4.4.4.3.1. Core FOC": "4.4.4.3.1. 核心 FOC",
    "Module": "模块",
    "Files": "文件",
    "Description": "描述",
    "Comments": "说明",
    "Dynamic current limit": "动态电流限制",
    "Top-level FOC": "顶层 FOC",
    "These functions are called from the": "这些函数从",
    "state machine": "状态机",
    "modules, as described in the": "模块调用，如",
    "implementation notes": "实现说明",
    "PI loop saturation management": "PI 环路饱和管理",
    "Initialization of FOC control parameters": "FOC 控制参数的初始化",
    "Parameters for specifying the outer loop type (velocity or": "用于指定外环类型（速度或",
    "voltage control": "电压控制",
    "Commutation": "换相",
    "4.4.4.3.2. Commutation": "4.4.4.3.2. 换相",
    "Top-level commutation / estimation": "顶层换相/估计",
    "Handling of output excitation for": "处理",
    "intrusive estimators": "侵入式估计器",
    "Contains functions to compute required excitation voltage — or zero, if only": "的输出激励。包含计算所需激励电压的函数——如果仅使用",
    "non-intrusive estimators": "非侵入式估计器",
    "are used.": "则为零。",
    "Angle-tracking Phase-locked Loop (ATPLL)": "角度跟踪锁相环（ATPLL）",
    "Common features used in all estimators": "所有估计器中使用的通用功能",
    "Quadrature encoder support": "正交编码器支持",
    "The quadrature encoder can be used as the primary estimator for commutation and velocity feedback, or to obtain a reference position and velocity for testing estimator performance.": "正交编码器可用作换相和速度反馈的主要估计器，或用于获取参考位置和速度以测试估计器性能。",
    "Back-EMF synchronization": "反电动势同步",
    "State Machine": "状态机",
    "Test Harness": "测试框架",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
