# -*- coding: utf-8 -*-
import txutil

rel = "components/adc"
title_zh = "4.2. ADC 校准与补偿"

m = {
    "Components": "组件",
    "ADC Calibration and Compensation": "ADC 校准与补偿",
    "4.2. ADC Calibration and Compensation": "4.2. ADC 校准与补偿",
    "Gain and offset errors in analog measurements (such as phase current) can cause several undesirable effects, notably torque ripple, increase in quiescent power, and derating of power semiconductor capability. As a result, MCAF includes support for ADC calibration and compensation of the following values.": "模拟测量（如相电流）中的增益和偏移误差会导致多种不良影响，特别是转矩脉动、静态功耗增加以及功率半导体能力的降额。因此，MCAF 支持对以下值进行 ADC 校准和补偿。",
    "Compensation target": "补偿目标",
    "Calibration type": "校准类型",
    "Comments": "说明",
    "Phase current offset": "相电流偏移",
    "Runtime, at startup": "运行时，启动时",
    "Phase currents are measured and filtered at startup, when": "启动时会测量并滤波相电流，此时",
    "outputs are in a safe state, and currents are known to be zero.": "输出处于安全状态，且电流已知为零。",
    "Phase current gain": "相电流增益",
    "Not calibrated at present, reserved for future use by Self-Commissioning in motorBench": "目前未校准，预留给 motorBench",
    "Development Suite, or other runtime methods": "开发套件中的自整定功能或其他运行时方法使用",
    "Includes compensation for cross-phase coupling.": "包括对相间耦合的补偿。",
    "ADC gain error (dsPIC33AK only)": "ADC 增益误差（仅限 dsPIC33AK）",
    "Runtime, in RESET state while PWMs are disabled": "运行时，在 PWM 禁用时的 RESET 状态下",
    "MCAF measures the resistor divider voltage on each ADC core and computes a gain correction factor.": "MCAF 测量每个 ADC 核上的电阻分压器电压，并计算增益校正因子。",
    "Phase Current Offset Compensation": "相电流偏移补偿",
    "4.2.1. Phase Current Offset Compensation": "4.2.1. 相电流偏移补偿",
    "The": "",
    "field of": "字段属于",
    "contains six gain terms:": "，包含六个增益项：",
    ", and": " 和",
    "terms represent a 2x2 gain matrix:": "项表示一个 2x2 增益矩阵：",
    "or (more concisely)": "或（更简洁地）",
    "These gains and offset are used to compensate for part-to-part variation and to correct for any board layout issues, such as those described in": "这些增益和偏移用于补偿器件间的差异，并纠正任何电路板布局问题，例如",
    "MCLV-2 Sense Resistors": "MCLV-2 采样电阻",
    "If": "如果",
    "triple-channel current measurement": "三通道电流测量",
    "is used, the 2x2 gain matrix is augmented with the": "被使用，则 2x2 增益矩阵将增加",
    "term to become a 3x3 gain matrix. The 3x3 equations become": "项，扩展为 3x3 增益矩阵。3x3 方程变为",
    "single-channel current measurement": "单通道电流测量",
    "is used, the following equation is used for DC link current measurement compensation:": "被使用，则以下方程用于直流母线电流测量补偿：",
    "ADC Gain Error Compensation": "ADC 增益误差补偿",
    "4.2.2. ADC Gain Error Compensation": "4.2.2. ADC 增益误差补偿",
    "The high-speed": "高速",
    "on dsPIC33A devices requires manual gain calibration for best performance. (For more information, see": "在 dsPIC33A 器件上需要手动增益校准以获得最佳性能。（更多信息请参见",
    ") For ADC gain error calibration with dsPIC33AK devices,": "）对于 dsPIC33AK 器件的 ADC 增益误差校准，",
    ", defined below, is the internal": "（定义如下）是内部",
    "voltage reference. This is a resistor divider for measuring ratiometric voltages that are close to the supply rails but within the ADC input range.": "电压基准。这是一个电阻分压器，用于测量接近供电轨但在 ADC 输入范围内的比例电压。",
    "ADC gain error, which is applied to each ADC core used by MCAF, is assumed to be a linear error that can be corrected by applying a gain": "ADC 增益误差（应用于 MCAF 使用的每个 ADC 核）被假定为线性误差，可通过施加增益",
    "to the raw ADC voltage reading,": "到原始 ADC 电压读数",
    ", to obtain the true, corrected value,": "，以获得真实的校正值",
    ", resulting in the equation": "，从而得到方程",
    "where": "其中",
    "is determined by evaluating a known voltage,": "通过评估已知电压",
    ", and taking the corresponding ADC reading of this known value,": "并获取该已知值的相应 ADC 读数",
    ", such that": "来确定，使得",
    "Each ADC core used in an MCAF configuration is independently measured during the RESTART motor state, which happens during the RESTART state as described in the": "MCAF 配置中使用的每个 ADC 核在 RESTART 电机状态期间独立测量，该状态在 RESTART 状态期间发生，如",
    "state machine": "状态机",
    ". These ADC core gain factors,": "中所述。这些 ADC 核增益因子",
    ", are then assigned to gain factors, which are used to scale the gain terms used in current compensation —": "随后被分配给增益因子，用于缩放电流补偿中使用的增益项——",
    "— dependent on which channels are configured for current measurement in MCAF, and which ADC core is used for each": "——具体取决于 MCAF 中配置了哪些通道用于电流测量，以及每个通道使用哪个 ADC 核",
    "These": "这些",
    "terms are used in place of the existing": "项用于替代现有的",
    "phase current compensation terms": "相电流补偿项",
    ", respectively.": "。",
    "Implementation Notes": "实现说明",
    "4.2.3. Implementation Notes": "4.2.3. 实现说明",
    "In MCAF R1 and R2, some portions of calibration and compensation functionality were located in the": "在 MCAF R1 和 R2 中，校准和补偿功能的某些部分位于",
    "module and others in the": "模块，其他部分位于",
    "module. In MCAF R3 – R6, all": "模块。在 MCAF R3 – R6 中，所有",
    "calibration and compensation functionality was located in the": "校准和补偿功能位于",
    "module.": "模块。",
    "As of MCAF R7, calibration and compensation functionality is located in the": "从 MCAF R7 开始，校准和补偿功能位于",
    "and": "和",
    "modules.": "模块。",
    "In MCAF R9, the": "在 MCAF R9 中，",
    "gain error compensation functionality was added to the": "增益误差补偿功能已添加到",
    "Modules": "模块",
    "4.2.3.4. Modules": "4.2.3.4. 模块",
    "Module": "模块",
    "Files": "文件",
    "Description": "描述",
    "ADC compensation": "ADC 补偿",
    "Prior to R7, included current offset calibration, which has been moved to the": "在 R7 之前，包含电流偏移校准，该功能已移至",
    "Current measurement": "电流测量",
    "Introduced in R7. Includes logic to handle": "在 R7 中引入。包含处理",
    "single-channel": "单通道",
    "(single-shunt),": "（单分流电阻）、",
    "dual-channel": "双通道",
    "triple-channel": "三通道",
    "current measurement, as appropriate.": "电流测量的逻辑，视情况而定。",
    "Main Application": "主应用程序",
    "State Machine": "状态机",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
