# -*- coding: utf-8 -*-
import txutil

rel = "components/testharness"
title_zh = "4.5. 测试框架"

m = {
    "Components": "组件",
    "Test Harness": "测试框架",
    "4.5. Test Harness": "4.5. 测试框架",
    "The test harness represents several runtime parameters, which, in combination with adjustable parameters used elsewhere in MCAF, can be used to put the controller into certain test modes in order to debug and test proper operation of control algorithms, the board, and/or motor. It is tightly coupled to the design of the": "测试框架包含若干运行时参数，这些参数与 MCAF 其他部分使用的可调参数相结合，可将控制器置于特定的测试模式，以调试和测试控制算法、电路板和/或电机的正确运行。它与",
    "modules.": "模块的设计紧密耦合。",
    "Overview": "概述",
    "4.5.1. Overview": "4.5.1. 概述",
    "The test harness includes the features listed below.": "测试框架包含以下功能。",
    "Operating mode": "操作模式",
    "— this determines whether the motor controller operates in its normal mode, or with a subset of the controller features, and is used for": "——决定电机控制器是以正常模式运行，还是以控制器功能的子集运行，用于",
    "accretive testing": "增量测试",
    ", so that, for example,": "，使得例如",
    "outputs can be tested first, then three-phase modulation, then the current loop, then the velocity loop.": "输出可以先测试，然后是三相调制，再是电流环路，最后是速度环路。",
    "Forced state change": "强制状态切换",
    "— this allows the test operator to force certain state transitions": "——允许测试操作员强制执行某些状态转换",
    "Overrides": "覆盖",
    "— these are boolean flags that determine whether certain features such as commutation angle, DC link compensation, or input velocity command to operate normally or receive input from alternate sources.": "——这些是布尔标志，决定某些功能（如换相角、直流母线补偿或输入速度命令）是正常运行还是从备用源接收输入。",
    "Perturbation signals": "扰动信号",
    "— This injects a perturbation signal to either velocity, current, or voltage commands. There are two options available:": "——向速度、电流或电压命令注入扰动信号。有两个可用选项：",
    "Symmetric perturbation": "对称扰动",
    "— injects a square-wave perturbation signal.": "——注入方波扰动信号。",
    "Asymmetric perturbation": "非对称扰动",
    "— injects an asymmetric pulse waveform perturbation signal.": "——注入非对称脉冲波形扰动信号。",
    "Seizures": "死循环",
    "— Setting an appropriate flag causes either the": "——设置适当的标志会使",
    "or the main loop to enter an infinite loop, triggering the watchdog timeout (if enabled). This allows testing of the watchdog timer.": "或主循环进入无限循环，触发看门狗超时（如果已启用）。这允许测试看门狗定时器。",
    "Intentional stack overflow": "故意堆栈溢出",
    "— Allows testing the hardware stack overflow trap.": "——允许测试硬件堆栈溢出陷阱。",
    "Guards": "保护",
    "— Test guards prevent accidental activation of test harness features.": "——测试保护防止意外激活测试框架功能。",
    "Profiling timestamps": "性能分析时间戳",
    "— these are 16-bit timer snapshots that can be used for profiling the main control ISR.": "——这些是 16 位定时器快照，可用于分析主控制 ISR 的性能。",
    "Triggered Average": "触发平均",
    "— this is used for calculating the average value of a variable over a desired time interval.": "——用于计算变量在所需时间间隔内的平均值。",
    "Seizures, stack overflow, and guards are features that apply to the MCAF firmware as a whole, whereas the remaining features apply to each motor in the system.": "死循环、堆栈溢出和保护是适用于整个 MCAF 固件的功能，而其余功能适用于系统中的每个电机。",
    "Accretive Testing": "增量测试",
    "4.5.2. Accretive Testing": "4.5.2. 增量测试",
    "Motor control testing should be possible using firmware that is as equivalent as possible (ideally identical) to the intended release firmware. This prevents errors reproducing a problem in the release firmware because it got out of sync with the test firmware.": "电机控制测试应能使用与预期发布固件尽可能等效（理想情况下完全相同）的固件进行。这避免了因测试固件与发布固件不同步而导致在发布固件中复现问题时出现错误。",
    "The MCAF includes built-in test modes to support so-called \u201caccretive\u201d testing at run-time, allowing engineers to start from low-level tests of the power electronics, and work up through verification of open-loop commutation, current control loop, and finally velocity control loop, all without having to recompile the software. This approach is vital, both when bringing up a new circuit board, and when troubleshooting.": "MCAF 包含内置测试模式，以支持运行时所谓的\u201c增量\u201d测试，允许工程师从功率电子器件的低级测试开始，逐步验证开环换相、电流控制环路，最后到速度控制环路，所有这些都无需重新编译软件。这种方法在调试新电路板和故障排除时都至关重要。",
    "Test Harness Parameters": "测试框架参数",
    "4.5.3. Test Harness Parameters": "4.5.3. 测试框架参数",
    "The following table lists test parameters used in various cases. Parameters are found both in the main motor data structure": "下表列出了各种情况下使用的测试参数。参数既存在于主电机数据结构",
    ", and the main system data structure": "中，也存在于主系统数据结构",
    ", and are hierarchical (e.g.": "中，并且是分层结构的（例如",
    "for the q-axis current command perturbation shown below).": "为下方所示的 q 轴电流命令扰动）。",
    "Parameter": "参数",
    "Description": "描述",
    "Contains testing parameters per motor": "包含每个电机的测试参数",
    "Contains parameters for square wave generator": "包含方波发生器的参数",
    "Half-period, in": "半周期，以",
    "cycles, of the test square wave": "个周期为单位，测试方波的",
    "Amplitude of velocity command perturbation": "速度命令扰动的幅值",
    "Amplitudes of current command perturbation": "电流命令扰动的幅值",
    "Amplitude of d-axis current command perturbation": "d 轴电流命令扰动的幅值",
    "Amplitude of q-axis current command perturbation": "q 轴电流命令扰动的幅值",
    "Amplitudes of voltage command perturbation": "电压命令扰动的幅值",
    "Amplitude of d-axis voltage command perturbation": "d 轴电压命令扰动的幅值",
    "Amplitude of q-axis voltage command perturbation": "q 轴电压命令扰动的幅值",
    "square wave signal, 0 or \u00b11 (0 to disable all perturbations)": "方波信号，0 或 \u00b11（0 禁用所有扰动）",
    "Contains parameters for asymmetric pulse waveform generator": "包含非对称脉冲波形发生器的参数",
    "Contains parameters for the two phases of the waveform": "包含波形两个相位的参数",
    "Duration, in": "持续时间，以",
    "cycles, of each phase": "个周期为单位，每个相位的",
    "Ratio of the amplitudes of the 2nd phase from the 1st phase amplitudes": "第二相位幅值与第一相位幅值的比值",
    "asymmetric pulse waveform signal, 0 or \u00b11 (0 to disable all perturbations)": "非对称脉冲波形信号，0 或 \u00b11（0 禁用所有扰动）",
    "Contains parameters for automatic stepping of the current perturbation signals": "包含电流扰动信号自动步进的参数",
    "Number of times to step the current per phase": "每个相位电流步进的次数",
    "Step sizes of current command perturbation": "电流命令扰动的步长",
    "Step size of d-axis current command perturbation": "d 轴电流命令扰动的步长",
    "Step size of q-axis current command perturbation": "q 轴电流命令扰动的步长",
    "Bit fields (denoted later in this document as": "位域（在本文档后面表示为",
    "where": "其中",
    "is the bit field), which control certain test overrides:": "是位域），控制某些测试覆盖：",
    ": Controls whether input velocity command comes from normal input, or is held static.": "：控制输入速度命令是来自正常输入还是保持静态。",
    ": Controls whether commutation angle is overridden": "：控制换相角是否被覆盖",
    ": Controls whether DC link compensation is overridden": "：控制直流母线补偿是否被覆盖",
    ": Controls whether stall detection is masked": "：控制堵转检测是否被屏蔽",
    ": Controls whether startup pauses when reaching the HOLD state": "：控制启动在达到 HOLD 状态时是否暂停",
    ": Controls whether d-axis current reference comes from the": "：控制 d 轴电流参考值是否来自",
    "module, or is held static.": "模块，还是保持静态。",
    ": Controls whether zero sequence modulation offset is overridden": "：控制零序调制偏移是否被覆盖",
    "Controls value of electrical frequency used during commutation overrides": "控制换相覆盖期间使用的电气频率值",
    "Allows delays in commutation angle changes, used during commutation overrides": "允许换相角变化的延迟，在换相覆盖期间使用",
    "Zero sequence modulation offset to add to the duty cycle of each phase.": "添加到每相占空比的零序调制偏移。",
    "Specifies the period of commutation frequency variations": "指定换相频率变化的周期",
    "Specifies the fraction of time where": "指定应用",
    "is applied": "的时间比例",
    "Controls operating mode of the motor": "控制电机的操作模式",
    "Affects state change of primary state machine": "影响主要状态机的状态切换",
    "Captured timestamp reference for profiling": "用于性能分析的捕获时间戳参考",
    "Captured timestamp values for profiling": "用于性能分析的捕获时间戳值",
    "Contains testing parameters per system": "包含每个系统的测试参数",
    "Test flags, including seizure flags for the": "测试标志，包括",
    "and main loop, and stack overflow": "和主循环的死循环标志，以及堆栈溢出",
    "Enables test harness functionality": "启用测试框架功能",
    "Notes": "说明",
    ", which is a union containing two members,": "，它是一个包含两个成员的联合体，",
    "mechanical": "机械",
    "electrical": "电气",
    ". These have identical value, but may facilitate special treatment in future real-time diagnostic tools.": "。它们具有相同的值，但可能便于未来实时诊断工具中的特殊处理。",
    "Test Guarding": "测试保护",
    "4.5.4. Test Guarding": "4.5.4. 测试保护",
    "The presence of test modes does represent a miniscule risk for accidental operation in these modes. If not set intentionally, the only way to enter a test mode is for certain state variables located in RAM to change autonomously. This can be considered an improbable event, with one of the following causes:": "测试模式的存在确实代表了意外进入这些模式的微小风险。如果未有意设置，进入测试模式的唯一方式是 RAM 中的某些状态变量自行改变。这可以被视为一个不太可能的事件，原因之一如下：",
    "random hardware failures": "随机硬件故障",
    "software implementation errors": "软件实现错误",
    "execution of write-memory commands from the": "从",
    ", which are in turn caused by either": "执行写内存命令，这又由以下原因之一引起：",
    "communications errors that somehow reproduce exactly the required data": "以某种方式精确复现所需数据的通信错误",
    "malicious sources": "恶意来源",
    "Unfortunately, such a change is persistent, and the test modes will not revert back to normal behavior on their own.": "不幸的是，这种变化是持久的，测试模式不会自行恢复到正常行为。",
    "Test Features in Production: Should They Stay or Should They Go?": "生产中的测试功能：保留还是移除？",
    "4.5.4.1. Test Features in Production: Should They Stay or Should They Go?": "4.5.4.1. 生产中的测试功能：保留还是移除？",
    "This raises a philosophical question: should a test harness remain in production code? There are two schools of thought for run-time test features.": "这引发了一个原则性问题：测试框架是否应保留在生产代码中？关于运行时测试功能有两种观点。",
    "Test features should be left in place in production code": "测试功能应保留在生产代码中",
    "Production code is actually the exact code being tested": "生产代码实际上就是被测试的代码",
    "In case of an issue observed later (e.g. customer problem), it facilitates understanding of the issue and can even be activated in the field": "如果以后观察到问题（例如客户问题），它有助于理解问题，甚至可以在现场激活",
    "Test features should not be left in place in production code": "测试功能不应保留在生产代码中",
    "They can take extra software resources (CPU time, program and data memory)": "它们会占用额外的软件资源（CPU 时间、程序和数据存储器）",
    "In safety-critical systems they increase the risk of unintended behavior": "在安全关键系统中，它们增加了意外行为的风险",
    "Code alterations should be removed upon completion of testing": "测试完成后应移除代码更改",
    "We believe the choice should be left up to the customer; as a future enhancement, the application framework will facilitate this by allowing removal of test features either through the code generation process or the preprocessor (": "我们认为选择权应留给客户；作为未来的增强功能，应用程序框架将通过代码生成过程或预处理器（",
    "). In any case, keeping the alterations used for testing to a minimum is extremely important: if we test codebase X but deliver codebase Y, any differences should not be significant with respect to the features being tested, otherwise they represent a shortcoming of the test process.": "）来允许移除测试功能。无论如何，将测试中使用的更改保持在最低限度非常重要：如果我们测试代码库 X 但交付代码库 Y，任何差异在所测试功能方面不应是显著的，否则它们代表测试过程的缺陷。",
    "Implementation of Test Guarding": "测试保护的实现",
    "4.5.4.2. Implementation of Test Guarding": "4.5.4.2. 测试保护的实现",
    "To mitigate the risk of accidentally entering test modes, an optional guard mechanism is provided. Essentially, on each": "为了减轻意外进入测试模式的风险，提供了可选的保护机制。基本上，在每个",
    "cycle the guard is checked and if not valid, the test parameters are reset to their normal mode of operation. The guard consists of two memory locations, a key and a timeout (": "周期时检查保护，如果无效，则将测试参数重置为正常操作模式。保护由两个内存位置组成：密钥和超时（",
    "). In order for the guard to be valid, the key must match a given value (": "）。要使保护有效，密钥必须匹配给定值（",
    "= \u201cDIAG\u201d). If the timeout has expired, the key is reset to an invalid value (zero), otherwise the timeout is decremented. If the guard is invalid, the test parameters are set to their normal conditions. An example of C code to implement this behavior is shown in": "= \u201cDIAG\u201d）。如果超时已过期，密钥被重置为无效值（零），否则超时递减。如果保护无效，测试参数被设置为正常条件。实现此行为的 C 代码示例如",
    "The intent is to require minimal execution time, and to disable test modes unless diagnostic tools are used to maintain those test modes in an active condition. The guard key should be set manually; the guard timeout can be automatically set to its maximum value (": "其目的是要求最少的执行时间，并在未使用诊断工具维护测试模式活动状态时禁用测试模式。保护密钥应手动设置；保护超时可由诊断工具定期自动设置为其最大值（",
    ") periodically by diagnostic tools; even at 20 kHz, 65536 counts represents 3.2768 seconds and should be enough time to allow reactivation in time, even if there are OS or communication hiccups.": "）；即使在 20 kHz 下，65536 个计数代表 3.2768 秒，应该有足够的时间允许及时重新激活，即使存在操作系统或通信故障。",
    "The guard timeout mechanism should be optional: publicly-available tools do not yet support the automatic timeout reset, and in some cases the extra program and data memory usage are not warranted.": "保护超时机制应为可选：公开可用的工具尚不支持自动超时重置，在某些情况下，额外的程序和数据存储器使用是不必要的。",
    "Note:": "注意：",
    "MCAF R1 – R5 implement test guarding but not the test guard timeout mechanism.": "MCAF R1 – R5 实现了测试保护但未实现测试保护超时机制。",
    "Test Harness Architecture": "测试框架架构",
    "4.5.5. Test Harness Architecture": "4.5.5. 测试框架架构",
    "Signal Valves": "信号阀",
    "4.5.5.1. Signal Valves": "4.5.5.1. 信号阀",
    "In order to add test mode hooks with minimal impact on the end application, we introduce the concept of a \u201csignal valve\u201d in a block diagram. This is shown in the following example as a circle with an arrow inside it:": "为了以对最终应用最小的影响添加测试模式钩子，我们在框图中引入了\u201c信号阀\u201d的概念。在以下示例中，它显示为一个内部有箭头的圆圈：",
    "Signal valve example": "信号阀示例",
    "The valve represents a state variable with a choice: in its normal mode of operation, the valve is \u201copen\u201d and data flows normally through the valve, so that in the example in": "阀门代表一个有选择的状态变量：在正常操作模式下，阀门\u201c打开\u201d，数据正常流过阀门，因此在",
    ", the signal": "的示例中，信号",
    "is determined by input signal": "由输入信号",
    "propagating through functions": "通过函数",
    ". In a test mode, the block or blocks upstream of the valve are not executed, and the valve retains its value, so that real-time diagnostic tools can modify that value as appropriate.": "传播决定。在测试模式下，阀门上游的模块不执行，阀门保持其值，以便实时诊断工具可以适当修改该值。",
    "For example, one way to implement it in C is shown in": "例如，在 C 中实现它的一种方式如",
    "This gives us a choice between running our control algorithm in its normal mode of operation (": "这使我们可以选择以正常操作模式运行控制算法（",
    ") with": "），以",
    "as an input variable, or in a test mode (": "作为输入变量，或以测试模式（",
    "as an input variable.": "作为输入变量。",
    "Test harness modes": "测试框架模式",
    "4.5.6. Test harness modes": "4.5.6. 测试框架模式",
    "The behavior shown in": "中所示的行为",
    "(reproduced from": "（ reproduced 自",
    ") represents the primary signal flow paths used in the motor controller. This does not show the complete functionality of the motor controller; in particular supervisory features like overcurrent and stall detection are not shown. Also note that the shaded area represents a vector controller, and signals within this area have multiple components (dq or alpha-beta or abc).": "）代表了电机控制器中使用的主要信号流路径。这并未显示电机控制器的完整功能；特别是过流和堵转检测等监控功能未显示。还请注意，阴影区域代表矢量控制器，该区域内的信号有多个分量（dq 或 alpha-beta 或 abc）。",
    "Block diagram of MCAF Field Oriented Control": "MCAF 磁场定向控制框图",
    "The behavior of the motor controller can be modified under several different modes, described in the following sections. Refer to": "电机控制器的行为可以在多种不同模式下修改，以下各节将进行描述。请参考",
    "for the block diagram behavior. The modes are enumerated values that can be assigned to the": "了解框图行为。这些模式是可以分配给",
    "parameter.": "参数的枚举值。",
    "The": "The ",
    "mode represents a disabled controller with output transistors set to a \u201cminimal impact state\u201d. Valves V2-V5 are all off.": "模式代表禁用的控制器，输出晶体管设置为\u201c最小影响状态\u201d。阀门 V2-V5 全部关闭。",
    "Active features of the motor controller": "电机控制器的活动功能",
    "All feedback computations execute normally, including": "所有反馈计算正常执行，包括",
    "readings": "读数",
    "Park and Clarke transforms": "Park 和 Clarke 变换",
    "Commutation angle estimator (if possible)": "换相角估计器（如果可能）",
    "Sine and cosine calculation": "正弦和余弦计算",
    "Supervisory algorithms (stall detection, overcurrent/overvoltage/etc.)": "监控算法（堵转检测、过流/过压等）",
    "Inactive features of the motor controller": "电机控制器的非活动功能",
    "All forward path computations are disabled, including": "所有前向通道计算被禁用，包括",
    "Rate limiters": "速率限制器",
    "Current and velocity control loops": "电流和速度控制环路",
    "Inverse Park and Clarke transforms": "逆 Park 和 Clarke 变换",
    "Zero Sequence Modulation or Space Vector Modulation": "零序调制或空间矢量调制",
    "PWM Minimal impact state": "PWM 最小影响状态",
    "Output transistors are set to a": "输出晶体管被设置为",
    "\u201cminimal impact state\u201d": "\u201c最小影响状态\u201d",
    ", namely:": "，即：",
    "upper transistors off": "上桥臂晶体管关断",
    "lower transistors at a minimal duty cycle to maintain bootstrap capacitor charge (or completely off if this is not required)": "下桥臂晶体管以最小占空比运行以维持自举电容充电（如果不需要则完全关断）",
    "The behavior in the": "在",
    "state is best implemented as a separate state (e.g.": "状态的行为最好实现为单独的状态（例如",
    ") in the main state machine outside the main state transitions, with": "），在主状态机的状态转换之外，通过",
    "forcing entrance to that state from any other state. Re-entry into other test modes or normal behavior can then be handled in the state machine, allows exiting of the": "强制从任何其他状态进入该状态。然后可以在状态机中处理重新进入其他测试模式或正常行为，允许退出",
    "state to occur cleanly.": "状态时进行干净的转换。",
    "mode represents a test mode where the": "模式代表一种测试模式，其中",
    "outputs are active and assigned from static motor state variables, shown as": "输出处于活动状态并从静态电机状态变量分配，如",
    "in": "如",
    ". Valves V2-V5 are all off.": "所示。阀门 V2-V5 全部关闭。",
    "Active/inactive features of the motor controller": "电机控制器的活动/非活动功能",
    ": Same as": "：同",
    "Use case": "用例",
    ": Testing system behavior with constant or slowly-changing": "：测试系统在恒定或缓慢变化的",
    "duty cycles.": "占空比下的行为。",
    "Motor or other load may or may not be connected.": "电机或其他负载可以连接也可以不连接。",
    "Using debug tools, set mode to": "使用调试工具，先将模式设置为",
    "first": "（先）",
    "Set": "设置",
    "to desired values": "为所需值",
    "Set mode to": "将模式设置为",
    "is best implemented as a separate state (e.g.": "最好实现为单独的状态（例如",
    ") in the main state machine outside the normal state transitions, with": "），在主状态机的正常状态转换之外，通过",
    "forcing entrance to that state from any other state. Overcurrent, or any other severe fault condition, should cause entrance to a disabled state that requires manual re-entry into the enabled state.": "强制从任何其他状态进入该状态。过流或任何其他严重故障条件应导致进入禁用状态，需要手动重新进入启用状态。",
    "Setting": "设置",
    "without using": "而不使用",
    "first is not forbidden, but may have undesirable consequences, since whichever values were present in": "（先）并非禁止，但可能产生不良后果，因为在模式切换时",
    "are \u201cfrozen\u201d at the time of mode switch, unless changed via debug tools.": "中的任何值都会被\u201c冻结\u201d，除非通过调试工具更改。",
    "outputs are active along with the ZSM block and inverse Clarke block, which takes its inputs from static motor state variables, shown as": "输出与 ZSM 模块和逆 Clarke 模块一起处于活动状态，后者从静态电机状态变量获取输入，如",
    ". Valves V2-V4 are off; valve V5 is on.": "所示。阀门 V2-V4 关闭；阀门 V5 打开。",
    ", but inverse Clarke and ZSM are now active.": "，但逆 Clarke 和 ZSM 现在处于活动状态。",
    ": Testing system behavior with the inverse Clarke transform active. (rare)": "：测试逆 Clarke 变换活动时的系统行为。（罕见）",
    "Otherwise this mode is similar to": "否则此模式类似于",
    "and should be handled in a special state (": "，应在特殊状态（",
    ") outside the normal state transitions.": "）中处理，在正常状态转换之外。",
    "outputs are active along with the ZSM block, inverse Clarke, and inverse Park block, which takes its inputs from static motor state variables, shown as": "输出与 ZSM 模块、逆 Clarke 和逆 Park 模块一起处于活动状态，后者从静态电机状态变量获取输入，如",
    ". Valves V2-V3 are off; valves V4-V5 are on.": "所示。阀门 V2-V3 关闭；阀门 V4-V5 打开。",
    ", but inverse Park, DC link compensation, and dq-voltage perturbation are now active.": "，但逆 Park、直流母线补偿和 dq 电压扰动现在处于活动状态。",
    ": Testing system behavior with the inverse Park transform active. This represents open-loop sinusoidal voltages applied line-to-line. Commutation angle can either be done through the normal feedback mechanism, or via": "：测试逆 Park 变换活动时的系统行为。这代表施加在线间的开环正弦电压。换相角可以通过正常反馈机制完成，也可以通过",
    "forced commutation": "强制换相",
    ". DC link voltage compensation can be active or inactive.": "完成。直流母线电压补偿可以激活或禁用。",
    "outputs are active along with the forward path and the current controller, which takes its input command from static motor state variables, shown as": "输出与前向通道和电流控制器一起处于活动状态，后者从静态电机状态变量获取输入命令，如",
    ". Valve V2 is off; valves V3-V5 are on.": "所示。阀门 V2 关闭；阀门 V3-V5 打开。",
    "This can be considered a \u201ctorque mode\u201d, since controlling": "这可以被视为\u201c转矩模式\u201d，因为控制",
    "effectively dictates motor torque. Because of this, unless the input command is small or there is a stiff mechanical load present, the motor will generally accelerate to its full speed.": "实际上决定了电机转矩。因此，除非输入命令很小或存在刚性机械负载，否则电机通常会加速到全速。",
    ", but the current controller and its input filter are now active.": "，但电流控制器及其输入滤波器现在处于活动状态。",
    ": Testing system behavior with a current loop active. Commutation angle can either be done through the normal feedback mechanism, or via": "：测试电流环路活动时的系统行为。换相角可以通过正常反馈机制完成，也可以通过",
    "Note": "注意",
    ": Because this is a test mode, the": "：由于这是测试模式，",
    "normal motor startup process": "正常电机启动过程",
    "does not operate, and no automatic transition occurs from open-loop commutation to closed-loop commutation. This mode should either be enabled after the motor startup has occurred, or commutation behavior will have to be managed manually.": "不运行，并且不会发生从开环换相到闭环换相的自动转换。此模式应在电机启动后启用，否则换相行为需要手动管理。",
    "mode represents the default operating mode of velocity control. All features are active, including the main state machine.": "模式代表速度控制的默认操作模式。所有功能都处于活动状态，包括主状态机。",
    "Interaction with the System State Machine": "与系统状态机的交互",
    "4.5.7. Interaction with the System State Machine": "4.5.7. 与系统状态机的交互",
    "shows the system state machine and its interaction with the operating mode. If the operating mode is": "显示了系统状态机及其与操作模式的交互。如果操作模式为",
    ", the state machine should revert to its reset state, where it can safely re-engage in its normal behavior. If the operating mode is": "，状态机应恢复到其复位状态，在那里可以安全地重新进入正常行为。如果操作模式为",
    ", the state machine should enter": "，状态机应进入",
    "state, where a new test operating mode can put it into the": "状态，在那里新的测试操作模式可以将其置于",
    "state with a clean transition. In order to support certain rare test cases, direct entry into": "状态，实现干净的转换。为了支持某些罕见的测试情况，允许直接进入",
    "is allowed but is discouraged.": "，但不鼓励这样做。",
    "Forcing System State Machine Transitions": "强制系统状态机转换",
    "4.5.8. Forcing System State Machine Transitions": "4.5.8. 强制系统状态机转换",
    "Operating modes other than": "除",
    "alter the behavior of the state machine. In some cases, it is useful to maintain the essential behavior of the state machine, but cause manual transitions in the state machine to some desired state.": "以外的操作模式会改变状态机的行为。在某些情况下，保持状态机的基本行为但手动将状态机转换到某个所需状态是有用的。",
    "This can be accomplished by setting": "这可以通过设置",
    "to one of the following values:": "为以下值之一来实现：",
    "— sets the": "——设置",
    "flag to": "标志为",
    ", behaving the same way as starting the motor with a button press.": "，行为与按键启动电机相同。",
    "— sets": "——设置",
    "false": "假",
    ", behaving the same way as stopping the motor with a button press.": "，行为与按键停止电机相同。",
    "and bypasses the time delay in the": "并绕过",
    "state by causing the coastdown timer to immediately expire, performing an abrupt transition to the": "状态中的时间延迟，通过使减速定时器立即到期，执行到",
    "state. Useful for high-inertia motors where the motor is brought to a stop quickly through external load torques, such as a mechanical brake.": "状态的突然转换。适用于高惯量电机，其中电机通过外部负载转矩（如机械制动器）快速停止。",
    "Using": "使用",
    "is preferable to directly altering the main motor FSM state (": "比直接更改主电机 FSM 状态（",
    "), since transitions in the state machine are allowed to happen normally. Setting": "）更可取，因为状态机中的转换可以正常发生。直接设置",
    "directly may cause initialization steps at the beginning of a state transition to be skipped.": "可能导致状态转换开始时的初始化步骤被跳过。",
    "Test Harness Switches (Overrides)": "测试框架开关（覆盖）",
    "4.5.9. Test Harness Switches (Overrides)": "4.5.9. 测试框架开关（覆盖）",
    "Test harness switches are boolean flags stored in an": "测试框架开关是存储在",
    "field.": "字段中的布尔标志。",
    "Input Velocity Command Override": "输入速度命令覆盖",
    "4.5.9.1. Input Velocity Command Override": "4.5.9.1. 输入速度命令覆盖",
    "If the bitfield": "如果位域",
    "is false, valve V1 is enabled and the velocity command comes from its normal source.": "为假，阀门 V1 启用，速度命令来自其正常源。",
    "If": "如果",
    "is true, the velocity command is static and may be changed via debug tools.": "为真，速度命令为静态，可通过调试工具更改。",
    "Commutation Override": "换相覆盖",
    "4.5.9.2. Commutation Override": "4.5.9.2. 换相覆盖",
    "is false, commutation angle is computed in its normal manner.": "为假，换相角以正常方式计算。",
    "is true, the commutation angle is updated automatically with the repetition of the following behavior (\u201con-off commutation\u201d or \u201cforced commutation\u201d):": "为真，换相角通过重复以下行为自动更新（\u201c开关换相\u201d或\u201c强制换相\u201d）：",
    "for": "对于",
    "cycles, the commutation angle accumulates the commutation frequency": "个周期，换相角累积换相频率",
    "cycles, the commutation angle is fixed.": "个周期，换相角固定。",
    "The available values of": "的可用值",
    ", and the program variables that control them, depend on the MCAF version, and are detailed in subsections below. There are a number of use cases that can be achieved with this feature; these can be controlled using real-time debug tools to set appropriate program variables.": "及其控制程序变量取决于 MCAF 版本，在以下各小节中详述。此功能可以实现多种用例；可以使用实时调试工具设置适当的程序变量来控制这些用例。",
    "Fixed commutation angle": "固定换相角",
    "— set": "——设置",
    ", set desired commutation angle.": "，设置所需换相角。",
    "Fixed commutation frequency": "固定换相频率",
    "Quasi-fixed, slow commutation frequency": "准固定、慢速换相频率",
    "(since MCAF R3) — set": "（自 MCAF R3 起）——设置",
    ", for an effective commutation frequency of": "，有效换相频率为",
    "Commutation angle jumps": "换相角跳变",
    ", for a jump angle of": "，跳变角为",
    "and a jump frequency of": "，跳变频率为",
    ". Setting": "。设置",
    "(10923 counts) can achieve quasi-six-step operation during open-loop testing.": "（10923 个计数）可以在开环测试期间实现准六步运行。",
    "Slew-rate-limited jumps": "压摆率限制跳变",
    "(since MCAF R4) — set": "（自 MCAF R4 起）——设置",
    ". This achieves the behavior shown in": "。这实现了",
    "On-off commutation for slew-rate-limited jumps": "压摆率限制跳变的开关换相",
    "The transition of commutation angle from forced commutation to normal commutation is an abrupt transition, and is likely to cause transient disturbances in motor current.": "从强制换相到正常换相的换相角转换是突然的转换，可能导致电机电流的瞬态扰动。",
    "Commutation frequency": "换相频率",
    "has different scaling factor from the velocity values used elsewhere in MCAF, such as": "的缩放因子与 MCAF 其他地方使用的速度值（如",
    "or": "或",
    ". This is done in order to minimize the CPU execution time of the test harness. The type of": "）不同。这是为了最小化测试框架的 CPU 执行时间。",
    "; this type is just an alias for": "；此类型只是",
    "but it is intended to signify scaling as a change in electrical angle per control update. With": "的别名，但其目的是表示缩放为每次控制更新的电气角度变化。使用",
    ", a value of 1 count will increment the commutation angle": "时，值 1 个计数将在每次控制更新时递增换相角",
    "by one count on each control update — for a 20 kHz control ISR, this amounts to \u2248 109.863\u00b0/s = 0.30518 Hz; a value of 32767 counts corresponds to just under 10kHz.": "一个计数——对于 20 kHz 控制 ISR，这相当于 \u2248 109.863\u00b0/s = 0.30518 Hz；值 32767 个计数对应于略低于 10kHz。",
    "MCAF R1 and R2": "MCAF R1 和 R2",
    "4.5.9.2.1. MCAF R1 and R2": "4.5.9.2.1. MCAF R1 和 R2",
    "Only": "仅支持",
    "is supported.": "。",
    "MCAF R3": "MCAF R3",
    "4.5.9.2.2. MCAF R3": "4.5.9.2.2. MCAF R3",
    "is the value of": "是",
    "is fixed.": "的值，固定。",
    "MCAF R4 and later": "MCAF R4 及更高版本",
    "4.5.9.2.3. MCAF R4 and later": "4.5.9.2.3. MCAF R4 及更高版本",
    "DC Link Voltage Compensation": "直流母线电压补偿",
    "4.5.9.3. DC Link Voltage Compensation": "4.5.9.3. 直流母线电压补偿",
    "is false, DC link compensation occurs normally.": "为假，直流母线补偿正常运行。",
    "is true, valve V6 is off and DC link compensation occurs using a value": "为真，阀门 V6 关闭，直流母线补偿使用一个值",
    "that can be either manually adjusted or left at a fixed value.": "运行，该值可以手动调整或保持固定值。",
    "Stall Detect Override": "堵转检测覆盖",
    "4.5.9.4. Stall Detect Override": "4.5.9.4. 堵转检测覆盖",
    "is false, all logic related to stall detection occurs normally.": "为假，所有与堵转检测相关的逻辑正常运行。",
    "is true, stall detection itself is not changed, but a detected stall condition is ignored.": "为真，堵转检测本身不变，但检测到的堵转条件被忽略。",
    "This is useful for running certain tests that would otherwise cause a detected stall condition (whether real or false) to trigger a transition in the state machine and disrupt the intended test.": "这对于运行某些测试很有用，这些测试否则会导致检测到的堵转条件（无论是真实还是误报）触发状态机中的转换并干扰预期的测试。",
    "Pause at end of open-loop startup": "开环启动结束时的暂停",
    "4.5.9.5. Pause at end of open-loop startup": "4.5.9.5. 开环启动结束时的暂停",
    "(Added in MCAF R5)": "（在 MCAF R5 中添加）",
    "is false, startup occurs normally, and proceeds to closed-loop commutation.": "为假，启动正常进行，并继续到闭环换相。",
    "is true, startup proceeds normally until reaching the HOLD state, and remains in the HOLD state (fixed current and electrical frequency, under open-loop commutation), until one of the following conditions is true:": "为真，启动正常进行直到达到 HOLD 状态，并保持在 HOLD 状态（固定电流和电气频率，在开环换相下），直到以下条件之一为真：",
    "Remain in HOLD": "保持在 HOLD",
    "— while in the HOLD state, normal state machine behavior continues; possible exit conditions are:": "——在 HOLD 状态下，正常状态机行为继续；可能的退出条件为：",
    "flag is cleared manually, at which point startup will proceed to closed-loop commutation and normal operation.": "标志被手动清除，此时启动将继续到闭环换相和正常操作。",
    "a STOP input is received (user presses a button in MCLV-2 or MCHV-2)": "收到 STOP 输入（用户在 MCLV-2 或 MCHV-2 上按键）",
    "a fault is detected": "检测到故障",
    "Switch to": "切换到",
    "— the force-current test mode may be entered by manually setting the following flags with real-time diagnostic tools:": "——可以通过使用实时诊断工具手动设置以下标志来进入强制电流测试模式：",
    ", to prevent normal closed-loop commutation once the test mode is reached": "，以在达到测试模式后防止正常闭环换相",
    "This will allow operation in a test state, where the normal state machine does not operate.": "这将允许在测试状态下运行，其中正常状态机不运行。",
    "Both are useful for debugging or analyzing behavior during open-loop operation. The switch-to-": "两者都可用于调试或分析开环操作期间的行为。切换到",
    "behavior is useful for running at a fixed current and commutation frequency; attempting to start in the": "行为对于以固定电流和换相频率运行很有用；尝试在",
    "mode and manually accelerate to some desired commutation frequency can be difficult.": "模式下启动并手动加速到某个所需换相频率可能很困难。",
    "To summarize the differences in these two approaches:": "总结这两种方法的差异：",
    "Comparison of pause-in-HOLD behaviors": "HOLD 暂停行为比较",
    "Can return to normal closed-loop startup": "可以返回正常闭环启动",
    "yes": "是",
    "no": "否",
    "Current control level value can be changed at runtime?": "电流控制水平值可以在运行时更改吗？",
    "Electrical frequency can be changed at runtime?": "电气频率可以在运行时更改吗？",
    "Interacts with normal state machine": "与正常状态机交互",
    "Example use of \u201cRemain in HOLD\u201d behavior. (This demonstrates the Weathervane startup algorithm.)": "\u201c保持在 HOLD\u201d行为的使用示例。（这演示了风向标启动算法。）",
    "shows an example of the \u201cRemain in Hold\u201d behavior with MCAF R5, using the": "显示了使用 MCAF R5 的\u201c保持在 HOLD\u201d行为示例，使用",
    "motor with the": "电机和",
    "MCLV\u20112 Development Board": "MCLV-2 开发板",
    "From t \u2248 0.4 s to t \u2248 1.0 s, motor is started, and normal startup occurs.": "从 t \u2248 0.4 s 到 t \u2248 1.0 s，电机启动，正常启动过程发生。",
    "At t \u2248 3.5 s, the motor is started with": "在 t \u2248 3.5 s，电机以设置",
    "set.": "启动。",
    "At t \u2248 4.0 s, the motor reaches and remains in the HOLD state (startup state 5).": "在 t \u2248 4.0 s，电机达到并保持在 HOLD 状态（启动状态 5）。",
    "At t \u2248 5.0 s, the motor is stopped.": "在 t \u2248 5.0 s，电机停止。",
    "At t \u2248 6.5 s, the motor is started, and it remains in the HOLD state since": "在 t \u2248 6.5 s，电机启动，由于",
    "is still set.": "仍然设置，因此保持在 HOLD 状态。",
    "At t \u2248 8.0 s,": "在 t \u2248 8.0 s，",
    "is manually cleared, so startup proceeds to transition to closed-loop.": "被手动清除，因此启动继续转换到闭环。",
    "(This test used the": "（此测试使用了",
    "feature to start and stop the motor programmatically rather than through the pushbuttons on the MCLV-2.)": "功能以编程方式启动和停止电机，而不是通过 MCLV-2 上的按键。）",
    "Example use of \u201cSwitch to": "\u201c切换到",
    "\u201d behavior.": "\u201d行为的使用示例。",
    "shows an example of the \u201cSwitch to": "显示了使用 MCAF R5 的\u201c切换到",
    "\u201d behavior with MCAF R5, also using the": "\u201d行为示例，也使用了",
    "t \u2248 0.5 s:": "t \u2248 0.5 s：",
    "is set manually and the motor is started.": "被手动设置，电机启动。",
    "t \u2248 1.0 s: the motor reaches and remains in the HOLD state (startup state 5).": "t \u2248 1.0 s：电机达到并保持在 HOLD 状态（启动状态 5）。",
    "t \u2248 2.0 s: set": "t \u2248 2.0 s：设置",
    "— note that": "——注意",
    "switches to": "切换到",
    "t \u2248 3.5 s:": "t \u2248 3.5 s：",
    "is set to an appropriate value to maintain speed, and": "被设置为适当的值以维持速度，并且",
    "is set to stop startup logic from running. (Note that active damping no longer runs, since it is a feature of normal startup.)": "被设置为停止启动逻辑运行。（注意，主动阻尼不再运行，因为它是正常启动的功能。）",
    "t \u2248 4.1 s: current is lowered by 20%": "t \u2248 4.1 s：电流降低 20%",
    "t \u2248 4.6 s:": "t \u2248 4.6 s：",
    "is lowered by 20%. Note that speed transients are very lightly damped, and cause oscillations in current; this is expected in open-loop commutation. Large transients in electrical frequency can cause cycle slips and loss of lock.": "降低 20%。注意，速度瞬态阻尼很轻，会导致电流振荡；这在开环换相中是预期的。电气频率的大瞬态可能导致周期滑移和失锁。",
    "t \u2248 5.6 s: motor is stopped by returning to": "t \u2248 5.6 s：电机通过返回到",
    "and forcing the motor to stop.": "并强制电机停止来停止。",
    "Flux control override": "磁通控制覆盖",
    "4.5.9.6. Flux control override": "4.5.9.6. 磁通控制覆盖",
    "(Added in MCAF R6)": "（在 MCAF R6 中添加）",
    "is false, d-axis reference current is computed from the": "为假，d 轴参考电流由",
    "Flux control": "磁通控制",
    "module.": "模块计算。",
    "is true, d-axis reference current is static and may be changed via real-time diagnostic tools.": "为真，d 轴参考电流为静态，可通过实时诊断工具更改。",
    "Zero-sequence modulation override": "零序调制覆盖",
    "4.5.9.7. Zero-sequence modulation override": "4.5.9.7. 零序调制覆盖",
    "(Added in MCAF R7)": "（在 MCAF R7 中添加）",
    "is false, normal": "为假，正常",
    "zero sequence modulation": "零序调制",
    "applies.": "适用。",
    "is true, a common offset is added to the duty cycle of each phase. This offset is stored in": "为真，一个公共偏移被添加到每相的占空比中。此偏移存储在",
    "Perturbation Signals": "扰动信号",
    "4.5.10. Perturbation Signals": "4.5.10. 扰动信号",
    "Perturbation signals may be created using the test harness, which allows step response and disturbance rejection testing for the different controllers. To enable symmetric perturbation, set the macro": "可以使用测试框架创建扰动信号，这允许对不同控制器进行阶跃响应和抗扰测试。要启用对称扰动，请将宏",
    "to 1 in": "在",
    ". Set this macro to 0 to enable asymmetric perturbation.": "中设置为 1。将此宏设置为 0 可启用非对称扰动。",
    "Symmetric Perturbation": "对称扰动",
    "4.5.10.1. Symmetric Perturbation": "4.5.10.1. 对称扰动",
    "The state variable": "状态变量",
    "is a structure containing several members to generate a square wave perturbation signal. The field": "是一个包含多个成员的结构体，用于生成方波扰动信号。字段",
    "either remains at 0 (its default value) or toggles back and forth between +1 and -1 every": "要么保持为 0（其默认值），要么每",
    "test harness updates. For example, if the test harness update is executed during the control": "次测试框架更新在 +1 和 -1 之间切换。例如，如果测试框架更新在控制",
    "at 20 kHz, and": "期间以 20 kHz 执行，并且",
    "is 8, then the half-period is 400 \u03bcs and the resulting square wave frequency is 1.25 kHz (= 1/800 \u03bcs). An example waveform generated by the test harness using this configuration is shown in": "为 8，则半周期为 400 \u03bcs，产生的方波频率为 1.25 kHz（= 1/800 \u03bcs）。使用此配置由测试框架生成的示例波形如",
    "Example of a square wave applied to the q-axis current with": "施加到 q 轴电流的方波示例，其中",
    "500": "500",
    "(=0.66A).": "(=0.66A)。",
    "is set to any other value, it will be limited in magnitude to 1. The code that manages": "设置为任何其他值时，其幅值将被限制为 1。管理",
    "is set to any other value, it will be limited in magnitude to 1. The": "设置为任何其他值时，其幅值将被限制为 1。",
    "is found in": "的代码位于",
    "field is then multiplied by one of several amplitudes elsewhere in the code to setup square wave perturbation signals of variable amplitude and added into the appropriate point of the calculation:": "字段随后乘以代码中其他位置的若干幅值之一，以设置可变幅值的方波扰动信号，并添加到计算的适当位置：",
    "Signal (see": "信号（见",
    "Amplitude variable(s)": "幅值变量",
    "Electrical velocity": "电气速度",
    "Mechanical velocity": "机械速度",
    "current command": "电流命令",
    "voltage command (output of current loop)": "电压命令（电流环路输出）",
    "This technique allows all test perturbation signals to be disabled by setting": "此技术允许通过设置",
    ", keeping the execution time of the test harness to a minimum (including guard processing).": "来禁用所有测试扰动信号，将测试框架的执行时间保持在最低限度（包括保护处理）。",
    "Asymmetric Perturbation": "非对称扰动",
    "4.5.10.2. Asymmetric Perturbation": "4.5.10.2. 非对称扰动",
    "An asymmetric pulse waveform perturbation signal is constructed from two pulses (referred to later in this document as phases) each with a different amplitude and duration. The state variable": "非对称脉冲波形扰动信号由两个脉冲（在本文档后面称为相位）构成，每个脉冲具有不同的幅值和持续时间。状态变量",
    "is a structure containing several parameters to generate an asymmetric perturbation signal. The array": "是一个包含多个参数的结构体，用于生成非对称扰动信号。数组",
    "contains two instances of the struct": "包含结构体",
    "for controlling the two phases of the waveform. This struct contains fields for setting the amplitudes of each of the control variables (described below) and the field": "的两个实例，用于控制波形的两个相位。此结构体包含用于设置每个控制变量幅值的字段（如下所述）和字段",
    "for setting the duration of each phase in control": "用于设置每个相位在控制",
    "cycles. The field": "周期中的持续时间。字段",
    "either remains at 0 (its default value) or toggles back and forth between +1 and -1. The high-time and low-time of": "要么保持为 0（其默认值），要么在 +1 和 -1 之间切换。",
    "depends on the": "取决于",
    "field for each of the phases.": "字段（对于每个相位）。",
    "For example, if the test harness update is executed during the control ISR at 20kHz,": "例如，如果测试框架更新在控制 ISR 期间以 20kHz 执行，",
    "is 8 and": "为 8 且",
    "is 12, then the length of each phase is 400 \u03bcs and 600 \u03bcs, respectively. The resulting frequency of this waveform is 1.0 kHz (= 1/1000 \u03bcs). An example waveform generated by the test harness using this configuration is shown in": "为 12，则每个相位的长度分别为 400 \u03bcs 和 600 \u03bcs。此波形的频率为 1.0 kHz（= 1/1000 \u03bcs）。使用此配置由测试框架生成的示例波形如",
    "Example of an asymmetric pulse waveform generated using the asymmetric perturbation feature with the field": "使用非对称扰动功能生成的非对称脉冲波形示例，字段",
    "set to 500 (=0.66A) and": "设置为 500（=0.66A），",
    "set to -200 (=-0.27 A).": "设置为 -200（=-0.27 A）。",
    "To automatically balance the amplitude of the second phase from the first phase, use the": "要自动平衡第二相位相对于第一相位的幅值，请使用",
    "field. For example, if": "字段。例如，如果",
    "is set to 1000, and": "设置为 1000，且",
    "is set to 32768 (=0.5 Q16), then": "设置为 32768（=0.5 Q16），则",
    "will automatically be set to 500.": "将自动设置为 500。",
    "Autostepping of current perturbation is available with asymmetric perturbation. This feature adds a specified value to the current amplitude a certain number of times during each phase. The struct": "非对称扰动支持电流扰动的自动步进。此功能在每个相位期间将指定值添加到电流幅值一定次数。结构体",
    "contains the field": "包含字段",
    "for setting the change in amplitude of each of the current control variables and the field": "用于设置每个电流控制变量的幅值变化，以及字段",
    "for setting the number of times the amplitude change is added to the current command. An example q-axis current waveform generated by the test harness stepping between -100A and +160A with 14 steps of 20A is shown in": "用于设置幅值变化添加到电流命令的次数。测试框架在 -100A 和 +160A 之间以 14 步 20A 步进生成的 q 轴电流波形示例如",
    "Example of an asymmetric pulse waveform using the autostepping feature with the field": "使用自动步进功能的非对称脉冲波形示例，字段",
    "set to -4960 (=-100A),": "设置为 -4960（=-100A），",
    "set to 14, and": "设置为 14，",
    "set to 992 (=20A).": "设置为 992（=20A）。",
    "field is then multiplied by one of several amplitudes elsewhere in the code to setup asymmetric pulse waveform perturbation signals of variable amplitude and added into the appropriate point of the calculation:": "字段随后乘以代码中其他位置的若干幅值之一，以设置可变幅值的非对称脉冲波形扰动信号，并添加到计算的适当位置：",
    "Similar to symmetric perturbation, this technique allows all test perturbation signals to be disabled by setting": "与对称扰动类似，此技术允许通过设置",
    "To test the": "要测试",
    "watchdog timer": "看门狗定时器",
    ", the test harness includes flags that can be set at runtime, to enter an infinite": "，测试框架包含可在运行时设置的标志，以在主循环或",
    "loop in either the main loop or": "中进入无限",
    ". The": "循环。",
    "test guards": "测试保护",
    "prevent accidental activation.": "防止意外激活。",
    "Stack overflow": "堆栈溢出",
    "4.5.12. Stack overflow": "4.5.12. 堆栈溢出",
    "To test the hardware stack overflow trap, the test harness includes a flag that can be set at runtime, to enter an infinite recursion to cause a stack overflow. The": "要测试硬件堆栈溢出陷阱，测试框架包含可在运行时设置的标志，以进入无限递归导致堆栈溢出。",
    "Profiling Timestamps": "性能分析时间戳",
    "4.5.13. Profiling Timestamps": "4.5.13. 性能分析时间戳",
    "An array of 16-bit timestamps is part of the test harness state structure. These timestamps are recorded in various places for use in profiling the main control ISR via real-time diagnostic tools. Sections of the": "一组 16 位时间戳是测试框架状态结构的一部分。这些时间戳在各处记录，用于通过实时诊断工具分析主控制 ISR 的性能。",
    "module contain code such as the following:": "模块的部分包含如下代码：",
    "This uses one of the timers to count at the system clock rate, so that the timer value indicates the elapsed system clock time.": "这使用其中一个定时器以系统时钟速率计数，使定时器值指示经过的系统时钟时间。",
    "The various": "各种",
    "enum values are defined in": "枚举值定义在",
    "Timestamp recording is disabled by default, but can be enabled via": "时间戳记录默认禁用，但可通过",
    ". (See": "启用。（见",
    "errata": "勘误",
    "Beta feature: subject to change in future versions": "测试功能：可能会在未来版本中更改",
    "A runtime average calculation routine is available for calculating the average of signals of interest. The struct definition": "可用的运行时平均计算例程用于计算感兴趣信号的平均值。结构体定义",
    "is used with the triggered average routine, described in": "与触发平均例程一起使用，如",
    "Triggered average routine parameters": "触发平均例程参数",
    "Flag that begins routine when set": "设置时开始例程的标志",
    "Number of samples to acquire": "要采集的样本数",
    "Right-shift count for average calculation": "用于平均计算的右移计数",
    "Result of average calculation": "平均计算的结果",
    "field is used in the average calculation to divide the sum of the samples by the number of samples. This is done to keep the execution time of this routine to a minimum. The": "字段用于平均计算中，将样本总和除以样本数。这是为了将此例程的执行时间保持在最低限度。",
    "field must be set according to the value of the": "字段必须根据",
    "is set to a value of 256, then": "的值设置。如果",
    "must be set to 8 for the routine to compute the correct value. The": "设置为 256，则",
    "flag may be set with a run-time diagnostic tool to start the calculation.": "必须设置为 8 才能使例程计算正确的值。",
    "To use the triggered average routine, manually declare an instance of": "要使用触发平均例程，请手动声明",
    ". Add a call to": "的一个实例。在初始化期间添加对",
    "during initialization and a call to": "的调用，在 ADC",
    "during the ADC": "期间添加对",
    ". An example use case of this routine is available by setting the": "的调用。通过将",
    "macro to 1 in": "宏在",
    ". This example calculates the average q-axis current over 256 samples. With a runtime diagnostic tool, set the": "中设置为 1 可以使用此例程的示例用例。此示例计算 256 个样本的平均 q 轴电流。使用运行时诊断工具，将",
    "boolean to 1 to run the calculation. When the calculation is complete,": "布尔值设置为 1 以运行计算。计算完成后，",
    "is set to 0, and the result is stored in": "被设置为 0，结果存储在",
    "Example use cases": "示例用例",
    "4.5.15. Example use cases": "4.5.15. 示例用例",
    "This section shows several use cases and how to achieve those use cases with the test harness described in this document. Our entry assumptions are that in each case:": "本节展示了几个用例以及如何使用本文档中描述的测试框架实现这些用例。我们的入口假设是每种情况下：",
    "We start with normal operation with": "我们从正常操作开始，",
    "The motor is at rest (not rotating)": "电机处于静止状态（未旋转）",
    "A debug tool is in use which can write variables to the target": "正在使用可以向目标写入变量的调试工具",
    "The debug tool can regularly assign": "调试工具可以定期分配",
    "as described in": "如",
    ", or the guard timeout feature is not in use": "中所述，或保护超时功能未使用",
    "We start each test case by setting": "我们通过设置",
    "Fixed-frequency sinusoidal current control": "固定频率正弦电流控制",
    "4.5.15.1. Fixed-frequency sinusoidal current control": "4.5.15.1. 固定频率正弦电流控制",
    "[some desired value of electrical frequency]": "[某个所需的电气频率值]",
    "Set desired dq current (see": "设置所需 dq 电流（见",
    "Current/torque control mode": "电流/转矩控制模式",
    "4.5.15.2. Current/torque control mode": "4.5.15.2. 电流/转矩控制模式",
    "Normal operation bypassing the external control (potentiometer)": "绕过外部控制（电位器）的正常操作",
    "4.5.15.3. Normal operation bypassing the external control (potentiometer)": "4.5.15.3. 绕过外部控制（电位器）的正常操作",
    "Note that the normal side effects of state machines and fault handling are still active here (e.g. open-loop \u2192 closed-loop transition, stall detection and retry, etc.) since we do not enter a test operating mode.": "注意，状态机和故障处理的正常副作用在此仍然有效（例如开环→闭环转换、堵转检测和重试等），因为我们不进入测试操作模式。",
    "[some desired value of motor velocity in terms of electrical frequency]": "[某个所需的电机速度值（以电气频率表示）]",
    "Square wave velocity command disturbances to a velocity controller with fixed velocity command": "对具有固定速度命令的速度控制器的方波速度命令扰动",
    "4.5.15.4. Square wave velocity command disturbances to a velocity controller with fixed velocity command": "4.5.15.4. 对具有固定速度命令的速度控制器的方波速度命令扰动",
    "This is the same as the previous case, but with a disturbance.": "与前一种情况相同，但增加了扰动。",
    "Ensure that": "确保",
    "is set to 1 before programming device.": "在编程器件之前设置为 1。",
    "[desired value of half period]": "[所需的半周期值]",
    "[some desired value of velocity amplitude]": "[某个所需的速度幅值]",
    "(starts the square wave)": "（启动方波）",
    "Square wave current command disturbances to a velocity controller with fixed velocity command": "对具有固定速度命令的速度控制器的方波电流命令扰动",
    "4.5.15.5. Square wave current command disturbances to a velocity controller with fixed velocity command": "4.5.15.5. 对具有固定速度命令的速度控制器的方波电流命令扰动",
    "Same as the previous section, but with a disturbance to the d and/or q currents. This case keeps the velocity roughly constant while allowing tests of the current step response. Often this is appropriate since a pure current controller will cause the motor to stall or reach its maximum operating speed and saturate.": "与上一节相同，但对 d 和/或 q 电流增加了扰动。这种情况保持速度大致恒定，同时允许测试电流阶跃响应。这通常是合适的，因为纯电流控制器会导致电机堵转或达到其最大运行速度并饱和。",
    "[some desired value of current amplitude]": "[某个所需的电流幅值]",
    "Square wave current command disturbances to a current controller with fixed current command": "对具有固定电流命令的电流控制器的方波电流命令扰动",
    "4.5.15.6. Square wave current command disturbances to a current controller with fixed current command": "4.5.15.6. 对具有固定电流命令的电流控制器的方波电流命令扰动",
    "This is the same as the": "这与",
    "current control mode": "电流控制模式",
    ", but with a disturbance to the d and/or q currents.": "相同，但对 d 和/或 q 电流增加了扰动。",
    "Asymmetric pulse waveform current command disturbances to a current controller with fixed current command": "对具有固定电流命令的电流控制器的非对称脉冲波形电流命令扰动",
    "4.5.15.7. Asymmetric pulse waveform current command disturbances to a current controller with fixed current command": "4.5.15.7. 对具有固定电流命令的电流控制器的非对称脉冲波形电流命令扰动",
    "Same as the previous section, but using asymmetric perturbation to generate the waveform.": "与上一节相同，但使用非对称扰动生成波形。",
    "is set to 0 before programming device.": "在编程器件之前设置为 0。",
    "[desired value of phase duration]": "[所需的相位持续时间值]",
    "[desired value of phase q-axis current]": "[所需的相位 q 轴电流值]",
    "[desired value of phase d-axis current]": "[所需的相位 d 轴电流值]",
    "(starts the asymmetric pulse waveform)": "（启动非对称脉冲波形）",
    "Implementation Notes": "实现说明",
    "4.5.16. Implementation Notes": "4.5.16. 实现说明",
    "Test harness feature support": "测试框架功能支持",
    "4.5.16.1. Test harness feature support": "4.5.16.1. 测试框架功能支持",
    "Certain features described in this section have not been implemented the MCAF test harness, but are planned for future versions:": "本节中描述的某些功能尚未在 MCAF 测试框架中实现，但计划在未来版本中实现：",
    "Test guarding timeout": "测试保护超时",
    "Low-level test modes": "低级测试模式",
    "Prior to MCAF R3, the overrides": "在 MCAF R3 之前，覆盖",
    "was not implemented. Since MCAF R3 it is implemented.": "未实现。从 MCAF R3 开始已实现。",
    "MCAF R3 and R4 have added support for": "MCAF R3 和 R4 添加了对",
    "on-off commutation": "开关换相",
    "Test harness errata": "测试框架勘误",
    "4.5.16.2. Test harness errata": "4.5.16.2. 测试框架勘误",
    "Manual adjustment of dq-current in": "在",
    "is not designed correctly.": "中手动调整 dq 电流的设计不正确。",
    "(DB_MC-1167; Applicability: MCAF R1, R2, R3)": "(DB_MC-1167；适用性：MCAF R1, R2, R3)",
    "has the following behavior:": "具有以下行为：",
    "D-axis: Current command prior to rate-limiting may be altered with real-time diagnostics by adjusting": "d 轴：速率限制前的电流命令可通过实时诊断调整",
    ". Square-wave perturbation using": "来修改。使用",
    "is disabled in": "的方波扰动在",
    "(more generally, whenever the velocity loop is disabled).": "中禁用（更一般地，当速度环路禁用时）。",
    "Q-axis: Current command prior to rate-limiting may be altered with real-time diagnostics by adjusting": "q 轴：速率限制前的电流命令可通过实时诊断调整",
    "is enabled in": "来修改。",
    "(more generally, whenever the current loop is enabled).": "在",
    "may not work properly with MCC-generated timer calls": "可能无法与 MCC 生成的定时器调用正常工作",
    ". (DB_MC-2671; Applicability: MCAF R5) There are two important points here:": "。（DB_MC-2671；适用性：MCAF R5）这里有两个重要点：",
    "For dsPIC33CK devices, the wrong timer is used. This can be fixed by manually changing": "对于 dsPIC33CK 器件，使用了错误的定时器。这可以通过手动更改",
    "in test_harness.h, from using": "（在 test_harness.h 中）来修复，从使用",
    "(incorrect) to using": "（不正确）改为使用",
    "(correct).": "（正确）。",
    "MCC-generated timer functions as of 16-bit libraries version 1.166.0 are not inline functions, and incur the cost of a function call. (CC16DEV-3543) This will impact the timing measurements. To workaround, change the implementation of": "截至 16 位库版本 1.166.0，MCC 生成的定时器函数不是内联函数，会产生函数调用的开销。（CC16DEV-3543）这将影响定时测量。要解决此问题，请将",
    "(dsPIC33CK devices) or": "（dsPIC33CK 器件）或",
    "(dsPIC33EP devices) to an": "（dsPIC33EP 器件）的实现更改为",
    "function. Note that this requires the function definition to be in the same translation unit as the call site, so it must be present in either test_harness.h or one of the .h files that is #included where": "函数。注意，这要求函数定义与调用点在同一翻译单元中，因此它必须存在于 test_harness.h 或调用",
    "is called; it cannot be located in a separate .c file.": "的 #include .h 文件中；它不能位于单独的 .c 文件中。",
    "Modules": "模块",
    "4.5.16.3. Modules": "4.5.16.3. 模块",
    "Module": "模块",
    "Files": "文件",
    "Comments": "说明",
    "Test harness": "测试框架",
    "Test harness logic for profiling execution times": "用于性能分析执行时间的测试框架逻辑",
    "Field-Oriented Control (FOC)": "磁场定向控制（FOC）",
    "Supervisory Algorithms": "监控算法",
    "4.5.11. Seizures": "4.5.11. 死循环",
    "4.5.14. Triggered Average": "4.5.14. 触发平均",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
