# -*- coding: utf-8 -*-
import txutil

rel = "components/statemach"
title_zh = "4.3. 状态机"

m = {
    "Components": "组件",
    "State Machine": "状态机",
    "4.3. State Machine": "4.3. 状态机",
    "The motor control state machine can be described as a hierarchical state machine, shown below in": "电机控制状态机可以描述为分层状态机，如下方",
    ". The states are shown in blue; the names (": "所示。状态以蓝色显示；名称（",
    ") are the ones used in the application framework code. Transition conditions are shown as labeled arrows.": "）是应用程序框架代码中使用的名称。转换条件以带标签的箭头显示。",
    "This state machine is intended to treat the motor controller at a very high level: rather than concern itself with detailed information about the motor (is a stall occurring? is there an overvoltage?), the state machine is designed around general events like whether a fault has been detected, or whether a start or stop sequence is complete.": "此状态机旨在从非常高的层面处理电机控制器：它不关注电机的详细信息（是否发生了堵转？是否存在过压？），而是围绕一般事件来设计，例如是否检测到故障，或者启动/停止序列是否完成。",
    "Motor controller state diagram": "电机控制器状态图",
    "States": "状态",
    "4.3.1. States": "4.3.1. 状态",
    "These states are divided into subgroups:": "这些状态分为以下子组：",
    "Primary states: all the states except for those used in test operation.": "主要状态：除测试操作中使用的状态外的所有状态。",
    "Normal states: states where a fault is not occurring.": "正常状态：未发生故障的状态。",
    ": a fault has occurred.": "：已发生故障。",
    "Secondary states: all the states used in test operation. These states cause the normal state machine to be ignored, along with some of the fault detection algorithms that may produce false positives when in test modes.": "次要状态：测试操作中使用的所有状态。这些状态会导致正常状态机被忽略，同时也会忽略一些在测试模式下可能产生误报的故障检测算法。",
    "The grouping here forms a hierarchical state machine. For example: any of the normal states will transition to": "此处的分组构成了一个分层状态机。例如：任何正常状态在检测到故障时都会转换到",
    "if a fault has been detected. (Traditional state machines would require transitions to": "。（传统状态机需要将到",
    "to be shown from": "的转换从",
    ", and": "，和",
    ".)": "分别显示出来。）",
    "The initial state after power-on reset is": "上电复位后的初始状态为",
    ". The states are described briefly below:": "。各状态简要描述如下：",
    "State": "状态",
    "Description": "描述",
    "Assumptions": "假设条件",
    "Initial state, entered whenever we power up, or we exit the fault state or a test mode and there is no fault present.": "初始状态，在每次上电、退出故障状态或测试模式且当前无故障时进入。",
    "Certain run-time calibration activities may be performed.": "可以执行某些运行时校准活动。",
    "It is acceptable to let the motor current stay at zero.": "可以接受电机电流保持为零。",
    "The motor controller attempts to bring the motor to a complete stop.": "电机控制器尝试使电机完全停止。",
    "The motor may be rotating.": "电机可能正在旋转。",
    "The motor controller has brought the motor to a complete stop.": "电机控制器已使电机完全停止。",
    "The motor is not rotating.": "电机未旋转。",
    "The motor controller attempts to rotate the motor from rest. This may require specialized code, for example in a controller with a sensorless estimator, or in a compressor.": "电机控制器尝试从静止状态启动电机旋转。这可能需要专门的代码，例如在使用无传感器估计器的控制器中，或在压缩机中。",
    "The motor velocity may be zero or small.": "电机速度可能为零或很小。",
    "The motor controller attempts to control the motor to a specified control goal, typically regulation of motor velocity.": "电机控制器尝试将电机控制到指定的控制目标，通常为电机速度调节。",
    "Control of the motor has been successful so far.": "到目前为止电机控制已成功。",
    "The motor controller has recognized a fault condition, under which it is unable to proceed safely with normal control activities.": "电机控制器已识别到故障状态，在此状态下无法安全地进行正常控制活动。",
    "The motor controller\u2019s actuators are brought to a": "电机控制器的执行器被置于",
    "\u201cminimal impact\u201d": "\u201c最小影响\u201d",
    "state which is deemed acceptable under fault conditions: typically the upper transistors are off, and lower transistors are either off, or set at a small duty cycle.": "状态，该状态在故障条件下被认为是可接受的：通常上桥臂晶体管关断，下桥臂晶体管关断或设置为小占空比。",
    "This is a \u201clatched\u201d state: on entry, latch an error code describing the fault, and display this code until external intervention occurs from a": "这是一个\u201c锁定\u201d状态：进入时锁定描述故障的错误代码，并显示此代码，直到来自",
    "condition.": "条件的外部干预发生。",
    "In general, none. The motor may be rotating or not. The motor may be damaged, the transistors may be damaged, voltages and currents may be out of range, etc.": "通常没有假设。电机可能正在旋转或未旋转。电机可能已损坏，晶体管可能已损坏，电压和电流可能超出范围等。",
    "Test state, for cleanly initializing system behavior, similar to": "测试状态，用于干净地初始化系统行为，类似于",
    "but for test modes.": "但用于测试模式。",
    "User interface inputs are generally ignored in favor of inputs from diagnostic equipment.": "用户界面输入通常被忽略，以诊断设备的输入为准。",
    "The motor controller is being operated in a nonstandard test mode, under controlled conditions, by someone who knows what they are doing.": "电机控制器正在受控条件下由了解操作的人员以非标准测试模式运行。",
    "Test state, with transistors set to a minimal impact state.": "测试状态，晶体管设置为最小影响状态。",
    "Either a fault has been detected during a test mode, or the controller is intentionally disabled.": "在测试模式下检测到故障，或控制器被有意禁用。",
    "Test state, with transistors enabled. Control goal is set by a test operating mode, and is usually different from normal running conditions.": "测试状态，晶体管已启用。控制目标由测试操作模式设定，通常与正常运行条件不同。",
    "For example: one or more control loops disabled, certain fault detections disabled, etc.": "例如：一个或多个控制环路被禁用，某些故障检测被禁用等。",
    "Input conditions": "输入条件",
    "4.3.2. Input conditions": "4.3.2. 输入条件",
    "The high-level input conditions, shown in the state diagram of": "高级输入条件（如",
    ", are used in a mutually exclusive manner (in other words, all conditions starting from a given state are mutually exclusive), and can be defined from more basic conditions as follows:": "的状态图所示）以互斥方式使用（换言之，从给定状态出发的所有条件互斥），并可由更基本的条件定义如下：",
    ": Both of the following are true:": "：以下两项均为真：",
    "is true (see next section)": "为真（见下一节）",
    "operating mode is": "操作模式为",
    ": True if all of the following are true:": "：以下所有条件均为真时为真：",
    "is not true": "不为真",
    "UI module indicates an intention to clear the latched fault.": "UI 模块指示要清除锁定的故障。",
    ": OK for the controller to leave the": "：控制器可以离开",
    "state. True if all of the following are true:": "状态。以下所有条件均为真时为真：",
    "state. True if all of the folowing are true:": "状态。以下所有条件均为真时为真：",
    "initialization activities for the": "",
    "state are complete": "状态的初始化活动已完成",
    "state into the": "状态进入",
    "is true": "为真",
    "stopping mode": "停止模式",
    "is closed-loop": "为闭环",
    "a startup completion flag has not yet been set by the startup routine.": "启动例程尚未设置启动完成标志。",
    "a startup completion flag has been set by the startup routine.": "启动例程已设置启动完成标志。",
    ": OK for the controller to move from the": "：控制器可以从",
    ": the motor will run. True if all of the following are true:": "：电机将运行。以下所有条件均为真时为真：",
    ": UI module indicates an intention for the motor to run.": "：UI 模块指示要运行电机。",
    ": motor is permitted to run; false if a stall condition has been detected.": "：允许电机运行；如果检测到堵转条件则为假。",
    "is not true.": "不为真。",
    "a stop completion flag has been set by the": "停止完成标志已由",
    "stopping routine": "停止例程",
    "TestRestartRequired flag from": "来自",
    "test harness": "测试框架",
    "is not set.": "的 TestRestartRequired 标志未设置。",
    "operating mode is any other mode aside from": "操作模式为除",
    "or": "或",
    "is set.": "的 TestRestartRequired 标志已设置。",
    ": True if the operating mode is": "：如果操作模式为",
    ": True if either of the following is true:": "：以下任一条件为真时为真：",
    "the operating mode is": "操作模式为",
    "the operating mode is not": "操作模式不为",
    "operating mode is not": "操作模式不为",
    "In some ways it may be easier to think about a prioritized implementation of state transitions, which would probably look like this:": "在某些方面，以优先级方式实现状态转换可能更容易理解，其实现可能如下所示：",
    "Miscellaneous state machine issues": "状态机其他问题",
    "4.3.3. Miscellaneous state machine issues": "4.3.3. 状态机其他问题",
    "Startup": "启动",
    "4.3.3.1. Startup": "4.3.3.1. 启动",
    "While in the": "在",
    "state, a specialized startup process is used to bring the motor from rest to a sufficient speed for the": "状态下，使用专门的启动过程将电机从静止加速到足够高的速度，以使",
    "sensorless estimator": "无传感器估计器",
    "to provide commutation information. During this state, the velocity loop is disabled, and commutation angle is slowly accelerated in an open-loop fashion, instead of using the commutation angle from the sensorless estimator.": "提供换相信息。在此状态下，速度环路被禁用，换相角以开环方式缓慢加速，而不是使用无传感器估计器的换相角。",
    "See the section on": "有关更多信息，请参见",
    "startup": "启动",
    "for more information.": "一节。",
    "Fault detection": "故障检测",
    "4.3.3.2. Fault detection": "4.3.3.2. 故障检测",
    "Fault detection behaves slightly differently, depending on whether the system is in a test state or a normal mode of operation.": "故障检测的行为略有不同，取决于系统处于测试状态还是正常操作模式。",
    ": In test states, we want to be more lenient in allowing requested operations, so this flag is true only when any of the most severe faults are true; these include things like hardware overcurrent, software overcurrent, overvoltage, etc.": "：在测试状态下，我们希望对允许请求的操作更加宽松，因此此标志仅在任一最严重的故障为真时才为真；这些包括硬件过流、软件过流、过压等。",
    ": In normal operating modes, we want to be more conservative, and stop operation under a wider set of conditions. This includes all of the faults used in": "：在正常操作模式下，我们希望更加保守，在更广泛的条件下停止操作。这包括",
    ", along with other faults not included in": "中使用的所有故障，以及",
    ", such as stall retry count exceeded.": "中未包含的其他故障，例如堵转重试次数超限。",
    "This allows detection techniques to be used in normal operating modes, but remain disabled in test modes, so that they do not interfere with tests that might otherwise trigger a fault. Certain heuristic detection techniques belong here, especially if they make assumptions about how the motor is operating (e.g. always in velocity control mode, always rotating in one direction, smoothly-changing velocity commands, etc.) or there is some uncertainty about whether the detection technique can avoid false positives.": "这允许检测技术在正常操作模式下使用，但在测试模式下保持禁用，以免干扰可能触发故障的测试。某些启发式检测技术属于此类，特别是当它们对电机的运行方式做出假设（例如始终在速度控制模式下、始终朝一个方向旋转、速度命令平滑变化等），或者对检测技术是否能避免误报存在不确定性时。",
    "Both fault detection schemes are latched, requiring outside action to clear them (for example, a UI button press for the primary states, diagnostic tool action for the test states).": "两种故障检测方案都是锁定的，需要外部操作来清除（例如，主要状态下按 UI 按钮，测试状态下通过诊断工具操作）。",
    "Implementation Notes": "实现说明",
    "4.3.4. Implementation Notes": "4.3.4. 实现说明",
    "The function": "函数",
    "is the main entry point for the system state machine. The approach used in this function is to execute these subtasks:": "是系统状态机的主入口点。此函数中使用的方法是执行以下子任务：",
    "First execute critical tasks common to all states —": "首先执行所有状态共有的关键任务——",
    "Determine next state —": "确定下一状态——",
    "and": "和",
    "Dispatch to the appropriate state —": "分派到适当的状态——",
    "Finally execute noncritical tasks common to all states —": "最后执行所有状态共有的非关键任务——",
    "Field-oriented control tasks are executed in": "磁场定向控制任务在以下函数中执行：",
    "— This function is executed in all states and includes feedback calculations such as Park/Clarke transforms and position/velocity estimation.": "——此函数在所有状态下执行，包括反馈计算，如 Park/Clarke 变换和位置/速度估计。",
    "— This function is executed in states when motor control is active, and includes both the controllers and other forward path elements such as the inverse Park/Clarke transforms and space vector modulation.": "——此函数在电机控制激活的状态下执行，包括控制器和其他前向通道元素，如逆 Park/Clarke 变换和空间矢量调制。",
    "executes low-priority tasks for the system state machine. At this time, the only such task is selecting LED patterns for the": "执行系统状态机的低优先级任务。目前，唯一的此类任务是为",
    "external interface": "外部接口",
    "to indicate motor direction and state machine state.": "选择 LED 图案，以指示电机方向和状态机状态。",
    "Implementation notes for stall detection and recovery:": "堵转检测和恢复的实现说明：",
    "4.3.4.1. Implementation notes for stall detection and recovery:": "4.3.4.1. 堵转检测和恢复的实现说明：",
    "A detection of stall would cause the": "检测到堵转将导致",
    "flag to be false, and therefore bring the motor from the": "标志为假，从而将电机从",
    "states into the": "状态带入",
    "state. It would not change the": "状态。它不会改变来自 UI 的",
    "flag from the UI.": "标志。",
    "Stall detection / recovery need to keep track of a retry count, just as in the existing implementation; when the retry count exceeded a threshold, the \u201cstall retry count exceeded\u201d fault would be produced, and the": "堵转检测/恢复需要跟踪重试次数，与现有实现一样；当重试次数超过阈值时，将产生\u201c堵转重试次数超限\u201d故障，并进入",
    "state entered.": "状态。",
    "Other implementation notes": "其他实现说明",
    "4.3.4.2. Other implementation notes": "4.3.4.2. 其他实现说明",
    "State machine functions in each state, and for transitions, should not be called except from the main state machine update function": "每个状态中的状态机函数以及转换函数，除主状态机更新函数",
    ". The approach used in the MCAF is to bring each of these functions out as inline functions, for code modularity and maintainability, but not run-time modularity (treat it as one large function at runtime).": "外，不应被调用。MCAF 中使用的方法是将这些函数作为内联函数提出，以实现代码模块化和可维护性，但不是运行时模块化（在运行时将其视为一个大函数）。",
    "The": "",
    "transition was added in MCAF R7, along with": "转换是在 MCAF R7 中添加的，同时添加了",
    "closed-loop stopping": "闭环停止",
    "transition was added in MCAF R7, along with the": "转换是在 MCAF R7 中添加的，同时添加了",
    "Note:": "注意：",
    "the exact conditions at which": "确定",
    "is valid are still under investigation, and are likely to change in a future version of MCAF.": "有效性的精确条件仍在研究中，可能会在 MCAF 的未来版本中发生变化。",
    "Modules": "模块",
    "4.3.4.3. Modules": "4.3.4.3. 模块",
    "Module": "模块",
    "Files": "文件",
    "Comments": "说明",
    "Motor startup including the transition from open-loop commutation to closed-loop commutation": "电机启动，包括从开环换相到闭环换相的转换",
    "Top-level state machine": "顶层状态机",
    "ADC Calibration and Compensation": "ADC 校准与补偿",
    "Field-Oriented Control (FOC)": "磁场定向控制（FOC）",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
