# -*- coding: utf-8 -*-
import txutil

rel = "faq"
title_zh = "8. 常见问题 (FAQ)"

m = {
    "Frequently Asked Questions (FAQ)": "常见问题 (FAQ)",
    "Contacting Microchip": "联系 Microchip",
    "We encourage you to contact your local Microchip representative for assistance with motorBench": "我们鼓励您联系当地的 Microchip 代表以获取 motorBench",
    "Development Suite or MCAF. Feedback and comments are welcome!": "Development Suite 或 MCAF 的支持。欢迎反馈和意见！",
    "For more information on Microchip support resources, see the \u201cCustomer Support\u201d section of the motorBench": "有关 Microchip 支持资源的更多信息，请参见 motorBench",
    "Development Suite Release Notes.": "Development Suite 发行说明的\u201c客户支持\u201d节。",
    "USB compatibility": "USB 兼容性",
    "Microchip does manufacture a few motor control parts that include a USB peripheral (the dsPIC33EPXXXMU806/810/814 series). The application framework does not support USB at this time, but we are considering it in the future.": "Microchip 确实制造了一些包含 USB 外设的电机控制器件（dsPIC33EPXXXMU806/810/814 系列）。应用框架目前不支持 USB，但我们正在考虑在未来支持。",
    "RTOS compatibility": "RTOS 兼容性",
    "We plan to investigate ways in which our application framework can meet the strict timing requirements of motor control, but also remain compatible with an RTOS. This is a future effort, and at this time is incomplete.": "我们计划研究使我们的应用框架既能满足电机控制的严格时序要求，又能与 RTOS 兼容的方法。这是一项未来的工作，目前尚不完整。",
    "MATLAB": "MATLAB",
    "and Simulink": "和 Simulink",
    "Our long-term goal is to support both customers that program PIC": "我们的长期目标是同时支持使用 C 语言编程 PIC",
    "microcontrollers and dsPIC": "微控制器和 dsPIC",
    "DSCs for motor control in C, and customers that use MATLAB": "DSC 进行电机控制的客户，以及使用 MATLAB",
    "for code generation. At this time, the motor control application framework is aimed at motor control projects which rely on MPLAB": "进行代码生成的客户。目前，电机控制应用框架面向依赖 MPLAB",
    "X and the XC16 C compiler, and it does not support Simulink code generation. The motor control application framework software has been written by hand to be readable and efficient; Simulink-generated C code is by its very nature not intended to be read or edited, but rather to be autogenerated for rapid prototyping and sufficient equivalency to simulation results, and it is constrained by features of the MATLAB code generation engine.": "X 和 XC16 C 编译器的电机控制项目，不支持 Simulink 代码生成。电机控制应用框架软件是手工编写的，具有可读性和高效性；Simulink 生成的 C 代码本质上不是为了阅读或编辑，而是为了快速原型设计和与仿真结果的充分等效而自动生成的，并受 MATLAB 代码生成引擎功能的限制。",
    "We are considering ways to support both types of customer; at least in the short term, it is likely that our support for customers using MATLAB and Simulink will be through a separate application, specifically aimed to use Simulink.": "我们正在考虑支持这两类客户的方法；至少在短期内，我们对使用 MATLAB 和 Simulink 的客户的支持可能通过一个单独的应用程序来实现，专门针对使用 Simulink。",
    "8. Frequently Asked Questions (FAQ)": "8. 常见问题 (FAQ)",
    "8.1. Contacting Microchip": "8.1. 联系 Microchip",
    "8.2. USB compatibility": "8.2. USB 兼容性",
    "8.3. RTOS compatibility": "8.3. RTOS 兼容性",
    "8.4. MATLAB": "8.4. MATLAB",
    "Revision History": "修订历史",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
