# -*- coding: utf-8 -*-
import txutil

rel = "implementation/sampling-rate"
title_zh = "6.4. 采样率与 PWM 频率的影响"

m = {
    "6.4. Sampling Rate and PWM Frequency Implications — MCAF R9 RC31 文档 (docver 9.0.1)": "6.4. 采样率与 PWM 频率的影响 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Sampling Rate and PWM Frequency Implications": "采样率与 PWM 频率的影响",
    "Since MCAF R6": "自 MCAF R6",
    ", changes in sampling rate and PWM frequency are supported through the Configure page of motorBench": "起，可通过 motorBench",
    "Development Suite. In MCAF R8 and later these settings are located under the System Parameters section. (In MCAF R6 and R7 they were located under the Board section.)": "Development Suite 的 Configure 页面支持采样率和 PWM 频率的更改。在 MCAF R8 及更高版本中，这些设置位于 System Parameters 节下。（在 MCAF R6 和 R7 中，它们位于 Board 节下。）",
    "shows a screenshot of the Configure page and the three settings that control these rates:": "显示了 Configure 页面的截图以及控制这些速率的三个设置：",
    "Current control loop sampling time factor": "电流控制环采样时间因子",
    "\u2014 controls the rate at which the bulk of motor control algorithms execute, including the current controller, reference transforms, and position and velocity estimator.": "\u2014 控制大部分电机控制算法的执行速率，包括电流控制器、参考变换以及位置和速度估计器。",
    "Note": "注",
    "The current control loop executes once every": "电流控制环每",
    "PWM periods, where": "个 PWM 周期执行一次，其中",
    "is the current control loop sampling time factor. MCAF R8 doesn\u2019t support modifying this parameter.": "为电流控制环采样时间因子。MCAF R8 不支持修改此参数。",
    "Velocity control loop sampling time factor": "速度控制环采样时间因子",
    "\u2014 controls the rate at which the velocity controller executes": "\u2014 控制速度控制器的执行速率",
    "The velocity control loop executes once every": "速度控制环每",
    "current control loop updates, where": "次电流控制环更新执行一次，其中",
    "is the velocity control loop sampling time factor.": "为速度控制环采样时间因子。",
    "PWM frequency": "PWM 频率",
    "\u2014 controls the PWM switching frequency": "\u2014 控制 PWM 开关频率",
    "For example, if the PWM frequency is 50 kHz, the current loop sampling time factor is 2, and the velocity loop sampling time factor is 10, then the current loop will update at 25 kHz and the velocity loop at 2.5 kHz.": "例如，如果 PWM 频率为 50 kHz，电流环采样时间因子为 2，速度环采样时间因子为 10，则电流环将以 25 kHz 更新，速度环以 2.5 kHz 更新。",
    "System parameters": "系统参数",
    "Effects of changing sampling rate and PWM frequency": "更改采样率和 PWM 频率的影响",
    "Changing the sampling rate or PWM frequency will have some effects on the system design. For the most part, MCAF operation is independent of these choices; some parameters in the generated code will have different scaling factors that depend on sampling rate and PWM frequency, but the net result is approximately the same. The autotuning feature of motorBench": "更改采样率或 PWM 频率会对系统设计产生一些影响。在大多数情况下，MCAF 的运行与这些选择无关；生成代码中的某些参数将具有取决于采样率和 PWM 频率的不同缩放因子，但净结果大致相同。motorBench",
    "Development Suite will produce approximately the same bandwidths of current and velocity loops.": "Development Suite 的自动整定功能将产生大致相同的电流环和速度环带宽。",
    "Amplitude of ripple current": "纹波电流幅值",
    "\u2014 ripple current amplitudes are proportional to": "\u2014 纹波电流幅值与",
    ", so in general the ripple current is proportional to PWM period, and decreasing the PWM frequency will increase the amplitude of ripple current at harmonics of the PWM frequency.": "成正比，因此一般来说纹波电流与 PWM 周期成正比，降低 PWM 频率将增加 PWM 频率谐波处的纹波电流幅值。",
    "Dead-time distortion": "死区失真",
    "\u2014 increasing PWM frequency will make the dead time a larger fraction of the PWM period. This not only increases dead-time distortion, but also reduces the effective utilization of voltage, since for the same dead time, higher PWM frequency causes the maximum duty cycle to be decreased, and the minimum duty cycle to be increased.": "\u2014 提高 PWM 频率会使死区时间占 PWM 周期的比例更大。这不仅增加了死区失真，还降低了电压的有效利用率，因为在相同死区时间下，较高的 PWM 频率会导致最大占空比降低、最小占空比增加。",
    "Switching losses": "开关损耗",
    "\u2014 switching loss energy per PWM period": "\u2014 每个 PWM 周期的开关损耗能量",
    "is dependent on the switching speeds during turn-on and turn-off, and on the switching voltages and currents. Power dissipated in switching loss is equal to": "取决于导通和关断期间的开关速度以及开关电压和电流。开关损耗中耗散的功率等于",
    ", so increasing switching frequency leads to higher switching power dissipation.": "，因此提高开关频率会导致更高的开关功率耗散。",
    "Sampling rate": "采样率",
    "CPU usage": "CPU 使用率",
    "\u2014 MCAF runs most of the motor control calculations in firmware once per control loop update, so increasing the sampling rate requires higher CPU usage.": "\u2014 MCAF 在固件中每次控制环更新运行大部分电机控制计算，因此提高采样率需要更高的 CPU 使用率。",
    "Current loop gains and bandwidth": "电流环增益和带宽",
    "\u2014 Current loop gains (in engineering units:": "\u2014 电流环增益（工程单位：",
    "has units of V/A, and": "单位为 V/A，",
    "has units of V/As) will change slightly due to the effects of sampling delay. This is most notable with an aggressive (high-bandwidth) current loop, where increasing the sampling rate lowers the delay from input sampling to output update, and allows a faster current loop bandwidth. If the current loop bandwidth is low (below": "单位为 V/As）会因采样延迟的影响而略有变化。这在激进（高带宽）电流环中最为明显，提高采样率会降低从输入采样到输出更新的延迟，并允许更快的电流环带宽。如果电流环带宽较低（低于",
    "), changes in sampling rate are generally not noticeable.": "），采样率的变化通常不明显。",
    "Velocity loop gains and bandwidth": "速度环增益和带宽",
    "\u2014 Velocity loop gains are affected similarly; increasing the velocity sampling rate will allow a faster maximum bandwidth of velocity loop, but will not have a significant impact if the velocity loop bandwidth is low. In addition, since the velocity control loop is cascaded outside the current loops, aggressive velocity loops will be limited by the current loop bandwidth.": "\u2014 速度环增益受类似影响；提高速度采样率将允许更快的速度环最大带宽，但如果速度环带宽较低则影响不大。此外，由于速度控制环级联在电流环之外，激进的速度环将受电流环带宽限制。",
    "Diagnostic kernel": "诊断内核",
    "\u2014 the diagnostic kernel runs in the same ISR as the current control loop, so raising the sampling rate will increase the rate at which data is reported to a host PC, and will increase communications bandwidth requirements.": "\u2014 诊断内核与电流控制环在同一 ISR 中运行，因此提高采样率将增加向主机 PC 报告数据的速率，并增加通信带宽需求。",
    "Compensating parameters": "补偿参数",
    "A number of parameters in the generated code will compensate for changes in PWM frequency and sampling rate. (Tuned gains and": "生成代码中的若干参数将补偿 PWM 频率和采样率的变化。（整定增益和",
    "customized application parameters": "自定义应用参数",
    "are always given in normalized unitless values or engineering units, and are independent of sampling times and PWM frequency, but are converted to fixed-point representation depending on scaling factors that may be dependent on sampling times or PWM frequency.)": "始终以归一化无单位值或工程单位给出，与采样时间和 PWM 频率无关，但根据可能依赖于采样时间或 PWM 频率的缩放因子转换为定点表示。）",
    "Time delays": "时间延迟",
    "Slew rates, ramp rates, and acceleration rates": "压摆率、斜坡率和加速度",
    "Integrator gains": "积分器增益",
    "Implementation notes": "实现说明",
    "Revision-specific information": "版本特定信息",
    "R1 \u2013 R5 supported only a fixed sampling rate and PWM frequency of 20 kHz. Certain gains and other parameters were calculated assuming this frequency.": "R1–R5 仅支持 20 kHz 的固定采样率和 PWM 频率。某些增益和其他参数在计算时假设此频率。",
    "R6 added flexibility for setting the PWM frequency, with the sampling rate locked to the PWM frequency. (See": "R6 增加了设置 PWM 频率的灵活性，采样率锁定为 PWM 频率。（见",
    "Restrictions": "限制",
    "section.)": "节。）",
    "If using MCC Melody (MCAF R7 for dsPIC33C devices), setting the PWM frequency in the Customize page of motorBench": "如果使用 MCC Melody（dsPIC33C 器件的 MCAF R7），在 motorBench",
    "Development Suite will automatically set the peripheral registers in Melody-generated code.": "Development Suite 的 Customize 页面中设置 PWM 频率将自动设置 Melody 生成代码中的外设寄存器。",
    "If using MCC Classic (MCAF R6 for all devices, or MCAF R7 for dsPIC33E devices), PWM frequency set in motorBench": "如果使用 MCC Classic（所有器件的 MCAF R6，或 dsPIC33E 器件的 MCAF R7），motorBench",
    "Development Suite must match the PWM frequency selected in MCC.": "Development Suite 中设置的 PWM 频率必须与 MCC 中选择的 PWM 频率一致。",
    "R7 added algorithm-dependent PWM modes, see": "R7 增加了算法相关的 PWM 模式，参见",
    "PWM update options": "PWM 更新选项",
    "for more details.": "以获取更多详情。",
    "In MCAF R6 \u2013 R9, sampling rates must be locked to specific ratios of the PWM frequency:": "在 MCAF R6–R9 中，采样率必须锁定为 PWM 频率的特定比例：",
    "Current sampling time": "电流采样时间",
    "must equal the PWM period, so that the bulk of the motor control algorithms run at the PWM frequency (": "必须等于 PWM 周期，使大部分电机控制算法以 PWM 频率运行（",
    "Velocity sampling time": "速度采样时间",
    "must equal 20 times the PWM period, so that the velocity controller runs every 20 PWM periods (": "必须等于 PWM 周期的 20 倍，使速度控制器每 20 个 PWM 周期运行一次（",
    "These restrictions will be removed in a future version of MCAF.": "这些限制将在未来版本的 MCAF 中移除。",
    "Testing": "测试",
    "MCAF R6 code was tested at several PWM frequencies (with current sampling rate locked to PWM frequency and velocity sampling rate locked to 1/20 PWM frequency, following the restrictions listed above):": "MCAF R6 代码在多个 PWM 频率下进行了测试（电流采样率锁定为 PWM 频率，速度采样率锁定为 1/20 PWM 频率，遵循上述限制）：",
    "12.5kHz, 20kHz, and 25kHz for confirmation of timing and CPU usage on both the dsPIC33EP256MC506 and the dsPIC33CK256MP508": "12.5kHz、20kHz 和 25kHz，用于确认 dsPIC33EP256MC506 和 dsPIC33CK256MP508 上的时序和 CPU 使用率",
    "10kHz, 12.5kHz, 16kHz, and 20kHz for general independence of tuning with PWM frequency and current loop sampling rate": "10kHz、12.5kHz、16kHz 和 20kHz，用于验证整定与 PWM 频率和电流环采样率的一般独立性",
    "12.5kHz and 20kHz for detailed verification of step response and estimator independence, for all three": "12.5kHz 和 20kHz，用于详细验证阶跃响应和估计器独立性，涵盖所有三种",
    "position and velocity estimators": "位置和速度估计器",
    "quadrature encoder": "正交编码器",
    ") on the dsPIC33CK256MP508": "）在 dsPIC33CK256MP508 上",
    "Step response tests used the": "阶跃响应测试使用",
    "test harness": "测试框架",
    "to add a": "添加",
    "square-wave perturbation": "方波扰动",
    "to the velocity command, and record the velocity and currents.": "到速度指令，并记录速度和电流。",
    "and": "和",
    "show the current and velocity step response for the ATPLL, logged at 12.5kHz and 20kHz PWM frequencies. Note that the step responses change very little between these cases, as expected.": "显示了 ATPLL 的电流和速度阶跃响应，分别在 12.5kHz 和 20kHz PWM 频率下记录。注意，这些情况之间的阶跃响应变化很小，符合预期。",
    "Step responses of current to changes in velocity command (orange = q-axis current command, blue = q-axis current)": "电流对速度指令变化的阶跃响应（橙色 = q 轴电流指令，蓝色 = q 轴电流）",
    "Step responses of velocity to changes in velocity command (orange = velocity command, blue = estimated velocity)": "速度对速度指令变化的阶跃响应（橙色 = 速度指令，蓝色 = 估计速度）",
    "6.4. Sampling Rate and PWM Frequency Implications": "6.4. 采样率与 PWM 频率的影响",
    "6.4.1. Effects of changing sampling rate and PWM frequency": "6.4.1. 更改采样率和 PWM 频率的影响",
    "6.4.1.1. PWM frequency": "6.4.1.1. PWM 频率",
    "6.4.1.2. Sampling rate": "6.4.1.2. 采样率",
    "6.4.1.3. Compensating parameters": "6.4.1.3. 补偿参数",
    "6.4.2. Implementation notes": "6.4.2. 实现说明",
    "6.4.2.1. Revision-specific information": "6.4.2.1. 版本特定信息",
    "6.4.2.2. Restrictions": "6.4.2.2. 限制",
    "6.4.3. Testing": "6.4.3. 测试",
    "Parameter customization": "参数定制",
    "Integration with Custom Code": "与自定义代码的集成",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
