# -*- coding: utf-8 -*-
import txutil

rel = "implementation/source-tree-structure"
title_zh = "6.1. 源代码树结构"

m = {
    "6.1. Source Tree Structure — MCAF R9 RC31 文档 (docver 9.0.1)": "6.1. 源代码树结构 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Source Tree Structure": "源代码树结构",
    "The MCAF is organized into several subdirectories. When used with motorBench": "MCAF 被组织为若干子目录。与 motorBench",
    "Development Suite, these are generated under the MPLAB": "Development Suite 一起使用时，这些目录生成在 MPLAB",
    "X project directory under": "X 项目目录下的",
    "Most modules are located under the top-level directory.": "大多数模块位于顶层目录下。",
    "contains the": "包含",
    "Hardware Abstraction Layer": "硬件抽象层",
    "contains header files with": "包含带有",
    "configurable parameters": "可配置参数的头文件",
    "contains library files for the": "包含",
    "Motor Control Library": "电机控制库的库文件",
    "contains auxiliary files that aren\u2019t C code, such as report files generated by motorBench": "包含非 C 代码的辅助文件，例如由 motorBench 生成的报告文件",
    "Information on particular source code files is organized by module name, in the": "特定源代码文件的信息按模块名组织，位于",
    "under \u201cmodules\u201d. (Module name is just the base name of the file, ignoring the file extension and, if present, the trailing": "的\u201cmodules\u201d条目下。（模块名即文件的基础名，忽略文件扩展名以及可能存在的尾部",
    ": for example,": "：例如，",
    ", and": "，以及",
    "are all part of the": "都属于",
    "module.)": "模块。）",
    "Code Generation": "代码生成",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
