# -*- coding: utf-8 -*-
import txutil

rel = "implementation/resource-usage"
title_zh = "6.7. 资源使用"

m = {
    "6.7. Resource Usage — MCAF R9 RC31 文档 (docver 9.0.1)": "6.7. 资源使用 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Resource Usage": "资源使用",
    "This section provides reference data for resource usage, covering program and data memory and CPU usage.": "本节提供资源使用的参考数据，涵盖程序存储器、数据存储器和 CPU 使用率。",
    "Please note": "请注意",
    ": Resource usage is dependent on a number of factors, and may be different than the data shown below. These factors include:": "：资源使用取决于多种因素，可能与以下所示数据不同。这些因素包括：",
    "Compiler version": "编译器版本",
    "Compiler optimization levels": "编译器优化级别",
    "Compiler flags": "编译器标志",
    "Settings in motorBench": "motorBench",
    "Development Suite": "Development Suite 中的设置",
    "Settings in MCC": "MCC 中的设置",
    "MCAF parameter values": "MCAF 参数值",
    "Test case": "测试用例",
    "In each case described below, MCAF firmware packages were used with default settings and the AN1292 PLL estimator selected, using the": "在以下描述的每种情况下，MCAF 固件包使用默认设置并选择 AN1292 PLL 估计器，使用",
    "motor and the": "电机和",
    "MCLV\u20112 Development Board": "MCLV-2 开发板",
    ". The source code was built using both XC16 and XC-DSC with": "。源代码使用 XC16 和 XC-DSC 以",
    "and": "和",
    "compilation levels for the devices dsPIC33EP256MC506, dsPIC33CK256MP508, and dsPIC33CK64MC105. The macros": "编译级别为器件 dsPIC33EP256MC506、dsPIC33CK256MP508 和 dsPIC33CK64MC105 构建。宏",
    "were enabled in options.h (see": "在 options.h 中启用（见",
    "Profiling timestamps": "性能分析时间戳",
    ").": "）。",
    "Program and data memory": "程序和数据存储器",
    "Resource usage statistics for program and data memory were derived from the map file.": "程序和数据存储器的资源使用统计数据来自 map 文件。",
    "CPU usage": "CPU 使用率",
    "CPU usage was determined with variants of MCAF modified to transmit CPU cycle count data via the UART, at various points in the motor control ISR, for a 20 kHz PWM ISR, using dsPIC33CK256MP508 and dsPIC33CK64MC105 running at 100 MIPS, and dsPIC33EP256MC506 running at 70 MIPS.": "CPU 使用率通过修改后的 MCAF 变体确定，这些变体在电机控制 ISR 的多个点通过 UART 传输 CPU 周期计数数据，针对 20 kHz PWM ISR，使用以 100 MIPS 运行的 dsPIC33CK256MP508 和 dsPIC33CK64MC105，以及以 70 MIPS 运行的 dsPIC33EP256MC506。",
    "CPU cycle count was measured over approximately 4 seconds, with the motor starting up, running, and slowing to a stop. The resulting time inside the motor control ISR was sorted from low to high, with the worst-case and 99.9% percentile computed. For example, 4 seconds of data at 20 kHz represents 80,000 data points, so the 99.9% percentile represents the 80th-highest sample of CPU usage. This represents conservative estimates of CPU usage for estimating remaining CPU capacity in aggregate over time, and exclude timing spikes which may occur when long execution paths coincide in the same ISR cycle. The worst-case CPU usage should be used to determine that the ISR does not exceed available CPU time. Variation in CPU time is due to a number of factors, including:": "CPU 周期计数在约 4 秒内测量，电机经历启动、运行和减速停止。电机控制 ISR 内的时间从低到高排序，计算最坏情况和 99.9% 百分位。例如，20 kHz 下 4 秒的数据代表 80,000 个数据点，因此 99.9% 百分位代表 CPU 使用率第 80 高的样本。这代表了用于估计随时间累积剩余 CPU 容量的保守估计，并排除了长执行路径在同一 ISR 周期中巧合时可能出现的时序尖峰。最坏情况 CPU 使用率应用于确定 ISR 不超过可用 CPU 时间。CPU 时间的变化由多种因素引起，包括：",
    "Branches (": "分支（",
    "statements) may take alternate and unequal execution paths": "语句）可能采取不同且不等长的执行路径",
    "Some algorithms run at submultiples of the ISR, so for example the PLL position estimator has a portion of code that runs once every 8 ISR cycles": "某些算法以 ISR 的约数频率运行，例如 PLL 位置估计器有一部分代码每 8 个 ISR 周期运行一次",
    "During different states of the": "在",
    "state machine": "状态机",
    ", different parts of the code are enabled or disabled": "的不同状态期间，代码的不同部分被启用或禁用",
    "Main loop CPU usage was not profiled but is minimal (estimated at < 0.1 MIPS); not much code runs in the main loop.": "主循环 CPU 使用率未进行性能分析但很小（估计 < 0.1 MIPS）；主循环中运行的代码不多。",
    "Usage statistics for MCAF R3": "MCAF R3 使用统计",
    "Statistic": "统计项",
    "Program memory": "程序存储器",
    "(bytes)": "（字节）",
    "Excluding X2Cscope": "不含 X2Cscope",
    "X2Cscope module": "X2Cscope 模块",
    "Total": "总计",
    "Data memory": "数据存储器",
    "CPU ISR usage": "CPU ISR 使用率",
    "(% at 70 MIPS, 20 kHz ISR)": "（70 MIPS、20 kHz ISR 下的百分比）",
    "Worst-case": "最坏情况",
    "99.9% percentile": "99.9% 百分位",
    "Usage statistics for MCAF R4": "MCAF R4 使用统计",
    "Usage statistics for MCAF R5": "MCAF R5 使用统计",
    "Usage statistics for MCAF R6": "MCAF R6 使用统计",
    "(approximate number of cycles, and percentage at 70 MIPS, 20 kHz ISR)": "（近似周期数，及 70 MIPS、20 kHz ISR 下的百分比）",
    "(approximate number of cycles, and percentage at 100 MIPS, 20 kHz ISR)": "（近似周期数，及 100 MIPS、20 kHz ISR 下的百分比）",
    "Algorithm options and variants": "算法选项和变体",
    "\u2014 these represent additional usage costs in CPU usage, program (code) memory size, and data memory size, above the base case shown above. CPU measurements are approximate, based on capturing elapsed timer measurements from the test harness. All measurements are made from independent test cases enabling one module or option at a time, which may not take into account interaction between modules; for example, the compiler may be able to identify additional optimization opportunities if more than one of the cases below are enabled simultaneously, or the additional computations may cause additional CPU cycles for register moves that are not required when the same modules are enabled separately.": "\u2014 这些表示在上述基准情况之上的 CPU 使用率、程序（代码）存储器大小和数据存储器大小的额外使用成本。CPU 测量是近似的，基于从测试框架捕获的已用定时器测量值。所有测量均来自独立测试用例，每次启用一个模块或选项，可能未考虑模块间的交互；例如，如果同时启用以下多个情况，编译器可能能够识别额外的优化机会，或者额外的计算可能导致在同一模块单独启用时不需要的额外寄存器移动 CPU 周期。",
    "Module": "模块",
    "Option": "选项",
    "(cycles)": "（周期）",
    "Size (bytes)": "大小（字节）",
    "Conditions": "条件",
    "Code": "代码",
    "Data": "数据",
    "Dead-time compensation": "死区补偿",
    "Per-phase": "逐相",
    "Flux control": "磁通控制",
    "Equation-based, FW+MTPA disabled": "基于方程，FW+MTPA 禁用",
    "Equation-based, FW enabled": "基于方程，FW 启用",
    "Equation-based, MTPA enabled": "基于方程，MTPA 启用",
    "Equation-based, FW+MTPA enabled": "基于方程，FW+MTPA 启用",
    "Usage statistics for MCAF R7": "MCAF R7 使用统计",
    "Usage Statistics for MCAF R8": "MCAF R8 使用统计",
    "Usage Statistics for MCAF R9": "MCAF R9 使用统计",
    "In execution-time testing for MCAF R9, dsPIC33A and dsPIC33C devices use MCC Melody, while dsPIC33E devices use MCC Classic.": "在 MCAF R9 的执行时间测试中，dsPIC33A 和 dsPIC33C 器件使用 MCC Melody，而 dsPIC33E 器件使用 MCC Classic。",
    "CPU ISR usage results for dsPIC33CK64MC105 with the XC-DSC 3.31 compiler are not available due to technical issues in profiling this configuration; MCAF team will update these results when the profiling issues are addressed": "由于此配置的性能分析存在技术问题，dsPIC33CK64MC105 与 XC-DSC 3.31 编译器的 CPU ISR 使用率结果不可用；MCAF 团队将在性能分析问题解决后更新这些结果",
    "Changes between MCAF revisions": "MCAF 版本间的变化",
    "The apparent decrease in ISR usage between MCAF R3 and R4 should not be taken as conclusive. Microchip staff have performed similar tests where the CPU usage time has increased slightly from MCAF R3 to MCAF R4; we are aware of the issue and are investigating more reliable methods to compare CPU usage between MCAF revisions under controlled conditions.": "MCAF R3 和 R4 之间 ISR 使用率的表观下降不应被视为结论性的。Microchip 工作人员进行了类似测试，其中 CPU 使用时间从 MCAF R3 到 R4 略有增加；我们已意识到此问题，正在研究在受控条件下比较 MCAF 版本间 CPU 使用率的更可靠方法。",
    "MCAF R6 and R7 have each increased CPU usage slightly, compared to MCAF R5.": "与 MCAF R5 相比，MCAF R6 和 R7 的 CPU 使用率均略有增加。",
    "CPU usage has increased slightly in MCAF R8 compared to MCAF R7.": "与 MCAF R7 相比，MCAF R8 的 CPU 使用率略有增加。",
    "Microchip staff is investigating potential ways to reduce these increases in CPU usage in future MCAF revisions.": "Microchip 工作人员正在研究在未来 MCAF 版本中减少 CPU 使用率增加的潜在方法。",
    "Current measurement": "电流测量",
    "Single-channel": "单通道",
    "Triple-channel": "三通道",
    "Dynamic current limit": "动态电流限制",
    "Simple": "简单",
    "Zero-Speed / Maximum Torque (ZS/MT)": "零速/最大转矩 (ZS/MT)",
    "ZS/MT standalone estimator": "ZS/MT 独立估计器",
    "Binary hard-switch hybrid estimator": "二进制硬切换混合估计器",
    "6.7. Resource Usage": "6.7. 资源使用",
    "6.7.1. Test case": "6.7.1. 测试用例",
    "6.7.1.1. Program and data memory": "6.7.1.1. 程序和数据存储器",
    "6.7.1.2. CPU usage": "6.7.1.2. CPU 使用率",
    "6.7.2. Usage statistics for MCAF R3": "6.7.2. MCAF R3 使用统计",
    "6.7.3. Usage statistics for MCAF R4": "6.7.3. MCAF R4 使用统计",
    "6.7.4. Usage statistics for MCAF R5": "6.7.4. MCAF R5 使用统计",
    "6.7.5. Usage statistics for MCAF R6": "6.7.5. MCAF R6 使用统计",
    "6.7.6. Usage statistics for MCAF R7": "6.7.6. MCAF R7 使用统计",
    "6.7.7. Usage Statistics for MCAF R8": "6.7.7. MCAF R8 使用统计",
    "6.7.8. Usage Statistics for MCAF R9": "6.7.8. MCAF R9 使用统计",
    "6.7.9. Changes between MCAF revisions": "6.7.9. MCAF 版本间的变化",
    "Custom board definition format": "自定义板级定义格式",
    "Appendix": "附录",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
