# -*- coding: utf-8 -*-
"""Translate remaining index/overview pages in batch."""
import txutil

# ---- appendix/index ----
appendix_m = {
    "Appendix": "附录",
    "Glossary": "术语表",
    "Resource Usage": "资源占用",
    "7. Appendix": "7. 附录",
    "7.1. Glossary": "7.1. 术语表",
    "7.2. Error code list": "7.2. 错误代码列表",
    "7.3. MCLV-2 Sense Resistors": "7.3. MCLV-2 采样电阻",
    "7.4. Related Documents": "7.4. 相关文档",
    "7.5. Revision History": "7.5. 修订历史",
    "7.5.1. MCAF Documentation Revision History": "7.5.1. MCAF 文档修订历史",
    "7.5.2. MCAF Revision History": "7.5.2. MCAF 修订历史",
}

# ---- components/index ----
components_m = {
    "Components": "组件",
    "Main Application": "主应用",
    "Treatment of Numerical Algorithms": "数值算法处理",
    "4. Components": "4. 组件",
    "4.1. Main Application": "4.1. 主应用",
    "4.1.1. Implementation Notes": "4.1.1. 实现说明",
    "4.2. ADC Calibration and Compensation": "4.2. ADC 校准与补偿",
    "4.2.1. Phase Current Offset Compensation": "4.2.1. 相电流偏置补偿",
    "4.2.2. ADC Gain Error Compensation": "4.2.2. ADC 增益误差补偿",
    "4.2.3. Implementation Notes": "4.2.3. 实现说明",
    "4.3. State Machine": "4.3. 状态机",
    "4.3.1. States": "4.3.1. 状态",
    "4.3.2. Input conditions": "4.3.2. 输入条件",
    "4.3.3. Miscellaneous state machine issues": "4.3.3. 状态机其他问题",
    "4.3.4. Implementation Notes": "4.3.4. 实现说明",
    "4.4. Field-Oriented Control (FOC)": "4.4. 磁场定向控制（FOC）",
    "4.4.1. Velocity Control": "4.4.1. 速度控制",
    "4.4.2. Current Control": "4.4.2. 电流控制",
    "4.4.3. Position and Velocity Estimator": "4.4.3. 位置与速度估计器",
    "4.4.4. Implementation Notes": "4.4.4. 实现说明",
    "4.5. Test Harness": "4.5. 测试框架",
    "4.5.1. Overview": "4.5.1. 概述",
    "4.5.2. Accretive Testing": "4.5.2. 增量测试",
    "4.5.3. Test Harness Parameters": "4.5.3. 测试框架参数",
    "4.5.4. Test Guarding": "4.5.4. 测试防护",
    "4.5.5. Test Harness Architecture": "4.5.5. 测试框架架构",
    "4.5.6. Test harness modes": "4.5.6. 测试框架模式",
    "4.5.7. Interaction with the System State Machine": "4.5.7. 与系统状态机的交互",
    "4.5.8. Forcing System State Machine Transitions": "4.5.8. 强制系统状态机转换",
    "4.5.9. Test Harness Switches (Overrides)": "4.5.9. 测试框架开关（覆盖）",
    "4.5.10. Perturbation Signals": "4.5.10. 扰动信号",
    "4.5.11. Seizures": "4.5.11. 卡住检测",
    "4.5.12. Stack overflow": "4.5.12. 栈溢出",
    "4.5.13. Profiling Timestamps": "4.5.13. 性能分析时间戳",
    "4.5.14. Triggered Average": "4.5.14. 触发平均",
    "4.5.15. Example use cases": "4.5.15. 用例示例",
    "4.5.16. Implementation Notes": "4.5.16. 实现说明",
    "4.6. Supervisory Algorithms": "4.6. 监督算法",
    "4.6.1. Implementation Notes": "4.6.1. 实现说明",
    "4.7. External Interface": "4.7. 外部接口",
    "4.7.1. General UI guidelines": "4.7.1. 通用 UI 指南",
    "4.7.2. Implemented Behavior": "4.7.2. 已实现的行为",
    "4.7.3. Error Codes": "4.7.3. 错误代码",
    "4.7.4. Timing and Fault-Clearing Issues in UI Indicators": "4.7.4. UI 指示灯的时序与故障清除问题",
    "4.7.5. Implementation": "4.7.5. 实现",
    "4.8. Diagnostic Kernel": "4.8. 诊断内核",
    "4.8.1. Implementation Notes": "4.8.1. 实现说明",
    "4.9. Hardware Abstraction Layer (HAL)": "4.9. 硬件抽象层（HAL）",
    "4.9.1. Hardware-related behavior": "4.9.1. 与硬件相关的行为",
    "4.9.2. Implementation": "4.9.2. 实现",
    "4.10. Motion Control API (MCAPI)": "4.10. 运动控制 API（MCAPI）",
    "4.10.1. Overview": "4.10.1. 概述",
    "4.10.2. API Description": "4.10.2. API 描述",
    "4.10.3. Usage Notes": "4.10.3. 使用说明",
    "4.10.4. Implementation Notes": "4.10.4. 实现说明",
    "4.11. Miscellaneous": "4.11. 其他",
    "4.11.1. Implementation Notes": "4.11.1. 实现说明",
}

# ---- implementation/index ----
impl_m = {
    "General Implementation Issues": "通用实现问题",
    "Source Tree Structure": "源码树结构",
    "Temperature measurement": "温度测量",
    "6. General Implementation Issues": "6. 通用实现问题",
    "6.1. Source Tree Structure": "6.1. 源码树结构",
    "6.2. Code Generation": "6.2. 代码生成",
    "6.2.1. Relationship with motorBench": "6.2.1. 与 motorBench 的关系",
    "Development Suite and MCC": "Development Suite 和 MCC",
    "6.2.2. Configurable parameters": "6.2.2. 可配置参数",
    "6.2.3. Source file organization": "6.2.3. 源文件组织",
    "6.2.4. Auxiliary reports": "6.2.4. 辅助报告",
    "6.3. Parameter customization": "6.3. 参数定制",
    "6.3.1. Summary": "6.3.1. 概要",
    "6.3.2. Detailed information": "6.3.2. 详细信息",
    "6.4. Sampling Rate and PWM Frequency Implications": "6.4. 采样速率与 PWM 频率的影响",
    "6.4.1. Effects of changing sampling rate and PWM frequency": "6.4.1. 改变采样速率和 PWM 频率的影响",
    "6.4.2. Implementation notes": "6.4.2. 实现说明",
    "6.4.3. Testing": "6.4.3. 测试",
    "6.5. Integration with Custom Code": "6.5. 与自定义代码的集成",
    "6.5.1. Overview": "6.5.1. 概述",
    "6.5.2. Modifying the Main Application": "6.5.2. 修改主应用",
    "6.5.3. Modifying the FOC module": "6.5.3. 修改 FOC 模块",
    "6.5.4. Modifying the State Machine": "6.5.4. 修改状态机",
    "6.5.5. Modifying the Supervisory Algorithms": "6.5.5. 修改监督算法",
    "6.6. Custom Board Support": "6.6. 定制板卡支持",
    "6.6.1. Overview of board support in motorBench": "6.6.1. motorBench 中的板卡支持概述",
    "Development Suite": "Development Suite",
    "6.6.2. Scope of hardware support": "6.6.2. 硬件支持范围",
    "6.6.3. Board definition file structure": "6.6.3. 板卡定义文件结构",
    "6.6.4. System parameters": "6.6.4. 系统参数",
    "6.6.5. Creating a custom board configuration": "6.6.5. 创建定制板卡配置",
    "6.6.6. Board definition file validation": "6.6.6. 板卡定义文件验证",
    "6.6.7. Support for MCP802X gate drivers, including MCP8021-based SiP (System-in-Package) devices": "6.6.7. 对 MCP802X 栅极驱动器的支持，包括基于 MCP8021 的 SiP（系统级封装）器件",
    "6.6.8. Verification and board bring-up": "6.6.8. 验证与板卡调试",
    "6.6.9. Custom board definition format": "6.6.9. 定制板卡定义格式",
    "6.7. Resource Usage": "6.7. 资源占用",
    "6.7.1. Test case": "6.7.1. 测试用例",
    "6.7.2. Usage statistics for MCAF R3": "6.7.2. MCAF R3 的资源占用统计",
    "6.7.3. Usage statistics for MCAF R4": "6.7.3. MCAF R4 的资源占用统计",
    "6.7.4. Usage statistics for MCAF R5": "6.7.4. MCAF R5 的资源占用统计",
    "6.7.5. Usage statistics for MCAF R6": "6.7.5. MCAF R6 的资源占用统计",
    "6.7.6. Usage statistics for MCAF R7": "6.7.6. MCAF R7 的资源占用统计",
    "6.7.7. Usage Statistics for MCAF R8": "6.7.7. MCAF R8 的资源占用统计",
    "6.7.8. Usage Statistics for MCAF R9": "6.7.8. MCAF R9 的资源占用统计",
    "6.7.9. Changes between MCAF revisions": "6.7.9. MCAF 各修订版之间的变化",
}

# ---- implementation/custom-board-support/index ----
cbs_m = {
    "Custom Board Support": "定制板卡支持",
    "Integration with Custom Code": "与自定义代码的集成",
    "Overview of board support in motorBench": "motorBench 中的板卡支持概述",
    "General Implementation Issues": "通用实现问题",
    "6.6. Custom Board Support": "6.6. 定制板卡支持",
    "6.6.1. Overview of board support in motorBench": "6.6.1. motorBench 中的板卡支持概述",
    "Development Suite": "Development Suite",
    "6.6.2. Scope of hardware support": "6.6.2. 硬件支持范围",
    "6.6.2.1. Board configuration features": "6.6.2.1. 板卡配置功能",
    "6.6.2.2. Assumptions": "6.6.2.2. 假设",
    "6.6.3. Board definition file structure": "6.6.3. 板卡定义文件结构",
    "6.6.4. System parameters": "6.6.4. 系统参数",
    "6.6.5. Creating a custom board configuration": "6.6.5. 创建定制板卡配置",
    "6.6.5.1. Starter board file": "6.6.5.1. 起始板卡文件",
    "6.6.5.2. Modifying the starter board definition": "6.6.5.2. 修改起始板卡定义",
    "6.6.5.3. Adding parameters to the board definition": "6.6.5.3. 向板卡定义添加参数",
    "6.6.5.4. Adding a non-MCAF UART": "6.6.5.4. 添加非 MCAF UART",
    "6.6.5.5. Custom boards without pushbuttons or potentiometer": "6.6.5.5. 不带按钮或电位器的定制板卡",
    "6.6.6. Board definition file validation": "6.6.6. 板卡定义文件验证",
    "6.6.7. Support for MCP802X gate drivers, including MCP8021-based SiP (System-in-Package) devices": "6.6.7. 对 MCP802X 栅极驱动器的支持，包括基于 MCP8021 的 SiP（系统级封装）器件",
    "6.6.7.1. Overview": "6.6.7.1. 概述",
    "6.6.7.2. Integration with MCAF": "6.6.7.2. 与 MCAF 的集成",
    "6.6.7.3. Configuration": "6.6.7.3. 配置",
    "6.6.7.4. System-level behavior": "6.6.7.4. 系统级行为",
    "6.6.8. Verification and board bring-up": "6.6.8. 验证与板卡调试",
    "6.6.8.1. Overview": "6.6.8.1. 概述",
    "6.6.8.2. General firmware execution": "6.6.8.2. 通用固件执行",
    "6.6.8.3. Open-loop voltage operation": "6.6.8.3. 开环电压运行",
    "6.6.8.4. Closed-loop current control": "6.6.8.4. 闭环电流控制",
    "6.6.9. Custom board definition format": "6.6.9. 定制板卡定义格式",
    "6.6.9.1. Working with Serialized Data Models": "6.6.9.1. 使用序列化数据模型",
    "6.6.9.2. Custom board schema": "6.6.9.2. 定制板卡架构",
}

# ---- algorithms/flux_control/index ----
flux_m = {
    "Detailed Algorithm Notes": "详细算法说明",
    "Flux control": "磁通控制",
    "Sliding Mode Observer (SMO)": "滑模观测器（SMO）",
    "Flux weakening": "弱磁",
    "PMSM": "PMSM",
    "Overview": "概述",
    "Flow chart and details": "流程图与细节",
    "D-axis current reference generation": "d 轴电流参考生成",
    "Overview of flux control algorithm": "磁通控制算法概述",
    "5.5. Flux control": "5.5. 磁通控制",
    "5.5.1. Flux weakening": "5.5.1. 弱磁",
    "5.5.1.1. Motivation": "5.5.1.1. 动机",
    "5.5.1.2. Effect on torque capability": "5.5.1.2. 对转矩能力的影响",
    "5.5.1.3. Flux-weakening algorithms": "5.5.1.3. 弱磁算法",
    "5.5.2. Maximum Torque Per Ampere (MTPA)": "5.5.2. 最大转矩/电流比（MTPA）",
    "5.5.2.1. Overview": "5.5.2.1. 概述",
    "5.5.2.2. Flow chart and description": "5.5.2.2. 流程图与说明",
    "5.5.2.3. Implementation notes": "5.5.2.3. 实现说明",
    "5.5.3. D-axis current reference generation": "5.5.3. d 轴电流参考生成",
    "5.5.3.1. Overview": "5.5.3.1. 概述",
    "5.5.3.2. Flow chart and description": "5.5.3.2. 流程图与说明",
    "5.5.3.3. Calculation of q-axis current limit": "5.5.3.3. q 轴电流限值计算",
    "5.5.4. Overview": "5.5.4. 概述",
    "5.5.5. Flow chart and details": "5.5.5. 流程图与细节",
    "The flux control module in MCAF deals with generation of a suitable reference value for the d-axis stator current in a":
        "MCAF 中的磁通控制模块负责为",
    "which is then given as an input to the d-axis current controller. The need for injecting a current component in the synchronous d axis could arise out of multiple requirements as described below.":
        "的 d 轴定子电流生成合适的参考值，该参考值随后作为 d 轴电流控制器的输入。在同步 d 轴注入电流分量的需求可能来自以下所述的多种要求。",
    "In a": "在",
    ", the stator voltage is required to increase with rotor velocity. The dc-link voltage of the inverter, however, puts a limitation on the stator voltage. Other important considerations which do not support increase in the DC link voltage are user safety and motor’s safe operating zone. Many applications require the motor to be operated at velocity higher than its rated value. In order to achieve this while also limiting the stator voltage, motor’s airgap flux is weakened by injecting a negative d-axis stator current in the motor. This operation is called as flux-weakening (FW). Flux-weakening is required for motors with salient as well as non-salient rotors. The FW module in Flux Control calculates a suitable d-axis current reference for the flux-weakening operation (":
        "中，定子电压需要随转子速度增加而增大。然而逆变器的母线电压对定子电压构成了限制。不支持提高母线电压的其他重要考量包括用户安全和电机的安全工作区。许多应用要求电机在高于其额定值的速度下运行。为实现这一点同时限制定子电压，通过向电机注入负的 d 轴定子电流来削弱电机的气隙磁通。这种操作称为弱磁（FW）。无论凸极还是非凸极转子电机都需要弱磁。磁通控制中的 FW 模块在特定速度和负载下计算弱磁运行所需的合适 d 轴电流参考（",
    ") at a particular velocity and load.": "）。",
    "The second requirement for the flux control module stems specifically from the motors with salient-pole rotors. In case of salient-pole motors, the reluctance torque (arising out of saliency of the motor) can be made to aid the permanent magnet torque by injecting a negative d-axis current in the motor. This ensures that the motor operates at its maximum efficiency by generating Maximum Torque Per Ampere (MTPA). The MTPA algorithm calculates a suitable reference for the MTPA operation (":
        "磁通控制模块的第二个需求专门源于凸极转子电机。对于凸极电机，通过向电机注入负的 d 轴电流，可以使磁阻转矩（由电机的凸极性产生）协助永磁转矩。这确保电机以最大效率运行，即产生最大转矩/电流比（MTPA）。MTPA 算法为特定工作点计算 MTPA 运行所需的合适参考（",
    ") for a particular operating point.": "）。",
    "The flux control module contains implementations of flux-weakening and MTPA. Depending on the requirement, either algorithm can be enabled or disabled independently. The flux-weakening module calculates and returns the d-axis current reference":
        "磁通控制模块包含弱磁和 MTPA 的实现。根据需求，两种算法可以独立启用或禁用。弱磁模块计算并返回 d 轴电流参考",
    ", whereas the MTPA module calculates and returns the d-axis current reference": "，而 MTPA 模块计算并返回 d 轴电流参考",
    ". When disabled, either of these algorithms returns a value equal to zero for their respective d-axis current reference. The": "。当禁用时，两种算法各自返回的 d 轴电流参考值均为零。",
    "generation module then chooses the appropriate value between": "生成模块随后在",
    "and": "和",
    "and generates the d-axis current reference": "之间选择合适的值，并生成 d 轴电流参考",
    "as an input to the current controller.": "作为电流控制器的输入。",
    "shows a flow chart of the overall flux control calculations.": "展示了整体磁通控制计算的流程图。",
    "Depending on the requirements, the flux control module can be enabled by setting it to Equation-based. If flux control is disabled by setting it to None,":
        "根据需求，可通过将磁通控制设置为基于方程（Equation-based）来启用。如果将磁通控制设置为 None（无）来禁用，则",
    "is made equal to zero. Once enabled, either or both of the MTPA and FW algorithms can be enabled.":
        "被置为零。启用后，MTPA 和 FW 算法中的任意一个或两个都可以被启用。",
    "The flux-weakening and MTPA modules calculate": "弱磁和 MTPA 模块分别计算",
    "respectively. In case these modules are disabled, corresponding calculated value is made equal to zero.":
        "。如果这些模块被禁用，相应的计算值被置为零。",
    "In case the application requires a salient-pole motor to operate beyond rated velocity, both MTPA as well as FW should be enabled. In this case, depending on the region of operation, a correct selection between the d-axis current references calculated by either module is made and that reference is given as an input to the d-axis current controller. Refer to":
        "如果应用要求凸极电机在额定速度以上运行，则应同时启用 MTPA 和 FW。此时，根据运行区域，在两个模块计算出的 d 轴电流参考之间做出正确选择，并将该参考作为 d 轴电流控制器的输入。详见",
    "for more details.": "以获取更多细节。",
}

PAGES = [
    ("appendix/index", "7. 附录", appendix_m),
    ("components/index", "4. 组件", components_m),
    ("implementation/index", "6. 通用实现问题", impl_m),
    ("implementation/custom-board-support/index", "6.6. 定制板卡支持", cbs_m),
    ("algorithms/flux_control/index", "5.5. 磁通控制", flux_m),
]

for rel, title_zh, m in PAGES:
    path = txutil.translate_dict_page(rel, title_zh, m)
    print("translated", path)
