# -*- coding: utf-8 -*-
import txutil

rel = "implementation/ui-customization"
title_zh = "6.3. 参数定制"

m = {
    "6.3. Parameter customization — MCAF R9 RC31 文档 (docver 9.0.1)": "6.3. 参数定制 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Parameter customization": "参数定制",
    "As of MCAF R4, parameter customization is available through the Customize page of motorBench": "自 MCAF R4 起，可通过 motorBench",
    "Development Suite, which provides access to various parameters that affect code generation.": "Development Suite 的 Customize 页面进行参数定制，该页面提供对影响代码生成的各种参数的访问。",
    "This section provides additional guidance for setting these parameters.": "本节提供设置这些参数的额外指导。",
    "Please note:": "请注意：",
    "MCAF has been designed so that the default values for customizable parameters are applicable to most motors. In the event that it is unclear what to do, the best course of action is to use the default value of each parameter.": "MCAF 的设计使得可定制参数的默认值适用于大多数电机。如果不确定如何操作，最佳做法是使用每个参数的默认值。",
    "Summary": "摘要",
    "The following table describes these parameters briefly. Links to detailed guidance are included.": "下表简要描述了这些参数。包含详细指导的链接。",
    "Customizable parameters": "可定制参数",
    "Section": "节",
    "Parameter": "参数",
    "Description": "描述",
    "Current measurement": "电流测量",
    "Selects which method is used to measure motor phase currents": "选择用于测量电机相电流的方法",
    "Single channel": "单通道",
    "Minimum time window": "最小时间窗口",
    "Minimum time window required to measure current": "测量电流所需的最小时间窗口",
    "ADC trigger delay": "ADC 触发延迟",
    "Delay between inverter switching state and ADC sampling point": "逆变器开关状态与 ADC 采样点之间的延迟",
    "Estimators": "估计器",
    "Primary estimator": "主估计器",
    "Selects which estimator is used for commutation and velocity feedback": "选择用于换相和速度反馈的估计器",
    "Active estimators": "活动估计器",
    "Selects which estimators are active, in addition to the primary estimator used for commutation": "除用于换相的主估计器外，选择哪些估计器处于活动状态",
    "Operating parameters": "运行参数",
    "Minimum velocity": "最小速度",
    "Determines minimum operating velocity": "确定最小运行速度",
    "Startup velocity": "启动速度",
    "Determines startup velocity": "确定启动速度",
    "Maximum velocity": "最大速度",
    "Determines maximum velocity command, as a ratio of nominal motor velocity": "确定最大速度指令，以标称电机速度的比例表示",
    "Full-scale velocity": "满量程速度",
    "Determines full-scale velocity, as a ratio of nominal motor velocity": "确定满量程速度，以标称电机速度的比例表示",
    "Outer loop controller": "外环控制器",
    "Determines the variable controlled by the outer control loop": "确定外控制环控制的变量",
    "Saliency: Saliency threshold": "凸极性：凸极阈值",
    "Determines saliency ratio below which the motor\u2019s saliency is neglected": "确定凸极比阈值，低于此值时忽略电机的凸极性",
    "Slew rate: max acceleration": "压摆率：最大加速度",
    "Determines maximum velocity slew rate in motoring quadrants": "确定电动象限的最大速度压摆率",
    "Slew rate: max deceleration": "压摆率：最大减速度",
    "Determines maximum velocity slew rate in generating quadrants": "确定发电象限的最大速度压摆率",
    "Dynamic current limit type": "动态电流限制类型",
    "Determines which type (if any) of dynamic current limit algorithm to use": "确定使用哪种类型（如有）的动态电流限制算法",
    "Closed-loop stopping": "闭环停止",
    "Determines which type (if any) of closed-loop stopping to use": "确定使用哪种类型（如有）的闭环停止",
    "Closed loop stopping: Speed": "闭环停止：速度",
    "speed at which the motor is considered stopped": "认为电机已停止的速度",
    "Closed loop stopping: Time": "闭环停止：时间",
    "time duration where the motor is below the stopping speed, after which the motor is considered stopped": "电机低于停止速度的持续时间，超过此时间后认为电机已停止",
    "Coastdown: Velocity threshold": "惯性减速：速度阈值",
    "Determines velocity threshold used to estimate when a motor stops": "确定用于估计电机何时停止的速度阈值",
    "Coastdown: Time": "惯性减速：时间",
    "Determines time to wait until a motor stops": "确定等待电机停止的时间",
    "Flux control": "磁通控制",
    "Flux control method": "磁通控制方法",
    "Selects flux control method (or \u201cNone\u201d if disabled)": "选择磁通控制方法（禁用时选\u201cNone\u201d）",
    "Current limit: Boundary type": "电流限制：边界类型",
    "Selects method used for defining the commanded Idq boundary": "选择用于定义指令 Idq 边界的方法",
    "Current limit: Idmax": "电流限制：Idmax",
    "Determines the maximum negative d-axis current": "确定最大负向 d 轴电流",
    "Current limit: Iqmax": "电流限制：Iqmax",
    "Determines the maximum q-axis current": "确定最大 q 轴电流",
    "Flux weakening: enable": "弱磁：启用",
    "Determines if flux weakening is enabled": "确定是否启用弱磁",
    "Flux weakening: Voltage limit": "弱磁：电压限值",
    "Determines the voltage amplitude limit used in flux weakening (FW)": "确定弱磁 (FW) 中使用的电压幅值限值",
    "MTPA: Enable": "MTPA：启用",
    "Determines if MTPA is enabled": "确定是否启用 MTPA",
    "MTPA: Idmax-MTPA": "MTPA：Idmax-MTPA",
    "Displays the maximum d-axis current allocated to MTPA, as a function of": "显示分配给 MTPA 的最大 d 轴电流，作为",
    "and": "和",
    "(Indication only)": "（仅指示）",
    "MTPA: gain-MTPA": "MTPA：gain-MTPA",
    "Displays the maximum increase in torque due to MTPA (Indication only)": "显示 MTPA 带来的最大转矩增加（仅指示）",
    "Dead-time compensation": "死区补偿",
    "Dead-time compensation method": "死区补偿方法",
    "Selects dead-time compensation method (or \u201cNone\u201d if disabled)": "选择死区补偿方法（禁用时选\u201cNone\u201d）",
    "Current linearity range": "电流线性范围",
    "Determines linear range of currents used for deadtime compensation; larger currents are treated as \u00b11": "确定用于死区补偿的电流线性范围；较大电流视为 \u00b11",
    "Forward gain": "前向增益",
    "Determines gain for dead-time compensation in the forward path": "确定前向通道中死区补偿的增益",
    "Feedback gain": "反馈增益",
    "Determines gain for dead-time compensation in the feedback path": "确定反馈通道中死区补偿的增益",
    "Fault detection": "故障检测",
    "Undervoltage margin": "欠压裕量",
    "Determines undervoltage threshold margin": "确定欠压阈值裕量",
    "Overvoltage margin": "过压裕量",
    "Determines overvoltage threshold margin": "确定过压阈值裕量",
    "Stall detect: enable": "堵转检测：启用",
    "Determines if stall detect is enabled": "确定是否启用堵转检测",
    "Startup": "启动",
    "Startup current": "启动电流",
    "Determines current used during startup": "确定启动期间使用的电流",
    "Rampup time": "斜坡上升时间",
    "Determines current rampup time during startup": "确定启动期间的电流斜坡上升时间",
    "Align time": "对齐时间",
    "Determines time to remain in the align state during startup": "确定启动期间停留在对齐状态的时间",
    "Min accel time": "最小加速时间",
    "Determines minimum acceleration time during startup": "确定启动期间的最小加速时间",
    "Acceleration": "加速度",
    "Determines fast acceleration rate": "确定快速加速率",
    "Determines slow acceleration rate": "确定慢速加速率",
    "Hold time": "保持时间",
    "Determines time to remain in the hold state during startup": "确定启动期间停留在保持状态的时间",
    "Speed threshold": "速度阈值",
    "Determines speed threshold for switching to fast acceleration": "确定切换到快速加速的速度阈值",
    "Angle converge rate": "角度收敛速率",
    "Determines rate of angle convergence during closed-loop transition of classic startup": "确定经典启动闭环转换期间的角度收敛速率",
    "Startup algorithm": "启动算法",
    "Selects startup method": "选择启动方法",
    "Active damping: max amplitude": "主动阻尼：最大幅值",
    "Determines maximum amplitude of active damping current": "确定主动阻尼电流的最大幅值",
    "Active damping: max gain": "主动阻尼：最大增益",
    "Determines maximum gain of active damping": "确定主动阻尼的最大增益",
    "Active damping: speed threshold": "主动阻尼：速度阈值",
    "Determines the minimum velocity to enable active damping": "确定启用主动阻尼的最小速度",
    "Overmodulation": "过调制",
    "D-axis limit": "d 轴限值",
    "Determines the maximum d-axis voltage": "确定最大 d 轴电压",
    "Q-axis limit": "q 轴限值",
    "Determines the maximum q-axis voltage": "确定最大 q 轴电压",
    "Duty cycle feedback with clipping": "带削波的占空比反馈",
    "Determines when in the forward path duty cycle feedback is obtained": "确定在前向通道中何时获取占空比反馈",
    "AN1292 PLL": "AN1292 PLL",
    "Time constant": "时间常数",
    "Specifies the velocity estimation time constant": "指定速度估计时间常数",
    "Loop filter bandwidth": "环路滤波器带宽",
    "Specifies the loop filter bandwidth": "指定环路滤波器带宽",
    "Filter threshold": "滤波器阈值",
    "Determines maximum velocity for slow filtering in the PLL": "确定 PLL 中慢速滤波的最大速度",
    "Quadrature encoder": "正交编码器",
    "Lines": "线数",
    "Specifies the number of lines of the encoder": "指定编码器的线数",
    "Index pulse present": "存在索引脉冲",
    "Specifies whether an index pulse is present": "指定是否存在索引脉冲",
    "Tracking loop time constant": "跟踪环路时间常数",
    "Determines bandwidth of tracking loop": "确定跟踪环路的带宽",
    "Synchronization method": "同步方法",
    "Selects method of synchronizing encoder with back-emf": "选择编码器与反电动势同步的方法",
    "Duration of alignment phase of startup": "启动对齐阶段的持续时间",
    "Align angle shift": "对齐角度偏移",
    "Determines angle shift between rampup and align states of startup": "确定启动的斜坡上升和对齐状态之间的角度偏移",
    "Align initial angle": "对齐初始角度",
    "Determines initial angle used in rampup state of startup": "确定启动斜坡上升状态中使用的初始角度",
    "Align-and-sweep rate": "对齐扫描速率",
    "Determines rotation rate during align state of startup, when using align-and-sweep method": "使用对齐扫描方法时，确定启动对齐状态期间的旋转速率",
    "Align-and-sweep setup angle": "对齐扫描设置角度",
    "Determines setup angle of align-and-sweep method, to allow transients to settle prior to measurements": "确定对齐扫描方法的设置角度，以允许在测量前瞬态稳定",
    "Pullout slip threshold": "失步滑差阈值",
    "Determines rotor slip threshold used for detecting a pullout condition": "确定用于检测失步状态的转子滑差阈值",
    "Dynamic current limit": "动态电流限制",
    "Determines peak current": "确定峰值电流",
    "Determines horizon current": "确定基准电流",
    "Determines relaxation time constant": "确定松弛时间常数",
    "Determines decimation ratio": "确定抽取比",
    "Voltage control": "电压控制",
    "Low-pass filter time constant": "低通滤波器时间常数",
    "Determines q-axis low pass filter time constant": "确定 q 轴低通滤波器时间常数",
    "Proportional gain": "比例增益",
    "Determines voltage controller proportional gain": "确定电压控制器比例增益",
    "Determines voltage controller time constant": "确定电压控制器时间常数",
    "Motion Control API": "运动控制 API",
    "Filter time constant Is": "滤波时间常数 Is",
    "Determines the time constant used for calculating low pass filtered value of amplitude of current in the motor (Is)": "确定用于计算电机电流幅值 (Is) 低通滤波值的时间常数",
    "Filter time constant Iq": "滤波时间常数 Iq",
    "Determines the time constant used for calculating low pass filtered value of the measured q-axis current in the motor (Iq)": "确定用于计算电机测量 q 轴电流 (Iq) 低通滤波值的时间常数",
    "ADC ISR user functions": "ADC ISR 用户函数",
    "Determines if the ADC ISR user functions are called periodically in the MCAF ISR": "确定 ADC ISR 用户函数是否在 MCAF ISR 中周期性调用",
    "Board Service": "板级服务",
    "UI service period": "UI 服务周期",
    "Determines the rate at which the board service ISR tasks get executed.": "确定板级服务 ISR 任务的执行速率。",
    "Button debounce time": "按钮消抖时间",
    "Determines the length of time required to register a logical high signal as a button press.": "确定将逻辑高电平信号注册为按钮按下所需的时间长度。",
    "Long button press time": "长按按钮时间",
    "Determines the amount of time before a button press is detected as a long button press.": "确定按钮按下被检测为长按之前的时间量。",
    "Optional analog inputs": "可选模拟输入",
    "Bridge temperature": "桥温度",
    "Determines if the temperature bridge ADC input is sampled": "确定是否采样温度桥 ADC 输入",
    "Temperature bridge: Overtemperature threshold": "温度桥：过温阈值",
    "Determines threshold for triggering an overtemperature fault": "确定触发过温故障的阈值",
    "Temperature bridge: Time constant": "温度桥：时间常数",
    "Determines temperature low-pass filter time constant": "确定温度低通滤波器时间常数",
    "Temperature bridge: Slew rate": "温度桥：压摆率",
    "Determines temperature slew rate": "确定温度压摆率",
    "Absolute voltage reference": "绝对电压参考",
    "Determines if the absolute voltage reference ADC input is sampled": "确定是否采样绝对电压参考 ADC 输入",
    "Phase voltage: A": "相电压：A",
    "Determines if the phase A ADC input is sampled": "确定是否采样 A 相 ADC 输入",
    "Phase voltage: B": "相电压：B",
    "Determines if the phase C ADC input is sampled": "确定是否采样 C 相 ADC 输入",
    "Phase voltage: C": "相电压：C",
    "Real-time diagnostics": "实时诊断",
    "Diagnostics library": "诊断库",
    "Selects real-time diagnostics library (or \u201cNone\u201d if disabled)": "选择实时诊断库（禁用时选\u201cNone\u201d）",
    "Detailed information": "详细信息",
    "Several current measurement algorithms have been implemented for obtaining phase current measurements and adapting them for use in the feedback path of field-oriented control. Each method has different hardware requirements, and are available depending on the current measurement capability of the selected board:": "已实现多种电流测量算法用于获取相电流测量值并将其适配用于磁场定向控制的反馈通道。每种方法有不同的硬件要求，可根据所选板的电流测量能力使用：",
    "Single channel (\u201csingle-shunt\u201d)": "单通道（\u201c单分流\u201d）",
    "\u2014 requires a DC link current shunt resistor": "\u2014 需要 DC 母线电流分流电阻",
    "Dual channel (\u201cdual-shunt\u201d)": "双通道（\u201c双分流\u201d）",
    "\u2014 requires two phase current shunt resistors": "\u2014 需要两个相电流分流电阻",
    "Triple channel (\u201ctriple-shunt\u201d)": "三通道（\u201c三分流\u201d）",
    "\u2014 requires three phase current shunt resistors": "\u2014 需要三个相电流分流电阻",
    "New in version R7.": "R7 版本新增。",
    "samples the DC link current at different inverter switching states to reconstruct the three phase currents.": "在不同逆变器开关状态下采样 DC 母线电流以重建三相电流。",
    "required to measure current signal using single channel. This time is added to the PWM dead time so that": "使用单通道测量电流信号所需的时间。此时间加到 PWM 死区时间上，使得",
    "Delay between the inverter switching state and the ADC sampling point. This delay may be required to avoid ringing current signals due to the inverter switching state, which can reduce the accuracy of single channel current measurement.": "逆变器开关状态与 ADC 采样点之间的延迟。此延迟可能是为避免因逆变器开关状态导致的电流信号振铃所必需的，振铃会降低单通道电流测量的精度。",
    "One position and velocity estimator must be chosen for use in commutation and velocity feedback.": "必须选择一个位置和速度估计器用于换相和速度反馈。",
    "Available estimators as of MCAF R7:": "MCAF R7 起可用的估计器：",
    "AN1292 Phase-locked Loop (PLL)": "AN1292 锁相环 (PLL)",
    "Angle-tracking Phase-locked Loop (ATPLL)": "角度跟踪锁相环 (ATPLL)",
    "Zero-Speed / Maximum Torque (ZS/MT)": "零速/最大转矩 (ZS/MT)",
    "New in version R5.": "R5 版本新增。",
    "(Previously this choice was made on the Configure page in motorBench": "（此前此选择在 motorBench",
    "Development Suite.)": "Development Suite 的 Configure 页面中进行。）",
    "In addition to the primary estimator, additional estimators may be selected. (Only the primary estimator is used for commutation and velocity feedback.)": "除主估计器外，还可选择附加估计器。（仅主估计器用于换相和速度反馈。）",
    "Usage of more than one estimator \u2014 particularly the quadrature encoder, which has higher angle and velocity accuracy \u2014 is recommended for troubleshooting or validation purposes. Please note that this will increase CPU and memory requirements.": "建议在排查或验证时使用多个估计器——尤其是正交编码器，其具有更高的角度和速度精度。请注意，这将增加 CPU 和内存需求。",
    "New in version R4.": "R4 版本新增。",
    "was moved in MCAF R5 to the Customize page from the Configure page. It is used in MCAF in two ways:": "在 MCAF R5 中从 Configure 页面移至 Customize 页面。它在 MCAF 中有两种用途：",
    "Determines the lower limit of the adjustable velocity range": "确定可调速度范围的下限",
    "In autotuning, determines dynamics of the sensorless estimator model; stability and performance of sensorless estimators are poorer at lower velocities, so lowering the minimum velocity will generally result in a lower-bandwidth velocity control loop to ensure stability.": "在自动整定中，确定无传感器估计器模型的动态特性；无传感器估计器在低速时稳定性和性能较差，因此降低最小速度通常会导致速度控制环带宽降低以确保稳定性。",
    "was previously used as the transition velocity at motor startup. As of MCAF R7, the": "此前用作电机启动时的转换速度。自 MCAF R7 起，",
    "startup velocity": "启动速度",
    "parameter determines the transition velocity at motor startup.": "参数确定电机启动时的转换速度。",
    "Determines the transition velocity at motor startup": "确定电机启动时的转换速度",
    ", from open-loop commutation to closed-loop commutation. (Before MCAF R7, minimum velocity": "，即从开环换相到闭环换相的转换。（MCAF R7 之前，最小速度",
    "was used.) This parameter is constrained so that startup velocity": "被使用。）此参数受约束，使启动速度",
    "must be greater than or equal to minimum velocity": "必须大于或等于最小速度",
    "Increase or decrease the maximum allowed velocity command, as a ratio of nominal motor velocity. The default value is sufficient in most cases. Increasing may be appropriate for motors with a wide flux weakening range above the nominal velocity.": "增加或减少最大允许速度指令，以标称电机速度的比例表示。默认值在大多数情况下足够。对于在标称速度以上有较宽弱磁范围的电机，增加此值可能是合适的。",
    "New in version R6.": "R6 版本新增。",
    "The full-scale velocity, determined as a ratio of nominal motor velocity, controls the": "满量程速度以标称电机速度的比例确定，控制",
    "numerical representation": "数值表示",
    "of motor velocity. Increase to allow more design margin against overflow.": "。增加此值可允许更多防止溢出的设计裕量。",
    "Full-scale velocity,": "满量程速度，",
    ", is proportional to full-scale electrical frequency,": "与满量程电气频率成正比，",
    ", where": "，其中",
    "is the number of pole pairs. (See also": "为极对数。（另见",
    "Torque production and reference frames": "转矩产生与参考坐标系",
    "There are two choices for the variable that is controlled by the outer loop controller:": "外环控制器控制的变量有两个选择：",
    "Velocity": "速度",
    "Voltage": "电压",
    "The velocity controller parameters are configurable in the tuning page, while the voltage controller": "速度控制器参数可在整定页面中配置，而电压控制器",
    "parameters": "参数",
    "are configurable in the Customize page.": "可在 Customize 页面中配置。",
    "Saliency threshold": "凸极阈值",
    "Saliency ratio": "凸极比",
    "helps determine whether the full-saliency motor model is used. This is a more complicated motor model, used in certain algorithms such as the": "帮助确定是否使用全凸极电机模型。这是一个更复杂的电机模型，用于某些算法如",
    "estimator,": "估计器、",
    "MTPA": "MTPA",
    ", and": "和",
    "flux weakening": "弱磁",
    ". The full-saliency motor model takes both inductances into account, but requires slightly more computation. Since most permanent-magnet motors are non-salient,": "。全凸极电机模型考虑两个电感，但需要稍多的计算。由于大多数永磁电机是非凸极的，",
    "and the saliency can be neglected, saving CPU cycles.": "且凸极性可以忽略，从而节省 CPU 周期。",
    "This threshold sets the minimum saliency to use the full-saliency motor model. Increasing the threshold can be used to neglect saliency if the extra computation is not desirable.": "此阈值设置使用全凸极电机模型的最小凸极性。如果不需要额外计算，可增加阈值以忽略凸极性。",
    "Slew rate (max acceleration/deceleration)": "压摆率（最大加速度/减速度）",
    "Maximum acceleration (in motoring quadrants) and deceleration (in generating quadrants) can be adjusted. Increasing the slew rates will increase the motor current required during acceleration or deceleration.": "可调整最大加速度（电动象限）和最大减速度（发电象限）。增加压摆率将增加加速或减速期间所需的电机电流。",
    "Determining maximum deceleration during regeneration must be done with some care: the motor drive converts mechanical energy into electrical energy, which must go somewhere, such as a battery or a dynamic brake resistor. Without a viable outlet for that energy, the DC link voltage will rise until the motor controller detects this and shuts down, or until one of the capacitors or transistors fails and dissipates this energy destructively.": "确定再生期间的最大减速度必须谨慎：电机驱动器将机械能转化为电能，这些电能必须有去处，如电池或动态制动电阻。如果没有可行的能量出口，DC 母线电压将上升，直到电机控制器检测到并关断，或者某个电容或晶体管故障并以破坏性方式耗散这些能量。",
    "The controlled d-axis and q-axis currents may have a fixed limit, or the limit may change based on the motor current if short higher-current transients are desired. Two options are available for dynamic current limit:": "受控的 d 轴和 q 轴电流可以有固定限值，如果需要短时高电流瞬态，限值也可根据电机电流变化。动态电流限制有两个选项：",
    "None": "None",
    "Simple": "Simple",
    "There are three stopping modes in MCAF that affect the": "MCAF 中有三种停止模式影响",
    "motor stopping behavior": "电机停止行为",
    "in the": "在",
    "state.": "状态中的。",
    "Minimal-impact PWM": "最小影响 PWM",
    "\u2014 Phase currents quickly reach zero. Does not allow estimators to operate during stopping.": "\u2014 相电流迅速降至零。不允许估计器在停止期间运行。",
    "Closed-loop current": "闭环电流",
    "\u2014 Controls the q-axis current to zero. Allows estimators to operate during stopping.": "\u2014 控制 q 轴电流至零。允许估计器在停止期间运行。",
    "Closed-loop velocity": "闭环速度",
    "\u2014 Controls the velocity to zero. Allows estimators to operate during stopping.": "\u2014 控制速度至零。允许估计器在停止期间运行。",
    "Speed and time thresholds": "速度和时间阈值",
    "There are two closed-loop stopping parameters used to define the condition at which the motor is considered stopped, before the state machine transitions from the": "有两个闭环停止参数用于定义电机被认为停止的条件，在状态机从",
    "state to the": "状态转换到",
    "Time threshold": "时间阈值",
    "For a transition from": "从",
    "to": "到",
    ", the motor speed must fall and remain below the speed threshold for at least the time threshold. This implementation is to avoid short speed transients below the speed threshold causing a false motor stop.": "的转换，电机速度必须下降并保持在速度阈值以下至少持续时间阈值。此实现是为了避免速度阈值以下的短时速度瞬态导致误停止。",
    "shows an example with the speed threshold set to 75 RPM and the time threshold set to 1.0 s. The state machine transitions to STOPPED only when the time threshold has fully elapsed while the motor speed remains below the speed threshold.": "显示了一个示例，速度阈值设为 75 RPM，时间阈值设为 1.0 s。状态机仅在时间阈值完全经过且电机速度仍低于速度阈值时才转换为 STOPPED。",
    "State machine transition from STOPPING to STOPPED with closed-loop stopping active.": "闭环停止激活时从 STOPPING 到 STOPPED 的状态机转换。",
    "Coastdown parameters": "惯性减速参数",
    "With": "当",
    "the stopping mode set to minimal-impact PWM": "停止模式设为最小影响 PWM",
    ", there are two interrelated coastdown parameters used to estimate the time required to bring the motor to a stop, before it can be safely restarted:": "时，有两个相关的惯性减速参数用于估计使电机停止所需的时间，然后才能安全重启：",
    "velocity threshold": "速度阈值",
    "time": "时间",
    "The resulting coastdown time is used in the": "产生的惯性减速时间用于",
    "state": "状态",
    "before proceeding to the": "在进入",
    "See the section on": "参见",
    "flux control": "磁通控制",
    "for more information.": "节以获取更多信息。",
    "Selects which": "选择使用哪种",
    "method is used, from among the following:": "方法，从以下选项中：",
    "\u201cNone\u201d \u2014 d-axis reference current will be set to zero": "\u201cNone\u201d——d 轴参考电流将设为零",
    "\u201cEquation-based\u201d \u2014 determines d-axis reference current from the": "\u201c基于方程\u201d——从",
    "algorithms": "算法确定 d 轴参考电流",
    "Rectangular type sets d-axis and q-axis current limits independently. Quadratic type sets the q-axis limit based on a quadratic approximation of a circular function.": "矩形类型独立设置 d 轴和 q 轴电流限值。二次类型基于圆形函数的二次近似设置 q 轴限值。",
    "See also": "另见",
    "Calculation of q-axis current limit": "q 轴电流限值的计算",
    "The d-axis current is normalized to maximum current Imax, where Imax = minimum of motor and drive continuous current ratings. It is recommended to set the current limit below the demagnetizing current of the motor.": "d 轴电流归一化到最大电流 Imax，其中 Imax = 电机和驱动器连续电流额定值的最小值。建议将电流限值设在电机去磁电流以下。",
    "The q-axis current limit is allocated as a fraction of current limit Imax, where Imax = minimum of motor and drive continuous current ratings. This is applicable only when rectangular boundary type is enabled.": "q 轴电流限值分配为电流限值 Imax 的一部分，其中 Imax = 电机和驱动器连续电流额定值的最小值。仅在启用矩形边界类型时适用。",
    "This parameter determines if flux weakening is enabled.": "此参数确定是否启用弱磁。",
    "Flux weakening: voltage limit": "弱磁：电压限值",
    "The voltage amplitude limit used in": "中使用的电压幅值限值",
    "(FW) is normalized to DC link voltage. D-axis current is computed so that the steady-state voltage requirements do not exceed this circular limit. Ideally a limit is chosen so that the motor enters FW operation just before entering": "(FW) 归一化到 DC 母线电压。计算 d 轴电流使稳态电压需求不超过此圆形限值。理想情况下选择限值使电机在进入",
    "overmodulation": "过调制",
    ". Higher limits may prevent the motor from entering FW region. Lower limits guarantee FW operation, at the cost of extra power dissipation.": "之前刚好进入 FW 运行。较高的限值可能阻止电机进入 FW 区域。较低的限值保证 FW 运行，但代价是额外的功率耗散。",
    "This parameter determines if MTPA is enabled.": "此参数确定是否启用 MTPA。",
    "MTPA display calculations": "MTPA 显示计算",
    "does not have any user-configurable parameters, but does include two display values for indication only:": "没有任何用户可配置参数，但包含两个仅用于指示的显示值：",
    "\u2014 displays the maximum d-axis current reference that can occur from MTPA": "\u2014 显示 MTPA 可能产生的最大 d 轴电流参考",
    "\u2014 displays the maximum torque gain that can occur from the use of MTPA, relative to the maximum torque with MTPA disabled (": "\u2014 显示使用 MTPA 可能产生的最大转矩增益，相对于 MTPA 禁用时的最大转矩（",
    ").": "）。",
    "Both are generally very small, except for motors that have significant rotor saliency and high flux utilization. The saliency flux utilization coefficient": "两者通常都很小，除非电机具有显著的转子凸极性和高磁通利用率。凸极磁通利用系数",
    "is a metric of rotor saliency and flux utilization, and represents how much change in air-gap flux can occur, relative to the permanent magnet flux.": "是转子凸极性和磁通利用率的度量，表示气隙磁通相对于永磁体磁通可以发生多少变化。",
    "The maximum d-axis current and maximum torque gain are approximately proportional to": "最大 d 轴电流和最大转矩增益大致与",
    ", so doubling the overall current capability": "成正比，因此将总电流能力加倍",
    "roughly quadruples both the d-axis current requested by MPTA and the contribution of MTPA towards torque.": "大致使 MTPA 请求的 d 轴电流和 MTPA 对转矩的贡献翻两番。",
    "dead-time compensation": "死区补偿",
    "\u201cNone\u201d \u2014 no dead-time compensation is required": "\u201cNone\u201d——不需要死区补偿",
    "\u201cPer-phase\u201d \u2014 uses the": "\u201c逐相\u201d——使用",
    "per-phase dead-time compensation algorithm": "逐相死区补偿算法",
    "Determines the maximum amplitude": "确定最大幅值",
    "for which a linear range of current is used in calculating unit disturbance signals": "用于计算单位扰动信号的电流线性范围",
    "\u2014 see": "\u2014 见",
    "per-phase dead-time compensation": "逐相死区补偿",
    "and the": "和",
    "current linearity range": "电流线性范围",
    "Determines the dead-time compensation gain used in the forward path to mitigate the effects of dead time distortion at high electrical frequencies. Unless this type of dead-time compensation is tested carefully with a specific motor, the default value of zero is recommended. See": "确定前向通道中用于减轻高电气频率下死区失真影响的死区补偿增益。除非此类型死区补偿已用特定电机仔细测试，否则建议使用默认值零。见",
    "forward-path gain": "前向通道增益",
    "Determines the dead-time compensation gain used in the feedback path to mitigate the effects of dead time distortion on sensorless estimators at low speeds. Increasing this gain will generally improve sensorless estimator performance at low speeds, but excessive gain may cause the current command to jump to its positive limit. See": "确定反馈通道中用于减轻低速下死区失真对无传感器估计器影响的死区补偿增益。增加此增益通常会改善低速下无传感器估计器的性能，但过大的增益可能导致电流指令跳变到正限值。见",
    "feedback-path gain": "反馈通道增益",
    "Determines the point at which the motor controller shuts down due to insufficient available voltage below its minimum operating voltage.": "确定电机控制器因可用电压低于最小工作电压而关断的点。",
    "Determines the point at which the motor controller shuts down due to excessive voltage above its maximum operating voltage.": "确定电机控制器因电压超过最大工作电压而关断的点。",
    "Determines if the": "确定",
    "state machine": "状态机",
    "enters the FAULT state due to a": "是否因",
    "stall detect": "堵转检测",
    "condition. Disabling the stall detect feature will exclude stall detect algorithms from the project build, reducing average CPU usage and memory requirements. Prior to MCAF R7, stall detection was enabled by default and not controllable through the Customize page.": "条件而进入 FAULT 状态。禁用堵转检测功能将从项目构建中排除堵转检测算法，降低平均 CPU 使用率和内存需求。MCAF R7 之前，堵转检测默认启用且不可通过 Customize 页面控制。",
    "The": "The",
    "startup sequence": "启动序列",
    "has numerous parameters that can be modified. These are shown in": "有多个可修改的参数。这些如",
    "Graph of current and electrical frequency in startup sequence. (The Weathervane startup algorithm is shown.)": "启动序列中的电流和电气频率图。（所示为 Weathervane 启动算法。）",
    "Startup current amplitude": "启动电流幅值",
    "represents a tradeoff between making startup robust (higher is better) and reducing power dissipation in the motor (lower is better). There\u2019s not much value in reducing it below 0.5, which specifies half of maximum continuous current.": "代表启动鲁棒性（越高越好）与降低电机功率耗散（越低越好）之间的权衡。将其降至 0.5 以下没有太大意义，0.5 指定最大连续电流的一半。",
    "Current rampup time": "电流斜坡上升时间",
    "affects only the initial state of startup, in which current increases from zero to its maximum amplitude. The current rampup time should be slow compared to": "仅影响启动的初始状态，其中电流从零增加到最大幅值。电流斜坡上升时间应比",
    ", so that it represents a smooth transition, but fast compared to the overall startup time.": "慢，以代表平滑过渡，但比整体启动时间快。",
    "Some motors, especially those with large inertia and cogging torque, may start more reliably with align time": "某些电机，特别是具有大惯性和齿槽转矩的电机，可能通过对齐时间",
    ". The default value of zero is sufficient in most cases.": "更可靠地启动。默认值零在大多数情况下足够。",
    "Increase the minimum acceleration time": "增加最小加速时间",
    "if a slower, less-aggressive startup is desired.": "如果需要更慢、更温和的启动。",
    "Increase or decrease the acceleration rate": "增加或减少加速率",
    "to control the faster second phase of acceleration. Slower acceleration is generally less prone to cycle slips, but takes longer.": "以控制较快的第二加速阶段。较慢的加速通常不容易发生周期滑移，但耗时更长。",
    "to control the slower first phase of acceleration. (Note: this is normalized to": "以控制较慢的第一加速阶段。（注：此值归一化到",
    ".) Slower acceleration is generally less prone to cycle slips, but takes longer.": "。）较慢的加速通常不容易发生周期滑移，但耗时更长。",
    "The hold time": "保持时间",
    "controls how long the startup sequence remains in the": "控制启动序列在",
    "state where electrical frequency and current are both held constant before transitioning to closed-loop commutation.": "状态中停留的时间，在该状态下电气频率和电流均保持恒定，然后转换到闭环换相。",
    "A value of zero is fine in most cases.": "在大多数情况下零值即可。",
    "Decreasing the velocity threshold": "降低速度阈值",
    "will switch to the faster second phase of acceleration sooner.": "将更早切换到较快的第二加速阶段。",
    "(Note that the threshold": "（注意，阈值",
    "is determined by the": "由",
    "minimum velocity setting": "最小速度设置",
    "under Operating parameters.)": "下的设置确定。）",
    "The angle converge rate controls how fast the transition from open-loop to closed-loop commutation with the": "角度收敛速率控制使用",
    "Classic": "Classic",
    "startup method.": "启动方法时从开环到闭环换相的过渡速度。",
    "Some motors may require a lower value to ensure a smooth transition to closed-loop commutation, typically in the range of 0.1\u00b0/ms \u2013 1.0\u00b0/ms.": "某些电机可能需要较低的值以确保平滑过渡到闭环换相，通常在 0.1\u00b0/ms–1.0\u00b0/ms 范围内。",
    "is the algorithm provided in MCAF R1 \u2013 R3.": "是 MCAF R1–R3 中提供的算法。",
    "Weathervane": "Weathervane",
    "transitions to closed-loop more quickly than the Classic algorithm, and was added in R4.": "比 Classic 算法更快地过渡到闭环，在 R4 中添加。",
    "ZS/MT + Initial position correction": "ZS/MT + 初始位置校正",
    "was added in MCAF R7, and is required by the": "在 MCAF R7 中添加，且为",
    "ZS/MT estimator": "ZS/MT 估计器",
    "See": "见",
    "choice of startup method": "启动方法的选择",
    "Controls the amplitude of active damping": "控制主动阻尼的幅值",
    ". Reduce this value if startup is noisy or unstable. Set to zero to eliminate active damping completely.": "。如果启动噪声大或不稳定，请减小此值。设为零以完全消除主动阻尼。",
    "Controls the feedback gain of active damping. Reduce this value if startup is noisy or unstable.": "控制主动阻尼的反馈增益。如果启动噪声大或不稳定，请减小此值。",
    "Determines the minimum velocity to enable active damping. Make sure to choose a velocity where the estimator is stable enough to be useful for active damping.": "确定启用主动阻尼的最小速度。确保选择估计器足够稳定可用于主动阻尼的速度。",
    "Determines the maximum d-axis voltage. Leaving this at 1.0 is recommended.": "确定最大 d 轴电压。建议保持 1.0。",
    "Determines the maximum q-axis voltage. A value between 1.05 and 1.25 is recommended. Larger values will allow higher output voltage amplitude, at the cost of higher distortion in output voltage and current.": "确定最大 q 轴电压。建议值在 1.05 到 1.25 之间。较大的值允许更高的输出电压幅值，但代价是输出电压和电流的失真更高。",
    "The section on": "关于",
    "overmodulation behavior in the synchronous frame": "同步坐标系中的过调制行为",
    "has more information on this subject.": "节有更多关于此主题的信息。",
    "Determines whether duty cycle feedback for active estimators is obtained after zero sequence modulation (ZSM) and clipping due to": "确定活动估计器的占空比反馈是在零序调制 (ZSM) 和因",
    ". If not selected, duty cycle feedback will be obtained before ZSM and clipping.": "削波之后获取。如果未选中，占空比反馈将在 ZSM 和削波之前获取。",
    "Determines the time constant": "确定时间常数",
    "used for velocity estimation. This does not affect estimator stability, but it does impact the velocity control loop performance. Lower values of time constant let more noise through, but allow higher-bandwidth velocity loops. Higher values of time constant filter out more noise, but reduce the achievable velocity loop bandwidth.": "用于速度估计。这不影响估计器稳定性，但影响速度控制环性能。较低的时间常数值允许更多噪声通过，但允许更高带宽的速度环。较高的时间常数值滤除更多噪声，但降低可实现的速度环带宽。",
    "Determines the loop filter bandwidth": "确定环路滤波器带宽",
    "used for angle estimation in the PLL. (Note: this is a different value than the startup velocity, also called": "用于 PLL 中的角度估计。（注：此值与启动速度不同，也称为",
    "Leaving this value at its default is recommended.": "建议保持默认值。",
    "Determines the maximum velocity for slow filtering in the PLL estimator. Leaving this value at its default is recommended.": "确定 PLL 估计器中慢速滤波的最大速度。建议保持默认值。",
    "quadrature encoder support": "正交编码器支持",
    "This should match the number of lines, or cycles per revolution (CPR), listed in the datasheet of the motor or encoder. The number of counts per revolution is 4\u00d7 the number of lines.": "应与电机或编码器数据手册中列出的线数或每转周期数 (CPR) 匹配。每转计数数为线数的 4 倍。",
    "Select this option if an index pulse signal is present.": "如果存在索引脉冲信号，请选择此选项。",
    "Values in the 1 ms \u2013 10 ms range are recommended. Smaller values will increase estimator bandwidth but allow more encoder quantization noise to appear in the velocity estimate. Larger values will decrease estimator bandwidth, along with the achievable velocity loop bandwidth, but will decrease the effect of encoder quantization noise.": "建议值在 1 ms–10 ms 范围内。较小的值将增加估计器带宽，但允许更多编码器量化噪声出现在速度估计中。较大的值将降低估计器带宽和可实现的速度环带宽，但会降低编码器量化噪声的影响。",
    "Note:": "注：",
    "With MCAF R4, out-of-range errors in code generation will occur for certain combinations of motors with low speed ratings, and choices of tracking loop time constant. This is expected when": "在 MCAF R4 中，对于低速电机和跟踪环路时间常数的某些组合，代码生成会出现超范围错误。这在",
    "where": "时是预期的，其中",
    "is the rated motor velocity in rad/s, and": "为额定电机速度（rad/s），",
    "is the tracking loop time constant. A viable workaround in most cases is to increase the tracking loop time constant, though this would reduce the velocity loop bandwidth.": "为跟踪环路时间常数。在大多数情况下，可行的解决方法是增加跟踪环路时间常数，但这会降低速度环带宽。",
    "For example, a motor with rated velocity of 2000 RPM \u2248 209 rad/s is likely to have out-of-range errors if the tracking loop time constant is less than approximately": "例如，额定速度为 2000 RPM \u2248 209 rad/s 的电机，如果跟踪环路时间常数小于约",
    "s or 1.9 ms.": "s 或 1.9 ms，则可能出现超范围错误。",
    "Align \u2014 best general-purpose synchronization method, fastest, sensitive to large cogging torque": "对齐——最佳通用同步方法，最快，对大齿槽转矩敏感",
    "Pullout \u2014 most immune to cogging torque, sensitive to high inertia": "失步——对齿槽转矩最不敏感，对大惯性敏感",
    "Align-and-sweep \u2014 slow, best accuracy": "对齐扫描——慢，精度最佳",
    "This determines the align time used for back-emf synchronization. Systems with larger inertia may need longer times. Shorter times (less than 0.5 s) may be adequate for very low inertia systems.": "确定用于反电动势同步的对齐时间。较大惯性的系统可能需要更长的时间。较短的时间（小于 0.5 s）对于极低惯性系统可能足够。",
    "Increase this angle for systems with high cogging torque. Values of 30\u00b0 \u2013 60\u00b0 are recommended.": "对于高齿槽转矩的系统，请增加此角度。建议值为 30\u00b0–60\u00b0。",
    "Controls the initial electrical angle used during the rampup state of startup. Some angles may be slightly more robust, but this must be determined empirically for a particular motor.": "控制启动斜坡上升状态期间使用的初始电气角度。某些角度可能略微更鲁棒，但必须针对特定电机通过实验确定。",
    "4 counts per ISR is the fastest, and is adequate for most motors with low cogging torque. Decrease this value for motors with high cogging torque.": "每 ISR 4 计数是最快的，适用于大多数低齿槽转矩的电机。对于高齿槽转矩的电机，请减小此值。",
    "This controls the setup angle prior to making commutation offset measurements. Smaller values may not leave enough time for transients to settle. Larger values will add more time for transients to settle. Increasing it for high-inertia systems may improve accuracy.": "控制进行换相偏移测量之前的设置角度。较小的值可能没有足够时间让瞬态稳定。较大的值会增加瞬态稳定时间。对于高惯性系统，增加此值可能提高精度。",
    "This parameter controls the slip at which pullout offset is measured for determining commutation offset. Slip here is defined as the rate of change of difference in the angle of the stationary frame voltage vector": "此参数控制测量失步偏移以确定换相偏移时的滑差。此处滑差定义为静止坐标系电压矢量角度与编码器原始电气位置之间差值的变化率",
    "and the raw electrical position from the encoder. Good choices for this parameter depend on the motor\u2019s mechanical properties, namely inertia": "。此参数的良好选择取决于电机的机械特性，即惯性",
    ", viscous damping": "、粘性阻尼",
    ", and friction torque": "和摩擦转矩",
    ". The slip threshold may need to be increased for motors with low inertia, or decreased for motors with higher inertia. The recommended range for slip threshold is approximately 0.059 to 0.47 rad/s. (0.5\u00d7 to 4\u00d7 the default value)": "。对于低惯性电机，滑差阈值可能需要增加；对于高惯性电机，可能需要减小。滑差阈值的推荐范围约为 0.059 到 0.47 rad/s。（默认值的 0.5 倍到 4 倍）",
    "The following parameters control the behavior of the simple dynamic current limit algorithm. See the section on": "以下参数控制简单动态电流限制算法的行为。参见",
    "dynamic current limit": "动态电流限制",
    "Peak current \u2014 Determines the absolute peak current": "峰值电流——确定绝对峰值电流",
    "Horizon current \u2014 Determines the horizon current": "基准电流——确定基准电流",
    "used in the simple dynamic current limit algorithm. The current limit relaxes to the horizon current.": "用于简单动态电流限制算法。电流限制松弛到基准电流。",
    "Time constant \u2014 Relaxation time constant": "时间常数——松弛时间常数",
    "that determines how fast the current limit relaxes to the horizon current.": "确定电流限制松弛到基准电流的速度。",
    "Decimation ratio \u2014 Determines the decimation ratio": "抽取比——确定抽取比",
    "for executing dynamic current limit algorithm every": "用于每",
    "samples of the current control loop.": "个电流控制环样本执行一次动态电流限制算法。",
    "for the first-order low-pass filter used to attenuate noise from the output of the current controller": "用于衰减电流控制器输出噪声的一阶低通滤波器",
    "used in the outer loop controller when voltage is the controlled variable. This parameter must be tuned manually; see the section on": "在外环控制器中当电压为受控变量时使用。此参数必须手动整定；参见",
    "voltage control": "电压控制",
    "for guidance.": "节以获取指导。",
    "used in the outer loop controller when voltage is the controlled variable. This parameter sets the": "在外环控制器中当电压为受控变量时使用。此参数设置",
    "gain of the voltage controller using": "电压控制器的增益，使用",
    ". This parameter must be tuned manually; see the section on": "。此参数必须手动整定；参见",
    "Values of the order of 0.1ms \u2013 10ms are recommended. Higher time constant values reduce noise in the Is signal that is made available through": "建议值在 0.1ms–10ms 量级。较高的时间常数值减少通过",
    "MCAPI": "MCAPI",
    "at the cost of adding some phase delay compared to the sampled value of Is in MCAF.": "可用的 Is 信号中的噪声，但与 MCAF 中 Is 的采样值相比会增加一些相位延迟。",
    "Values of the order of 0.1ms \u2013 10ms are recommended. Higher time constant values reduce noise in the Iq signal that is made available through": "建议值在 0.1ms–10ms 量级。较高的时间常数值减少通过",
    "at the cost of adding some phase delay compared to the sampled value of Iq in MCAF.": "可用的 Iq 信号中的噪声，但与 MCAF 中 Iq 的采样值相比会增加一些相位延迟。",
    "Determines if the user-defined functions": "确定用户定义函数",
    "are called at the beginning and end, respectively, of every MCAF ISR. These functions are defined in": "是否分别在每次 MCAF ISR 的开始和结束时调用。这些函数定义在",
    "with the \u201cweak\u201d attribute, and can be redefined by user-written code for purposes such as functional safety.": "中，带有\u201cweak\u201d属性，可由用户编写的代码重新定义，用于功能安全等目的。",
    "Board service": "板级服务",
    "Determines the rate at which board service ISR tasks get executed. For further information on board service module please refer to": "确定板级服务 ISR 任务的执行速率。有关板级服务模块的更多信息，请参阅",
    "board service module": "板级服务模块",
    "This parameter determines the amount of time a logical high signal needs to stay high until it is registered as a button press.": "此参数确定逻辑高电平信号需要保持高电平多长时间才能被注册为按钮按下。",
    "The amount of time it takes for a button press to be registered as a long button press. Increasing this value increases the length of time before a button is recognized as a long button press.": "按钮按下被注册为长按所需的时间。增加此值会增加按钮被识别为长按之前的时间长度。",
    "Optional analog inputs, for signals such as phase voltages and absolute reference voltage, are available for sampling on some boards. The optional analog input selection in the Customize page will be limited by the selected board.": "可选模拟输入（如相电压和绝对参考电压等信号）在某些板上可用于采样。Customize 页面中的可选模拟输入选择受所选板的限制。",
    "Analog input for sampling the voltage output of the temperature sensor, if available. The temperature sampled from this input is used for triggering an overtemperature fault. There are three parameters associated with this analog input:": "用于采样温度传感器电压输出的模拟输入（如有）。从此输入采样的温度用于触发过温故障。此模拟输入有三个相关参数：",
    "Overtemperature threshold \u2014 Determines the temperature at which the overtemperature fault will occur": "过温阈值——确定过温故障发生的温度",
    "Time constant \u2014 Low-pass filter time constant for attenuating the temperature signal": "时间常数——用于衰减温度信号的低通滤波器时间常数",
    "Slew rate \u2014 Maximum slew rate of the temperature signal, used for voltage spike rejection": "压摆率——温度信号的最大压摆率，用于电压尖峰抑制",
    "temperature measurement": "温度测量",
    "Analog input for sampling the absolute voltage reference of the board, if available.": "用于采样板级绝对电压参考的模拟输入（如有）。",
    "Phase voltages": "相电压",
    "Analog inputs for sampling the voltages on phases A, B, and C, if available.": "用于采样 A、B、C 相电压的模拟输入（如有）。",
    "diagnostic kernel": "诊断内核",
    "library is used, from among the following:": "库，从以下选项中：",
    "X2Cscope": "X2Cscope",
    "None \u2014 Disables real-time diagnostics": "None——禁用实时诊断",
    "New in version R8.": "R8 版本新增。",
    "6.3. Parameter customization": "6.3. 参数定制",
    "6.3.1. Summary": "6.3.1. 摘要",
    "6.3.2. Detailed information": "6.3.2. 详细信息",
    "6.3.2.1. Current measurement": "6.3.2.1. 电流测量",
    "6.3.2.1.1. Single channel": "6.3.2.1.1. 单通道",
    "6.3.2.1.1.1. Minimum time window": "6.3.2.1.1.1. 最小时间窗口",
    "6.3.2.1.1.2. ADC trigger delay": "6.3.2.1.1.2. ADC 触发延迟",
    "6.3.2.2. Estimators": "6.3.2.2. 估计器",
    "6.3.2.2.1. Primary estimator": "6.3.2.2.1. 主估计器",
    "6.3.2.2.2. Active estimators": "6.3.2.2.2. 活动估计器",
    "6.3.2.3. Operating parameters": "6.3.2.3. 运行参数",
    "6.3.2.3.1. Minimum velocity": "6.3.2.3.1. 最小速度",
    "6.3.2.3.2. Startup velocity": "6.3.2.3.2. 启动速度",
    "6.3.2.3.3. Maximum velocity": "6.3.2.3.3. 最大速度",
    "6.3.2.3.4. Full-scale velocity": "6.3.2.3.4. 满量程速度",
    "6.3.2.3.5. Outer loop controller": "6.3.2.3.5. 外环控制器",
    "6.3.2.3.6. Saliency threshold": "6.3.2.3.6. 凸极阈值",
    "6.3.2.3.7. Slew rate (max acceleration/deceleration)": "6.3.2.3.7. 压摆率（最大加速度/减速度）",
    "6.3.2.3.8. Dynamic current limit type": "6.3.2.3.8. 动态电流限制类型",
    "6.3.2.3.9. Closed-loop stopping": "6.3.2.3.9. 闭环停止",
    "6.3.2.3.9.1. Speed and time thresholds": "6.3.2.3.9.1. 速度和时间阈值",
    "6.3.2.3.10. Coastdown parameters": "6.3.2.3.10. 惯性减速参数",
    "6.3.2.4. Flux control": "6.3.2.4. 磁通控制",
    "6.3.2.4.1. Flux control method": "6.3.2.4.1. 磁通控制方法",
    "6.3.2.4.2. Current limit: Boundary type": "6.3.2.4.2. 电流限制：边界类型",
    "6.3.2.4.3. Current limit: Idmax": "6.3.2.4.3. 电流限制：Idmax",
    "6.3.2.4.4. Current limit: Iqmax": "6.3.2.4.4. 电流限制：Iqmax",
    "6.3.2.4.5. Flux weakening: enable": "6.3.2.4.5. 弱磁：启用",
    "6.3.2.4.6. Flux weakening: voltage limit": "6.3.2.4.6. 弱磁：电压限值",
    "6.3.2.4.7. MTPA: Enable": "6.3.2.4.7. MTPA：启用",
    "6.3.2.4.8. MTPA display calculations": "6.3.2.4.8. MTPA 显示计算",
    "6.3.2.5. Dead-time compensation": "6.3.2.5. 死区补偿",
    "6.3.2.5.1. Dead-time compensation method": "6.3.2.5.1. 死区补偿方法",
    "6.3.2.5.2. Current linearity range": "6.3.2.5.2. 电流线性范围",
    "6.3.2.5.3. Forward gain": "6.3.2.5.3. 前向增益",
    "6.3.2.5.4. Feedback gain": "6.3.2.5.4. 反馈增益",
    "6.3.2.6. Fault detection": "6.3.2.6. 故障检测",
    "6.3.2.6.1. Undervoltage margin": "6.3.2.6.1. 欠压裕量",
    "6.3.2.6.2. Overvoltage margin": "6.3.2.6.2. 过压裕量",
    "6.3.2.6.3. Stall detect: enable": "6.3.2.6.3. 堵转检测：启用",
    "6.3.2.7. Startup": "6.3.2.7. 启动",
    "6.3.2.7.1. Startup current": "6.3.2.7.1. 启动电流",
    "6.3.2.7.2. Rampup time": "6.3.2.7.2. 斜坡上升时间",
    "6.3.2.7.3. Align time": "6.3.2.7.3. 对齐时间",
    "6.3.2.7.4. Min accel time": "6.3.2.7.4. 最小加速时间",
    "6.3.2.7.5. Acceleration": "6.3.2.7.5. 加速度",
    "6.3.2.7.6. Acceleration": "6.3.2.7.6. 加速度",
    "6.3.2.7.7. Hold time": "6.3.2.7.7. 保持时间",
    "6.3.2.7.8. Speed threshold": "6.3.2.7.8. 速度阈值",
    "6.3.2.7.9. Angle converge rate": "6.3.2.7.9. 角度收敛速率",
    "6.3.2.7.10. Startup algorithm": "6.3.2.7.10. 启动算法",
    "6.3.2.7.11. Active damping: max amplitude": "6.3.2.7.11. 主动阻尼：最大幅值",
    "6.3.2.7.12. Active damping: max gain": "6.3.2.7.12. 主动阻尼：最大增益",
    "6.3.2.7.13. Active damping: speed threshold": "6.3.2.7.13. 主动阻尼：速度阈值",
    "6.3.2.8. Overmodulation": "6.3.2.8. 过调制",
    "6.3.2.8.1. D-axis limit": "6.3.2.8.1. d 轴限值",
    "6.3.2.8.2. Q-axis limit": "6.3.2.8.2. q 轴限值",
    "6.3.2.8.3. Duty cycle feedback with clipping": "6.3.2.8.3. 带削波的占空比反馈",
    "6.3.2.9. AN1292 PLL": "6.3.2.9. AN1292 PLL",
    "6.3.2.9.1. Time constant": "6.3.2.9.1. 时间常数",
    "6.3.2.9.2. Loop filter bandwidth": "6.3.2.9.2. 环路滤波器带宽",
    "6.3.2.9.3. Filter threshold": "6.3.2.9.3. 滤波器阈值",
    "6.3.2.10. Quadrature encoder": "6.3.2.10. 正交编码器",
    "6.3.2.10.1. Lines": "6.3.2.10.1. 线数",
    "6.3.2.10.2. Index pulse present": "6.3.2.10.2. 存在索引脉冲",
    "6.3.2.10.3. Tracking loop time constant": "6.3.2.10.3. 跟踪环路时间常数",
    "6.3.2.10.4. Synchronization method": "6.3.2.10.4. 同步方法",
    "6.3.2.10.5. Align time": "6.3.2.10.5. 对齐时间",
    "6.3.2.10.6. Align angle shift": "6.3.2.10.6. 对齐角度偏移",
    "6.3.2.10.7. Align initial angle": "6.3.2.10.7. 对齐初始角度",
    "6.3.2.10.8. Align-and-sweep rate": "6.3.2.10.8. 对齐扫描速率",
    "6.3.2.10.9. Align-and-sweep setup angle": "6.3.2.10.9. 对齐扫描设置角度",
    "6.3.2.10.10. Pullout slip threshold": "6.3.2.10.10. 失步滑差阈值",
    "6.3.2.11. Dynamic current limit": "6.3.2.11. 动态电流限制",
    "6.3.2.12. Voltage control": "6.3.2.12. 电压控制",
    "6.3.2.12.1. Low-pass filter time constant": "6.3.2.12.1. 低通滤波器时间常数",
    "6.3.2.12.2. Proportional gain": "6.3.2.12.2. 比例增益",
    "6.3.2.12.3. Time constant": "6.3.2.12.3. 时间常数",
    "6.3.2.13. Motion Control API": "6.3.2.13. 运动控制 API",
    "6.3.2.13.1. Filter time constant Is": "6.3.2.13.1. 滤波时间常数 Is",
    "6.3.2.13.2. Filter time constant Iq": "6.3.2.13.2. 滤波时间常数 Iq",
    "6.3.2.13.3. ADC ISR user functions": "6.3.2.13.3. ADC ISR 用户函数",
    "6.3.2.14. Board service": "6.3.2.14. 板级服务",
    "6.3.2.14.1. UI service period": "6.3.2.14.1. UI 服务周期",
    "6.3.2.14.2. Button debounce time": "6.3.2.14.2. 按钮消抖时间",
    "6.3.2.14.3. Long button press time": "6.3.2.14.3. 长按按钮时间",
    "6.3.2.15. Optional analog inputs": "6.3.2.15. 可选模拟输入",
    "6.3.2.15.1. Bridge temperature": "6.3.2.15.1. 桥温度",
    "6.3.2.15.2. Absolute voltage reference": "6.3.2.15.2. 绝对电压参考",
    "6.3.2.15.3. Phase voltages": "6.3.2.15.3. 相电压",
    "6.3.2.16. Diagnostics library": "6.3.2.16. 诊断库",
    "Code Generation": "代码生成",
    "Sampling Rate and PWM Frequency Implications": "采样率与 PWM 频率的影响",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
