# -*- coding: utf-8 -*-
import txutil

rel = "implementation/codegen"
title_zh = "6.2. 代码生成"

m = {
    "6.2. Code Generation — MCAF R9 RC31 文档 (docver 9.0.1)": "6.2. 代码生成 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Code Generation": "代码生成",
    "Relationship with motorBench": "与 motorBench 的关系",
    "Development Suite and MCC": "Development Suite 和 MCC",
    "Code Configurator (MCC) can be used with motorBench": "Code Configurator (MCC) 可作为 MCC 的插件库与 motorBench",
    "Development Suite as a plugin library for MCC. Each version of motorBench": "Development Suite 一起使用。每个版本的 motorBench",
    "Development Suite contains a firmware package which allows generation of a particular version of MCAF.": "Development Suite 都包含一个固件包，用于生成特定版本的 MCAF。",
    "Since": "自",
    ", all peripheral and system initialization code is produced by MCC, not MCAF. The only exception to this is the": "起，所有外设和系统初始化代码均由 MCC 而非 MCAF 生成。唯一的例外是",
    "peripheral, which is not supported by MCC yet for dsPIC33E devices, and requires setting certain peripheral, oscillator, and configuration settings in MCC. See the motorBench": "外设，MCC 尚不支持 dsPIC33E 器件的该外设，需要在 MCC 中设置某些外设、振荡器和配置选项。详见 motorBench",
    "Development Suite help documentation and release notes for more information.": "Development Suite 帮助文档和发行说明以获取更多信息。",
    ", the": "，",
    "peripheral is also included in peripheral and system initialization code produced by MCC Melody. MCAF is no longer responsible for the generation of any peripheral and/or system initialization code. This way MCAF can leverage MCC Melody to broaden its support for devices and hardware. MCC Classic (required for 33EP devices) does not support the": "外设也包含在 MCC Melody 生成的外设和系统初始化代码中。MCAF 不再负责生成任何外设和/或系统初始化代码。这样 MCAF 可以利用 MCC Melody 来扩大对器件和硬件的支持。MCC Classic（33EP 器件所需）不支持",
    "peripheral, so MCAF provides an appropriate implementation in place of code generation for this device.": "外设，因此 MCAF 为该器件提供了适当的实现以替代代码生成。",
    "Configurable parameters": "可配置参数",
    "Generated files in the": "生成的文件位于",
    "directory contain configurable parameters that are computed from information entered or derived in motorBench": "目录中，包含根据 motorBench",
    "Development Suite and MPLAB": "Development Suite 和 MPLAB",
    "Code Configurator.": "Code Configurator 中输入或推导的信息计算得出的可配置参数。",
    "Microchip is investigating methods of making these parameter calculations more transparent and more easily manipulated if necessary.": "Microchip 正在研究使这些参数计算更加透明、更易于在必要时调整的方法。",
    "A full table of configurable parameters is given in the file": "完整的可配置参数表见文件",
    "which looks somewhat like the following excerpt:": "，其内容类似以下摘录：",
    "Key": "键",
    "Symbol": "符号",
    "Intended Value": "目标值",
    "Units": "单位",
    "Description": "描述",
    "Field-oriented control (FOC) parameters": "磁场定向控制（FOC）参数",
    "Current loop integral gain": "电流环积分增益",
    "Current loop proportional gain": "电流环比例增益",
    "Velocity loop integral gain": "速度环积分增益",
    "Velocity loop proportional gain": "速度环比例增益",
    "line-to-line": "线电压",
    "Limit for output line-to-line voltage of d-axis current controller, expressed as a fraction of DC link voltage": "d 轴电流控制器输出线电压限值，以占 DC 母线电压的比例表示",
    "This shows the real-world engineering values for each configuration parameter. The corresponding parameters file looks like this, containing fixed-point integer values along with a C comment detailing the conversion to fixed-point:": "此处显示的是每个配置参数的实际工程值。对应的参数文件如下所示，包含定点整数值以及详细说明定点转换的 C 注释：",
    "Listing 6.1": "代码清单 6.1",
    "Parameter names are given in \u201ccamelCase\u201d except in the C header file where they are converted to all-capitals with underscores separating words, for example": "参数名采用\u201c驼峰命名法\u201d，但在 C 头文件中会转换为全大写并以下划线分隔单词，例如",
    "is converted to": "被转换为",
    "in the": "在",
    "file.": "文件中。",
    "Out-of-range errors": "超范围错误",
    "In rare circumstances the configuration parameters may produce errors during code generation. This can result from motor parameters that may be extremely small or large values compared to typical motors. In this case, code generation will fail and an error message will be shown in MPLAB": "在少数情况下，配置参数可能在代码生成期间产生错误。这可能是由于电机参数与典型电机相比过大或过小。此时，代码生成将失败，并在 MPLAB",
    "Code Configurator. (Please read the release notes of motorBench": "Code Configurator 中显示错误消息。（请阅读 motorBench",
    "Development Suite for more information on how these messages are displayed.)": "Development Suite 的发行说明以了解这些消息的显示方式。）",
    "A typical out-of-range error message looks like this:": "典型的超范围错误消息如下所示：",
    "In this instance, the code generation engine attempted to convert a real-world value of 4140.66 V/A into a Q8 representation of 345.055, which is too large; Q8 supports only \u00b1 128.": "在此例中，代码生成引擎试图将实际值 4140.66 V/A 转换为 Q8 表示的 345.055，该值过大；Q8 仅支持 \u00b1 128。",
    "Microchip is investigating methods of providing guidelines for troubleshooting and correcting out-of-range errors; in the interim, if you encounter an out-of-range error, please": "Microchip 正在研究提供超范围错误排查和纠正指南的方法；在此期间，如果您遇到超范围错误，请",
    "contact Microchip": "联系 Microchip",
    "for assistance.": "寻求帮助。",
    "Source file organization": "源文件组织",
    "Each source file begins with a header that looks like this:": "每个源文件以如下头部开始：",
    "Listing 6.2": "代码清单 6.2",
    "These are two comment blocks.": "这是两个注释块。",
    "The first one is used for some computer-assisted documentation, and contains the filename, a brief description, and the": "第一个用于某些计算机辅助文档，包含文件名、简要描述和",
    "component": "组件",
    "name.": "名。",
    "The second comment block contains the MCAF version (for example, R3 = release 3, RC14 = release candidate 14), commit ID, and build date, along with the copyright notice.": "第二个注释块包含 MCAF 版本（例如，R3 = 第 3 版，RC14 = 第 14 个候选发布版）、提交 ID 和构建日期，以及版权声明。",
    "In general, code for each": "通常，每个",
    "module": "模块",
    "is divided into two or three files, for example the": "的代码分为两到三个文件，例如",
    "module:": "模块：",
    "compilation unit (": "编译单元（",
    ") \u2014 contains C-callable function definitions": "）——包含可 C 调用的函数定义",
    "header files:": "头文件：",
    "main header file (": "主头文件（",
    ") \u2014 contains function declarations and inline function implementations": "）——包含函数声明和内联函数实现",
    "types header file (": "类型头文件（",
    ") \u2014 contains type definitions separate from function declarations": "）——包含与函数声明分离的类型定义",
    "With the exception of the types header file, this is a typical organization in C code. Types header files were separated to help remove unnecessary dependencies between modules, so that state variables could be allocated without pulling in additional modules as dependencies.": "除类型头文件外，这是 C 代码中的典型组织方式。类型头文件被分离出来是为了帮助消除模块间不必要的依赖，使得状态变量可以在不引入额外模块依赖的情况下进行分配。",
    "Auxiliary reports": "辅助报告",
    "MCAF includes a few additional files generated in the": "MCAF 包含在",
    "directory:": "目录中生成的若干附加文件：",
    "\u2014 a table of": "——一个",
    "configurable parameters": "可配置参数表",
    "\u2014 a table of motor parameters and metrics. In the event you need assistance in troubleshooting behavior of a particular motor, please provide this file to Microchip staff so they can better understand the motor\u2019s characteristics. Derived parameters or metrics like": "——一个电机参数和指标表。如果您在排查特定电机的行为时需要帮助，请将此文件提供给 Microchip 工作人员，以便他们更好地了解电机的特性。派生参数或指标如",
    "and": "和",
    "can help explain some observations or guide experienced motor control engineers to point out certain challenges of working with that particular motor. Time constants like the electrical time constant": "可以帮助解释某些观察结果，或引导经验丰富的电机控制工程师指出使用该特定电机时的某些挑战。电气时间常数",
    "and the mechanical time constant": "和机械时间常数",
    "can help illustrate the time scale of electrical and mechanical dynamics. The normalized inertia": "等时间常数可以帮助说明电气和机械动态的时间尺度。归一化惯量",
    "is the ratio of these two time constants and can highlight whether a system has a small inertia (": "是这两个时间常数的比值，可以突出系统是否具有小惯量（",
    ") in which case electrical and mechanical dynamics are not well-separated and can lead to control stability challenges, or a large inertia (": "），此时电气和机械动态不能很好地分离，可能导致控制稳定性挑战；或大惯量（",
    ") in which case slow velocity control loops are to be expected.": "），此时可以预期速度控制环较慢。",
    "\u2014 machine-readable motor parameter values, in": "——机器可读的电机参数值，采用",
    "format.": "格式。",
    "These files are experimental. Any comments or suggestions on improving the content of these files are welcome; please": "这些文件是实验性的。欢迎任何关于改进这些文件内容的意见或建议；请",
    "6.2. Code Generation": "6.2. 代码生成",
    "6.2.1. Relationship with motorBench": "6.2.1. 与 motorBench 的关系",
    "6.2.2. Configurable parameters": "6.2.2. 可配置参数",
    "6.2.2.1. Out-of-range errors": "6.2.2.1. 超范围错误",
    "6.2.3. Source file organization": "6.2.3. 源文件组织",
    "6.2.4. Auxiliary reports": "6.2.4. 辅助报告",
    "Source Tree Structure": "源代码树结构",
    "Parameter customization": "参数定制",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
