# -*- coding: utf-8 -*-
import txutil

rel = "implementation/integration"
title_zh = "6.5. 与自定义代码的集成"

m = {
    "6.5. Integration with Custom Code — MCAF R9 RC31 文档 (docver 9.0.1)": "6.5. 与自定义代码的集成 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Integration with Custom Code": "与自定义代码的集成",
    "Overview": "概述",
    "The Motor Control Application Framework and the accompanying": "电机控制应用框架及附带的",
    "Sample Application": "示例应用",
    "are designed so that the code generated from motorBench": "设计为使 motorBench",
    "Development Suite may be used with no changes as a demonstration project with the following development boards:": "Development Suite 生成的代码可在以下开发板上作为演示项目直接使用，无需修改：",
    "MCLV\u20112 Development Board": "MCLV-2 开发板",
    "MCHV\u20112 Development Board": "MCHV-2 开发板",
    "MCHV\u20113 Development Board": "MCHV-3 开发板",
    "dsPIC33CK Low Voltage Motor Control (LVMC) Development Board": "dsPIC33CK 低压电机控制 (LVMC) 开发板",
    "MCS MCLV\u201148V\u2011300W Development Board": "MCS MCLV-48V-300W 开发板",
    "MCHV\u2011230VAC\u20111.5kW Motor Control High-Voltage Development Board": "MCHV-230VAC-1.5kW 电机控制高压开发板",
    "Use of MCAF in other projects usually requires a manual effort to replace the sample application with a custom application. While": "在其他项目中使用 MCAF 通常需要手动将示例应用替换为自定义应用。虽然",
    "MCAPI": "MCAPI",
    "will allow the custom application to control and obtain feedback from the motor without needing to know the different components and modules of MCAF, this effort still requires the application developer to be aware of the timing and resource requirements of MCAF. See": "允许自定义应用在无需了解 MCAF 各组件和模块的情况下控制电机并获取反馈，但此工作仍要求应用开发者了解 MCAF 的时序和资源需求。参见",
    "Scheduling and Optimization": "调度与优化",
    "and": "和",
    "Resource Usage": "资源使用",
    "for more information.": "以获取更多信息。",
    "Block diagram showing the User Application relative to MCAPI": "显示用户应用相对于 MCAPI 的框图",
    "Note": "注",
    "Except for existing interfaces in mcapi.h and mcapi_types.h, the functions, modules, and components in MCAF are still subject to change, and as of MCAF R7, none of the interfaces within MCAF have been frozen. As a result of this, it is not recommended for a custom application to access any of MCAF components directly without using the": "除 mcapi.h 和 mcapi_types.h 中的现有接口外，MCAF 中的函数、模块和组件仍可能变更，截至 MCAF R7，MCAF 内部没有任何接口已被冻结。因此，不建议自定义应用在不使用",
    "Finally: if integration with custom code is important to you, we encourage your feedback to help guide future development in this area. Please": "最后：如果与自定义代码的集成对您很重要，我们鼓励您提供反馈以指导该领域的未来开发。请",
    "contact Microchip": "联系 Microchip",
    "with any comments or suggestions.": "提出任何意见或建议。",
    "Modifying the Main Application": "修改主应用",
    "The main application includes a": "主应用包含一个",
    "sample application": "示例应用",
    "in": "于",
    "that implements a simple user interface to control the motor using the": "中，使用",
    "Motion Control API (MCAPI)": "运动控制 API (MCAPI)",
    ". All interfaces of the sample application have names starting with the": "实现控制电机的简单用户界面。示例应用的所有接口名称均以",
    "prefix. This sample application may be modified or replaced with custom code.": "前缀开头。此示例应用可被修改或替换为自定义代码。",
    "The requirements for MCAF to work properly with the modified main application are as follows:": "MCAF 与修改后的主应用正常工作的要求如下：",
    "should be called at system startup after": "应在系统启动时在",
    "should be called at each iteration of the main loop. This does not have to be executed periodically, but the minimum repetition rate should be approximately 100Hz to service the various features.": "之后调用。应在主循环的每次迭代中调用。此函数不必周期性执行，但最小重复频率应约为 100Hz 以服务各项功能。",
    "The board handler function,": "板级处理函数，",
    ", should be called periodically at a rate that is defined by the": "应按",
    "UI service period": "UI 服务周期",
    "in the Customize page of motorBench": "（在 motorBench",
    "Development Suite. For instance, this function may be called from an application timer": "Development Suite 的 Customize 页面中定义）的频率周期性调用。例如，此函数可从应用定时器",
    "ISR": "ISR",
    "or a scheduler.": "或调度器中调用。",
    "The requirements for a custom application to interface with MCAF are as follows:": "自定义应用与 MCAF 接口的要求如下：",
    "An application initialization function should be set up to initialize pointers to the": "应设置应用初始化函数以初始化指向 MCAF 中",
    "data in MCAF. See": "数据的指针。参见",
    "in mcaf_sample_application.c for an example.": "中的示例。",
    "The application initialization function should be called from": "应用初始化函数应从",
    "in mcaf_main.c to initialize the application-MCAF interface.": "中调用以初始化应用-MCAF 接口。",
    "Application should use": "应用应使用",
    "to interact with MCAF at runtime.": "在运行时与 MCAF 交互。",
    "Modifying the FOC module": "修改 FOC 模块",
    "Because of tight coupling that remains in MCAF between the state machine,": "由于 MCAF 中状态机、",
    "FOC": "FOC",
    ", and supervisory algorithms, modifications to the": "和监督算法之间仍存在紧密耦合，不建议修改",
    "module are not recommended. This includes changes to the sensorless estimators, the PI controllers or the": "模块。这包括对无传感器估计器、PI 控制器或",
    "flux control module": "磁通控制模块",
    "Modifying the State Machine": "修改状态机",
    "Because of tight coupling that remains in MCAF R7 between the state machine,": "由于 MCAF R7 中状态机、",
    ", and supervisory algorithms, modifications to the state machine are not recommended.": "和监督算法之间仍存在紧密耦合，不建议修改状态机。",
    "Modifying the Supervisory Algorithms": "修改监督算法",
    "Supervisory algorithms, with the exception of watchdog management, are subject to change in the upcoming revisions after MCAF R7. Due to this reason, modifications to this module are not recommended.": "监督算法（看门狗管理除外）在 MCAF R7 之后的后续版本中可能变更。因此，不建议修改此模块。",
    "Watchdog management involves several areas of MCAF; to change this behavior, see the section on": "看门狗管理涉及 MCAF 的多个方面；要更改此行为，请参见",
    "watchdog management": "看门狗管理",
    "and/or search the code for": "和/或在代码中搜索",
    "watchdog": "watchdog",
    "; the relevant sections are in the": "；相关部分位于",
    "traps": "traps",
    "ui": "ui",
    "isr": "isr",
    ", and": "和",
    "main": "main",
    "modules.": "模块。",
    "6.5. Integration with Custom Code": "6.5. 与自定义代码的集成",
    "6.5.1. Overview": "6.5.1. 概述",
    "6.5.2. Modifying the Main Application": "6.5.2. 修改主应用",
    "6.5.3. Modifying the FOC module": "6.5.3. 修改 FOC 模块",
    "6.5.4. Modifying the State Machine": "6.5.4. 修改状态机",
    "6.5.5. Modifying the Supervisory Algorithms": "6.5.5. 修改监督算法",
    "Sampling Rate and PWM Frequency Implications": "采样率与 PWM 频率的影响",
    "Custom Board Support": "自定义板级支持",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
