# -*- coding: utf-8 -*-
import txutil

rel = "implementation/custom-board-support/verification"
title_zh = "6.6.8. 验证与板级调试"

m = {
    "6.6.8. Verification and board bring-up — MCAF R9 RC31 文档 (docver 9.0.1)": "6.6.8. 验证与板级调试 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Custom Board Support": "自定义板级支持",
    "Verification and board bring-up": "验证与板级调试",
    "Overview": "概述",
    "This section provides guidance on bringing up a custom board for the first time with MCAF, after creating and importing a new board definition.": "本节提供在创建并导入新板级定义后，首次使用 MCAF 调试自定义板的指导。",
    "Warning": "警告",
    "Use a current-limited power supply to power the custom board until you gain sufficient confidence in the board definition in motorBench and the board design/build.": "在充分信任 motorBench 中的板级定义和板设计/构建之前，请使用限流电源为自定义板供电。",
    "Caution": "注意",
    "Do not try to connect or start the motor": "不要尝试连接或启动电机",
    "after programming the code generated from MCC for the first time. Follow the procedure described below to reduce the risk of hardware damage.": "在首次编程 MCC 生成的代码后。请按照以下步骤操作以降低硬件损坏风险。",
    "Recommended equipment": "推荐设备",
    "In addition to the desired motor and custom board, we recommend:": "除了所需的电机和自定义板外，我们推荐：",
    "Non-contact current probe (such as Chauvin Arnoux E3N or AEMC SL261) for measuring phase currents.": "非接触式电流探头（如 Chauvin Arnoux E3N 或 AEMC SL261），用于测量相电流。",
    "Three-phase alternator stator for low-voltage systems, as an alternative to a motor load; for example,": "用于低压系统的三相交流发电机定子，作为电机负载的替代方案；例如，",
    "General procedure": "一般流程",
    "At a high level, we recommend the following steps when working with a new board:": "在高层面上，我们建议使用新板时遵循以下步骤：",
    "Firmware execution": "固件执行",
    ": is the board executing properly? (heartbeat LEDs, PWM channels, real-time diagnostic connection)": "：板是否正常执行？（心跳 LED、PWM 通道、实时诊断连接）",
    "Verify open-loop voltage operation": "验证开环电压运行",
    "Configure system for open-loop voltage operation": "配置系统为开环电压运行",
    "Verify PWM": "验证 PWM",
    "operation: ensure PWM outputs are switching.": "运行：确保 PWM 输出正在切换。",
    "Verify DC link": "验证 DC 母线",
    "voltage measurement within expected range.": "电压测量在预期范围内。",
    "Test overcurrent fault": "测试过流故障",
    "functionality.": "功能。",
    "Verify current measurement": "验证电流测量",
    "Verify closed-loop current": "验证闭环电流",
    "control.": "控制。",
    "General firmware execution": "一般固件执行",
    "Look for signs of correct CPU execution and timing:": "寻找 CPU 正确执行和时序正确的迹象：",
    "\u201cHeartbeat LEDs\u201d \u2014 if present on the board, these will either be flashing at a 1Hz rate under normal operation, or flashing an error code if there is a fault condition (see": "\u201c心跳 LED\u201d——如果板上有此 LED，正常运行时将以 1Hz 速率闪烁，或在故障状态下闪烁错误代码（见",
    "External Interface": "外部接口",
    "PWM Channels \u2014 if the board is not in a fault condition, the PWM low-side channels (PWMxL) will be switching in a": "PWM 通道——如果板未处于故障状态，PWM 低侧通道 (PWMxL) 将以",
    "\u201cminimal impact\u201d state": "\u201c最小影响\u201d状态",
    "at the specified PWM frequency.": "按指定 PWM 频率切换。",
    "Test point": "测试点",
    ", if available \u2014 should have a pulse at PWM switching frequency, representing the time interval when the MCAF ADC ISR is executing.": "（如有）——应有 PWM 开关频率的脉冲，表示 MCAF ADC ISR 执行的时间间隔。",
    "Real-time diagnostic": "实时诊断",
    "connection (X2Cscope) \u2014 the board should be able to communicate with the real-time diagnostic software.": "连接 (X2Cscope)——板应能与实时诊断软件通信。",
    "If these are not working properly, there may be an issue with the CPU running at the correct frequency.": "如果这些不能正常工作，可能是 CPU 未以正确频率运行的问题。",
    "Open-loop voltage operation": "开环电压运行",
    "The": "The",
    "test harness": "测试框架",
    "can be used to run the controller in an": "可用于在",
    "open-loop voltage mode": "开环电压模式",
    "where PWM outputs are driven at a forced commutation frequency and the outputs drive the PWM with a sinusoidally-varying line-to-line duty cycle. Each phase has an individual duty cycle that follows the characteristic double-humped waveforms of space-vector PWM / zero-sequence modulation as shown in": "下运行控制器，其中 PWM 输出以强制换相频率驱动，输出以正弦变化的线间占空比驱动 PWM。每相具有单独的占空比，遵循空间矢量 PWM / 零序调制的特征双峰波形，如",
    "Zero sequence modulation waveforms as a function of commutation angle. The dark-colored curves are line-to-negative-link voltages, and the light-colored curves are line-to-neutral voltages. The gray curve": "零序调制波形作为换相角的函数。深色曲线为线对负母线电压，浅色曲线为线对中性点电压。灰色曲线",
    "is the zero sequence voltage (average of the three line voltages, effectively neutral-to-negative-link voltage) which moves up and down during the commutation cycle to keep the range of line voltages centered within the available DC link voltage.": "是零序电压（三个线电压的平均值，即中性点对负母线电压），在换相周期内上下移动以使线电压范围居中于可用 DC 母线电压范围内。",
    "Make sure that the motor terminals of the board are open-circuited (not connected to any motor or load)": "确保板的电机端子开路（未连接任何电机或负载）",
    "Follow the steps in": "按照",
    "to prepare the controller for verification using open-loop voltage control.": "中的步骤准备控制器以使用开环电压控制进行验证。",
    "Enabling open-loop voltage control": "启用开环电压控制",
    "Step": "步骤",
    "Program variable": "程序变量",
    "Value": "值",
    "Comments": "注释",
    "Define the macro": "定义宏",
    "in options.h.": "于 options.h 中。",
    "Build and program the project to the test hardware.": "构建项目并编程到测试硬件。",
    "Needed to enable automatic shutdown of test modes \u2014 see": "用于启用测试模式的自动关断——见",
    "Implementation of Test Guarding": "测试保护的实现",
    "Set the test harness mode to normal operation prior to configuring the desired test cases. \u2014 see": "在配置所需测试用例之前，将测试框架模式设为正常运行。——见",
    "Test harness modes": "测试框架模式",
    "Set both d- and q-axis components of": "将",
    "to 0.": "的 d 轴和 q 轴分量均设为 0。",
    "Override commutation angle \u2014 see": "覆盖换相角——见",
    "Commutation Override": "换相覆盖",
    "as needed": "按需",
    "Small values allow for slow changes in electrical angle; for example,": "较小的值允许电气角度缓慢变化；例如，",
    "set to 1 count causes": "设为 1 计数时，",
    "to completes a full electrical cycle in 65536 current loop updates, or 3.2768 seconds for a 20 kHz control ISR. Values from 0 to 50 counts (15.25 Hz electrical for a 20 kHz control ISR) are typical during these kinds of tests.": "在 65536 次电流环更新中完成一个完整电气周期，或在 20 kHz 控制 ISR 下为 3.2768 秒。在此类测试中，0 到 50 计数（20 kHz 控制 ISR 下 15.25 Hz 电气频率）的值是典型的。",
    "Set the test harness mode to force dq-axis voltage \u2014 see": "将测试框架模式设为强制 dq 轴电压——见",
    "Verify PWM operation": "验证 PWM 运行",
    "With the motor disconnected from any load, slowly increase the inverter\u2019s dq-axis reference voltage": "在电机与任何负载断开的情况下，缓慢增加逆变器的 dq 轴参考电压",
    "from zero during testing. At each step, observe the following:": "从零开始。在每一步，观察以下内容：",
    "Check that the duty cycles of the PWM outputs are changing at the expected electrical frequency": "检查 PWM 输出的占空比是否以预期电气频率变化",
    "Verify": "验证",
    "dead time": "死区时间",
    "of the digital gate drive signals is occurring as expected.": "是否如预期出现在数字栅极驱动信号中。",
    "Make sure transistor turn-on transients look ok.": "确保晶体管导通瞬态正常。",
    "Check each half-bridge output to ensure it swings between 0V and the DC link voltage as expected.": "检查每个半桥输出，确保其在 0V 和 DC 母线电压之间如预期摆动。",
    "Verify DC link voltage measurement": "验证 DC 母线电压测量",
    "If you can operate the board from an adjustable power supply, adjust it up or down through the intended range to check that the voltage read by the ADC falls within the expected tolerance range for a given DC link voltage.": "如果可以使用可调电源操作板，在预期范围内上下调节，检查 ADC 读取的电压是否落在给定 DC 母线电压的预期容差范围内。",
    "Verify hardware overcurrent fault": "验证硬件过流故障",
    "Trigger the overcurrent input manually by connecting the microcontroller\u2019s overcurrent sense input to the appropriate power rail, depending on the value of": "通过将微控制器的过流检测输入连接到适当的电源轨来手动触发过流输入，具体取决于",
    "(see": "（见",
    "custom board schema": "自定义板级 schema",
    "):": "）：",
    "to Vss (": "至 Vss（",
    "polarity": "polarity",
    "active-low": "active-low",
    "to Vdd (": "至 Vdd（",
    "active-high": "active-high",
    "Verify that the PWM outputs stop switching.": "验证 PWM 输出停止切换。",
    "Reset the overcurrent input (if using the": "复位过流输入（如果使用",
    "Sample Application": "示例应用",
    ", press the primary pushbutton).": "，按下主按钮）。",
    "Verify that the PWM outputs start switching again.": "验证 PWM 输出重新开始切换。",
    "Verify scaling and polarity of current measurement": "验证电流测量的缩放和极性",
    "Ensure the test harness is configured in open-loop voltage mode as described in": "确保测试框架按",
    "Connect a three-phase inductive load (alternator stator or test motor).": "连接三相感性负载（交流发电机定子或测试电机）。",
    "If using a motor, to prevent back-emf from affecting measurements, take either of the following approaches:": "如果使用电机，为防止反电动势影响测量，请采取以下任一方法：",
    "Lock the rotor so it does not move": "锁定转子使其不动",
    "Set the electrical frequency": "将电气频率",
    "to zero": "设为零",
    "Increase d-axis voltage": "增加 d 轴电压",
    "in small steps until a modest amount of current (10-20% of maximum continuous current) flows through the motor phases. The required voltage should be approximately": "逐步增加，直到适量电流（最大连续电流的 10-20%）流过电机相位。所需电压约为",
    "where": "其中",
    "is the": "为",
    ", expressed as a duty cycle, and IR is the line-to-neutral voltage drop across the motor winding. Small increases of 5 \u2013 20 counts at a time should be sufficient.": "，以占空比表示，IR 为电机绕组上的线对中性点电压降。每次增加 5–20 计数即可。",
    "Depending on the electrical angle": "根据电气角度",
    ", the current in one motor phase may be near zero even though current flows in the other two phases. Make sure to measure current on at least two of the motor phases, to ensure that the motor phase current is not excessive. Alternatively, use a value of": "，一个电机相位的电流可能接近零，即使其他两相有电流流过。确保至少测量两个电机相位的电流，以确保电机相电流不过大。或者，使用足够大的",
    "that is large enough to ensure at least 5 Hz electrical, while adjusting d-axis voltage, so that the electrical angle is changing smoothly and current is visible on all phases.": "值以确保至少 5 Hz 电气频率，同时调节 d 轴电压，使电气角度平滑变化且所有相位均可见电流。",
    "Set": "设置",
    "to zero, so that the voltages and currents are at DC.": "为零，使电压和电流为直流。",
    "Measure actual phase currents with a current probe, and compare with digitized current in firmware located in the": "用电流探头测量实际相电流，并与固件中",
    "structure; the measured and digitized currents should be within a reasonable range of each other.": "结构中的数字化电流比较；测量值和数字化电流应在合理范围内。",
    "Verify that positive digitized current corresponds with the": "验证正向数字化电流与",
    "expected direction of current": "预期电流方向",
    "Closed-loop current control": "闭环电流控制",
    "In this step, the inductive load (motor or stator) will be used to operate MCAF in closed-loop current control, with commanded current set to a small desired value and a superimposed square wave perturbation. (For an example of what this looks like, see": "在此步骤中，将使用感性负载（电机或定子）以闭环电流控制运行 MCAF，指令电流设为较小的期望值并叠加方波扰动。（示例见",
    "in": "中的",
    "Examples of poorly-tuned and well-tuned current loops": "整定不良和整定良好的电流环示例",
    "As shown in the": "如",
    "data flow diagram": "数据流图",
    ", there are three important sets of dq-axis currents:": "所示，有三组重要的 dq 轴电流：",
    "Description": "描述",
    "Desired dq-axis currents, prior to perturbation": "扰动前的期望 dq 轴电流",
    "Desired dq-axis currents, including perturbation": "包含扰动的期望 dq 轴电流",
    "(commanded input to current controller)": "（电流控制器的指令输入）",
    "Measured dq-axis currents": "测量的 dq 轴电流",
    "The goal of this step is to ensure that the measured currents": "此步骤的目标是确保测量电流",
    "follow the commanded currents": "跟随指令电流",
    "; both d- and q-axis components of these currents should be examined using real-time diagnostics software.": "；应使用实时诊断软件检查这些电流的 d 轴和 q 轴分量。",
    "Using the": "使用",
    "Make sure MCAF is initialized for forced commutation:": "确保 MCAF 初始化为强制换相：",
    "(53670)": "(53670)",
    "to keep output transistors in a minimal impact state)": "以保持输出晶体管处于最小影响状态）",
    "to force commutation)": "以强制换相）",
    "to force a fixed commutation angle": "以强制固定换相角",
    "and": "和",
    "to run the controller in closed-loop current control, but disable the outer loop)": "以闭环电流控制运行控制器，但禁用外环）",
    "to a modest value (for example 10-25% of rated continuous current; see": "设为适中值（例如额定连续电流的 10-25%；见",
    "in sat_PI_params.h)": "于 sat_PI_params.h）",
    "Verify that the measured d- and q- axis currents (": "验证测量的 d 轴和 q 轴电流（",
    ") follow their respective commanded currents (": "）跟随各自的指令电流（",
    ").": "）。",
    "Add a perturbation square wave signal, as described in the": "添加扰动方波信号，如",
    ", to the d-axis current command:": "所述，到 d 轴电流指令：",
    "to a small value (half of the value used in": "设为较小值（建议为",
    "is suggested)": "中使用的值的一半）",
    "to a mid-range frequency (10Hz \u2013 100Hz suggested)": "设为中频（建议 10Hz–100Hz）",
    "to 1, to enable perturbation": "设为 1，以启用扰动",
    "6.6.8. Verification and board bring-up": "6.6.8. 验证与板级调试",
    "6.6.8.1. Overview": "6.6.8.1. 概述",
    "6.6.8.1.1. Recommended equipment": "6.6.8.1.1. 推荐设备",
    "6.6.8.1.2. General procedure": "6.6.8.1.2. 一般流程",
    "6.6.8.2. General firmware execution": "6.6.8.2. 一般固件执行",
    "6.6.8.3. Open-loop voltage operation": "6.6.8.3. 开环电压运行",
    "6.6.8.3.1. Verify PWM operation": "6.6.8.3.1. 验证 PWM 运行",
    "6.6.8.3.2. Verify DC link voltage measurement": "6.6.8.3.2. 验证 DC 母线电压测量",
    "6.6.8.3.3. Verify hardware overcurrent fault": "6.6.8.3.3. 验证硬件过流故障",
    "6.6.8.3.4. Verify scaling and polarity of current measurement": "6.6.8.3.4. 验证电流测量的缩放和极性",
    "6.6.8.4. Closed-loop current control": "6.6.8.4. 闭环电流控制",
    "Creating a custom board configuration": "创建自定义板级配置",
    "Custom board definition format": "自定义板级定义格式",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
