# -*- coding: utf-8 -*-
import txutil

rel = "implementation/custom-board-support/custom_board_definitions"
title_zh = "6.6.9. 自定义板级定义格式"

m = {
    "6.6.9. Custom board definition format — MCAF R9 RC31 文档 (docver 9.0.1)": "6.6.9. 自定义板级定义格式 — MCAF R9 RC31 文档 (docver 9.0.1)",
    "General Implementation Issues": "通用实现问题",
    "Custom Board Support": "自定义板级支持",
    "Custom board definition format": "自定义板级定义格式",
    "Custom board definition files follow a prescribed format in motorBench": "自定义板级定义文件在 motorBench",
    "Development Suite. They are human-readable and hand-editable, but they are based on a defined data structure, organized as a data model.": "Development Suite 中遵循规定格式。它们可读且可手动编辑，但基于定义的数据结构，组织为数据模型。",
    "The data model must conform to the": "数据模型必须符合",
    "board definition schema": "板级定义 schema",
    "The data model is": "数据模型",
    "serialized as a text format": "被序列化为文本格式",
    "(YAML in motorBench 2.50)": "（motorBench 2.50 中为 YAML）",
    "The following sections describe these constraints.": "以下章节描述这些约束。",
    "Working with Serialized Data Models": "使用序列化数据模型",
    "Introduction": "简介",
    "The term data model refers to any hierarchical tree structure used to model a system. In motorBench": "术语数据模型指用于建模系统的任何层次树结构。在 motorBench",
    "Development Suite we use several data models, for processes such as": "Development Suite 中，我们使用多个数据模型，用于",
    "code generation": "代码生成",
    "parameter customization": "参数定制",
    "and": "和",
    "custom board support": "自定义板级支持",
    "Some data models can be serialized into text formats such as": "某些数据模型可以序列化为文本格式，如",
    ", which facilitates use of version control and hand-editing where appropriate. The custom board feature in motorBench": "，这便于在适当情况下使用版本控制和手动编辑。motorBench",
    "Development Suite 2.50 supports importing files in YAML format.": "Development Suite 2.50 的自定义板功能支持导入 YAML 格式的文件。",
    "The data model for board definitions in motorBench is": "motorBench 中板级定义的数据模型",
    "serializable to JSON and deserializable from JSON, including support for the following types of values": "可序列化为 JSON 并可从 JSON 反序列化，支持以下值类型",
    "numbers": "数字",
    "strings": "字符串",
    "booleans (": "布尔值（",
    "lists of values (= arrays / ordered sequences)": "值列表（= 数组/有序序列）",
    "maps of values (= dictionaries / unordered sets of key-value pairs)": "值映射（= 字典/无序键值对集合）",
    "generally described in YAML format (easier to read/write than JSON)": "通常以 YAML 格式描述（比 JSON 更易读写）",
    "referenced by a path separated by dots, for example": "通过以点分隔的路径引用，例如",
    "Example in YAML": "YAML 示例",
    "Here is an excerpt containing a partial board definition in YAML. Its hierarchical structure is expressed through levels of indentation.": "以下是 YAML 格式的部分板级定义摘录。其层次结构通过缩进层级表达。",
    "Note": "注",
    "When editing, we suggest using an editor that supports YAML, such as VSCode or Notepad++, with syntax highlighting and ability to expand/collapse sections of the hierarchy.": "编辑时，建议使用支持 YAML 的编辑器，如 VSCode 或 Notepad++，具备语法高亮和展开/折叠层次结构部分的功能。",
    "Warning": "警告",
    "To avoid misalignment and incompatibility, use spaces for indentation, not tabs.": "为避免对齐不当和不兼容，请使用空格而非制表符进行缩进。",
    "Listing 6.3": "代码清单 6.3",
    "Comments": "注释",
    "are expressed as a": "表示为",
    "followed by arbitrary text that will be ignored until the end of the line": "后跟任意文本，该文本将被忽略至行尾",
    "Numbers": "数字",
    "are expressed as integers, floating-point values, or scientific notation": "表示为整数、浮点值或科学记数法",
    "Floating-point values": "浮点值",
    "may be expressed as decimals (examples:": "可以表示为小数（示例：",
    ") or as scientific notation (examples:": "）或科学记数法（示例：",
    ").": "）。",
    "When using scientific notation, make sure to use a decimal before the exponent, for example": "使用科学记数法时，请确保在指数前使用小数点，例如",
    "rather than": "而非",
    ". This avoids issues in some software libraries.": "。这可避免某些软件库中的问题。",
    "are expressed as the fixed text": "表示为固定文本",
    "(note: content is case-sensitive)": "（注：内容区分大小写）",
    "Null": "Null",
    "values are expressed as the fixed text": "值表示为固定文本",
    "Strings": "字符串",
    "are expressed as text that is not a number or a boolean or null.": "表示为非数字、非布尔值、非 null 的文本。",
    "To be safe in YAML, use quotes to delimit the string; YAML includes other confusing and quirky representations like": "为安全起见，在 YAML 中使用引号分隔字符串；YAML 包含其他令人困惑的表示方式，如",
    "(for booleans) or": "（用于布尔值）或",
    "which is a time.": "这是一个时间值。",
    "There are several other ways to express multiline strings in YAML; you won\u2019t need them for board definition files and should not use them.": "YAML 中还有其他几种表达多行字符串的方式；板级定义文件中不需要也不应使用它们。",
    "Lists": "列表",
    "are ordered sequences of indented values, each of which is preceded by a hyphen character (the 1,2,3 at the end under": "是缩进值的有序序列，每个值前以连字符开头（末尾",
    "Lists may also be represented by an alternate compact syntax": "列表也可以用替代的紧凑语法表示",
    "as in Javascript and Python, but we generally don\u2019t use this in our examples.": "如 Javascript 和 Python 中所示，但我们通常不在示例中使用。",
    "Maps": "映射",
    "are unordered sequences of indented key/value pairs, where the key is a string, followed by a colon, followed by a value that is separated from the colon by a space or newline.": "是缩进键/值对的无序序列，其中键为字符串，后跟冒号，再跟一个与冒号以空格或换行符分隔的值。",
    "The example document above is a map with three keys,": "上面的示例文档是一个包含三个键的映射，",
    "The value associated with the": "与",
    "key is itself a map containing three keys:": "键关联的值本身是一个包含三个键的映射：",
    ". These keys each refer to a string value that immediately follows the key, after a space.": "。这些键各自引用紧随键后（空格之后）的字符串值。",
    "Maps may also be represented by an alternate compact syntax as in Javascript, but we generally don\u2019t use this in our examples:": "映射也可以用 Javascript 中的替代紧凑语法表示，但我们通常不在示例中使用：",
    "The ordering of elements in a map is not important, and may be permuted without changing the value, even though the resulting serialized YAML file is different.": "映射中元素的顺序不重要，可以排列而不改变值，即使生成的序列化 YAML 文件不同。",
    "Values within a data model may be referenced by a": "数据模型中的值可以通过",
    "path": "路径",
    ", which is a string that uses a period/dot": "引用，它是一个使用句点/点",
    "to denote indexing a map by key, and brackets": "来表示按键索引映射，使用方括号",
    "to denote indexing a list by an integer value. In the example data model above:": "来表示按整数值索引列表。在上面的示例数据模型中：",
    "the path": "路径",
    "refers to the string": "引用字符串",
    "refers to the number": "引用数字",
    "refers to the following map:": "引用以下映射：",
    "For a more detailed introduction on YAML, there are various public sources; these appear to be among the more readable tutorials:": "有关 YAML 的更详细介绍，有各种公开资源；以下似乎是较为易读的教程：",
    "Custom board schema": "自定义板级 schema",
    "The data models in custom board definitions are hierarchical tree structures that conform to the schema listed in the table below, organized under three top-level sections:": "自定义板级定义中的数据模型是符合下表所列 schema 的层次树结构，组织在三个顶层节下：",
    "\u2014 covers data associated with the name and description of a board": "\u2014 涵盖与板名称和描述相关的数据",
    "\u2014 covers parameters associated with a board, such as maximum PWM frequency, full-scale DC link voltage, maximum continuous phase current, etc.": "\u2014 涵盖与板相关的参数，如最大 PWM 频率、满量程 DC 母线电压、最大连续相电流等",
    "\u2014 covers peripheral configuration choices, such as UART pin assignment, ADC channel mapping, PWM fault source and polarity, etc.": "\u2014 涵盖外设配置选择，如 UART 引脚分配、ADC 通道映射、PWM 故障源和极性等",
    "Each row of the table describes an entry in the tree, which has several properties:": "表格的每一行描述树中的一个条目，具有以下属性：",
    "a type, which is either one of the": "一个类型，可以是",
    "standard data model types": "标准数据模型类型",
    "or one of the following:": "之一，或以下之一：",
    "a named type, such as": "命名类型，如",
    ", that has a constrained structure. These types are listed at the end of the table.": "，具有约束结构。这些类型列在表格末尾。",
    "an": "一个",
    ", which is a choice from among several fixed options (these are listed in the description)": "，即从若干固定选项中选择（这些在描述中列出）",
    "a constrained numeric range, shown here as an inequality in either": "约束数值范围，此处以不等式表示为",
    ": integer range, for example": "：整数范围，例如",
    ": floating-point range, for example": "：浮点范围，例如",
    "units, if applicable \u2014 for example V (volts) or A (amperes) or s (seconds)": "单位（如适用）——例如 V（伏特）或 A（安培）或 s（秒）",
    "whether the entry is required (Req\u2019d, denoted by a green checkmark": "该条目是否为必填（Req'd，以绿色勾号",
    ") or optional": "）或可选",
    "Entries are required or optional in the context of their parent entries. For example,": "条目在其父条目的上下文中为必填或可选。例如，",
    "is optional, but if it is present, then": "是可选的，但如果存在，则",
    "is required.": "为必填。",
    "further descriptive notes under \u201cDescription\u201d": "\u201cDescription\u201d下的进一步描述性注释",
    "Path": "路径",
    "Type": "类型",
    "Units": "单位",
    "Req\u2019d": "必填",
    "Description": "描述",
    "Board identification": "板级标识",
    "Unique ID for a given instance of a board. This parameter is restricted to printable ASCII characters (codes 32-126, including space but excluding DELETE (127)).": "板的给定实例的唯一 ID。此参数限于可打印 ASCII 字符（代码 32-126，包括空格但不包括 DELETE (127)）。",
    "Board name that will appear in motorBench when the board configuration file is loaded. This parameter is restricted to printable ASCII characters (codes 32-126, including space but excluding DELETE (127)).": "加载板级配置文件时在 motorBench 中显示的板名称。此参数限于可打印 ASCII 字符（代码 32-126，包括空格但不包括 DELETE (127)）。",
    "Description of the board configuration": "板级配置的描述",
    "Board characteristics": "板级特性",
    "Microcontroller part number. Restricted to dsPIC33CK and dsPIC33AK discrete devices and dsPIC33CDV, dsPIC33CDVC, and dsPIC33CDVL SiP devices.": "微控制器型号。限于 dsPIC33CK 和 dsPIC33AK 独立器件以及 dsPIC33CDV、dsPIC33CDVC 和 dsPIC33CDVL SiP 器件。",
    "Use the device name as in MPLAB X, without any part suffixes to indicate packaging or temperature range. For example,": "使用 MPLAB X 中的器件名，不含任何表示封装或温度范围的后缀。例如，",
    "PWM gate driver configuration for boards with MCP802(1/2/7) gate drivers or SiP-based boards": "使用 MCP802(1/2/7) 栅极驱动器或基于 SiP 的板的 PWM 栅极驱动器配置",
    "Gate driver device name. Restricted to": "栅极驱动器器件名。限于",
    "Gate driver configuration. See device datasheet for more information on each parameter.": "栅极驱动器配置。各参数详情请参见器件数据手册。",
    "Device mode when disabled (SLEEP)": "禁用时的器件模式 (SLEEP)",
    "Options:": "选项：",
    "Enable external MOSFET short circuit detection (EXTSC)": "启用外部 MOSFET 短路检测 (EXTSC)",
    "Enable external MOSFET under-voltage lockout (EXTUVLO)": "启用外部 MOSFET 欠压锁定 (EXTUVLO)",
    "Enable op amps during device standby mode (OPAMP). Only required if using MCP8022.": "在器件待机模式下启用运放 (OPAMP)。仅在使用 MCP8022 时需要。",
    "Enable LIN pull-up resistors (PU30K). Only required if using MCP8027.": "启用 LIN 上拉电阻 (PU30K)。仅在使用 MCP8027 时需要。",
    "Sets the DAC current reference value (DACREF). Only required if using MCP8027.": "设置 DAC 电流参考值 (DACREF)。仅在使用 MCP8027 时需要。",
    "Pin assignment for the MCP802x gate driver RX, TX, fault, and device enable pins. If using a SiP device, refer to the internal connections block diagram of the device datasheet.": "MCP802x 栅极驱动器 RX、TX、fault 和 device enable 引脚的引脚分配。如果使用 SiP 器件，请参阅器件数据手册的内部连接框图。",
    "GPIO pin name. See device datasheet for which pins are available on the selected device.": "GPIO 引脚名。可用引脚请参见器件数据手册。",
    "Board voltage measurement characteristics": "板级电压测量特性",
    "Phase voltage measurement characteristics": "相电压测量特性",
    "Time constant of phase voltage measurement circuit": "相电压测量电路的时间常数",
    "Full scale value of phase voltage measurement": "相电压测量的满量程值",
    "DC link voltage measurement characteristics": "DC 母线电压测量特性",
    "Time constant of DC link voltage measurement circuit": "DC 母线电压测量电路的时间常数",
    "Full scale value of DC link voltage measurement. 0V-to-3.3V range at ADC corresponds to 0V-to-fullscale range.": "DC 母线电压测量的满量程值。ADC 的 0V 至 3.3V 范围对应 0V 至满量程范围。",
    "Minimum allowable value of DC link voltage": "DC 母线电压的最小允许值",
    "Maximum allowable value of DC link voltage": "DC 母线电压的最大允许值",
    "Default value of DC link voltage. Used to initialize the system parameter for \u201cNominal DC link voltage\u201d when motorBench starts a new project.": "DC 母线电压的默认值。用于 motorBench 启动新项目时初始化\u201c标称 DC 母线电压\u201d系统参数。",
    "Board": "板级",
    "current measurement": "电流测量",
    "DC link current measurement characteristics": "DC 母线电流测量特性",
    "Full scale value of DC link current measurement": "DC 母线电流测量的满量程值",
    "Time constant of DC link current measurement circuit": "DC 母线电流测量电路的时间常数",
    "Phase current measurement characteristics": "相电流测量特性",
    "Full scale value of phase current measurement": "相电流测量的满量程值",
    "Time constant of phase current measurement circuit": "相电流测量电路的时间常数",
    "Maximum phase current characteristics": "最大相电流特性",
    "Maximum continuous phase current. This value must be well below the full scale phase current measurement range to account for current ripple and hardware tolerances while leaving enough margin for current controller overshoot.": "最大连续相电流。此值必须远低于满量程相电流测量范围，以考虑电流纹波和硬件容差，同时为电流控制器过冲留出足够裕量。",
    "Maximum peak phase current. This value must be well below the full scale phase current measurement range to account for current ripple and hardware tolerances while leaving enough margin for current controller overshoot.": "最大峰值相电流。此值必须远低于满量程相电流测量范围，以考虑电流纹波和硬件容差，同时为电流控制器过冲留出足够裕量。",
    "Phase current measurement gain correction factors. These five parameters form a 3x3 matrix (Kac, Kbc, Kca, and Kcb are set to zero) used for current measurement compensation. Optional; if not present, the 3x3 identity matrix is used.": "相电流测量增益校正因子。这五个参数构成 3x3 矩阵（Kac、Kbc、Kca 和 Kcb 设为零），用于电流测量补偿。可选；如不存在，使用 3x3 单位矩阵。",
    "Optional; supports boards that measure phase C current and need gain correction": "可选；支持测量 C 相电流并需要增益校正的板",
    "3-phase PWM characteristics": "三相 PWM 特性",
    "Switching frequency of 3-phase PWM signals": "三相 PWM 信号的开关频率",
    "Minimum allowable value": "最小允许值",
    "Maximum allowable value": "Default value",
    "Default value": "默认值",
    "Dead time": "死区时间",
    "of 3-phase PWM signals. Brief period of time when the high and low PWM signals in a phase are off, preventing conduction and short circuits between the DC link voltage and ground.": "三相 PWM 信号的。即一相中高侧和低侧 PWM 信号同时关闭的短暂时间，防止 DC 母线电压与地之间的导通和短路。",
    "PWM duty cycle characteristics": "PWM 占空比特性",
    "Minimum duty cycle supported by the board, taking into consideration the minimum pulse width limitations of the inverter stage.": "板支持的最小占空比，考虑了逆变级的最小脉冲宽度限制。",
    "Maximum duty cycle supported by the board, taking into consideration the minimum pulse width limitations of the inverter stage, bootstrap limitations of the gate driver (if present) and current measurement limitations of low-side shunt-based current amplifier circuits (if present).": "板支持的最大占空比，考虑了逆变级的最小脉冲宽度限制、栅极驱动器（如存在）的自举限制以及低侧分流电流放大电路（如存在）的电流测量限制。",
    "Power-on characteristics": "上电特性",
    "Power-on delay characteristics": "上电延迟特性",
    "Worst-case power-on delay before circuitry stabilizes and is ready for use": "电路稳定并准备好使用前的最坏情况上电延迟",
    "Programming/Debugging configuration": "编程/调试配置",
    "PGDx/PGCx channel for Programming/Debugging. Refer to device datasheet for which Programming/Debugging channels are available.": "用于编程/调试的 PGDx/PGCx 通道。可用编程/调试通道请参见器件数据手册。",
    "Oscillator configuration": "振荡器配置",
    "Clock source selection. Possible options are": "时钟源选择。可用选项为",
    "crystal": "crystal",
    "oscillator": "oscillator",
    "internal": "internal",
    ", or": "，或",
    "external": "external",
    "clock": "clock",
    "Primary Oscillator with PLL": "带 PLL 的主振荡器",
    "FRC Oscillator with PLL": "带 PLL 的 FRC 振荡器",
    "External Oscillator with PLL": "带 PLL 的外部振荡器",
    "Frequency of input clock used to generate system clock frequency": "用于生成系统时钟频率的输入时钟频率",
    "Configuration of ADC peripheral and ADC channels. See device datasheet for which ADC channels are available on the selected device.": "ADC 外设和 ADC 通道的配置。可用 ADC 通道请参见器件数据手册。",
    "Sampling time of ADC channels": "ADC 通道的采样时间",
    "For all devices there is a limited valid range of ADC sampling time. Refer to the device datasheet and ensure the corresponding register (ADCON2H.SHRSAMC for 33C devices, ADxCHyCON.SAMC for 33A devices) in the generated code results in a sampling time that is appropriate for the end application.": "所有器件的 ADC 采样时间都有有限的有效范围。请参阅器件数据手册，确保生成的代码中相应的寄存器（33C 器件为 ADCON2H.SHRSAMC，33A 器件为 ADxCHyCON.SAMC）产生适合终端应用的采样时间。",
    "Configures": "配置",
    "ADC channels for current measurement": "用于电流测量的 ADC 通道",
    ". This determines which": "。这决定了哪些",
    "methods are available.": "方法可用。",
    "Current measurement ADC channel configuration": "电流测量 ADC 通道配置",
    "ADC channel to sample": "要采样的 ADC 通道",
    "Determines if the ADC channel measurement is inverted.": "确定 ADC 通道测量是否反相。",
    "= inverted,": "= 反相，",
    "= not inverted": "= 非反相",
    "Determines if the ADC measurement is treated as a signed value relative to mid-scale (AVdd/2) or an unsigned value relative to AVss.": "确定 ADC 测量是否被视为相对于中点 (AVdd/2) 的有符号值或相对于 AVss 的无符号值。",
    "= signed,": "= 有符号，",
    "= unsigned": "= 无符号",
    "Configuration of ADC channels for voltage measurement. DC link voltage measurement is required, all other voltage measurements are optional.": "用于电压测量的 ADC 通道配置。DC 母线电压测量为必填，所有其他电压测量为可选。",
    "DC link voltage measurement channel configuration": "DC 母线电压测量通道配置",
    "Phase A voltage measurement channel configuration": "A 相电压测量通道配置",
    "Phase B voltage measurement channel configuration": "B 相电压测量通道配置",
    "Phase C voltage measurement channel configuration": "C 相电压测量通道配置",
    "Absolute voltage reference channel configuration": "绝对电压参考通道配置",
    "Nominal analog voltage (AVdd)": "标称模拟电压 (AVdd)",
    "Unused parameter": "未使用的参数",
    "ADC measurements supported by MCAF that don\u2019t fit into the current or voltage categories. The ADC measurements in this category are optional.": "MCAF 支持的不属于电流或电压类别的 ADC 测量。此类 ADC 测量为可选。",
    "Bridge temperature measurement channel configuration": "桥温度测量通道配置",
    "Offset of bridge temperature measurement": "桥温度测量的偏移",
    "Gain of bridge temperature measurement": "桥温度测量的增益",
    "Potentiometer measurement channel configuration": "电位器测量通道配置",
    "Polarity of measurement.": "测量的极性。",
    "Minimum measured voltage as a fraction of AVdd. Defaults to 0.0.": "最小测量电压，以 AVdd 的比例表示。默认为 0.0。",
    "Maximum measured voltage as a fraction of AVdd. Defaults to 1.0.": "最大测量电压，以 AVdd 的比例表示。默认为 1.0。",
    "Custom ADC channel configuration. These ADC channels are not used by MCAF, and may be managed by the application. They are sampled at the same frequency (PWM frequency) as other MCAF ADC channels. The custom name of the channel must be a valid C identifier.": "自定义 ADC 通道配置。这些 ADC 通道不由 MCAF 使用，可由应用管理。它们以与其他 MCAF ADC 通道相同的频率（PWM 频率）采样。通道的自定义名称必须为有效的 C 标识符。",
    "3-phase PWM configuration": "三相 PWM 配置",
    "Polarity of the upper (PWMxH) and lower (PWMxL) PWM signals": "高侧 (PWMxH) 和低侧 (PWMxL) PWM 信号的极性",
    "Digital polarity": "数字极性",
    "PWM generator to motor phase mapping. See device datasheet for which PWM generators are available on the selected device.": "PWM 发生器到电机相位的映射。可用 PWM 发生器请参见器件数据手册。",
    "PWM generator number. See device datasheet for which PWM generators are available on the selected device.": "PWM 发生器编号。可用 PWM 发生器请参见器件数据手册。",
    "Swap the outputs of the upper (PWMxH) and lower (PWMxL) signals for each generator": "交换每个发生器的高侧 (PWMxH) 和低侧 (PWMxL) 信号输出",
    "Determines if the PWMxH and PWMxL signals are swapped": "确定 PWMxH 和 PWMxL 信号是否交换",
    "PWM fault configuration. This signal will cause the PWM generators to shut down when the digital signal transitions (low or high, depending on the polarity configuration).": "PWM 故障配置。当数字信号跳变（低或高，取决于极性配置）时，此信号将导致 PWM 发生器关断。",
    "Fault source selection": "故障源选择",
    "Fault source tied to 0V": "故障源连接至 0V",
    "Comparator 1 Output": "比较器 1 输出",
    "Comparator 2 Output": "比较器 2 输出",
    "Comparator 3 Output": "比较器 3 输出",
    "Device pin, PCI19": "器件引脚，PCI19",
    "Device pin, PCI20": "器件引脚，PCI20",
    "Device pin, PCI21": "器件引脚，PCI21",
    "Device pin, PCI22": "器件引脚，PCI22",
    "Configurable logic cell 1": "可配置逻辑单元 1",
    "Remappable peripheral function input, PCI18R": "可重映射外设功能输入，PCI18R",
    "Remappable peripheral function input, PCI17R": "可重映射外设功能输入，PCI17R",
    "Remappable peripheral function input, PCI16R": "可重映射外设功能输入，PCI16R",
    "Remappable peripheral function input, PCI15R": "可重映射外设功能输入，PCI15R",
    "Remappable peripheral function input, PCI14R": "可重映射外设功能输入，PCI14R",
    "Remappable peripheral function input, PCI13R": "可重映射外设功能输入，PCI13R",
    "Remappable peripheral function input, PCI12R": "可重映射外设功能输入，PCI12R",
    "Remappable peripheral function input, PCI11R": "可重映射外设功能输入，PCI11R",
    "Remappable peripheral function input, PCI10R": "可重映射外设功能输入，PCI10R",
    "Remappable peripheral function input, PCI9R": "可重映射外设功能输入，PCI9R",
    "Remappable peripheral function input, PCI8R": "可重映射外设功能输入，PCI8R",
    "Internal op amp configuration": "内部运放配置",
    "A list of which op amps are enabled": "已启用的运放列表",
    "Internal comparator/DAC configuration. The comparator/DAC can be configured for the PWM fault source.": "内部比较器/DAC 配置。比较器/DAC 可配置为 PWM 故障源。",
    "Source that triggers the comparator output": "触发比较器输出的源",
    "Polarity of the comparator output.": "比较器输出的极性。",
    "= non inverted": "= 非反相",
    "Fraction of AVDD": "AVDD 的比例",
    "Trigger threshold as a fraction of AVdd": "触发阈值，以 AVdd 的比例表示",
    "GPIO configuration": "GPIO 配置",
    "QEI configuration. Must be configured to use the QEI estimator. See device datasheet for which pins are available on the selected device.": "QEI 配置。使用 QEI 估计器时必须配置。可用引脚请参见器件数据手册。",
    "QEI pin configuration": "QEI 引脚配置",
    "UART configuration. Must be configured if real-time debugging is desired. See device datasheet for which pins are available on the selected device.": "UART 配置。如需实时调试则必须配置。可用引脚请参见器件数据手册。",
    "UART pin configuration": "UART 引脚配置",
    "Referenced types": "引用类型",
    "Direction of GPIO": "GPIO 方向",
    "Open drain pin configuration": "开漏引脚配置",
    "Enable internal weak pull-up resistor": "启用内部弱上拉电阻",
    "Enable internal weak pull-down resistor": "启用内部弱下拉电阻",
    "Start condition of pin (LATx)": "引脚起始条件 (LATx)",
    "6.6.9. Custom board definition format": "6.6.9. 自定义板级定义格式",
    "6.6.9.1. Working with Serialized Data Models": "6.6.9.1. 使用序列化数据模型",
    "6.6.9.1.1. Introduction": "6.6.9.1.1. 简介",
    "6.6.9.1.2. Example in YAML": "6.6.9.1.2. YAML 示例",
    "6.6.9.2. Custom board schema": "6.6.9.2. 自定义板级 schema",
    "Verification and board bring-up": "验证与板级调试",
    "Resource Usage": "资源使用",
}

path = txutil.translate_dict_page(rel, title_zh, m)
print("translated", path)
